/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft16b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    float64_t a2061, a2062, a2063, a2064, a2065, a2066, a2067, a2068, 
            a2069, a2070, a2071, a2072, a2073, a2074, a2075, a2076, 
            a2077, a2078, a2079, a2080, a2081, a2082, a2083, a2084, 
            a2085, a2086, a2087, a2088, a2089, a2090;
    int a2051, a2060, j1, l1, m1;
    svfloat64x2_t s924, s927, s930, s933, s936, s939, s942, s945, 
            s948, s951, s954, s957, s960, s963, s966, s969, 
            svex2_17, svex2_18, svex2_19, svex2_20, svex2_21, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32;
    svfloat64_t a2052, a2053, a2054, a2055, a2056, a2057, a2058, a2059, 
            s1000, s1001, s1002, s1003, s1004, s1005, s1006, s1007, 
            s1008, s1009, s1010, s1011, s1012, s1013, s1014, s1015, 
            s1016, s1017, s1018, s1019, s1020, s1021, s1022, s1023, 
            s1024, s1025, s925, s926, s928, s929, s931, s932, 
            s934, s935, s937, s938, s940, s941, s943, s944, 
            s946, s947, s949, s950, s952, s953, s955, s956, 
            s958, s959, s961, s962, s964, s965, s967, s968, 
            s970, s971, s972, s973, s974, s975, s976, s977, 
            s978, s979, s980, s981, s982, s983, s984, s985, 
            s986, s987, s988, s989, s990, s991, s992, s993, 
            s994, s995, s996, s997, s998, s999, t3019, t3020, 
            t3021, t3022, t3023, t3024, t3025, t3026, t3027, t3028, 
            t3029, t3030, t3031, t3032, t3033, t3034, t3035, t3036, 
            t3037, t3038, t3039, t3040, t3041, t3042, t3043, t3044, 
            t3045, t3046, t3047, t3048, t3049, t3050, t3051, t3052, 
            t3053, t3054, t3055, t3056, t3057, t3058, t3059, t3060, 
            t3061, t3062, t3063, t3064, t3065, t3066, t3067, t3068, 
            t3069, t3070, t3071, t3072, t3073, t3074, t3075, t3076, 
            t3077, t3078, t3079, t3080, t3081, t3082, t3083, t3084, 
            t3085, t3086, t3087, t3088, t3089, t3090, t3091, t3092, 
            t3093, t3094, t3095, t3096, t3097, t3098, t3099, t3100, 
            t3101, t3102, t3103, t3104, t3105, t3106;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a2051 = (k1 + ((j1)*(m1)));
            s924 = svld2_f64(pg1, (X + ((2)*(a2051))));
            s925 = s924.v0;
            s926 = s924.v1;
            s927 = svld2_f64(pg1, (X + ((2)*((a2051 + ((l1)*(m1)))))));
            s928 = s927.v0;
            s929 = s927.v1;
            s930 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((2)*(l1)))*(m1)))))));
            s931 = s930.v0;
            s932 = s930.v1;
            s933 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((3)*(l1)))*(m1)))))));
            s934 = s933.v0;
            s935 = s933.v1;
            s936 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((4)*(l1)))*(m1)))))));
            s937 = s936.v0;
            s938 = s936.v1;
            s939 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((5)*(l1)))*(m1)))))));
            s940 = s939.v0;
            s941 = s939.v1;
            s942 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((6)*(l1)))*(m1)))))));
            s943 = s942.v0;
            s944 = s942.v1;
            s945 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((7)*(l1)))*(m1)))))));
            s946 = s945.v0;
            s947 = s945.v1;
            s948 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((8)*(l1)))*(m1)))))));
            s949 = s948.v0;
            s950 = s948.v1;
            s951 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((9)*(l1)))*(m1)))))));
            s952 = s951.v0;
            s953 = s951.v1;
            s954 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((10)*(l1)))*(m1)))))));
            s955 = s954.v0;
            s956 = s954.v1;
            s957 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((11)*(l1)))*(m1)))))));
            s958 = s957.v0;
            s959 = s957.v1;
            s960 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((12)*(l1)))*(m1)))))));
            s961 = s960.v0;
            s962 = s960.v1;
            s963 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((13)*(l1)))*(m1)))))));
            s964 = s963.v0;
            s965 = s963.v1;
            s966 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((14)*(l1)))*(m1)))))));
            s967 = s966.v0;
            s968 = s966.v1;
            s969 = svld2_f64(pg1, (X + ((2)*((a2051 + ((((15)*(l1)))*(m1)))))));
            s970 = s969.v0;
            s971 = s969.v1;
            t3019 = svadd_f64_x(pg1, s925, s949);
            t3020 = svadd_f64_x(pg1, s926, s950);
            t3021 = svsub_f64_x(pg1, s925, s949);
            t3022 = svsub_f64_x(pg1, s926, s950);
            t3023 = svadd_f64_x(pg1, s937, s961);
            t3024 = svadd_f64_x(pg1, s938, s962);
            t3025 = svsub_f64_x(pg1, s937, s961);
            t3026 = svsub_f64_x(pg1, s938, s962);
            t3027 = svadd_f64_x(pg1, t3019, t3023);
            t3028 = svadd_f64_x(pg1, t3020, t3024);
            t3029 = svsub_f64_x(pg1, t3019, t3023);
            t3030 = svsub_f64_x(pg1, t3020, t3024);
            t3031 = svadd_f64_x(pg1, t3021, t3026);
            t3032 = svsub_f64_x(pg1, t3022, t3025);
            t3033 = svsub_f64_x(pg1, t3021, t3026);
            t3034 = svadd_f64_x(pg1, t3022, t3025);
            t3035 = svadd_f64_x(pg1, s928, s952);
            t3036 = svadd_f64_x(pg1, s929, s953);
            t3037 = svsub_f64_x(pg1, s928, s952);
            t3038 = svsub_f64_x(pg1, s929, s953);
            t3039 = svadd_f64_x(pg1, s940, s964);
            t3040 = svadd_f64_x(pg1, s941, s965);
            t3041 = svsub_f64_x(pg1, s940, s964);
            t3042 = svsub_f64_x(pg1, s941, s965);
            t3043 = svadd_f64_x(pg1, t3035, t3039);
            t3044 = svadd_f64_x(pg1, t3036, t3040);
            a2052 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3035, t3039), 0.70710678118654757);
            a2053 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3036, t3040), 0.70710678118654757);
            s972 = svadd_f64_x(pg1, a2052, a2053);
            s973 = svsub_f64_x(pg1, a2053, a2052);
            t3045 = svadd_f64_x(pg1, t3037, t3042);
            t3046 = svsub_f64_x(pg1, t3038, t3041);
            t3047 = svsub_f64_x(pg1, t3037, t3042);
            t3048 = svadd_f64_x(pg1, t3038, t3041);
            s1018 = svmla_n_f64_x(pg1, t3045, t3046, 0.41421356237309509);
            s974 = svmul_n_f64_x(pg1, s1018, 0.92387953251128674);
            s1019 = svmls_n_f64_x(pg1, t3046, t3045, 0.41421356237309509);
            s975 = svmul_n_f64_x(pg1, s1019, 0.92387953251128674);
            s1020 = svmla_n_f64_x(pg1, t3047, t3048, 2.4142135623730949);
            s976 = svmul_n_f64_x(pg1, s1020, 0.38268343236508978);
            s1021 = svmls_n_f64_x(pg1, t3048, t3047, 2.4142135623730949);
            s977 = svmul_n_f64_x(pg1, s1021, 0.38268343236508978);
            t3049 = svadd_f64_x(pg1, s931, s955);
            t3050 = svadd_f64_x(pg1, s932, s956);
            t3051 = svsub_f64_x(pg1, s931, s955);
            t3052 = svsub_f64_x(pg1, s932, s956);
            t3053 = svadd_f64_x(pg1, s943, s967);
            t3054 = svadd_f64_x(pg1, s944, s968);
            t3055 = svsub_f64_x(pg1, s943, s967);
            t3056 = svsub_f64_x(pg1, s944, s968);
            t3057 = svadd_f64_x(pg1, t3049, t3053);
            t3058 = svadd_f64_x(pg1, t3050, t3054);
            t3059 = svsub_f64_x(pg1, t3049, t3053);
            t3060 = svsub_f64_x(pg1, t3050, t3054);
            a2054 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t3051, t3056), 0.70710678118654757);
            a2055 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3052, t3055), 0.70710678118654757);
            s978 = svadd_f64_x(pg1, a2054, a2055);
            s979 = svsub_f64_x(pg1, a2055, a2054);
            a2056 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t3052, t3055), 0.70710678118654757);
            a2057 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3051, t3056), 0.70710678118654757);
            s980 = svsub_f64_x(pg1, a2056, a2057);
            s981 = svadd_f64_x(pg1, a2057, a2056);
            t3061 = svadd_f64_x(pg1, s934, s958);
            t3062 = svadd_f64_x(pg1, s935, s959);
            t3063 = svsub_f64_x(pg1, s934, s958);
            t3064 = svsub_f64_x(pg1, s935, s959);
            t3065 = svadd_f64_x(pg1, s946, s970);
            t3066 = svadd_f64_x(pg1, s947, s971);
            t3067 = svsub_f64_x(pg1, s946, s970);
            t3068 = svsub_f64_x(pg1, s947, s971);
            t3069 = svadd_f64_x(pg1, t3061, t3065);
            t3070 = svadd_f64_x(pg1, t3062, t3066);
            a2058 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3062, t3066), 0.70710678118654757);
            a2059 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3061, t3065), 0.70710678118654757);
            s982 = svsub_f64_x(pg1, a2058, a2059);
            s983 = svadd_f64_x(pg1, a2059, a2058);
            t3071 = svadd_f64_x(pg1, t3063, t3068);
            t3072 = svsub_f64_x(pg1, t3064, t3067);
            t3073 = svsub_f64_x(pg1, t3063, t3068);
            t3074 = svadd_f64_x(pg1, t3064, t3067);
            s1022 = svmla_n_f64_x(pg1, t3071, t3072, 2.4142135623730949);
            s984 = svmul_n_f64_x(pg1, s1022, 0.38268343236508978);
            s1023 = svmls_n_f64_x(pg1, t3072, t3071, 2.4142135623730949);
            s985 = svmul_n_f64_x(pg1, s1023, 0.38268343236508978);
            s1024 = svmla_n_f64_x(pg1, t3073, t3074, 0.41421356237309509);
            s986 = svmul_n_f64_x(pg1, s1024, 0.92387953251128674);
            s1025 = svmls_n_f64_x(pg1, t3073, t3074, 2.4142135623730949);
            s987 = svmul_n_f64_x(pg1, s1025, 0.38268343236508978);
            t3075 = svadd_f64_x(pg1, t3027, t3057);
            t3076 = svadd_f64_x(pg1, t3028, t3058);
            t3077 = svsub_f64_x(pg1, t3027, t3057);
            t3078 = svsub_f64_x(pg1, t3028, t3058);
            t3079 = svadd_f64_x(pg1, t3043, t3069);
            t3080 = svadd_f64_x(pg1, t3044, t3070);
            t3081 = svsub_f64_x(pg1, t3043, t3069);
            t3082 = svsub_f64_x(pg1, t3044, t3070);
            s988 = svsub_f64_x(pg1, t3075, t3079);
            s989 = svsub_f64_x(pg1, t3076, t3080);
            s990 = svadd_f64_x(pg1, t3077, t3082);
            s991 = svsub_f64_x(pg1, t3078, t3081);
            s992 = svsub_f64_x(pg1, t3077, t3082);
            s993 = svadd_f64_x(pg1, t3078, t3081);
            t3083 = svadd_f64_x(pg1, t3031, s978);
            t3084 = svadd_f64_x(pg1, t3032, s979);
            t3085 = svsub_f64_x(pg1, t3031, s978);
            t3086 = svsub_f64_x(pg1, t3032, s979);
            t3087 = svadd_f64_x(pg1, s974, s984);
            t3088 = svadd_f64_x(pg1, s975, s985);
            t3089 = svsub_f64_x(pg1, s974, s984);
            t3090 = svsub_f64_x(pg1, s975, s985);
            s994 = svadd_f64_x(pg1, t3083, t3087);
            s995 = svadd_f64_x(pg1, t3084, t3088);
            s996 = svsub_f64_x(pg1, t3083, t3087);
            s997 = svsub_f64_x(pg1, t3084, t3088);
            s998 = svadd_f64_x(pg1, t3085, t3090);
            s999 = svsub_f64_x(pg1, t3086, t3089);
            s1000 = svsub_f64_x(pg1, t3085, t3090);
            s1001 = svadd_f64_x(pg1, t3086, t3089);
            t3091 = svadd_f64_x(pg1, t3029, t3060);
            t3092 = svsub_f64_x(pg1, t3030, t3059);
            t3093 = svsub_f64_x(pg1, t3029, t3060);
            t3094 = svadd_f64_x(pg1, t3030, t3059);
            t3095 = svadd_f64_x(pg1, s972, s982);
            t3096 = svsub_f64_x(pg1, s973, s983);
            t3097 = svsub_f64_x(pg1, s972, s982);
            t3098 = svadd_f64_x(pg1, s973, s983);
            s1002 = svadd_f64_x(pg1, t3091, t3095);
            s1003 = svadd_f64_x(pg1, t3092, t3096);
            s1004 = svsub_f64_x(pg1, t3091, t3095);
            s1005 = svsub_f64_x(pg1, t3092, t3096);
            s1006 = svadd_f64_x(pg1, t3093, t3098);
            s1007 = svsub_f64_x(pg1, t3094, t3097);
            s1008 = svsub_f64_x(pg1, t3093, t3098);
            s1009 = svadd_f64_x(pg1, t3094, t3097);
            t3099 = svadd_f64_x(pg1, t3033, s980);
            t3100 = svsub_f64_x(pg1, t3034, s981);
            t3101 = svsub_f64_x(pg1, t3033, s980);
            t3102 = svadd_f64_x(pg1, t3034, s981);
            t3103 = svsub_f64_x(pg1, s976, s986);
            t3104 = svadd_f64_x(pg1, s977, s987);
            t3105 = svadd_f64_x(pg1, s976, s986);
            t3106 = svsub_f64_x(pg1, s977, s987);
            s1010 = svadd_f64_x(pg1, t3099, t3103);
            s1011 = svadd_f64_x(pg1, t3100, t3104);
            s1012 = svsub_f64_x(pg1, t3099, t3103);
            s1013 = svsub_f64_x(pg1, t3100, t3104);
            s1014 = svadd_f64_x(pg1, t3101, t3106);
            s1015 = svsub_f64_x(pg1, t3102, t3105);
            s1016 = svsub_f64_x(pg1, t3101, t3106);
            s1017 = svadd_f64_x(pg1, t3102, t3105);
            a2060 = ((30)*(j1));
            a2061 = TW1[a2060];
            a2062 = TW1[(a2060 + 1)];
            a2063 = TW1[(a2060 + 2)];
            a2064 = TW1[(a2060 + 3)];
            a2065 = TW1[(a2060 + 4)];
            a2066 = TW1[(a2060 + 5)];
            a2067 = TW1[(a2060 + 6)];
            a2068 = TW1[(a2060 + 7)];
            a2069 = TW1[(a2060 + 8)];
            a2070 = TW1[(a2060 + 9)];
            a2071 = TW1[(a2060 + 10)];
            a2072 = TW1[(a2060 + 11)];
            a2073 = TW1[(a2060 + 12)];
            a2074 = TW1[(a2060 + 13)];
            a2075 = TW1[(a2060 + 14)];
            a2076 = TW1[(a2060 + 15)];
            a2077 = TW1[(a2060 + 16)];
            a2078 = TW1[(a2060 + 17)];
            a2079 = TW1[(a2060 + 18)];
            a2080 = TW1[(a2060 + 19)];
            a2081 = TW1[(a2060 + 20)];
            a2082 = TW1[(a2060 + 21)];
            a2083 = TW1[(a2060 + 22)];
            a2084 = TW1[(a2060 + 23)];
            a2085 = TW1[(a2060 + 24)];
            a2086 = TW1[(a2060 + 25)];
            a2087 = TW1[(a2060 + 26)];
            a2088 = TW1[(a2060 + 27)];
            a2089 = TW1[(a2060 + 28)];
            a2090 = TW1[(a2060 + 29)];
            svex2_17.v0 = svadd_f64_x(pg1, t3075, t3079);
            svex2_17.v1 = svadd_f64_x(pg1, t3076, t3080);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)))))), svex2_17);
            svex2_18.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s995, a2062), s994, a2061);
            svex2_18.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s995, a2061), s994, a2062);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + m1)))), svex2_18);
            svex2_19.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1003, a2064), s1002, a2063);
            svex2_19.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1003, a2063), s1002, a2064);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_19);
            svex2_20.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1011, a2066), s1010, a2065);
            svex2_20.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1011, a2065), s1010, a2066);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_20);
            svex2_21.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s991, a2068), s990, a2067);
            svex2_21.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s991, a2067), s990, a2068);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_21);
            svex2_22.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s999, a2070), s998, a2069);
            svex2_22.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s999, a2069), s998, a2070);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_22);
            svex2_23.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1007, a2072), s1006, a2071);
            svex2_23.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1007, a2071), s1006, a2072);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_23);
            svex2_24.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1015, a2074), s1014, a2073);
            svex2_24.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1015, a2073), s1014, a2074);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_24);
            svex2_25.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s989, a2076), s988, a2075);
            svex2_25.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s989, a2075), s988, a2076);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_25);
            svex2_26.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s997, a2078), s996, a2077);
            svex2_26.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s997, a2077), s996, a2078);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((9)*(m1)))))), svex2_26);
            svex2_27.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1005, a2080), s1004, a2079);
            svex2_27.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1005, a2079), s1004, a2080);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((10)*(m1)))))), svex2_27);
            svex2_28.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1013, a2082), s1012, a2081);
            svex2_28.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1013, a2081), s1012, a2082);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((11)*(m1)))))), svex2_28);
            svex2_29.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s993, a2084), s992, a2083);
            svex2_29.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s993, a2083), s992, a2084);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((12)*(m1)))))), svex2_29);
            svex2_30.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1001, a2086), s1000, a2085);
            svex2_30.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1001, a2085), s1000, a2086);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((13)*(m1)))))), svex2_30);
            svex2_31.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1009, a2088), s1008, a2087);
            svex2_31.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1009, a2087), s1008, a2088);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((14)*(m1)))))), svex2_31);
            svex2_32.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1017, a2090), s1016, a2089);
            svex2_32.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1017, a2089), s1016, a2090);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((16)*(j1)))*(m1)) + ((15)*(m1)))))), svex2_32);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
