/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft18b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    static float64_t D39[12];
    static float64_t D40[24];
    float64_t a3611, a3612, a3613, a3614, a3615, a3616, a3617, a3618, 
            a3619, a3620, a3621, a3622, a3623, a3624, a3625, a3626, 
            a3627, a3628, a3629, a3630, a3631, a3632, a3633, a3634, 
            a3635, a3636, a3637, a3638, a3639, a3640, a3641, a3642, 
            a3643, a3644;
    int a3609, a3610, j1, l1, m1;
    svfloat64x2_t s1722, s1725, s1728, s1731, s1734, s1737, s1740, s1743, 
            s1746, s1749, s1752, s1755, s1758, s1761, s1764, s1767, 
            s1770, s1773, svex2_19, svex2_20, svex2_21, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36;
    svfloat64_t s1723, s1724, s1726, s1727, s1729, s1730, s1732, s1733, 
            s1735, s1736, s1738, s1739, s1741, s1742, s1744, s1745, 
            s1747, s1748, s1750, s1751, s1753, s1754, s1756, s1757, 
            s1759, s1760, s1762, s1763, s1765, s1766, s1768, s1769, 
            s1771, s1772, s1774, s1775, s1776, s1777, s1778, s1779, 
            s1780, s1781, s1782, s1783, s1784, s1785, s1786, s1787, 
            s1788, s1789, s1790, s1791, s1792, s1793, s1794, s1795, 
            s1796, s1797, s1798, s1799, s1800, s1801, s1802, s1803, 
            s1804, s1805, s1806, s1807, s1808, s1809, s1810, s1811, 
            s1812, s1813, s1814, s1815, s1816, s1817, s1818, s1819, 
            s1820, s1821, s1822, s1823, s1824, s1825, s1826, s1827, 
            s1828, s1829, s1830, s1831, s1832, s1833, s1834, s1835, 
            s1836, s1837, s1838, s1839, s1840, s1841, s1842, s1843, 
            s1844, s1845, s1846, s1847, s1848, s1849, s1850, s1851, 
            s1852, s1853, s1854, s1855, s1856, s1857, s1858, s1859, 
            s1860, s1861, s1862, s1863, s1864, s1865, s1866, s1867, 
            s1868, s1869, s1870, s1871, s1872, s1873, s1874, s1875, 
            s1876, s1877, s1878, s1879, s1880, s1881, s1882, s1883, 
            s1884, s1885, s1886, s1887, s1888, s1889, s1890, s1891, 
            s1892, s1893, t2075, t2076, t2077, t2078, t2079, t2080, 
            t2081, t2082, t2083, t2084, t2085, t2086, t2087, t2088, 
            t2089, t2090, t2091, t2092, t2093, t2094, t2095, t2096, 
            t2097, t2098, t2099, t2100, t2101, t2102, t2103, t2104, 
            t2105, t2106, t2107, t2108, t2109, t2110, t2111, t2112, 
            t2113, t2114, t2115, t2116, t2117, t2118, t2119, t2120, 
            t2121, t2122, t2123, t2124, t2125, t2126, t2127, t2128, 
            t2129, t2130, t2131, t2132, t2133, t2134, t2135, t2136, 
            t2137, t2138, t2139, t2140, t2141, t2142, t2143, t2144, 
            t2145, t2146, t2147, t2148, t2149, t2150, t2151, t2152, 
            t2153, t2154, t2155, t2156, t2157, t2158, t2159, t2160, 
            t2161, t2162, t2163, t2164, t2165, t2166, t2167, t2168, 
            t2169, t2170, t2171, t2172, t2173, t2174, t2175, t2176, 
            t2177, t2178, t2179, t2180, t2181, t2182, t2183, t2184, 
            t2185, t2186, t2187, t2188, t2189, t2190, t2191, t2192, 
            t2193, t2194;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a3609 = (k1 + ((j1)*(m1)));
            s1722 = svld2_f64(pg1, (X + ((2)*(a3609))));
            s1723 = s1722.v0;
            s1724 = s1722.v1;
            s1725 = svld2_f64(pg1, (X + ((2)*((a3609 + ((l1)*(m1)))))));
            s1726 = s1725.v0;
            s1727 = s1725.v1;
            s1728 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((2)*(l1)))*(m1)))))));
            s1729 = s1728.v0;
            s1730 = s1728.v1;
            s1731 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((3)*(l1)))*(m1)))))));
            s1732 = s1731.v0;
            s1733 = s1731.v1;
            s1734 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((4)*(l1)))*(m1)))))));
            s1735 = s1734.v0;
            s1736 = s1734.v1;
            s1737 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((5)*(l1)))*(m1)))))));
            s1738 = s1737.v0;
            s1739 = s1737.v1;
            s1740 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((6)*(l1)))*(m1)))))));
            s1741 = s1740.v0;
            s1742 = s1740.v1;
            s1743 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((7)*(l1)))*(m1)))))));
            s1744 = s1743.v0;
            s1745 = s1743.v1;
            s1746 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((8)*(l1)))*(m1)))))));
            s1747 = s1746.v0;
            s1748 = s1746.v1;
            s1749 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((9)*(l1)))*(m1)))))));
            s1750 = s1749.v0;
            s1751 = s1749.v1;
            s1752 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((10)*(l1)))*(m1)))))));
            s1753 = s1752.v0;
            s1754 = s1752.v1;
            s1755 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((11)*(l1)))*(m1)))))));
            s1756 = s1755.v0;
            s1757 = s1755.v1;
            s1758 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((12)*(l1)))*(m1)))))));
            s1759 = s1758.v0;
            s1760 = s1758.v1;
            s1761 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((13)*(l1)))*(m1)))))));
            s1762 = s1761.v0;
            s1763 = s1761.v1;
            s1764 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((14)*(l1)))*(m1)))))));
            s1765 = s1764.v0;
            s1766 = s1764.v1;
            s1767 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((15)*(l1)))*(m1)))))));
            s1768 = s1767.v0;
            s1769 = s1767.v1;
            s1770 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((16)*(l1)))*(m1)))))));
            s1771 = s1770.v0;
            s1772 = s1770.v1;
            s1773 = svld2_f64(pg1, (X + ((2)*((a3609 + ((((17)*(l1)))*(m1)))))));
            s1774 = s1773.v0;
            s1775 = s1773.v1;
            t2075 = svadd_f64_x(pg1, s1741, s1759);
            t2076 = svadd_f64_x(pg1, s1742, s1760);
            t2077 = svadd_f64_x(pg1, s1723, t2075);
            t2078 = svadd_f64_x(pg1, s1724, t2076);
            t2079 = svmls_n_f64_x(pg1, s1723, t2075, 0.5);
            t2080 = svmls_n_f64_x(pg1, s1724, t2076, 0.5);
            s1776 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1742, s1760), 0.8660254037844386);
            s1777 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1741, s1759), 0.8660254037844386);
            s1778 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2078, D39[1]), t2077, D39[0]);
            s1779 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2078, D39[0]), t2077, D39[1]);
            t2081 = svadd_f64_x(pg1, t2079, s1776);
            t2082 = svsub_f64_x(pg1, t2080, s1777);
            t2083 = svsub_f64_x(pg1, t2079, s1776);
            t2084 = svadd_f64_x(pg1, t2080, s1777);
            s1780 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2082, D40[1]), t2081, D40[0]);
            s1781 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2082, D40[0]), t2081, D40[1]);
            s1782 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2084, D40[3]), t2083, D40[2]);
            s1783 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2084, D40[2]), t2083, D40[3]);
            t2085 = svadd_f64_x(pg1, s1744, s1762);
            t2086 = svadd_f64_x(pg1, s1745, s1763);
            t2087 = svadd_f64_x(pg1, s1726, t2085);
            t2088 = svadd_f64_x(pg1, s1727, t2086);
            t2089 = svmls_n_f64_x(pg1, s1726, t2085, 0.5);
            t2090 = svmls_n_f64_x(pg1, s1727, t2086, 0.5);
            s1784 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1745, s1763), 0.8660254037844386);
            s1785 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1744, s1762), 0.8660254037844386);
            s1786 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2088, D39[3]), t2087, D39[2]);
            s1787 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2088, D39[2]), t2087, D39[3]);
            t2091 = svadd_f64_x(pg1, t2089, s1784);
            t2092 = svsub_f64_x(pg1, t2090, s1785);
            t2093 = svsub_f64_x(pg1, t2089, s1784);
            t2094 = svadd_f64_x(pg1, t2090, s1785);
            s1788 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2092, D40[5]), t2091, D40[4]);
            s1789 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2092, D40[4]), t2091, D40[5]);
            s1790 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2094, D40[7]), t2093, D40[6]);
            s1791 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2094, D40[6]), t2093, D40[7]);
            t2095 = svadd_f64_x(pg1, s1747, s1765);
            t2096 = svadd_f64_x(pg1, s1748, s1766);
            t2097 = svadd_f64_x(pg1, s1729, t2095);
            t2098 = svadd_f64_x(pg1, s1730, t2096);
            t2099 = svmls_n_f64_x(pg1, s1729, t2095, 0.5);
            t2100 = svmls_n_f64_x(pg1, s1730, t2096, 0.5);
            s1792 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1748, s1766), 0.8660254037844386);
            s1793 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1747, s1765), 0.8660254037844386);
            s1794 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2098, D39[5]), t2097, D39[4]);
            s1795 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2098, D39[4]), t2097, D39[5]);
            t2101 = svadd_f64_x(pg1, t2099, s1792);
            t2102 = svsub_f64_x(pg1, t2100, s1793);
            t2103 = svsub_f64_x(pg1, t2099, s1792);
            t2104 = svadd_f64_x(pg1, t2100, s1793);
            s1796 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2102, D40[9]), t2101, D40[8]);
            s1797 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2102, D40[8]), t2101, D40[9]);
            s1798 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2104, D40[11]), t2103, D40[10]);
            s1799 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2104, D40[10]), t2103, D40[11]);
            t2105 = svadd_f64_x(pg1, s1750, s1768);
            t2106 = svadd_f64_x(pg1, s1751, s1769);
            t2107 = svadd_f64_x(pg1, s1732, t2105);
            t2108 = svadd_f64_x(pg1, s1733, t2106);
            t2109 = svmls_n_f64_x(pg1, s1732, t2105, 0.5);
            t2110 = svmls_n_f64_x(pg1, s1733, t2106, 0.5);
            s1800 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1751, s1769), 0.8660254037844386);
            s1801 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1750, s1768), 0.8660254037844386);
            s1802 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2108, D39[7]), t2107, D39[6]);
            s1803 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2108, D39[6]), t2107, D39[7]);
            t2111 = svadd_f64_x(pg1, t2109, s1800);
            t2112 = svsub_f64_x(pg1, t2110, s1801);
            t2113 = svsub_f64_x(pg1, t2109, s1800);
            t2114 = svadd_f64_x(pg1, t2110, s1801);
            s1804 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2112, D40[13]), t2111, D40[12]);
            s1805 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2112, D40[12]), t2111, D40[13]);
            s1806 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2114, D40[15]), t2113, D40[14]);
            s1807 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2114, D40[14]), t2113, D40[15]);
            t2115 = svadd_f64_x(pg1, s1753, s1771);
            t2116 = svadd_f64_x(pg1, s1754, s1772);
            t2117 = svadd_f64_x(pg1, s1735, t2115);
            t2118 = svadd_f64_x(pg1, s1736, t2116);
            t2119 = svmls_n_f64_x(pg1, s1735, t2115, 0.5);
            t2120 = svmls_n_f64_x(pg1, s1736, t2116, 0.5);
            s1808 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1754, s1772), 0.8660254037844386);
            s1809 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1753, s1771), 0.8660254037844386);
            s1810 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2118, D39[9]), t2117, D39[8]);
            s1811 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2118, D39[8]), t2117, D39[9]);
            t2121 = svadd_f64_x(pg1, t2119, s1808);
            t2122 = svsub_f64_x(pg1, t2120, s1809);
            t2123 = svsub_f64_x(pg1, t2119, s1808);
            t2124 = svadd_f64_x(pg1, t2120, s1809);
            s1812 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2122, D40[17]), t2121, D40[16]);
            s1813 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2122, D40[16]), t2121, D40[17]);
            s1814 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2124, D40[19]), t2123, D40[18]);
            s1815 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2124, D40[18]), t2123, D40[19]);
            t2125 = svadd_f64_x(pg1, s1756, s1774);
            t2126 = svadd_f64_x(pg1, s1757, s1775);
            t2127 = svadd_f64_x(pg1, s1738, t2125);
            t2128 = svadd_f64_x(pg1, s1739, t2126);
            t2129 = svmls_n_f64_x(pg1, s1738, t2125, 0.5);
            t2130 = svmls_n_f64_x(pg1, s1739, t2126, 0.5);
            s1816 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1757, s1775), 0.8660254037844386);
            s1817 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1756, s1774), 0.8660254037844386);
            s1818 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2128, D39[11]), t2127, D39[10]);
            s1819 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2128, D39[10]), t2127, D39[11]);
            t2131 = svadd_f64_x(pg1, t2129, s1816);
            t2132 = svsub_f64_x(pg1, t2130, s1817);
            t2133 = svsub_f64_x(pg1, t2129, s1816);
            t2134 = svadd_f64_x(pg1, t2130, s1817);
            s1820 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2132, D40[21]), t2131, D40[20]);
            s1821 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2132, D40[20]), t2131, D40[21]);
            s1822 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2134, D40[23]), t2133, D40[22]);
            s1823 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2134, D40[22]), t2133, D40[23]);
            t2135 = svadd_f64_x(pg1, s1794, s1810);
            t2136 = svadd_f64_x(pg1, s1795, s1811);
            t2137 = svadd_f64_x(pg1, s1778, t2135);
            t2138 = svadd_f64_x(pg1, s1779, t2136);
            t2139 = svmls_n_f64_x(pg1, s1778, t2135, 0.5);
            t2140 = svmls_n_f64_x(pg1, s1779, t2136, 0.5);
            s1824 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1795, s1811), 0.8660254037844386);
            s1825 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1794, s1810), 0.8660254037844386);
            t2141 = svadd_f64_x(pg1, t2139, s1824);
            t2142 = svsub_f64_x(pg1, t2140, s1825);
            t2143 = svsub_f64_x(pg1, t2139, s1824);
            t2144 = svadd_f64_x(pg1, t2140, s1825);
            t2145 = svadd_f64_x(pg1, s1802, s1818);
            t2146 = svadd_f64_x(pg1, s1803, s1819);
            t2147 = svadd_f64_x(pg1, s1786, t2145);
            t2148 = svadd_f64_x(pg1, s1787, t2146);
            t2149 = svmls_n_f64_x(pg1, s1786, t2145, 0.5);
            t2150 = svmls_n_f64_x(pg1, s1787, t2146, 0.5);
            s1826 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1803, s1819), 0.8660254037844386);
            s1827 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1802, s1818), 0.8660254037844386);
            t2151 = svadd_f64_x(pg1, t2149, s1826);
            t2152 = svsub_f64_x(pg1, t2150, s1827);
            t2153 = svsub_f64_x(pg1, t2149, s1826);
            t2154 = svadd_f64_x(pg1, t2150, s1827);
            s1882 = svmla_n_f64_x(pg1, t2151, t2152, 1.7320508075688772);
            s1828 = svmul_n_f64_x(pg1, s1882, 0.5);
            s1883 = svmls_n_f64_x(pg1, t2152, t2151, 1.7320508075688772);
            s1829 = svmul_n_f64_x(pg1, s1883, 0.5);
            s1884 = svmls_n_f64_x(pg1, t2154, t2153, 0.57735026918962584);
            s1830 = svmul_n_f64_x(pg1, s1884, 0.8660254037844386);
            s1885 = svmla_n_f64_x(pg1, t2153, t2154, 0.57735026918962584);
            s1831 = svmul_n_f64_x(pg1, s1885, 0.8660254037844386);
            s1832 = svsub_f64_x(pg1, t2137, t2147);
            s1833 = svsub_f64_x(pg1, t2138, t2148);
            s1834 = svadd_f64_x(pg1, t2141, s1828);
            s1835 = svadd_f64_x(pg1, t2142, s1829);
            s1836 = svsub_f64_x(pg1, t2141, s1828);
            s1837 = svsub_f64_x(pg1, t2142, s1829);
            s1838 = svadd_f64_x(pg1, t2143, s1830);
            s1839 = svsub_f64_x(pg1, t2144, s1831);
            s1840 = svsub_f64_x(pg1, t2143, s1830);
            s1841 = svadd_f64_x(pg1, t2144, s1831);
            t2155 = svadd_f64_x(pg1, s1796, s1812);
            t2156 = svadd_f64_x(pg1, s1797, s1813);
            t2157 = svadd_f64_x(pg1, s1780, t2155);
            t2158 = svadd_f64_x(pg1, s1781, t2156);
            t2159 = svmls_n_f64_x(pg1, s1780, t2155, 0.5);
            t2160 = svmls_n_f64_x(pg1, s1781, t2156, 0.5);
            s1842 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1797, s1813), 0.8660254037844386);
            s1843 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1796, s1812), 0.8660254037844386);
            t2161 = svadd_f64_x(pg1, t2159, s1842);
            t2162 = svsub_f64_x(pg1, t2160, s1843);
            t2163 = svsub_f64_x(pg1, t2159, s1842);
            t2164 = svadd_f64_x(pg1, t2160, s1843);
            t2165 = svadd_f64_x(pg1, s1804, s1820);
            t2166 = svadd_f64_x(pg1, s1805, s1821);
            t2167 = svadd_f64_x(pg1, s1788, t2165);
            t2168 = svadd_f64_x(pg1, s1789, t2166);
            t2169 = svmls_n_f64_x(pg1, s1788, t2165, 0.5);
            t2170 = svmls_n_f64_x(pg1, s1789, t2166, 0.5);
            s1844 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1805, s1821), 0.8660254037844386);
            s1845 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1804, s1820), 0.8660254037844386);
            t2171 = svadd_f64_x(pg1, t2169, s1844);
            t2172 = svsub_f64_x(pg1, t2170, s1845);
            t2173 = svsub_f64_x(pg1, t2169, s1844);
            t2174 = svadd_f64_x(pg1, t2170, s1845);
            s1886 = svmla_n_f64_x(pg1, t2171, t2172, 1.7320508075688772);
            s1846 = svmul_n_f64_x(pg1, s1886, 0.5);
            s1887 = svmls_n_f64_x(pg1, t2172, t2171, 1.7320508075688772);
            s1847 = svmul_n_f64_x(pg1, s1887, 0.5);
            s1888 = svmls_n_f64_x(pg1, t2174, t2173, 0.57735026918962584);
            s1848 = svmul_n_f64_x(pg1, s1888, 0.8660254037844386);
            s1889 = svmla_n_f64_x(pg1, t2173, t2174, 0.57735026918962584);
            s1849 = svmul_n_f64_x(pg1, s1889, 0.8660254037844386);
            s1850 = svadd_f64_x(pg1, t2157, t2167);
            s1851 = svadd_f64_x(pg1, t2158, t2168);
            s1852 = svsub_f64_x(pg1, t2157, t2167);
            s1853 = svsub_f64_x(pg1, t2158, t2168);
            s1854 = svadd_f64_x(pg1, t2161, s1846);
            s1855 = svadd_f64_x(pg1, t2162, s1847);
            s1856 = svsub_f64_x(pg1, t2161, s1846);
            s1857 = svsub_f64_x(pg1, t2162, s1847);
            s1858 = svadd_f64_x(pg1, t2163, s1848);
            s1859 = svsub_f64_x(pg1, t2164, s1849);
            s1860 = svsub_f64_x(pg1, t2163, s1848);
            s1861 = svadd_f64_x(pg1, t2164, s1849);
            t2175 = svadd_f64_x(pg1, s1798, s1814);
            t2176 = svadd_f64_x(pg1, s1799, s1815);
            t2177 = svadd_f64_x(pg1, s1782, t2175);
            t2178 = svadd_f64_x(pg1, s1783, t2176);
            t2179 = svmls_n_f64_x(pg1, s1782, t2175, 0.5);
            t2180 = svmls_n_f64_x(pg1, s1783, t2176, 0.5);
            s1862 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1799, s1815), 0.8660254037844386);
            s1863 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1798, s1814), 0.8660254037844386);
            t2181 = svadd_f64_x(pg1, t2179, s1862);
            t2182 = svsub_f64_x(pg1, t2180, s1863);
            t2183 = svsub_f64_x(pg1, t2179, s1862);
            t2184 = svadd_f64_x(pg1, t2180, s1863);
            t2185 = svadd_f64_x(pg1, s1806, s1822);
            t2186 = svadd_f64_x(pg1, s1807, s1823);
            t2187 = svadd_f64_x(pg1, s1790, t2185);
            t2188 = svadd_f64_x(pg1, s1791, t2186);
            t2189 = svmls_n_f64_x(pg1, s1790, t2185, 0.5);
            t2190 = svmls_n_f64_x(pg1, s1791, t2186, 0.5);
            s1864 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1807, s1823), 0.8660254037844386);
            s1865 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1806, s1822), 0.8660254037844386);
            t2191 = svadd_f64_x(pg1, t2189, s1864);
            t2192 = svsub_f64_x(pg1, t2190, s1865);
            t2193 = svsub_f64_x(pg1, t2189, s1864);
            t2194 = svadd_f64_x(pg1, t2190, s1865);
            s1890 = svmla_n_f64_x(pg1, t2191, t2192, 1.7320508075688772);
            s1866 = svmul_n_f64_x(pg1, s1890, 0.5);
            s1891 = svmls_n_f64_x(pg1, t2192, t2191, 1.7320508075688772);
            s1867 = svmul_n_f64_x(pg1, s1891, 0.5);
            s1892 = svmls_n_f64_x(pg1, t2194, t2193, 0.57735026918962584);
            s1868 = svmul_n_f64_x(pg1, s1892, 0.8660254037844386);
            s1893 = svmla_n_f64_x(pg1, t2193, t2194, 0.57735026918962584);
            s1869 = svmul_n_f64_x(pg1, s1893, 0.8660254037844386);
            s1870 = svadd_f64_x(pg1, t2177, t2187);
            s1871 = svadd_f64_x(pg1, t2178, t2188);
            s1872 = svsub_f64_x(pg1, t2177, t2187);
            s1873 = svsub_f64_x(pg1, t2178, t2188);
            s1874 = svadd_f64_x(pg1, t2181, s1866);
            s1875 = svadd_f64_x(pg1, t2182, s1867);
            s1876 = svsub_f64_x(pg1, t2181, s1866);
            s1877 = svsub_f64_x(pg1, t2182, s1867);
            s1878 = svadd_f64_x(pg1, t2183, s1868);
            s1879 = svsub_f64_x(pg1, t2184, s1869);
            s1880 = svsub_f64_x(pg1, t2183, s1868);
            s1881 = svadd_f64_x(pg1, t2184, s1869);
            a3610 = ((34)*(j1));
            a3611 = TW1[a3610];
            a3612 = TW1[(a3610 + 1)];
            a3613 = TW1[(a3610 + 2)];
            a3614 = TW1[(a3610 + 3)];
            a3615 = TW1[(a3610 + 4)];
            a3616 = TW1[(a3610 + 5)];
            a3617 = TW1[(a3610 + 6)];
            a3618 = TW1[(a3610 + 7)];
            a3619 = TW1[(a3610 + 8)];
            a3620 = TW1[(a3610 + 9)];
            a3621 = TW1[(a3610 + 10)];
            a3622 = TW1[(a3610 + 11)];
            a3623 = TW1[(a3610 + 12)];
            a3624 = TW1[(a3610 + 13)];
            a3625 = TW1[(a3610 + 14)];
            a3626 = TW1[(a3610 + 15)];
            a3627 = TW1[(a3610 + 16)];
            a3628 = TW1[(a3610 + 17)];
            a3629 = TW1[(a3610 + 18)];
            a3630 = TW1[(a3610 + 19)];
            a3631 = TW1[(a3610 + 20)];
            a3632 = TW1[(a3610 + 21)];
            a3633 = TW1[(a3610 + 22)];
            a3634 = TW1[(a3610 + 23)];
            a3635 = TW1[(a3610 + 24)];
            a3636 = TW1[(a3610 + 25)];
            a3637 = TW1[(a3610 + 26)];
            a3638 = TW1[(a3610 + 27)];
            a3639 = TW1[(a3610 + 28)];
            a3640 = TW1[(a3610 + 29)];
            a3641 = TW1[(a3610 + 30)];
            a3642 = TW1[(a3610 + 31)];
            a3643 = TW1[(a3610 + 32)];
            a3644 = TW1[(a3610 + 33)];
            svex2_19.v0 = svadd_f64_x(pg1, t2137, t2147);
            svex2_19.v1 = svadd_f64_x(pg1, t2138, t2148);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)))))), svex2_19);
            svex2_20.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1851, a3612), s1850, a3611);
            svex2_20.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1851, a3611), s1850, a3612);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + m1)))), svex2_20);
            svex2_21.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1871, a3614), s1870, a3613);
            svex2_21.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1871, a3613), s1870, a3614);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_21);
            svex2_22.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1835, a3616), s1834, a3615);
            svex2_22.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1835, a3615), s1834, a3616);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_22);
            svex2_23.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1855, a3618), s1854, a3617);
            svex2_23.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1855, a3617), s1854, a3618);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_23);
            svex2_24.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1875, a3620), s1874, a3619);
            svex2_24.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1875, a3619), s1874, a3620);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_24);
            svex2_25.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1839, a3622), s1838, a3621);
            svex2_25.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1839, a3621), s1838, a3622);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_25);
            svex2_26.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1859, a3624), s1858, a3623);
            svex2_26.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1859, a3623), s1858, a3624);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_26);
            svex2_27.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1879, a3626), s1878, a3625);
            svex2_27.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1879, a3625), s1878, a3626);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_27);
            svex2_28.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1833, a3628), s1832, a3627);
            svex2_28.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1833, a3627), s1832, a3628);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((9)*(m1)))))), svex2_28);
            svex2_29.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1853, a3630), s1852, a3629);
            svex2_29.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1853, a3629), s1852, a3630);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((10)*(m1)))))), svex2_29);
            svex2_30.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1873, a3632), s1872, a3631);
            svex2_30.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1873, a3631), s1872, a3632);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((11)*(m1)))))), svex2_30);
            svex2_31.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1837, a3634), s1836, a3633);
            svex2_31.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1837, a3633), s1836, a3634);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((12)*(m1)))))), svex2_31);
            svex2_32.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1857, a3636), s1856, a3635);
            svex2_32.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1857, a3635), s1856, a3636);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((13)*(m1)))))), svex2_32);
            svex2_33.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1877, a3638), s1876, a3637);
            svex2_33.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1877, a3637), s1876, a3638);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((14)*(m1)))))), svex2_33);
            svex2_34.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1841, a3640), s1840, a3639);
            svex2_34.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1841, a3639), s1840, a3640);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((15)*(m1)))))), svex2_34);
            svex2_35.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1861, a3642), s1860, a3641);
            svex2_35.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1861, a3641), s1860, a3642);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((16)*(m1)))))), svex2_35);
            svex2_36.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1881, a3644), s1880, a3643);
            svex2_36.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1881, a3643), s1880, a3644);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((18)*(j1)))*(m1)) + ((17)*(m1)))))), svex2_36);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
