/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft16a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a1978;
    svfloat64x2_t s1001, s956, s959, s962, s965, s968, s971, s974, 
            s977, s980, s983, s986, s989, s992, s995, s998;
    svfloat64_t a1970, a1971, a1972, a1973, a1974, a1975, a1976, a1977, 
            a1979, a1980, a1981, a1982, a1983, a1984, a1985, a1986, 
            a1987, a1988, a1989, a1990, a1991, a1992, a1993, a1994, 
            a1995, a1996, a1997, a1998, a1999, a2000, a2001, a2002, 
            a2003, a2004, a2005, a2006, a2007, a2008, s1000, s1002, 
            s1003, s1004, s1005, s1006, s1007, s1008, s1009, s1010, 
            s1011, s1012, s1013, s1014, s1015, s1016, s1017, s1018, 
            s1019, s1020, s1021, s1022, s1023, s1024, s1025, s1026, 
            s1027, s1028, s1029, s1030, s1031, s1032, s1033, s1034, 
            s1035, s1036, s1037, s1038, s1039, s1040, s1041, s1042, 
            s1043, s1044, s1045, s1046, s1047, s1048, s1049, s1050, 
            s1051, s1052, s1053, s1054, s1055, s1056, s1057, s1058, 
            s1059, s1060, s1061, s1062, s1063, s1064, s1065, s1066, 
            s1067, s1068, s1069, s1070, s1071, s1072, s1073, s1074, 
            s1075, s1076, s1077, s1078, s1079, s1080, s1081, s1082, 
            s1083, s1084, s1085, s1086, s1087, s1088, s1089, s957, 
            s958, s960, s961, s963, s964, s966, s967, s969, 
            s970, s972, s973, s975, s976, s978, s979, s981, 
            s982, s984, s985, s987, s988, s990, s991, s993, 
            s994, s996, s997, s999, t3019, t3020, t3021, t3022, 
            t3023, t3024, t3025, t3026, t3027, t3028, t3029, t3030, 
            t3031, t3032, t3033, t3034, t3035, t3036, t3037, t3038, 
            t3039, t3040, t3041, t3042, t3043, t3044, t3045, t3046, 
            t3047, t3048, t3049, t3050, t3051, t3052, t3053, t3054, 
            t3055, t3056, t3057, t3058, t3059, t3060, t3061, t3062, 
            t3063, t3064, t3065, t3066, t3067, t3068, t3069, t3070, 
            t3071, t3072, t3073, t3074, t3075, t3076, t3077, t3078, 
            t3079, t3080, t3081, t3082, t3083, t3084, t3085, t3086, 
            t3087, t3088, t3089, t3090, t3091, t3092, t3093, t3094, 
            t3095, t3096, t3097, t3098, t3099, t3100, t3101, t3102, 
            t3103, t3104, t3105, t3106;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s956 = svld2_f64(pg1, (X + ((2)*(j1))));
        s957 = s956.v0;
        s958 = s956.v1;
        s959 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s960 = s959.v0;
        s961 = s959.v1;
        s962 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s963 = s962.v0;
        s964 = s962.v1;
        s965 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s966 = s965.v0;
        s967 = s965.v1;
        s968 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s969 = s968.v0;
        s970 = s968.v1;
        s971 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s972 = s971.v0;
        s973 = s971.v1;
        s974 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s975 = s974.v0;
        s976 = s974.v1;
        s977 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s978 = s977.v0;
        s979 = s977.v1;
        s980 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s981 = s980.v0;
        s982 = s980.v1;
        s983 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s984 = s983.v0;
        s985 = s983.v1;
        s986 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s987 = s986.v0;
        s988 = s986.v1;
        s989 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s990 = s989.v0;
        s991 = s989.v1;
        s992 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s993 = s992.v0;
        s994 = s992.v1;
        s995 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s996 = s995.v0;
        s997 = s995.v1;
        s998 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s999 = s998.v0;
        s1000 = s998.v1;
        s1001 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s1002 = s1001.v0;
        s1003 = s1001.v1;
        t3019 = svadd_f64_x(pg1, s957, s981);
        t3020 = svadd_f64_x(pg1, s958, s982);
        t3021 = svsub_f64_x(pg1, s957, s981);
        t3022 = svsub_f64_x(pg1, s958, s982);
        t3023 = svadd_f64_x(pg1, s969, s993);
        t3024 = svadd_f64_x(pg1, s970, s994);
        t3025 = svsub_f64_x(pg1, s969, s993);
        t3026 = svsub_f64_x(pg1, s970, s994);
        t3027 = svadd_f64_x(pg1, t3019, t3023);
        t3028 = svadd_f64_x(pg1, t3020, t3024);
        t3029 = svsub_f64_x(pg1, t3019, t3023);
        t3030 = svsub_f64_x(pg1, t3020, t3024);
        t3031 = svadd_f64_x(pg1, t3021, t3026);
        t3032 = svsub_f64_x(pg1, t3022, t3025);
        t3033 = svsub_f64_x(pg1, t3021, t3026);
        t3034 = svadd_f64_x(pg1, t3022, t3025);
        t3035 = svadd_f64_x(pg1, s960, s984);
        t3036 = svadd_f64_x(pg1, s961, s985);
        t3037 = svsub_f64_x(pg1, s960, s984);
        t3038 = svsub_f64_x(pg1, s961, s985);
        t3039 = svadd_f64_x(pg1, s972, s996);
        t3040 = svadd_f64_x(pg1, s973, s997);
        t3041 = svsub_f64_x(pg1, s972, s996);
        t3042 = svsub_f64_x(pg1, s973, s997);
        t3043 = svadd_f64_x(pg1, t3035, t3039);
        t3044 = svadd_f64_x(pg1, t3036, t3040);
        a1970 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3035, t3039), 0.70710678118654757);
        a1971 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3036, t3040), 0.70710678118654757);
        s1004 = svadd_f64_x(pg1, a1970, a1971);
        s1005 = svsub_f64_x(pg1, a1971, a1970);
        t3045 = svadd_f64_x(pg1, t3037, t3042);
        t3046 = svsub_f64_x(pg1, t3038, t3041);
        t3047 = svsub_f64_x(pg1, t3037, t3042);
        t3048 = svadd_f64_x(pg1, t3038, t3041);
        s1082 = svmla_n_f64_x(pg1, t3045, t3046, 0.41421356237309509);
        s1006 = svmul_n_f64_x(pg1, s1082, 0.92387953251128674);
        s1083 = svmls_n_f64_x(pg1, t3046, t3045, 0.41421356237309509);
        s1007 = svmul_n_f64_x(pg1, s1083, 0.92387953251128674);
        s1084 = svmla_n_f64_x(pg1, t3047, t3048, 2.4142135623730949);
        s1008 = svmul_n_f64_x(pg1, s1084, 0.38268343236508978);
        s1085 = svmls_n_f64_x(pg1, t3048, t3047, 2.4142135623730949);
        s1009 = svmul_n_f64_x(pg1, s1085, 0.38268343236508978);
        t3049 = svadd_f64_x(pg1, s963, s987);
        t3050 = svadd_f64_x(pg1, s964, s988);
        t3051 = svsub_f64_x(pg1, s963, s987);
        t3052 = svsub_f64_x(pg1, s964, s988);
        t3053 = svadd_f64_x(pg1, s975, s999);
        t3054 = svadd_f64_x(pg1, s976, s1000);
        t3055 = svsub_f64_x(pg1, s975, s999);
        t3056 = svsub_f64_x(pg1, s976, s1000);
        t3057 = svadd_f64_x(pg1, t3049, t3053);
        t3058 = svadd_f64_x(pg1, t3050, t3054);
        t3059 = svsub_f64_x(pg1, t3049, t3053);
        t3060 = svsub_f64_x(pg1, t3050, t3054);
        a1972 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t3051, t3056), 0.70710678118654757);
        a1973 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3052, t3055), 0.70710678118654757);
        s1010 = svadd_f64_x(pg1, a1972, a1973);
        s1011 = svsub_f64_x(pg1, a1973, a1972);
        a1974 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t3052, t3055), 0.70710678118654757);
        a1975 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3051, t3056), 0.70710678118654757);
        s1012 = svsub_f64_x(pg1, a1974, a1975);
        s1013 = svadd_f64_x(pg1, a1975, a1974);
        t3061 = svadd_f64_x(pg1, s966, s990);
        t3062 = svadd_f64_x(pg1, s967, s991);
        t3063 = svsub_f64_x(pg1, s966, s990);
        t3064 = svsub_f64_x(pg1, s967, s991);
        t3065 = svadd_f64_x(pg1, s978, s1002);
        t3066 = svadd_f64_x(pg1, s979, s1003);
        t3067 = svsub_f64_x(pg1, s978, s1002);
        t3068 = svsub_f64_x(pg1, s979, s1003);
        t3069 = svadd_f64_x(pg1, t3061, t3065);
        t3070 = svadd_f64_x(pg1, t3062, t3066);
        a1976 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3062, t3066), 0.70710678118654757);
        a1977 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3061, t3065), 0.70710678118654757);
        s1014 = svsub_f64_x(pg1, a1976, a1977);
        s1015 = svadd_f64_x(pg1, a1977, a1976);
        t3071 = svadd_f64_x(pg1, t3063, t3068);
        t3072 = svsub_f64_x(pg1, t3064, t3067);
        t3073 = svsub_f64_x(pg1, t3063, t3068);
        t3074 = svadd_f64_x(pg1, t3064, t3067);
        s1086 = svmla_n_f64_x(pg1, t3071, t3072, 2.4142135623730949);
        s1016 = svmul_n_f64_x(pg1, s1086, 0.38268343236508978);
        s1087 = svmls_n_f64_x(pg1, t3072, t3071, 2.4142135623730949);
        s1017 = svmul_n_f64_x(pg1, s1087, 0.38268343236508978);
        s1088 = svmla_n_f64_x(pg1, t3073, t3074, 0.41421356237309509);
        s1018 = svmul_n_f64_x(pg1, s1088, 0.92387953251128674);
        s1089 = svmls_n_f64_x(pg1, t3073, t3074, 2.4142135623730949);
        s1019 = svmul_n_f64_x(pg1, s1089, 0.38268343236508978);
        t3075 = svadd_f64_x(pg1, t3027, t3057);
        t3076 = svadd_f64_x(pg1, t3028, t3058);
        t3077 = svsub_f64_x(pg1, t3027, t3057);
        t3078 = svsub_f64_x(pg1, t3028, t3058);
        t3079 = svadd_f64_x(pg1, t3043, t3069);
        t3080 = svadd_f64_x(pg1, t3044, t3070);
        t3081 = svsub_f64_x(pg1, t3043, t3069);
        t3082 = svsub_f64_x(pg1, t3044, t3070);
        s1020 = svadd_f64_x(pg1, t3075, t3079);
        s1021 = svadd_f64_x(pg1, t3076, t3080);
        s1022 = svsub_f64_x(pg1, t3075, t3079);
        s1023 = svsub_f64_x(pg1, t3076, t3080);
        s1024 = svadd_f64_x(pg1, t3077, t3082);
        s1025 = svsub_f64_x(pg1, t3078, t3081);
        s1026 = svsub_f64_x(pg1, t3077, t3082);
        s1027 = svadd_f64_x(pg1, t3078, t3081);
        t3083 = svadd_f64_x(pg1, t3031, s1010);
        t3084 = svadd_f64_x(pg1, t3032, s1011);
        t3085 = svsub_f64_x(pg1, t3031, s1010);
        t3086 = svsub_f64_x(pg1, t3032, s1011);
        t3087 = svadd_f64_x(pg1, s1006, s1016);
        t3088 = svadd_f64_x(pg1, s1007, s1017);
        t3089 = svsub_f64_x(pg1, s1006, s1016);
        t3090 = svsub_f64_x(pg1, s1007, s1017);
        s1028 = svadd_f64_x(pg1, t3083, t3087);
        s1029 = svadd_f64_x(pg1, t3084, t3088);
        s1030 = svsub_f64_x(pg1, t3083, t3087);
        s1031 = svsub_f64_x(pg1, t3084, t3088);
        s1032 = svadd_f64_x(pg1, t3085, t3090);
        s1033 = svsub_f64_x(pg1, t3086, t3089);
        s1034 = svsub_f64_x(pg1, t3085, t3090);
        s1035 = svadd_f64_x(pg1, t3086, t3089);
        t3091 = svadd_f64_x(pg1, t3029, t3060);
        t3092 = svsub_f64_x(pg1, t3030, t3059);
        t3093 = svsub_f64_x(pg1, t3029, t3060);
        t3094 = svadd_f64_x(pg1, t3030, t3059);
        t3095 = svadd_f64_x(pg1, s1004, s1014);
        t3096 = svsub_f64_x(pg1, s1005, s1015);
        t3097 = svsub_f64_x(pg1, s1004, s1014);
        t3098 = svadd_f64_x(pg1, s1005, s1015);
        s1036 = svadd_f64_x(pg1, t3091, t3095);
        s1037 = svadd_f64_x(pg1, t3092, t3096);
        s1038 = svsub_f64_x(pg1, t3091, t3095);
        s1039 = svsub_f64_x(pg1, t3092, t3096);
        s1040 = svadd_f64_x(pg1, t3093, t3098);
        s1041 = svsub_f64_x(pg1, t3094, t3097);
        s1042 = svsub_f64_x(pg1, t3093, t3098);
        s1043 = svadd_f64_x(pg1, t3094, t3097);
        t3099 = svadd_f64_x(pg1, t3033, s1012);
        t3100 = svsub_f64_x(pg1, t3034, s1013);
        t3101 = svsub_f64_x(pg1, t3033, s1012);
        t3102 = svadd_f64_x(pg1, t3034, s1013);
        t3103 = svsub_f64_x(pg1, s1008, s1018);
        t3104 = svadd_f64_x(pg1, s1009, s1019);
        t3105 = svadd_f64_x(pg1, s1008, s1018);
        t3106 = svsub_f64_x(pg1, s1009, s1019);
        s1044 = svadd_f64_x(pg1, t3099, t3103);
        s1045 = svadd_f64_x(pg1, t3100, t3104);
        s1046 = svsub_f64_x(pg1, t3099, t3103);
        s1047 = svsub_f64_x(pg1, t3100, t3104);
        s1048 = svadd_f64_x(pg1, t3101, t3106);
        s1049 = svsub_f64_x(pg1, t3102, t3105);
        s1050 = svsub_f64_x(pg1, t3101, t3106);
        s1051 = svadd_f64_x(pg1, t3102, t3105);
        a1978 = (TW1 + ((30)*(j1)));
        a1979 = svld1_gather_u64offset_f64(pg1, a1978, svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1980 = svld1_gather_u64offset_f64(pg1, (a1978 + 1), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1052 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1980, s1029), a1979, s1028);
        s1053 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1979, s1029), a1980, s1028);
        a1981 = svld1_gather_u64offset_f64(pg1, (a1978 + 2), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1982 = svld1_gather_u64offset_f64(pg1, (a1978 + 3), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1054 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1982, s1037), a1981, s1036);
        s1055 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1981, s1037), a1982, s1036);
        a1983 = svld1_gather_u64offset_f64(pg1, (a1978 + 4), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1984 = svld1_gather_u64offset_f64(pg1, (a1978 + 5), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1056 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1984, s1045), a1983, s1044);
        s1057 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1983, s1045), a1984, s1044);
        a1985 = svld1_gather_u64offset_f64(pg1, (a1978 + 6), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1986 = svld1_gather_u64offset_f64(pg1, (a1978 + 7), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1058 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1986, s1025), a1985, s1024);
        s1059 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1985, s1025), a1986, s1024);
        a1987 = svld1_gather_u64offset_f64(pg1, (a1978 + 8), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1988 = svld1_gather_u64offset_f64(pg1, (a1978 + 9), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1060 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1988, s1033), a1987, s1032);
        s1061 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1987, s1033), a1988, s1032);
        a1989 = svld1_gather_u64offset_f64(pg1, (a1978 + 10), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1990 = svld1_gather_u64offset_f64(pg1, (a1978 + 11), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1062 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1990, s1041), a1989, s1040);
        s1063 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1989, s1041), a1990, s1040);
        a1991 = svld1_gather_u64offset_f64(pg1, (a1978 + 12), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1992 = svld1_gather_u64offset_f64(pg1, (a1978 + 13), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1064 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1992, s1049), a1991, s1048);
        s1065 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1991, s1049), a1992, s1048);
        a1993 = svld1_gather_u64offset_f64(pg1, (a1978 + 14), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1994 = svld1_gather_u64offset_f64(pg1, (a1978 + 15), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1066 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1994, s1023), a1993, s1022);
        s1067 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1993, s1023), a1994, s1022);
        a1995 = svld1_gather_u64offset_f64(pg1, (a1978 + 16), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1996 = svld1_gather_u64offset_f64(pg1, (a1978 + 17), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1068 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1996, s1031), a1995, s1030);
        s1069 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1995, s1031), a1996, s1030);
        a1997 = svld1_gather_u64offset_f64(pg1, (a1978 + 18), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a1998 = svld1_gather_u64offset_f64(pg1, (a1978 + 19), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1070 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1998, s1039), a1997, s1038);
        s1071 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1997, s1039), a1998, s1038);
        a1999 = svld1_gather_u64offset_f64(pg1, (a1978 + 20), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a2000 = svld1_gather_u64offset_f64(pg1, (a1978 + 21), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1072 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2000, s1047), a1999, s1046);
        s1073 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1999, s1047), a2000, s1046);
        a2001 = svld1_gather_u64offset_f64(pg1, (a1978 + 22), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a2002 = svld1_gather_u64offset_f64(pg1, (a1978 + 23), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1074 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2002, s1027), a2001, s1026);
        s1075 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2001, s1027), a2002, s1026);
        a2003 = svld1_gather_u64offset_f64(pg1, (a1978 + 24), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a2004 = svld1_gather_u64offset_f64(pg1, (a1978 + 25), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1076 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2004, s1035), a2003, s1034);
        s1077 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2003, s1035), a2004, s1034);
        a2005 = svld1_gather_u64offset_f64(pg1, (a1978 + 26), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a2006 = svld1_gather_u64offset_f64(pg1, (a1978 + 27), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1078 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2006, s1043), a2005, s1042);
        s1079 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2005, s1043), a2006, s1042);
        a2007 = svld1_gather_u64offset_f64(pg1, (a1978 + 28), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        a2008 = svld1_gather_u64offset_f64(pg1, (a1978 + 29), svindex_u64(0, (int64_t)(30 * sizeof(float64_t))));
        s1080 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2008, s1051), a2007, s1050);
        s1081 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2007, s1051), a2008, s1050);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1020);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1021);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1052);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1053);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1054);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1055);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1056);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1057);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1058);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1059);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1060);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1061);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1062);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1063);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1064);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1065);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1066);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1067);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1068);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1069);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1070);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1071);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1072);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1073);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1074);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1075);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1076);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1077);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1078);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1079);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1080);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((32)*(j1)))), svindex_u64(0, (int64_t)(32 * sizeof(float64_t))), s1081);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
