/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft12c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    int l1, m1;
    svfloat64x2_t s878, s881, s884, s887, s890, s893, s896, s899, 
            s902, s905, s908, s911, svex2_13, svex2_14, svex2_15, svex2_16, 
            svex2_17, svex2_18, svex2_19, svex2_20, svex2_21, svex2_22, svex2_23, svex2_24;
    svfloat64_t s879, s880, s882, s883, s885, s886, s888, s889, 
            s891, s892, s894, s895, s897, s898, s900, s901, 
            s903, s904, s906, s907, s909, s910, s912, s913, 
            s914, s915, s916, s917, s918, s919, s920, s921, 
            s922, s923, s924, s925, s926, s927, s928, s929, 
            s930, s931, s932, s933, s934, s935, s936, s937, 
            t2714, t2715, t2716, t2717, t2718, t2719, t2720, t2721, 
            t2722, t2723, t2724, t2725, t2726, t2727, t2728, t2729, 
            t2730, t2731, t2732, t2733, t2734, t2735, t2736, t2737, 
            t2738, t2739, t2740, t2741, t2742, t2743, t2744, t2745, 
            t2746, t2747, t2748, t2749, t2750, t2751, t2752, t2753, 
            t2754, t2755, t2756, t2757, t2758, t2759, t2760, t2761, 
            t2762, t2763, t2764, t2765, t2766, t2767, t2768, t2769, 
            t2770, t2771, t2772, t2773, t2774, t2775, t2776, t2777;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s878 = svld2_f64(pg1, (X + ((2)*(k1))));
        s879 = s878.v0;
        s880 = s878.v1;
        s881 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s882 = s881.v0;
        s883 = s881.v1;
        s884 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s885 = s884.v0;
        s886 = s884.v1;
        s887 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s888 = s887.v0;
        s889 = s887.v1;
        s890 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s891 = s890.v0;
        s892 = s890.v1;
        s893 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s894 = s893.v0;
        s895 = s893.v1;
        s896 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s897 = s896.v0;
        s898 = s896.v1;
        s899 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s900 = s899.v0;
        s901 = s899.v1;
        s902 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s903 = s902.v0;
        s904 = s902.v1;
        s905 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s906 = s905.v0;
        s907 = s905.v1;
        s908 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s909 = s908.v0;
        s910 = s908.v1;
        s911 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s912 = s911.v0;
        s913 = s911.v1;
        t2714 = svadd_f64_x(pg1, s879, s897);
        t2715 = svadd_f64_x(pg1, s880, s898);
        t2716 = svsub_f64_x(pg1, s879, s897);
        t2717 = svsub_f64_x(pg1, s880, s898);
        t2718 = svadd_f64_x(pg1, s888, s906);
        t2719 = svadd_f64_x(pg1, s889, s907);
        t2720 = svsub_f64_x(pg1, s888, s906);
        t2721 = svsub_f64_x(pg1, s889, s907);
        t2722 = svadd_f64_x(pg1, t2714, t2718);
        t2723 = svadd_f64_x(pg1, t2715, t2719);
        t2724 = svsub_f64_x(pg1, t2714, t2718);
        t2725 = svsub_f64_x(pg1, t2715, t2719);
        t2726 = svadd_f64_x(pg1, t2716, t2721);
        t2727 = svsub_f64_x(pg1, t2717, t2720);
        t2728 = svsub_f64_x(pg1, t2716, t2721);
        t2729 = svadd_f64_x(pg1, t2717, t2720);
        t2730 = svadd_f64_x(pg1, s882, s900);
        t2731 = svadd_f64_x(pg1, s883, s901);
        t2732 = svsub_f64_x(pg1, s882, s900);
        t2733 = svsub_f64_x(pg1, s883, s901);
        t2734 = svadd_f64_x(pg1, s891, s909);
        t2735 = svadd_f64_x(pg1, s892, s910);
        t2736 = svsub_f64_x(pg1, s891, s909);
        t2737 = svsub_f64_x(pg1, s892, s910);
        t2738 = svadd_f64_x(pg1, t2730, t2734);
        t2739 = svadd_f64_x(pg1, t2731, t2735);
        t2740 = svsub_f64_x(pg1, t2730, t2734);
        t2741 = svsub_f64_x(pg1, t2731, t2735);
        s930 = svmla_n_f64_x(pg1, t2740, t2741, 1.7320508075688772);
        s914 = svmul_n_f64_x(pg1, s930, 0.5);
        s931 = svmls_n_f64_x(pg1, t2741, t2740, 1.7320508075688772);
        s915 = svmul_n_f64_x(pg1, s931, 0.5);
        t2742 = svadd_f64_x(pg1, t2732, t2737);
        t2743 = svsub_f64_x(pg1, t2733, t2736);
        t2744 = svsub_f64_x(pg1, t2732, t2737);
        t2745 = svadd_f64_x(pg1, t2733, t2736);
        s932 = svmla_n_f64_x(pg1, t2742, t2743, 0.57735026918962584);
        s916 = svmul_n_f64_x(pg1, s932, 0.8660254037844386);
        s933 = svmls_n_f64_x(pg1, t2743, t2742, 0.57735026918962584);
        s917 = svmul_n_f64_x(pg1, s933, 0.8660254037844386);
        t2746 = svadd_f64_x(pg1, s885, s903);
        t2747 = svadd_f64_x(pg1, s886, s904);
        t2748 = svsub_f64_x(pg1, s885, s903);
        t2749 = svsub_f64_x(pg1, s886, s904);
        t2750 = svadd_f64_x(pg1, s894, s912);
        t2751 = svadd_f64_x(pg1, s895, s913);
        t2752 = svsub_f64_x(pg1, s894, s912);
        t2753 = svsub_f64_x(pg1, s895, s913);
        t2754 = svadd_f64_x(pg1, t2746, t2750);
        t2755 = svadd_f64_x(pg1, t2747, t2751);
        t2756 = svsub_f64_x(pg1, t2746, t2750);
        t2757 = svsub_f64_x(pg1, t2747, t2751);
        s934 = svmls_n_f64_x(pg1, t2757, t2756, 0.57735026918962584);
        s918 = svmul_n_f64_x(pg1, s934, 0.8660254037844386);
        s935 = svmla_n_f64_x(pg1, t2756, t2757, 0.57735026918962584);
        s919 = svmul_n_f64_x(pg1, s935, 0.8660254037844386);
        t2758 = svadd_f64_x(pg1, t2748, t2753);
        t2759 = svsub_f64_x(pg1, t2749, t2752);
        t2760 = svsub_f64_x(pg1, t2748, t2753);
        t2761 = svadd_f64_x(pg1, t2749, t2752);
        s936 = svmla_n_f64_x(pg1, t2758, t2759, 1.7320508075688772);
        s920 = svmul_n_f64_x(pg1, s936, 0.5);
        s937 = svmls_n_f64_x(pg1, t2759, t2758, 1.7320508075688772);
        s921 = svmul_n_f64_x(pg1, s937, 0.5);
        t2762 = svadd_f64_x(pg1, t2738, t2754);
        t2763 = svadd_f64_x(pg1, t2739, t2755);
        t2764 = svmls_n_f64_x(pg1, t2722, t2762, 0.5);
        t2765 = svmls_n_f64_x(pg1, t2723, t2763, 0.5);
        s922 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2739, t2755), 0.8660254037844386);
        s923 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2738, t2754), 0.8660254037844386);
        t2766 = svadd_f64_x(pg1, s916, s920);
        t2767 = svadd_f64_x(pg1, s917, s921);
        t2768 = svmls_n_f64_x(pg1, t2726, t2766, 0.5);
        t2769 = svmls_n_f64_x(pg1, t2727, t2767, 0.5);
        s924 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s917, s921), 0.8660254037844386);
        s925 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s916, s920), 0.8660254037844386);
        t2770 = svadd_f64_x(pg1, s914, s918);
        t2771 = svsub_f64_x(pg1, s915, s919);
        t2772 = svmls_n_f64_x(pg1, t2724, t2770, 0.5);
        t2773 = svmls_n_f64_x(pg1, t2725, t2771, 0.5);
        s926 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s915, s919), 0.8660254037844386);
        s927 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s914, s918), 0.8660254037844386);
        t2774 = svsub_f64_x(pg1, t2745, t2760);
        t2775 = svadd_f64_x(pg1, t2744, t2761);
        t2776 = svmls_n_f64_x(pg1, t2728, t2774, 0.5);
        t2777 = svmla_n_f64_x(pg1, t2729, t2775, 0.5);
        s928 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2761, t2744), 0.8660254037844386);
        s929 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t2745, t2760), 0.8660254037844386);
        svex2_13.v0 = svadd_f64_x(pg1, t2722, t2762);
        svex2_13.v1 = svadd_f64_x(pg1, t2723, t2763);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_13);
        svex2_14.v0 = svadd_f64_x(pg1, t2726, t2766);
        svex2_14.v1 = svadd_f64_x(pg1, t2727, t2767);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_14);
        svex2_15.v0 = svadd_f64_x(pg1, t2724, t2770);
        svex2_15.v1 = svadd_f64_x(pg1, t2725, t2771);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_15);
        svex2_16.v0 = svadd_f64_x(pg1, t2728, t2774);
        svex2_16.v1 = svsub_f64_x(pg1, t2729, t2775);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_16);
        svex2_17.v0 = svadd_f64_x(pg1, t2764, s922);
        svex2_17.v1 = svsub_f64_x(pg1, t2765, s923);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_17);
        svex2_18.v0 = svadd_f64_x(pg1, t2768, s924);
        svex2_18.v1 = svsub_f64_x(pg1, t2769, s925);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_18);
        svex2_19.v0 = svadd_f64_x(pg1, t2772, s926);
        svex2_19.v1 = svsub_f64_x(pg1, t2773, s927);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_19);
        svex2_20.v0 = svadd_f64_x(pg1, t2776, s928);
        svex2_20.v1 = svsub_f64_x(pg1, t2777, s929);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_20);
        svex2_21.v0 = svsub_f64_x(pg1, t2764, s922);
        svex2_21.v1 = svadd_f64_x(pg1, t2765, s923);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_21);
        svex2_22.v0 = svsub_f64_x(pg1, t2768, s924);
        svex2_22.v1 = svadd_f64_x(pg1, t2769, s925);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_22);
        svex2_23.v0 = svsub_f64_x(pg1, t2772, s926);
        svex2_23.v1 = svadd_f64_x(pg1, t2773, s927);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_23);
        svex2_24.v0 = svsub_f64_x(pg1, t2776, s928);
        svex2_24.v1 = svadd_f64_x(pg1, t2777, s929);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_24);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
