/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft14a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a3574;
    svfloat64x2_t s2898, s2901, s2904, s2907, s2910, s2913, s2916, s2919, 
            s2922, s2925, s2928, s2931, s2934, s2937;
    svfloat64_t a3575, a3576, a3577, a3578, a3579, a3580, a3581, a3582, 
            a3583, a3584, a3585, a3586, a3587, a3588, a3589, a3590, 
            a3591, a3592, a3593, a3594, a3595, a3596, a3597, a3598, 
            a3599, a3600, s2899, s2900, s2902, s2903, s2905, s2906, 
            s2908, s2909, s2911, s2912, s2914, s2915, s2917, s2918, 
            s2920, s2921, s2923, s2924, s2926, s2927, s2929, s2930, 
            s2932, s2933, s2935, s2936, s2938, s2939, s2940, s2941, 
            s2942, s2943, s2944, s2945, s2946, s2947, s2948, s2949, 
            s2950, s2951, s2952, s2953, s2954, s2955, s2956, s2957, 
            s2958, s2959, s2960, s2961, s2962, s2963, s2964, s2965, 
            s2966, s2967, s2968, s2969, s2970, s2971, s2972, s2973, 
            s2974, s2975, s2976, s2977, s2978, s2979, s2980, s2981, 
            s2982, s2983, s2984, s2985, s2986, s2987, s2988, s2989, 
            s2990, s2991, s2992, s2993, s2994, s2995, s2996, s2997, 
            s2998, s2999, s3000, s3001, s3002, s3003, s3004, s3005, 
            s3006, s3007, s3008, s3009, s3010, s3011, s3012, s3013, 
            s3014, s3015, s3016, s3017, s3018, s3019, s3020, s3021, 
            s3022, s3023, s3024, s3025, s3026, s3027, s3028, s3029, 
            s3030, s3031, s3032, s3033, s3034, s3035, s3036, s3037, 
            s3038, s3039, s3040, s3041, s3042, s3043, s3044, s3045, 
            s3046, s3047, s3048, s3049, s3050, s3051, s3052, s3053, 
            s3054, s3055, s3056, s3057, s3058, s3059, s3060, s3061, 
            s3062, s3063, s3064, s3065, s3066, s3067, s3068, s3069, 
            s3070, s3071, s3072, s3073, s3074, s3075, s3076, s3077, 
            s3078, s3079, s3080, s3081, s3082, s3083, s3084, s3085, 
            s3086, s3087, s3088, s3089, s3090, s3091, s3092, s3093, 
            s3094, s3095, s3096, s3097, s3098, s3099, s3100, s3101, 
            t6735, t6736, t6737, t6738, t6739, t6740, t6741, t6742, 
            t6743, t6744, t6745, t6746, t6747, t6748, t6749, t6750, 
            t6751, t6752, t6753, t6754, t6755, t6756, t6757, t6758, 
            t6759, t6760, t6761, t6762, t6763, t6764, t6765, t6766, 
            t6767, t6768, t6769, t6770, t6771, t6772, t6773, t6774, 
            t6775, t6776, t6777, t6778, t6779, t6780, t6781, t6782, 
            t6783, t6784, t6785, t6786, t6787, t6788, t6789, t6790, 
            t6791, t6792, t6793, t6794, t6795, t6796, t6797, t6798, 
            t6799, t6800, t6801, t6802, t6803, t6804, t6805, t6806, 
            t6807, t6808, t6809, t6810, t6811, t6812, t6813, t6814, 
            t6815, t6816, t6817, t6818, t6819, t6820, t6821, t6822, 
            t6823, t6824, t6825, t6826, t6827, t6828, t6829, t6830, 
            t6831, t6832, t6833, t6834, t6835, t6836, t6837, t6838, 
            t6839, t6840, t6841, t6842, t6843, t6844, t6845, t6846, 
            t6847, t6848, t6849, t6850, t6851, t6852, t6853, t6854, 
            t6855, t6856, t6857, t6858, t6859, t6860, t6861, t6862, 
            t6863, t6864, t6865, t6866;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s2898 = svld2_f64(pg1, (X + ((2)*(j1))));
        s2899 = s2898.v0;
        s2900 = s2898.v1;
        s2901 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s2902 = s2901.v0;
        s2903 = s2901.v1;
        s2904 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s2905 = s2904.v0;
        s2906 = s2904.v1;
        s2907 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s2908 = s2907.v0;
        s2909 = s2907.v1;
        s2910 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s2911 = s2910.v0;
        s2912 = s2910.v1;
        s2913 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s2914 = s2913.v0;
        s2915 = s2913.v1;
        s2916 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s2917 = s2916.v0;
        s2918 = s2916.v1;
        s2919 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s2920 = s2919.v0;
        s2921 = s2919.v1;
        s2922 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s2923 = s2922.v0;
        s2924 = s2922.v1;
        s2925 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s2926 = s2925.v0;
        s2927 = s2925.v1;
        s2928 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s2929 = s2928.v0;
        s2930 = s2928.v1;
        s2931 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s2932 = s2931.v0;
        s2933 = s2931.v1;
        s2934 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s2935 = s2934.v0;
        s2936 = s2934.v1;
        s2937 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s2938 = s2937.v0;
        s2939 = s2937.v1;
        t6735 = svadd_f64_x(pg1, s2911, s2923);
        t6736 = svadd_f64_x(pg1, s2912, s2924);
        t6737 = svadd_f64_x(pg1, s2905, t6735);
        t6738 = svadd_f64_x(pg1, s2906, t6736);
        t6739 = svmls_n_f64_x(pg1, s2905, t6735, 0.5);
        t6740 = svmls_n_f64_x(pg1, s2906, t6736, 0.5);
        s2940 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2912, s2924), 0.8660254037844386);
        s2941 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2911, s2923), 0.8660254037844386);
        t6741 = svadd_f64_x(pg1, t6739, s2940);
        t6742 = svsub_f64_x(pg1, t6740, s2941);
        t6743 = svsub_f64_x(pg1, t6739, s2940);
        t6744 = svadd_f64_x(pg1, t6740, s2941);
        t6745 = svadd_f64_x(pg1, s2935, s2929);
        t6746 = svadd_f64_x(pg1, s2936, s2930);
        t6747 = svadd_f64_x(pg1, s2917, t6745);
        t6748 = svadd_f64_x(pg1, s2918, t6746);
        t6749 = svmls_n_f64_x(pg1, s2917, t6745, 0.5);
        t6750 = svmls_n_f64_x(pg1, s2918, t6746, 0.5);
        s2942 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2936, s2930), 0.8660254037844386);
        s2943 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2935, s2929), 0.8660254037844386);
        t6751 = svadd_f64_x(pg1, t6749, s2942);
        t6752 = svsub_f64_x(pg1, t6750, s2943);
        t6753 = svsub_f64_x(pg1, t6749, s2942);
        t6754 = svadd_f64_x(pg1, t6750, s2943);
        s3058 = svmla_n_f64_x(pg1, t6751, t6752, 1.7320508075688772);
        s2944 = svmul_n_f64_x(pg1, s3058, 0.5);
        s3059 = svmls_n_f64_x(pg1, t6752, t6751, 1.7320508075688772);
        s2945 = svmul_n_f64_x(pg1, s3059, 0.5);
        s3060 = svmls_n_f64_x(pg1, t6754, t6753, 0.57735026918962584);
        s2946 = svmul_n_f64_x(pg1, s3060, 0.8660254037844386);
        s3061 = svmla_n_f64_x(pg1, t6753, t6754, 0.57735026918962584);
        s2947 = svmul_n_f64_x(pg1, s3061, 0.8660254037844386);
        t6755 = svadd_f64_x(pg1, t6737, t6747);
        t6756 = svadd_f64_x(pg1, t6738, t6748);
        t6757 = svadd_f64_x(pg1, t6741, s2944);
        t6758 = svadd_f64_x(pg1, t6742, s2945);
        t6759 = svsub_f64_x(pg1, t6741, s2944);
        t6760 = svsub_f64_x(pg1, t6742, s2945);
        t6761 = svadd_f64_x(pg1, t6743, s2946);
        t6762 = svsub_f64_x(pg1, t6744, s2947);
        t6763 = svsub_f64_x(pg1, t6743, s2946);
        t6764 = svadd_f64_x(pg1, t6744, s2947);
        t6765 = svadd_f64_x(pg1, s2899, t6755);
        t6766 = svadd_f64_x(pg1, s2900, t6756);
        t6767 = svmls_n_f64_x(pg1, s2899, t6755, 0.16666666666666666);
        t6768 = svmls_n_f64_x(pg1, s2900, t6756, 0.16666666666666666);
        s3062 = svmla_n_f64_x(pg1, t6757, t6758, 0.41908315722758349);
        s2948 = svmul_n_f64_x(pg1, s3062, 0.4066888930575896);
        s3063 = svmls_n_f64_x(pg1, t6758, t6757, 0.41908315722758349);
        s2949 = svmul_n_f64_x(pg1, s3063, 0.4066888930575896);
        s3064 = svmla_n_f64_x(pg1, t6761, t6762, 0.49572725516748389);
        s2950 = svmul_n_f64_x(pg1, s3064, 0.39507823426270006);
        s3065 = svmls_n_f64_x(pg1, t6762, t6761, 0.49572725516748389);
        s2951 = svmul_n_f64_x(pg1, s3065, 0.39507823426270006);
        s2952 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t6738, t6748), 0.44095855184409843);
        s2953 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t6737, t6747), 0.44095855184409843);
        s3066 = svmls_n_f64_x(pg1, t6759, t6760, 0.49572725516748389);
        s2954 = svmul_n_f64_x(pg1, s3066, 0.39507823426270006);
        s3067 = svmla_n_f64_x(pg1, t6759, t6760, 2.0172382889501304);
        s2955 = svmul_n_f64_x(pg1, s3067, 0.1958510486474645);
        s3068 = svmls_n_f64_x(pg1, t6764, t6763, 2.386161273135941);
        s2956 = svmul_n_f64_x(pg1, s3068, 0.17043646531196566);
        s3069 = svmla_n_f64_x(pg1, t6763, t6764, 2.386161273135941);
        s2957 = svmul_n_f64_x(pg1, s3069, 0.17043646531196566);
        t6769 = svadd_f64_x(pg1, s2950, s2954);
        t6770 = svadd_f64_x(pg1, s2951, s2955);
        t6771 = svadd_f64_x(pg1, t6767, t6769);
        t6772 = svadd_f64_x(pg1, t6768, t6770);
        t6773 = svmls_n_f64_x(pg1, t6767, t6769, 0.5);
        t6774 = svmls_n_f64_x(pg1, t6768, t6770, 0.5);
        s2958 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2951, s2955), 0.8660254037844386);
        s2959 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2950, s2954), 0.8660254037844386);
        t6775 = svadd_f64_x(pg1, t6773, s2958);
        t6776 = svsub_f64_x(pg1, t6774, s2959);
        t6777 = svsub_f64_x(pg1, t6773, s2958);
        t6778 = svadd_f64_x(pg1, t6774, s2959);
        t6779 = svadd_f64_x(pg1, s2952, s2956);
        t6780 = svadd_f64_x(pg1, s2953, s2957);
        t6781 = svadd_f64_x(pg1, s2948, t6779);
        t6782 = svsub_f64_x(pg1, s2949, t6780);
        t6783 = svmls_n_f64_x(pg1, s2948, t6779, 0.5);
        t6784 = svmla_n_f64_x(pg1, s2949, t6780, 0.5);
        s2960 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2957, s2953), 0.8660254037844386);
        s2961 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2952, s2956), 0.8660254037844386);
        t6785 = svadd_f64_x(pg1, t6783, s2960);
        t6786 = svsub_f64_x(pg1, t6784, s2961);
        t6787 = svsub_f64_x(pg1, t6783, s2960);
        t6788 = svadd_f64_x(pg1, t6784, s2961);
        s3070 = svmla_n_f64_x(pg1, t6785, t6786, 1.7320508075688772);
        s2962 = svmul_n_f64_x(pg1, s3070, 0.5);
        s3071 = svmls_n_f64_x(pg1, t6786, t6785, 1.7320508075688772);
        s2963 = svmul_n_f64_x(pg1, s3071, 0.5);
        s3072 = svmls_n_f64_x(pg1, t6788, t6787, 0.57735026918962584);
        s2964 = svmul_n_f64_x(pg1, s3072, 0.8660254037844386);
        s3073 = svmla_n_f64_x(pg1, t6787, t6788, 0.57735026918962584);
        s2965 = svmul_n_f64_x(pg1, s3073, 0.8660254037844386);
        t6789 = svadd_f64_x(pg1, t6771, t6781);
        t6790 = svadd_f64_x(pg1, t6772, t6782);
        t6791 = svsub_f64_x(pg1, t6771, t6781);
        t6792 = svsub_f64_x(pg1, t6772, t6782);
        t6793 = svadd_f64_x(pg1, t6775, s2962);
        t6794 = svadd_f64_x(pg1, t6776, s2963);
        t6795 = svsub_f64_x(pg1, t6775, s2962);
        t6796 = svsub_f64_x(pg1, t6776, s2963);
        t6797 = svadd_f64_x(pg1, t6777, s2964);
        t6798 = svsub_f64_x(pg1, t6778, s2965);
        t6799 = svsub_f64_x(pg1, t6777, s2964);
        t6800 = svadd_f64_x(pg1, t6778, s2965);
        t6801 = svadd_f64_x(pg1, s2914, s2926);
        t6802 = svadd_f64_x(pg1, s2915, s2927);
        t6803 = svadd_f64_x(pg1, s2908, t6801);
        t6804 = svadd_f64_x(pg1, s2909, t6802);
        t6805 = svmls_n_f64_x(pg1, s2908, t6801, 0.5);
        t6806 = svmls_n_f64_x(pg1, s2909, t6802, 0.5);
        s2966 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2915, s2927), 0.8660254037844386);
        s2967 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2914, s2926), 0.8660254037844386);
        t6807 = svadd_f64_x(pg1, t6805, s2966);
        t6808 = svsub_f64_x(pg1, t6806, s2967);
        t6809 = svsub_f64_x(pg1, t6805, s2966);
        t6810 = svadd_f64_x(pg1, t6806, s2967);
        t6811 = svadd_f64_x(pg1, s2938, s2932);
        t6812 = svadd_f64_x(pg1, s2939, s2933);
        t6813 = svadd_f64_x(pg1, s2920, t6811);
        t6814 = svadd_f64_x(pg1, s2921, t6812);
        t6815 = svmls_n_f64_x(pg1, s2920, t6811, 0.5);
        t6816 = svmls_n_f64_x(pg1, s2921, t6812, 0.5);
        s2968 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2939, s2933), 0.8660254037844386);
        s2969 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2938, s2932), 0.8660254037844386);
        t6817 = svadd_f64_x(pg1, t6815, s2968);
        t6818 = svsub_f64_x(pg1, t6816, s2969);
        t6819 = svsub_f64_x(pg1, t6815, s2968);
        t6820 = svadd_f64_x(pg1, t6816, s2969);
        s3074 = svmla_n_f64_x(pg1, t6817, t6818, 1.7320508075688772);
        s2970 = svmul_n_f64_x(pg1, s3074, 0.5);
        s3075 = svmls_n_f64_x(pg1, t6818, t6817, 1.7320508075688772);
        s2971 = svmul_n_f64_x(pg1, s3075, 0.5);
        s3076 = svmls_n_f64_x(pg1, t6820, t6819, 0.57735026918962584);
        s2972 = svmul_n_f64_x(pg1, s3076, 0.8660254037844386);
        s3077 = svmla_n_f64_x(pg1, t6819, t6820, 0.57735026918962584);
        s2973 = svmul_n_f64_x(pg1, s3077, 0.8660254037844386);
        t6821 = svadd_f64_x(pg1, t6803, t6813);
        t6822 = svadd_f64_x(pg1, t6804, t6814);
        t6823 = svadd_f64_x(pg1, t6807, s2970);
        t6824 = svadd_f64_x(pg1, t6808, s2971);
        t6825 = svsub_f64_x(pg1, t6807, s2970);
        t6826 = svsub_f64_x(pg1, t6808, s2971);
        t6827 = svadd_f64_x(pg1, t6809, s2972);
        t6828 = svsub_f64_x(pg1, t6810, s2973);
        t6829 = svsub_f64_x(pg1, t6809, s2972);
        t6830 = svadd_f64_x(pg1, t6810, s2973);
        t6831 = svadd_f64_x(pg1, s2902, t6821);
        t6832 = svadd_f64_x(pg1, s2903, t6822);
        t6833 = svmls_n_f64_x(pg1, s2902, t6821, 0.16666666666666666);
        t6834 = svmls_n_f64_x(pg1, s2903, t6822, 0.16666666666666666);
        s3078 = svmla_n_f64_x(pg1, t6823, t6824, 0.41908315722758349);
        s2974 = svmul_n_f64_x(pg1, s3078, 0.4066888930575896);
        s3079 = svmls_n_f64_x(pg1, t6824, t6823, 0.41908315722758349);
        s2975 = svmul_n_f64_x(pg1, s3079, 0.4066888930575896);
        s3080 = svmla_n_f64_x(pg1, t6827, t6828, 0.49572725516748389);
        s2976 = svmul_n_f64_x(pg1, s3080, 0.39507823426270006);
        s3081 = svmls_n_f64_x(pg1, t6828, t6827, 0.49572725516748389);
        s2977 = svmul_n_f64_x(pg1, s3081, 0.39507823426270006);
        s2978 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t6804, t6814), 0.44095855184409843);
        s2979 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t6803, t6813), 0.44095855184409843);
        s3082 = svmls_n_f64_x(pg1, t6825, t6826, 0.49572725516748389);
        s2980 = svmul_n_f64_x(pg1, s3082, 0.39507823426270006);
        s3083 = svmla_n_f64_x(pg1, t6825, t6826, 2.0172382889501304);
        s2981 = svmul_n_f64_x(pg1, s3083, 0.1958510486474645);
        s3084 = svmls_n_f64_x(pg1, t6830, t6829, 2.386161273135941);
        s2982 = svmul_n_f64_x(pg1, s3084, 0.17043646531196566);
        s3085 = svmla_n_f64_x(pg1, t6829, t6830, 2.386161273135941);
        s2983 = svmul_n_f64_x(pg1, s3085, 0.17043646531196566);
        t6835 = svadd_f64_x(pg1, s2976, s2980);
        t6836 = svadd_f64_x(pg1, s2977, s2981);
        t6837 = svadd_f64_x(pg1, t6833, t6835);
        t6838 = svadd_f64_x(pg1, t6834, t6836);
        t6839 = svmls_n_f64_x(pg1, t6833, t6835, 0.5);
        t6840 = svmls_n_f64_x(pg1, t6834, t6836, 0.5);
        s2984 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2977, s2981), 0.8660254037844386);
        s2985 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2976, s2980), 0.8660254037844386);
        t6841 = svadd_f64_x(pg1, t6839, s2984);
        t6842 = svsub_f64_x(pg1, t6840, s2985);
        t6843 = svsub_f64_x(pg1, t6839, s2984);
        t6844 = svadd_f64_x(pg1, t6840, s2985);
        t6845 = svadd_f64_x(pg1, s2978, s2982);
        t6846 = svadd_f64_x(pg1, s2979, s2983);
        t6847 = svadd_f64_x(pg1, s2974, t6845);
        t6848 = svsub_f64_x(pg1, s2975, t6846);
        t6849 = svmls_n_f64_x(pg1, s2974, t6845, 0.5);
        t6850 = svmla_n_f64_x(pg1, s2975, t6846, 0.5);
        s2986 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2983, s2979), 0.8660254037844386);
        s2987 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2978, s2982), 0.8660254037844386);
        t6851 = svadd_f64_x(pg1, t6849, s2986);
        t6852 = svsub_f64_x(pg1, t6850, s2987);
        t6853 = svsub_f64_x(pg1, t6849, s2986);
        t6854 = svadd_f64_x(pg1, t6850, s2987);
        s3086 = svmla_n_f64_x(pg1, t6851, t6852, 1.7320508075688772);
        s2988 = svmul_n_f64_x(pg1, s3086, 0.5);
        s3087 = svmls_n_f64_x(pg1, t6852, t6851, 1.7320508075688772);
        s2989 = svmul_n_f64_x(pg1, s3087, 0.5);
        s3088 = svmls_n_f64_x(pg1, t6854, t6853, 0.57735026918962584);
        s2990 = svmul_n_f64_x(pg1, s3088, 0.8660254037844386);
        s3089 = svmla_n_f64_x(pg1, t6853, t6854, 0.57735026918962584);
        s2991 = svmul_n_f64_x(pg1, s3089, 0.8660254037844386);
        t6855 = svadd_f64_x(pg1, t6837, t6847);
        t6856 = svadd_f64_x(pg1, t6838, t6848);
        t6857 = svsub_f64_x(pg1, t6837, t6847);
        t6858 = svsub_f64_x(pg1, t6838, t6848);
        s3090 = svmla_n_f64_x(pg1, t6855, t6856, 0.48157461880752861);
        s2992 = svmul_n_f64_x(pg1, s3090, 0.90096886790241915);
        s3091 = svmls_n_f64_x(pg1, t6856, t6855, 0.48157461880752861);
        s2993 = svmul_n_f64_x(pg1, s3091, 0.90096886790241915);
        s3092 = svmls_n_f64_x(pg1, t6858, t6857, 2.0765213965723368);
        s2994 = svmul_n_f64_x(pg1, s3092, 0.43388373911755812);
        s3093 = svmla_n_f64_x(pg1, t6857, t6858, 2.0765213965723368);
        s2995 = svmul_n_f64_x(pg1, s3093, 0.43388373911755812);
        t6859 = svadd_f64_x(pg1, t6841, s2988);
        t6860 = svadd_f64_x(pg1, t6842, s2989);
        t6861 = svsub_f64_x(pg1, t6841, s2988);
        t6862 = svsub_f64_x(pg1, t6842, s2989);
        s3094 = svmla_n_f64_x(pg1, t6859, t6860, 4.381286267534823);
        s2996 = svmul_n_f64_x(pg1, s3094, 0.22252093395631439);
        s3095 = svmls_n_f64_x(pg1, t6860, t6859, 4.381286267534823);
        s2997 = svmul_n_f64_x(pg1, s3095, 0.22252093395631439);
        s3096 = svmls_n_f64_x(pg1, t6862, t6861, 0.22824347439014991);
        s2998 = svmul_n_f64_x(pg1, s3096, 0.97492791218182362);
        s3097 = svmla_n_f64_x(pg1, t6861, t6862, 0.22824347439014991);
        s2999 = svmul_n_f64_x(pg1, s3097, 0.97492791218182362);
        t6863 = svadd_f64_x(pg1, t6843, s2990);
        t6864 = svsub_f64_x(pg1, t6844, s2991);
        t6865 = svsub_f64_x(pg1, t6843, s2990);
        t6866 = svadd_f64_x(pg1, t6844, s2991);
        s3098 = svmla_n_f64_x(pg1, t6863, t6864, 1.253960337662704);
        s3000 = svmul_n_f64_x(pg1, s3098, 0.62348980185873348);
        s3099 = svmls_n_f64_x(pg1, t6864, t6863, 1.253960337662704);
        s3001 = svmul_n_f64_x(pg1, s3099, 0.62348980185873348);
        s3100 = svmls_n_f64_x(pg1, t6866, t6865, 0.79747338888240393);
        s3002 = svmul_n_f64_x(pg1, s3100, 0.7818314824680298);
        s3101 = svmla_n_f64_x(pg1, t6865, t6866, 0.79747338888240393);
        s3003 = svmul_n_f64_x(pg1, s3101, 0.7818314824680298);
        s3004 = svadd_f64_x(pg1, t6765, t6831);
        s3005 = svadd_f64_x(pg1, t6766, t6832);
        s3006 = svsub_f64_x(pg1, t6765, t6831);
        s3007 = svsub_f64_x(pg1, t6766, t6832);
        s3008 = svadd_f64_x(pg1, t6789, s2992);
        s3009 = svadd_f64_x(pg1, t6790, s2993);
        s3010 = svsub_f64_x(pg1, t6789, s2992);
        s3011 = svsub_f64_x(pg1, t6790, s2993);
        s3012 = svadd_f64_x(pg1, t6797, s3000);
        s3013 = svadd_f64_x(pg1, t6798, s3001);
        s3014 = svsub_f64_x(pg1, t6797, s3000);
        s3015 = svsub_f64_x(pg1, t6798, s3001);
        s3016 = svadd_f64_x(pg1, t6793, s2996);
        s3017 = svadd_f64_x(pg1, t6794, s2997);
        s3018 = svsub_f64_x(pg1, t6793, s2996);
        s3019 = svsub_f64_x(pg1, t6794, s2997);
        s3020 = svadd_f64_x(pg1, t6795, s2998);
        s3021 = svsub_f64_x(pg1, t6796, s2999);
        s3022 = svsub_f64_x(pg1, t6795, s2998);
        s3023 = svadd_f64_x(pg1, t6796, s2999);
        s3024 = svadd_f64_x(pg1, t6799, s3002);
        s3025 = svsub_f64_x(pg1, t6800, s3003);
        s3026 = svsub_f64_x(pg1, t6799, s3002);
        s3027 = svadd_f64_x(pg1, t6800, s3003);
        s3028 = svadd_f64_x(pg1, t6791, s2994);
        s3029 = svsub_f64_x(pg1, t6792, s2995);
        s3030 = svsub_f64_x(pg1, t6791, s2994);
        s3031 = svadd_f64_x(pg1, t6792, s2995);
        a3574 = (TW1 + ((26)*(j1)));
        a3575 = svld1_gather_u64offset_f64(pg1, a3574, svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3576 = svld1_gather_u64offset_f64(pg1, (a3574 + 1), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3032 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3576, s3009), a3575, s3008);
        s3033 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3575, s3009), a3576, s3008);
        a3577 = svld1_gather_u64offset_f64(pg1, (a3574 + 2), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3578 = svld1_gather_u64offset_f64(pg1, (a3574 + 3), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3034 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3578, s3013), a3577, s3012);
        s3035 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3577, s3013), a3578, s3012);
        a3579 = svld1_gather_u64offset_f64(pg1, (a3574 + 4), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3580 = svld1_gather_u64offset_f64(pg1, (a3574 + 5), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3036 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3580, s3017), a3579, s3016);
        s3037 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3579, s3017), a3580, s3016);
        a3581 = svld1_gather_u64offset_f64(pg1, (a3574 + 6), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3582 = svld1_gather_u64offset_f64(pg1, (a3574 + 7), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3038 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3582, s3021), a3581, s3020);
        s3039 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3581, s3021), a3582, s3020);
        a3583 = svld1_gather_u64offset_f64(pg1, (a3574 + 8), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3584 = svld1_gather_u64offset_f64(pg1, (a3574 + 9), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3040 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3584, s3025), a3583, s3024);
        s3041 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3583, s3025), a3584, s3024);
        a3585 = svld1_gather_u64offset_f64(pg1, (a3574 + 10), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3586 = svld1_gather_u64offset_f64(pg1, (a3574 + 11), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3042 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3586, s3029), a3585, s3028);
        s3043 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3585, s3029), a3586, s3028);
        a3587 = svld1_gather_u64offset_f64(pg1, (a3574 + 12), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3588 = svld1_gather_u64offset_f64(pg1, (a3574 + 13), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3044 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3588, s3007), a3587, s3006);
        s3045 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3587, s3007), a3588, s3006);
        a3589 = svld1_gather_u64offset_f64(pg1, (a3574 + 14), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3590 = svld1_gather_u64offset_f64(pg1, (a3574 + 15), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3046 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3590, s3011), a3589, s3010);
        s3047 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3589, s3011), a3590, s3010);
        a3591 = svld1_gather_u64offset_f64(pg1, (a3574 + 16), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3592 = svld1_gather_u64offset_f64(pg1, (a3574 + 17), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3048 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3592, s3015), a3591, s3014);
        s3049 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3591, s3015), a3592, s3014);
        a3593 = svld1_gather_u64offset_f64(pg1, (a3574 + 18), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3594 = svld1_gather_u64offset_f64(pg1, (a3574 + 19), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3050 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3594, s3019), a3593, s3018);
        s3051 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3593, s3019), a3594, s3018);
        a3595 = svld1_gather_u64offset_f64(pg1, (a3574 + 20), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3596 = svld1_gather_u64offset_f64(pg1, (a3574 + 21), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3052 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3596, s3023), a3595, s3022);
        s3053 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3595, s3023), a3596, s3022);
        a3597 = svld1_gather_u64offset_f64(pg1, (a3574 + 22), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3598 = svld1_gather_u64offset_f64(pg1, (a3574 + 23), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3054 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3598, s3027), a3597, s3026);
        s3055 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3597, s3027), a3598, s3026);
        a3599 = svld1_gather_u64offset_f64(pg1, (a3574 + 24), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        a3600 = svld1_gather_u64offset_f64(pg1, (a3574 + 25), svindex_u64(0, (int64_t)(26 * sizeof(float64_t))));
        s3056 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3600, s3031), a3599, s3030);
        s3057 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3599, s3031), a3600, s3030);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3004);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3005);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3032);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3033);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3034);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3035);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3036);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3037);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3038);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3039);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3040);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3041);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3042);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3043);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3044);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3045);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3046);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3047);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3048);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3049);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3050);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3051);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3052);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3053);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3054);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3055);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3056);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((28)*(j1)))), svindex_u64(0, (int64_t)(28 * sizeof(float64_t))), s3057);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
