/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft12a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a1602;
    svfloat64x2_t s1001, s968, s971, s974, s977, s980, s983, s986, 
            s989, s992, s995, s998;
    svfloat64_t a1603, a1604, a1605, a1606, a1607, a1608, a1609, a1610, 
            a1611, a1612, a1613, a1614, a1615, a1616, a1617, a1618, 
            a1619, a1620, a1621, a1622, a1623, a1624, s1000, s1002, 
            s1003, s1004, s1005, s1006, s1007, s1008, s1009, s1010, 
            s1011, s1012, s1013, s1014, s1015, s1016, s1017, s1018, 
            s1019, s1020, s1021, s1022, s1023, s1024, s1025, s1026, 
            s1027, s1028, s1029, s1030, s1031, s1032, s1033, s1034, 
            s1035, s1036, s1037, s1038, s1039, s1040, s1041, s1042, 
            s1043, s1044, s1045, s1046, s1047, s1048, s1049, s1050, 
            s1051, s1052, s1053, s1054, s1055, s1056, s1057, s1058, 
            s1059, s1060, s1061, s1062, s1063, s1064, s1065, s1066, 
            s1067, s1068, s1069, s1070, s1071, s1072, s1073, s969, 
            s970, s972, s973, s975, s976, s978, s979, s981, 
            s982, s984, s985, s987, s988, s990, s991, s993, 
            s994, s996, s997, s999, t2715, t2716, t2717, t2718, 
            t2719, t2720, t2721, t2722, t2723, t2724, t2725, t2726, 
            t2727, t2728, t2729, t2730, t2731, t2732, t2733, t2734, 
            t2735, t2736, t2737, t2738, t2739, t2740, t2741, t2742, 
            t2743, t2744, t2745, t2746, t2747, t2748, t2749, t2750, 
            t2751, t2752, t2753, t2754, t2755, t2756, t2757, t2758, 
            t2759, t2760, t2761, t2762, t2763, t2764, t2765, t2766, 
            t2767, t2768, t2769, t2770, t2771, t2772, t2773, t2774, 
            t2775, t2776, t2777, t2778;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s968 = svld2_f64(pg1, (X + ((2)*(j1))));
        s969 = s968.v0;
        s970 = s968.v1;
        s971 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s972 = s971.v0;
        s973 = s971.v1;
        s974 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s975 = s974.v0;
        s976 = s974.v1;
        s977 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s978 = s977.v0;
        s979 = s977.v1;
        s980 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s981 = s980.v0;
        s982 = s980.v1;
        s983 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s984 = s983.v0;
        s985 = s983.v1;
        s986 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s987 = s986.v0;
        s988 = s986.v1;
        s989 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s990 = s989.v0;
        s991 = s989.v1;
        s992 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s993 = s992.v0;
        s994 = s992.v1;
        s995 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s996 = s995.v0;
        s997 = s995.v1;
        s998 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s999 = s998.v0;
        s1000 = s998.v1;
        s1001 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s1002 = s1001.v0;
        s1003 = s1001.v1;
        t2715 = svadd_f64_x(pg1, s969, s987);
        t2716 = svadd_f64_x(pg1, s970, s988);
        t2717 = svsub_f64_x(pg1, s969, s987);
        t2718 = svsub_f64_x(pg1, s970, s988);
        t2719 = svadd_f64_x(pg1, s978, s996);
        t2720 = svadd_f64_x(pg1, s979, s997);
        t2721 = svsub_f64_x(pg1, s978, s996);
        t2722 = svsub_f64_x(pg1, s979, s997);
        t2723 = svadd_f64_x(pg1, t2715, t2719);
        t2724 = svadd_f64_x(pg1, t2716, t2720);
        t2725 = svsub_f64_x(pg1, t2715, t2719);
        t2726 = svsub_f64_x(pg1, t2716, t2720);
        t2727 = svadd_f64_x(pg1, t2717, t2722);
        t2728 = svsub_f64_x(pg1, t2718, t2721);
        t2729 = svsub_f64_x(pg1, t2717, t2722);
        t2730 = svadd_f64_x(pg1, t2718, t2721);
        t2731 = svadd_f64_x(pg1, s972, s990);
        t2732 = svadd_f64_x(pg1, s973, s991);
        t2733 = svsub_f64_x(pg1, s972, s990);
        t2734 = svsub_f64_x(pg1, s973, s991);
        t2735 = svadd_f64_x(pg1, s981, s999);
        t2736 = svadd_f64_x(pg1, s982, s1000);
        t2737 = svsub_f64_x(pg1, s981, s999);
        t2738 = svsub_f64_x(pg1, s982, s1000);
        t2739 = svadd_f64_x(pg1, t2731, t2735);
        t2740 = svadd_f64_x(pg1, t2732, t2736);
        t2741 = svsub_f64_x(pg1, t2731, t2735);
        t2742 = svsub_f64_x(pg1, t2732, t2736);
        s1066 = svmla_n_f64_x(pg1, t2741, t2742, 1.7320508075688772);
        s1004 = svmul_n_f64_x(pg1, s1066, 0.5);
        s1067 = svmls_n_f64_x(pg1, t2742, t2741, 1.7320508075688772);
        s1005 = svmul_n_f64_x(pg1, s1067, 0.5);
        t2743 = svadd_f64_x(pg1, t2733, t2738);
        t2744 = svsub_f64_x(pg1, t2734, t2737);
        t2745 = svsub_f64_x(pg1, t2733, t2738);
        t2746 = svadd_f64_x(pg1, t2734, t2737);
        s1068 = svmla_n_f64_x(pg1, t2743, t2744, 0.57735026918962584);
        s1006 = svmul_n_f64_x(pg1, s1068, 0.8660254037844386);
        s1069 = svmls_n_f64_x(pg1, t2744, t2743, 0.57735026918962584);
        s1007 = svmul_n_f64_x(pg1, s1069, 0.8660254037844386);
        t2747 = svadd_f64_x(pg1, s975, s993);
        t2748 = svadd_f64_x(pg1, s976, s994);
        t2749 = svsub_f64_x(pg1, s975, s993);
        t2750 = svsub_f64_x(pg1, s976, s994);
        t2751 = svadd_f64_x(pg1, s984, s1002);
        t2752 = svadd_f64_x(pg1, s985, s1003);
        t2753 = svsub_f64_x(pg1, s984, s1002);
        t2754 = svsub_f64_x(pg1, s985, s1003);
        t2755 = svadd_f64_x(pg1, t2747, t2751);
        t2756 = svadd_f64_x(pg1, t2748, t2752);
        t2757 = svsub_f64_x(pg1, t2747, t2751);
        t2758 = svsub_f64_x(pg1, t2748, t2752);
        s1070 = svmls_n_f64_x(pg1, t2758, t2757, 0.57735026918962584);
        s1008 = svmul_n_f64_x(pg1, s1070, 0.8660254037844386);
        s1071 = svmla_n_f64_x(pg1, t2757, t2758, 0.57735026918962584);
        s1009 = svmul_n_f64_x(pg1, s1071, 0.8660254037844386);
        t2759 = svadd_f64_x(pg1, t2749, t2754);
        t2760 = svsub_f64_x(pg1, t2750, t2753);
        t2761 = svsub_f64_x(pg1, t2749, t2754);
        t2762 = svadd_f64_x(pg1, t2750, t2753);
        s1072 = svmla_n_f64_x(pg1, t2759, t2760, 1.7320508075688772);
        s1010 = svmul_n_f64_x(pg1, s1072, 0.5);
        s1073 = svmls_n_f64_x(pg1, t2760, t2759, 1.7320508075688772);
        s1011 = svmul_n_f64_x(pg1, s1073, 0.5);
        t2763 = svadd_f64_x(pg1, t2739, t2755);
        t2764 = svadd_f64_x(pg1, t2740, t2756);
        t2765 = svmls_n_f64_x(pg1, t2723, t2763, 0.5);
        t2766 = svmls_n_f64_x(pg1, t2724, t2764, 0.5);
        s1012 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2740, t2756), 0.8660254037844386);
        s1013 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2739, t2755), 0.8660254037844386);
        s1014 = svadd_f64_x(pg1, t2723, t2763);
        s1015 = svadd_f64_x(pg1, t2724, t2764);
        s1016 = svadd_f64_x(pg1, t2765, s1012);
        s1017 = svsub_f64_x(pg1, t2766, s1013);
        s1018 = svsub_f64_x(pg1, t2765, s1012);
        s1019 = svadd_f64_x(pg1, t2766, s1013);
        t2767 = svadd_f64_x(pg1, s1006, s1010);
        t2768 = svadd_f64_x(pg1, s1007, s1011);
        t2769 = svmls_n_f64_x(pg1, t2727, t2767, 0.5);
        t2770 = svmls_n_f64_x(pg1, t2728, t2768, 0.5);
        s1020 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1007, s1011), 0.8660254037844386);
        s1021 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1006, s1010), 0.8660254037844386);
        s1022 = svadd_f64_x(pg1, t2727, t2767);
        s1023 = svadd_f64_x(pg1, t2728, t2768);
        s1024 = svadd_f64_x(pg1, t2769, s1020);
        s1025 = svsub_f64_x(pg1, t2770, s1021);
        s1026 = svsub_f64_x(pg1, t2769, s1020);
        s1027 = svadd_f64_x(pg1, t2770, s1021);
        t2771 = svadd_f64_x(pg1, s1004, s1008);
        t2772 = svsub_f64_x(pg1, s1005, s1009);
        t2773 = svmls_n_f64_x(pg1, t2725, t2771, 0.5);
        t2774 = svmls_n_f64_x(pg1, t2726, t2772, 0.5);
        s1028 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1005, s1009), 0.8660254037844386);
        s1029 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1004, s1008), 0.8660254037844386);
        s1030 = svadd_f64_x(pg1, t2725, t2771);
        s1031 = svadd_f64_x(pg1, t2726, t2772);
        s1032 = svadd_f64_x(pg1, t2773, s1028);
        s1033 = svsub_f64_x(pg1, t2774, s1029);
        s1034 = svsub_f64_x(pg1, t2773, s1028);
        s1035 = svadd_f64_x(pg1, t2774, s1029);
        t2775 = svsub_f64_x(pg1, t2746, t2761);
        t2776 = svadd_f64_x(pg1, t2745, t2762);
        t2777 = svmls_n_f64_x(pg1, t2729, t2775, 0.5);
        t2778 = svmla_n_f64_x(pg1, t2730, t2776, 0.5);
        s1036 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2762, t2745), 0.8660254037844386);
        s1037 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t2746, t2761), 0.8660254037844386);
        s1038 = svadd_f64_x(pg1, t2729, t2775);
        s1039 = svsub_f64_x(pg1, t2730, t2776);
        s1040 = svadd_f64_x(pg1, t2777, s1036);
        s1041 = svsub_f64_x(pg1, t2778, s1037);
        s1042 = svsub_f64_x(pg1, t2777, s1036);
        s1043 = svadd_f64_x(pg1, t2778, s1037);
        a1602 = (TW1 + ((22)*(j1)));
        a1603 = svld1_gather_u64offset_f64(pg1, a1602, svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1604 = svld1_gather_u64offset_f64(pg1, (a1602 + 1), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1044 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1604, s1023), a1603, s1022);
        s1045 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1603, s1023), a1604, s1022);
        a1605 = svld1_gather_u64offset_f64(pg1, (a1602 + 2), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1606 = svld1_gather_u64offset_f64(pg1, (a1602 + 3), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1046 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1606, s1031), a1605, s1030);
        s1047 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1605, s1031), a1606, s1030);
        a1607 = svld1_gather_u64offset_f64(pg1, (a1602 + 4), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1608 = svld1_gather_u64offset_f64(pg1, (a1602 + 5), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1048 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1608, s1039), a1607, s1038);
        s1049 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1607, s1039), a1608, s1038);
        a1609 = svld1_gather_u64offset_f64(pg1, (a1602 + 6), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1610 = svld1_gather_u64offset_f64(pg1, (a1602 + 7), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1050 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1610, s1017), a1609, s1016);
        s1051 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1609, s1017), a1610, s1016);
        a1611 = svld1_gather_u64offset_f64(pg1, (a1602 + 8), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1612 = svld1_gather_u64offset_f64(pg1, (a1602 + 9), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1052 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1612, s1025), a1611, s1024);
        s1053 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1611, s1025), a1612, s1024);
        a1613 = svld1_gather_u64offset_f64(pg1, (a1602 + 10), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1614 = svld1_gather_u64offset_f64(pg1, (a1602 + 11), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1054 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1614, s1033), a1613, s1032);
        s1055 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1613, s1033), a1614, s1032);
        a1615 = svld1_gather_u64offset_f64(pg1, (a1602 + 12), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1616 = svld1_gather_u64offset_f64(pg1, (a1602 + 13), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1056 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1616, s1041), a1615, s1040);
        s1057 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1615, s1041), a1616, s1040);
        a1617 = svld1_gather_u64offset_f64(pg1, (a1602 + 14), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1618 = svld1_gather_u64offset_f64(pg1, (a1602 + 15), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1058 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1618, s1019), a1617, s1018);
        s1059 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1617, s1019), a1618, s1018);
        a1619 = svld1_gather_u64offset_f64(pg1, (a1602 + 16), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1620 = svld1_gather_u64offset_f64(pg1, (a1602 + 17), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1060 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1620, s1027), a1619, s1026);
        s1061 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1619, s1027), a1620, s1026);
        a1621 = svld1_gather_u64offset_f64(pg1, (a1602 + 18), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1622 = svld1_gather_u64offset_f64(pg1, (a1602 + 19), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1062 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1622, s1035), a1621, s1034);
        s1063 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1621, s1035), a1622, s1034);
        a1623 = svld1_gather_u64offset_f64(pg1, (a1602 + 20), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        a1624 = svld1_gather_u64offset_f64(pg1, (a1602 + 21), svindex_u64(0, (int64_t)(22 * sizeof(float64_t))));
        s1064 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1624, s1043), a1623, s1042);
        s1065 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1623, s1043), a1624, s1042);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1014);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1015);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1044);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1045);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1046);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1047);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1048);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1049);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1050);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1051);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1052);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1053);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1054);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1055);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1056);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1057);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1058);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1059);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1060);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1061);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1062);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1063);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1064);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((24)*(j1)))), svindex_u64(0, (int64_t)(24 * sizeof(float64_t))), s1065);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
