/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft18c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D39[12];
    static float64_t D40[24];
    int l1, m1;
    svfloat64x2_t s1620, s1623, s1626, s1629, s1632, s1635, s1638, s1641, 
            s1644, s1647, s1650, s1653, s1656, s1659, s1662, s1665, 
            s1668, s1671, svex2_19, svex2_20, svex2_21, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36;
    svfloat64_t s1621, s1622, s1624, s1625, s1627, s1628, s1630, s1631, 
            s1633, s1634, s1636, s1637, s1639, s1640, s1642, s1643, 
            s1645, s1646, s1648, s1649, s1651, s1652, s1654, s1655, 
            s1657, s1658, s1660, s1661, s1663, s1664, s1666, s1667, 
            s1669, s1670, s1672, s1673, s1674, s1675, s1676, s1677, 
            s1678, s1679, s1680, s1681, s1682, s1683, s1684, s1685, 
            s1686, s1687, s1688, s1689, s1690, s1691, s1692, s1693, 
            s1694, s1695, s1696, s1697, s1698, s1699, s1700, s1701, 
            s1702, s1703, s1704, s1705, s1706, s1707, s1708, s1709, 
            s1710, s1711, s1712, s1713, s1714, s1715, s1716, s1717, 
            s1718, s1719, s1720, s1721, s1722, s1723, s1724, s1725, 
            s1726, s1727, s1728, s1729, s1730, s1731, s1732, s1733, 
            s1734, s1735, s1736, s1737, s1738, s1739, s1740, s1741, 
            s1742, s1743, s1744, s1745, s1746, s1747, s1748, s1749, 
            s1750, s1751, s1752, s1753, s1754, s1755, s1756, s1757, 
            t2074, t2075, t2076, t2077, t2078, t2079, t2080, t2081, 
            t2082, t2083, t2084, t2085, t2086, t2087, t2088, t2089, 
            t2090, t2091, t2092, t2093, t2094, t2095, t2096, t2097, 
            t2098, t2099, t2100, t2101, t2102, t2103, t2104, t2105, 
            t2106, t2107, t2108, t2109, t2110, t2111, t2112, t2113, 
            t2114, t2115, t2116, t2117, t2118, t2119, t2120, t2121, 
            t2122, t2123, t2124, t2125, t2126, t2127, t2128, t2129, 
            t2130, t2131, t2132, t2133, t2134, t2135, t2136, t2137, 
            t2138, t2139, t2140, t2141, t2142, t2143, t2144, t2145, 
            t2146, t2147, t2148, t2149, t2150, t2151, t2152, t2153, 
            t2154, t2155, t2156, t2157, t2158, t2159, t2160, t2161, 
            t2162, t2163, t2164, t2165, t2166, t2167, t2168, t2169, 
            t2170, t2171, t2172, t2173, t2174, t2175, t2176, t2177, 
            t2178, t2179, t2180, t2181, t2182, t2183, t2184, t2185, 
            t2186, t2187, t2188, t2189, t2190, t2191, t2192, t2193;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s1620 = svld2_f64(pg1, (X + ((2)*(k1))));
        s1621 = s1620.v0;
        s1622 = s1620.v1;
        s1623 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s1624 = s1623.v0;
        s1625 = s1623.v1;
        s1626 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s1627 = s1626.v0;
        s1628 = s1626.v1;
        s1629 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s1630 = s1629.v0;
        s1631 = s1629.v1;
        s1632 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s1633 = s1632.v0;
        s1634 = s1632.v1;
        s1635 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s1636 = s1635.v0;
        s1637 = s1635.v1;
        s1638 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s1639 = s1638.v0;
        s1640 = s1638.v1;
        s1641 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s1642 = s1641.v0;
        s1643 = s1641.v1;
        s1644 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s1645 = s1644.v0;
        s1646 = s1644.v1;
        s1647 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s1648 = s1647.v0;
        s1649 = s1647.v1;
        s1650 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s1651 = s1650.v0;
        s1652 = s1650.v1;
        s1653 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s1654 = s1653.v0;
        s1655 = s1653.v1;
        s1656 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s1657 = s1656.v0;
        s1658 = s1656.v1;
        s1659 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s1660 = s1659.v0;
        s1661 = s1659.v1;
        s1662 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s1663 = s1662.v0;
        s1664 = s1662.v1;
        s1665 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s1666 = s1665.v0;
        s1667 = s1665.v1;
        s1668 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s1669 = s1668.v0;
        s1670 = s1668.v1;
        s1671 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s1672 = s1671.v0;
        s1673 = s1671.v1;
        t2074 = svadd_f64_x(pg1, s1639, s1657);
        t2075 = svadd_f64_x(pg1, s1640, s1658);
        t2076 = svadd_f64_x(pg1, s1621, t2074);
        t2077 = svadd_f64_x(pg1, s1622, t2075);
        t2078 = svmls_n_f64_x(pg1, s1621, t2074, 0.5);
        t2079 = svmls_n_f64_x(pg1, s1622, t2075, 0.5);
        s1674 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1640, s1658), 0.8660254037844386);
        s1675 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1639, s1657), 0.8660254037844386);
        s1676 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2077, D39[1]), t2076, D39[0]);
        s1677 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2077, D39[0]), t2076, D39[1]);
        t2080 = svadd_f64_x(pg1, t2078, s1674);
        t2081 = svsub_f64_x(pg1, t2079, s1675);
        t2082 = svsub_f64_x(pg1, t2078, s1674);
        t2083 = svadd_f64_x(pg1, t2079, s1675);
        s1678 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2081, D40[1]), t2080, D40[0]);
        s1679 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2081, D40[0]), t2080, D40[1]);
        s1680 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2083, D40[3]), t2082, D40[2]);
        s1681 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2083, D40[2]), t2082, D40[3]);
        t2084 = svadd_f64_x(pg1, s1642, s1660);
        t2085 = svadd_f64_x(pg1, s1643, s1661);
        t2086 = svadd_f64_x(pg1, s1624, t2084);
        t2087 = svadd_f64_x(pg1, s1625, t2085);
        t2088 = svmls_n_f64_x(pg1, s1624, t2084, 0.5);
        t2089 = svmls_n_f64_x(pg1, s1625, t2085, 0.5);
        s1682 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1643, s1661), 0.8660254037844386);
        s1683 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1642, s1660), 0.8660254037844386);
        s1684 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2087, D39[3]), t2086, D39[2]);
        s1685 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2087, D39[2]), t2086, D39[3]);
        t2090 = svadd_f64_x(pg1, t2088, s1682);
        t2091 = svsub_f64_x(pg1, t2089, s1683);
        t2092 = svsub_f64_x(pg1, t2088, s1682);
        t2093 = svadd_f64_x(pg1, t2089, s1683);
        s1686 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2091, D40[5]), t2090, D40[4]);
        s1687 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2091, D40[4]), t2090, D40[5]);
        s1688 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2093, D40[7]), t2092, D40[6]);
        s1689 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2093, D40[6]), t2092, D40[7]);
        t2094 = svadd_f64_x(pg1, s1645, s1663);
        t2095 = svadd_f64_x(pg1, s1646, s1664);
        t2096 = svadd_f64_x(pg1, s1627, t2094);
        t2097 = svadd_f64_x(pg1, s1628, t2095);
        t2098 = svmls_n_f64_x(pg1, s1627, t2094, 0.5);
        t2099 = svmls_n_f64_x(pg1, s1628, t2095, 0.5);
        s1690 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1646, s1664), 0.8660254037844386);
        s1691 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1645, s1663), 0.8660254037844386);
        s1692 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2097, D39[5]), t2096, D39[4]);
        s1693 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2097, D39[4]), t2096, D39[5]);
        t2100 = svadd_f64_x(pg1, t2098, s1690);
        t2101 = svsub_f64_x(pg1, t2099, s1691);
        t2102 = svsub_f64_x(pg1, t2098, s1690);
        t2103 = svadd_f64_x(pg1, t2099, s1691);
        s1694 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2101, D40[9]), t2100, D40[8]);
        s1695 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2101, D40[8]), t2100, D40[9]);
        s1696 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2103, D40[11]), t2102, D40[10]);
        s1697 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2103, D40[10]), t2102, D40[11]);
        t2104 = svadd_f64_x(pg1, s1648, s1666);
        t2105 = svadd_f64_x(pg1, s1649, s1667);
        t2106 = svadd_f64_x(pg1, s1630, t2104);
        t2107 = svadd_f64_x(pg1, s1631, t2105);
        t2108 = svmls_n_f64_x(pg1, s1630, t2104, 0.5);
        t2109 = svmls_n_f64_x(pg1, s1631, t2105, 0.5);
        s1698 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1649, s1667), 0.8660254037844386);
        s1699 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1648, s1666), 0.8660254037844386);
        s1700 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2107, D39[7]), t2106, D39[6]);
        s1701 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2107, D39[6]), t2106, D39[7]);
        t2110 = svadd_f64_x(pg1, t2108, s1698);
        t2111 = svsub_f64_x(pg1, t2109, s1699);
        t2112 = svsub_f64_x(pg1, t2108, s1698);
        t2113 = svadd_f64_x(pg1, t2109, s1699);
        s1702 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2111, D40[13]), t2110, D40[12]);
        s1703 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2111, D40[12]), t2110, D40[13]);
        s1704 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2113, D40[15]), t2112, D40[14]);
        s1705 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2113, D40[14]), t2112, D40[15]);
        t2114 = svadd_f64_x(pg1, s1651, s1669);
        t2115 = svadd_f64_x(pg1, s1652, s1670);
        t2116 = svadd_f64_x(pg1, s1633, t2114);
        t2117 = svadd_f64_x(pg1, s1634, t2115);
        t2118 = svmls_n_f64_x(pg1, s1633, t2114, 0.5);
        t2119 = svmls_n_f64_x(pg1, s1634, t2115, 0.5);
        s1706 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1652, s1670), 0.8660254037844386);
        s1707 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1651, s1669), 0.8660254037844386);
        s1708 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2117, D39[9]), t2116, D39[8]);
        s1709 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2117, D39[8]), t2116, D39[9]);
        t2120 = svadd_f64_x(pg1, t2118, s1706);
        t2121 = svsub_f64_x(pg1, t2119, s1707);
        t2122 = svsub_f64_x(pg1, t2118, s1706);
        t2123 = svadd_f64_x(pg1, t2119, s1707);
        s1710 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2121, D40[17]), t2120, D40[16]);
        s1711 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2121, D40[16]), t2120, D40[17]);
        s1712 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2123, D40[19]), t2122, D40[18]);
        s1713 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2123, D40[18]), t2122, D40[19]);
        t2124 = svadd_f64_x(pg1, s1654, s1672);
        t2125 = svadd_f64_x(pg1, s1655, s1673);
        t2126 = svadd_f64_x(pg1, s1636, t2124);
        t2127 = svadd_f64_x(pg1, s1637, t2125);
        t2128 = svmls_n_f64_x(pg1, s1636, t2124, 0.5);
        t2129 = svmls_n_f64_x(pg1, s1637, t2125, 0.5);
        s1714 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1655, s1673), 0.8660254037844386);
        s1715 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1654, s1672), 0.8660254037844386);
        s1716 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2127, D39[11]), t2126, D39[10]);
        s1717 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2127, D39[10]), t2126, D39[11]);
        t2130 = svadd_f64_x(pg1, t2128, s1714);
        t2131 = svsub_f64_x(pg1, t2129, s1715);
        t2132 = svsub_f64_x(pg1, t2128, s1714);
        t2133 = svadd_f64_x(pg1, t2129, s1715);
        s1718 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2131, D40[21]), t2130, D40[20]);
        s1719 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2131, D40[20]), t2130, D40[21]);
        s1720 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2133, D40[23]), t2132, D40[22]);
        s1721 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2133, D40[22]), t2132, D40[23]);
        t2134 = svadd_f64_x(pg1, s1692, s1708);
        t2135 = svadd_f64_x(pg1, s1693, s1709);
        t2136 = svadd_f64_x(pg1, s1676, t2134);
        t2137 = svadd_f64_x(pg1, s1677, t2135);
        t2138 = svmls_n_f64_x(pg1, s1676, t2134, 0.5);
        t2139 = svmls_n_f64_x(pg1, s1677, t2135, 0.5);
        s1722 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1693, s1709), 0.8660254037844386);
        s1723 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1692, s1708), 0.8660254037844386);
        t2140 = svadd_f64_x(pg1, t2138, s1722);
        t2141 = svsub_f64_x(pg1, t2139, s1723);
        t2142 = svsub_f64_x(pg1, t2138, s1722);
        t2143 = svadd_f64_x(pg1, t2139, s1723);
        t2144 = svadd_f64_x(pg1, s1700, s1716);
        t2145 = svadd_f64_x(pg1, s1701, s1717);
        t2146 = svadd_f64_x(pg1, s1684, t2144);
        t2147 = svadd_f64_x(pg1, s1685, t2145);
        t2148 = svmls_n_f64_x(pg1, s1684, t2144, 0.5);
        t2149 = svmls_n_f64_x(pg1, s1685, t2145, 0.5);
        s1724 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1701, s1717), 0.8660254037844386);
        s1725 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1700, s1716), 0.8660254037844386);
        t2150 = svadd_f64_x(pg1, t2148, s1724);
        t2151 = svsub_f64_x(pg1, t2149, s1725);
        t2152 = svsub_f64_x(pg1, t2148, s1724);
        t2153 = svadd_f64_x(pg1, t2149, s1725);
        s1746 = svmla_n_f64_x(pg1, t2150, t2151, 1.7320508075688772);
        s1726 = svmul_n_f64_x(pg1, s1746, 0.5);
        s1747 = svmls_n_f64_x(pg1, t2151, t2150, 1.7320508075688772);
        s1727 = svmul_n_f64_x(pg1, s1747, 0.5);
        s1748 = svmls_n_f64_x(pg1, t2153, t2152, 0.57735026918962584);
        s1728 = svmul_n_f64_x(pg1, s1748, 0.8660254037844386);
        s1749 = svmla_n_f64_x(pg1, t2152, t2153, 0.57735026918962584);
        s1729 = svmul_n_f64_x(pg1, s1749, 0.8660254037844386);
        t2154 = svadd_f64_x(pg1, s1694, s1710);
        t2155 = svadd_f64_x(pg1, s1695, s1711);
        t2156 = svadd_f64_x(pg1, s1678, t2154);
        t2157 = svadd_f64_x(pg1, s1679, t2155);
        t2158 = svmls_n_f64_x(pg1, s1678, t2154, 0.5);
        t2159 = svmls_n_f64_x(pg1, s1679, t2155, 0.5);
        s1730 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1695, s1711), 0.8660254037844386);
        s1731 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1694, s1710), 0.8660254037844386);
        t2160 = svadd_f64_x(pg1, t2158, s1730);
        t2161 = svsub_f64_x(pg1, t2159, s1731);
        t2162 = svsub_f64_x(pg1, t2158, s1730);
        t2163 = svadd_f64_x(pg1, t2159, s1731);
        t2164 = svadd_f64_x(pg1, s1702, s1718);
        t2165 = svadd_f64_x(pg1, s1703, s1719);
        t2166 = svadd_f64_x(pg1, s1686, t2164);
        t2167 = svadd_f64_x(pg1, s1687, t2165);
        t2168 = svmls_n_f64_x(pg1, s1686, t2164, 0.5);
        t2169 = svmls_n_f64_x(pg1, s1687, t2165, 0.5);
        s1732 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1703, s1719), 0.8660254037844386);
        s1733 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1702, s1718), 0.8660254037844386);
        t2170 = svadd_f64_x(pg1, t2168, s1732);
        t2171 = svsub_f64_x(pg1, t2169, s1733);
        t2172 = svsub_f64_x(pg1, t2168, s1732);
        t2173 = svadd_f64_x(pg1, t2169, s1733);
        s1750 = svmla_n_f64_x(pg1, t2170, t2171, 1.7320508075688772);
        s1734 = svmul_n_f64_x(pg1, s1750, 0.5);
        s1751 = svmls_n_f64_x(pg1, t2171, t2170, 1.7320508075688772);
        s1735 = svmul_n_f64_x(pg1, s1751, 0.5);
        s1752 = svmls_n_f64_x(pg1, t2173, t2172, 0.57735026918962584);
        s1736 = svmul_n_f64_x(pg1, s1752, 0.8660254037844386);
        s1753 = svmla_n_f64_x(pg1, t2172, t2173, 0.57735026918962584);
        s1737 = svmul_n_f64_x(pg1, s1753, 0.8660254037844386);
        t2174 = svadd_f64_x(pg1, s1696, s1712);
        t2175 = svadd_f64_x(pg1, s1697, s1713);
        t2176 = svadd_f64_x(pg1, s1680, t2174);
        t2177 = svadd_f64_x(pg1, s1681, t2175);
        t2178 = svmls_n_f64_x(pg1, s1680, t2174, 0.5);
        t2179 = svmls_n_f64_x(pg1, s1681, t2175, 0.5);
        s1738 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1697, s1713), 0.8660254037844386);
        s1739 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1696, s1712), 0.8660254037844386);
        t2180 = svadd_f64_x(pg1, t2178, s1738);
        t2181 = svsub_f64_x(pg1, t2179, s1739);
        t2182 = svsub_f64_x(pg1, t2178, s1738);
        t2183 = svadd_f64_x(pg1, t2179, s1739);
        t2184 = svadd_f64_x(pg1, s1704, s1720);
        t2185 = svadd_f64_x(pg1, s1705, s1721);
        t2186 = svadd_f64_x(pg1, s1688, t2184);
        t2187 = svadd_f64_x(pg1, s1689, t2185);
        t2188 = svmls_n_f64_x(pg1, s1688, t2184, 0.5);
        t2189 = svmls_n_f64_x(pg1, s1689, t2185, 0.5);
        s1740 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1705, s1721), 0.8660254037844386);
        s1741 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1704, s1720), 0.8660254037844386);
        t2190 = svadd_f64_x(pg1, t2188, s1740);
        t2191 = svsub_f64_x(pg1, t2189, s1741);
        t2192 = svsub_f64_x(pg1, t2188, s1740);
        t2193 = svadd_f64_x(pg1, t2189, s1741);
        s1754 = svmla_n_f64_x(pg1, t2190, t2191, 1.7320508075688772);
        s1742 = svmul_n_f64_x(pg1, s1754, 0.5);
        s1755 = svmls_n_f64_x(pg1, t2191, t2190, 1.7320508075688772);
        s1743 = svmul_n_f64_x(pg1, s1755, 0.5);
        s1756 = svmls_n_f64_x(pg1, t2193, t2192, 0.57735026918962584);
        s1744 = svmul_n_f64_x(pg1, s1756, 0.8660254037844386);
        s1757 = svmla_n_f64_x(pg1, t2192, t2193, 0.57735026918962584);
        s1745 = svmul_n_f64_x(pg1, s1757, 0.8660254037844386);
        svex2_19.v0 = svadd_f64_x(pg1, t2136, t2146);
        svex2_19.v1 = svadd_f64_x(pg1, t2137, t2147);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_19);
        svex2_20.v0 = svadd_f64_x(pg1, t2156, t2166);
        svex2_20.v1 = svadd_f64_x(pg1, t2157, t2167);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_20);
        svex2_21.v0 = svadd_f64_x(pg1, t2176, t2186);
        svex2_21.v1 = svadd_f64_x(pg1, t2177, t2187);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_21);
        svex2_22.v0 = svadd_f64_x(pg1, t2140, s1726);
        svex2_22.v1 = svadd_f64_x(pg1, t2141, s1727);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_22);
        svex2_23.v0 = svadd_f64_x(pg1, t2160, s1734);
        svex2_23.v1 = svadd_f64_x(pg1, t2161, s1735);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_23);
        svex2_24.v0 = svadd_f64_x(pg1, t2180, s1742);
        svex2_24.v1 = svadd_f64_x(pg1, t2181, s1743);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_24);
        svex2_25.v0 = svadd_f64_x(pg1, t2142, s1728);
        svex2_25.v1 = svsub_f64_x(pg1, t2143, s1729);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_25);
        svex2_26.v0 = svadd_f64_x(pg1, t2162, s1736);
        svex2_26.v1 = svsub_f64_x(pg1, t2163, s1737);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_26);
        svex2_27.v0 = svadd_f64_x(pg1, t2182, s1744);
        svex2_27.v1 = svsub_f64_x(pg1, t2183, s1745);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_27);
        svex2_28.v0 = svsub_f64_x(pg1, t2136, t2146);
        svex2_28.v1 = svsub_f64_x(pg1, t2137, t2147);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_28);
        svex2_29.v0 = svsub_f64_x(pg1, t2156, t2166);
        svex2_29.v1 = svsub_f64_x(pg1, t2157, t2167);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_29);
        svex2_30.v0 = svsub_f64_x(pg1, t2176, t2186);
        svex2_30.v1 = svsub_f64_x(pg1, t2177, t2187);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_30);
        svex2_31.v0 = svsub_f64_x(pg1, t2140, s1726);
        svex2_31.v1 = svsub_f64_x(pg1, t2141, s1727);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_31);
        svex2_32.v0 = svsub_f64_x(pg1, t2160, s1734);
        svex2_32.v1 = svsub_f64_x(pg1, t2161, s1735);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_32);
        svex2_33.v0 = svsub_f64_x(pg1, t2180, s1742);
        svex2_33.v1 = svsub_f64_x(pg1, t2181, s1743);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_33);
        svex2_34.v0 = svsub_f64_x(pg1, t2142, s1728);
        svex2_34.v1 = svadd_f64_x(pg1, t2143, s1729);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_34);
        svex2_35.v0 = svsub_f64_x(pg1, t2162, s1736);
        svex2_35.v1 = svadd_f64_x(pg1, t2163, s1737);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_35);
        svex2_36.v0 = svsub_f64_x(pg1, t2182, s1744);
        svex2_36.v1 = svadd_f64_x(pg1, t2183, s1745);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_36);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
