/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft21a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D91[14];
    static float64_t D92[28];
    int l1;
    float64_t  *a5104;
    svfloat64x2_t s2907, s2910, s2913, s2916, s2919, s2922, s2925, s2928, 
            s2931, s2934, s2937, s2940, s2943, s2946, s2949, s2952, 
            s2955, s2958, s2961, s2964, s2967;
    svfloat64_t a5105, a5106, a5107, a5108, a5109, a5110, a5111, a5112, 
            a5113, a5114, a5115, a5116, a5117, a5118, a5119, a5120, 
            a5121, a5122, a5123, a5124, a5125, a5126, a5127, a5128, 
            a5129, a5130, a5131, a5132, a5133, a5134, a5135, a5136, 
            a5137, a5138, a5139, a5140, a5141, a5142, a5143, a5144, 
            s2908, s2909, s2911, s2912, s2914, s2915, s2917, s2918, 
            s2920, s2921, s2923, s2924, s2926, s2927, s2929, s2930, 
            s2932, s2933, s2935, s2936, s2938, s2939, s2941, s2942, 
            s2944, s2945, s2947, s2948, s2950, s2951, s2953, s2954, 
            s2956, s2957, s2959, s2960, s2962, s2963, s2965, s2966, 
            s2968, s2969, s2970, s2971, s2972, s2973, s2974, s2975, 
            s2976, s2977, s2978, s2979, s2980, s2981, s2982, s2983, 
            s2984, s2985, s2986, s2987, s2988, s2989, s2990, s2991, 
            s2992, s2993, s2994, s2995, s2996, s2997, s2998, s2999, 
            s3000, s3001, s3002, s3003, s3004, s3005, s3006, s3007, 
            s3008, s3009, s3010, s3011, s3012, s3013, s3014, s3015, 
            s3016, s3017, s3018, s3019, s3020, s3021, s3022, s3023, 
            s3024, s3025, s3026, s3027, s3028, s3029, s3030, s3031, 
            s3032, s3033, s3034, s3035, s3036, s3037, s3038, s3039, 
            s3040, s3041, s3042, s3043, s3044, s3045, s3046, s3047, 
            s3048, s3049, s3050, s3051, s3052, s3053, s3054, s3055, 
            s3056, s3057, s3058, s3059, s3060, s3061, s3062, s3063, 
            s3064, s3065, s3066, s3067, s3068, s3069, s3070, s3071, 
            s3072, s3073, s3074, s3075, s3076, s3077, s3078, s3079, 
            s3080, s3081, s3082, s3083, s3084, s3085, s3086, s3087, 
            s3088, s3089, s3090, s3091, s3092, s3093, s3094, s3095, 
            s3096, s3097, s3098, s3099, s3100, s3101, s3102, s3103, 
            s3104, s3105, s3106, s3107, s3108, s3109, s3110, s3111, 
            s3112, s3113, s3114, s3115, s3116, s3117, s3118, s3119, 
            s3120, s3121, s3122, s3123, s3124, s3125, s3126, s3127, 
            s3128, s3129, s3130, s3131, s3132, s3133, s3134, s3135, 
            s3136, s3137, s3138, s3139, s3140, s3141, s3142, s3143, 
            s3144, s3145, s3146, s3147, s3148, s3149, s3150, s3151, 
            s3152, s3153, s3154, s3155, s3156, s3157, s3158, s3159, 
            s3160, s3161, s3162, s3163, s3164, s3165, s3166, s3167, 
            s3168, s3169, s3170, s3171, s3172, s3173, s3174, s3175, 
            s3176, s3177, s3178, s3179, s3180, s3181, s3182, s3183, 
            s3184, s3185, s3186, s3187, s3188, s3189, s3190, s3191, 
            s3192, s3193, s3194, s3195, s3196, s3197, s3198, s3199, 
            s3200, s3201, s3202, s3203, s3204, s3205, s3206, s3207, 
            s3208, s3209, s3210, s3211, s3212, s3213, s3214, s3215, 
            s3216, s3217, s3218, s3219, s3220, s3221, s3222, s3223, 
            s3224, s3225, s3226, s3227, s3228, s3229, s3230, s3231, 
            s3232, s3233, t4309, t4310, t4311, t4312, t4313, t4314, 
            t4315, t4316, t4317, t4318, t4319, t4320, t4321, t4322, 
            t4323, t4324, t4325, t4326, t4327, t4328, t4329, t4330, 
            t4331, t4332, t4333, t4334, t4335, t4336, t4337, t4338, 
            t4339, t4340, t4341, t4342, t4343, t4344, t4345, t4346, 
            t4347, t4348, t4349, t4350, t4351, t4352, t4353, t4354, 
            t4355, t4356, t4357, t4358, t4359, t4360, t4361, t4362, 
            t4363, t4364, t4365, t4366, t4367, t4368, t4369, t4370, 
            t4371, t4372, t4373, t4374, t4375, t4376, t4377, t4378, 
            t4379, t4380, t4381, t4382, t4383, t4384, t4385, t4386, 
            t4387, t4388, t4389, t4390, t4391, t4392, t4393, t4394, 
            t4395, t4396, t4397, t4398, t4399, t4400, t4401, t4402, 
            t4403, t4404, t4405, t4406, t4407, t4408, t4409, t4410, 
            t4411, t4412, t4413, t4414, t4415, t4416, t4417, t4418, 
            t4419, t4420, t4421, t4422, t4423, t4424, t4425, t4426, 
            t4427, t4428, t4429, t4430, t4431, t4432, t4433, t4434, 
            t4435, t4436, t4437, t4438, t4439, t4440, t4441, t4442, 
            t4443, t4444, t4445, t4446, t4447, t4448, t4449, t4450, 
            t4451, t4452, t4453, t4454, t4455, t4456, t4457, t4458, 
            t4459, t4460, t4461, t4462, t4463, t4464, t4465, t4466, 
            t4467, t4468, t4469, t4470, t4471, t4472, t4473, t4474, 
            t4475, t4476, t4477, t4478, t4479, t4480, t4481, t4482, 
            t4483, t4484, t4485, t4486, t4487, t4488, t4489, t4490, 
            t4491, t4492, t4493, t4494, t4495, t4496, t4497, t4498, 
            t4499, t4500, t4501, t4502, t4503, t4504, t4505, t4506, 
            t4507, t4508, t4509, t4510, t4511, t4512, t4513, t4514, 
            t4515, t4516, t4517, t4518, t4519, t4520, t4521, t4522, 
            t4523, t4524, t4525, t4526, t4527, t4528, t4529, t4530, 
            t4531, t4532, t4533, t4534;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s2907 = svld2_f64(pg1, (X + ((2)*(j1))));
        s2908 = s2907.v0;
        s2909 = s2907.v1;
        s2910 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s2911 = s2910.v0;
        s2912 = s2910.v1;
        s2913 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s2914 = s2913.v0;
        s2915 = s2913.v1;
        s2916 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s2917 = s2916.v0;
        s2918 = s2916.v1;
        s2919 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s2920 = s2919.v0;
        s2921 = s2919.v1;
        s2922 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s2923 = s2922.v0;
        s2924 = s2922.v1;
        s2925 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s2926 = s2925.v0;
        s2927 = s2925.v1;
        s2928 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s2929 = s2928.v0;
        s2930 = s2928.v1;
        s2931 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s2932 = s2931.v0;
        s2933 = s2931.v1;
        s2934 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s2935 = s2934.v0;
        s2936 = s2934.v1;
        s2937 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s2938 = s2937.v0;
        s2939 = s2937.v1;
        s2940 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s2941 = s2940.v0;
        s2942 = s2940.v1;
        s2943 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s2944 = s2943.v0;
        s2945 = s2943.v1;
        s2946 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s2947 = s2946.v0;
        s2948 = s2946.v1;
        s2949 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s2950 = s2949.v0;
        s2951 = s2949.v1;
        s2952 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s2953 = s2952.v0;
        s2954 = s2952.v1;
        s2955 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s2956 = s2955.v0;
        s2957 = s2955.v1;
        s2958 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s2959 = s2958.v0;
        s2960 = s2958.v1;
        s2961 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s2962 = s2961.v0;
        s2963 = s2961.v1;
        s2964 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s2965 = s2964.v0;
        s2966 = s2964.v1;
        s2967 = svld2_f64(pg1, (X + ((2)*((j1 + ((20)*(l1)))))));
        s2968 = s2967.v0;
        s2969 = s2967.v1;
        t4309 = svadd_f64_x(pg1, s2929, s2950);
        t4310 = svadd_f64_x(pg1, s2930, s2951);
        t4311 = svadd_f64_x(pg1, s2908, t4309);
        t4312 = svadd_f64_x(pg1, s2909, t4310);
        t4313 = svmls_n_f64_x(pg1, s2908, t4309, 0.5);
        t4314 = svmls_n_f64_x(pg1, s2909, t4310, 0.5);
        s2970 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2930, s2951), 0.8660254037844386);
        s2971 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2929, s2950), 0.8660254037844386);
        s2972 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4312, D91[1]), t4311, D91[0]);
        s2973 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4312, D91[0]), t4311, D91[1]);
        t4315 = svadd_f64_x(pg1, t4313, s2970);
        t4316 = svsub_f64_x(pg1, t4314, s2971);
        t4317 = svsub_f64_x(pg1, t4313, s2970);
        t4318 = svadd_f64_x(pg1, t4314, s2971);
        s2974 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4316, D92[1]), t4315, D92[0]);
        s2975 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4316, D92[0]), t4315, D92[1]);
        s2976 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4318, D92[3]), t4317, D92[2]);
        s2977 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4318, D92[2]), t4317, D92[3]);
        t4319 = svadd_f64_x(pg1, s2932, s2953);
        t4320 = svadd_f64_x(pg1, s2933, s2954);
        t4321 = svadd_f64_x(pg1, s2911, t4319);
        t4322 = svadd_f64_x(pg1, s2912, t4320);
        t4323 = svmls_n_f64_x(pg1, s2911, t4319, 0.5);
        t4324 = svmls_n_f64_x(pg1, s2912, t4320, 0.5);
        s2978 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2933, s2954), 0.8660254037844386);
        s2979 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2932, s2953), 0.8660254037844386);
        s2980 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4322, D91[3]), t4321, D91[2]);
        s2981 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4322, D91[2]), t4321, D91[3]);
        t4325 = svadd_f64_x(pg1, t4323, s2978);
        t4326 = svsub_f64_x(pg1, t4324, s2979);
        t4327 = svsub_f64_x(pg1, t4323, s2978);
        t4328 = svadd_f64_x(pg1, t4324, s2979);
        s2982 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4326, D92[5]), t4325, D92[4]);
        s2983 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4326, D92[4]), t4325, D92[5]);
        s2984 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4328, D92[7]), t4327, D92[6]);
        s2985 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4328, D92[6]), t4327, D92[7]);
        t4329 = svadd_f64_x(pg1, s2935, s2956);
        t4330 = svadd_f64_x(pg1, s2936, s2957);
        t4331 = svadd_f64_x(pg1, s2914, t4329);
        t4332 = svadd_f64_x(pg1, s2915, t4330);
        t4333 = svmls_n_f64_x(pg1, s2914, t4329, 0.5);
        t4334 = svmls_n_f64_x(pg1, s2915, t4330, 0.5);
        s2986 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2936, s2957), 0.8660254037844386);
        s2987 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2935, s2956), 0.8660254037844386);
        s2988 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4332, D91[5]), t4331, D91[4]);
        s2989 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4332, D91[4]), t4331, D91[5]);
        t4335 = svadd_f64_x(pg1, t4333, s2986);
        t4336 = svsub_f64_x(pg1, t4334, s2987);
        t4337 = svsub_f64_x(pg1, t4333, s2986);
        t4338 = svadd_f64_x(pg1, t4334, s2987);
        s2990 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4336, D92[9]), t4335, D92[8]);
        s2991 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4336, D92[8]), t4335, D92[9]);
        s2992 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4338, D92[11]), t4337, D92[10]);
        s2993 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4338, D92[10]), t4337, D92[11]);
        t4339 = svadd_f64_x(pg1, s2938, s2959);
        t4340 = svadd_f64_x(pg1, s2939, s2960);
        t4341 = svadd_f64_x(pg1, s2917, t4339);
        t4342 = svadd_f64_x(pg1, s2918, t4340);
        t4343 = svmls_n_f64_x(pg1, s2917, t4339, 0.5);
        t4344 = svmls_n_f64_x(pg1, s2918, t4340, 0.5);
        s2994 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2939, s2960), 0.8660254037844386);
        s2995 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2938, s2959), 0.8660254037844386);
        s2996 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4342, D91[7]), t4341, D91[6]);
        s2997 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4342, D91[6]), t4341, D91[7]);
        t4345 = svadd_f64_x(pg1, t4343, s2994);
        t4346 = svsub_f64_x(pg1, t4344, s2995);
        t4347 = svsub_f64_x(pg1, t4343, s2994);
        t4348 = svadd_f64_x(pg1, t4344, s2995);
        s2998 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4346, D92[13]), t4345, D92[12]);
        s2999 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4346, D92[12]), t4345, D92[13]);
        s3000 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4348, D92[15]), t4347, D92[14]);
        s3001 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4348, D92[14]), t4347, D92[15]);
        t4349 = svadd_f64_x(pg1, s2941, s2962);
        t4350 = svadd_f64_x(pg1, s2942, s2963);
        t4351 = svadd_f64_x(pg1, s2920, t4349);
        t4352 = svadd_f64_x(pg1, s2921, t4350);
        t4353 = svmls_n_f64_x(pg1, s2920, t4349, 0.5);
        t4354 = svmls_n_f64_x(pg1, s2921, t4350, 0.5);
        s3002 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2942, s2963), 0.8660254037844386);
        s3003 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2941, s2962), 0.8660254037844386);
        s3004 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4352, D91[9]), t4351, D91[8]);
        s3005 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4352, D91[8]), t4351, D91[9]);
        t4355 = svadd_f64_x(pg1, t4353, s3002);
        t4356 = svsub_f64_x(pg1, t4354, s3003);
        t4357 = svsub_f64_x(pg1, t4353, s3002);
        t4358 = svadd_f64_x(pg1, t4354, s3003);
        s3006 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4356, D92[17]), t4355, D92[16]);
        s3007 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4356, D92[16]), t4355, D92[17]);
        s3008 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4358, D92[19]), t4357, D92[18]);
        s3009 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4358, D92[18]), t4357, D92[19]);
        t4359 = svadd_f64_x(pg1, s2944, s2965);
        t4360 = svadd_f64_x(pg1, s2945, s2966);
        t4361 = svadd_f64_x(pg1, s2923, t4359);
        t4362 = svadd_f64_x(pg1, s2924, t4360);
        t4363 = svmls_n_f64_x(pg1, s2923, t4359, 0.5);
        t4364 = svmls_n_f64_x(pg1, s2924, t4360, 0.5);
        s3010 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2945, s2966), 0.8660254037844386);
        s3011 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2944, s2965), 0.8660254037844386);
        s3012 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4362, D91[11]), t4361, D91[10]);
        s3013 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4362, D91[10]), t4361, D91[11]);
        t4365 = svadd_f64_x(pg1, t4363, s3010);
        t4366 = svsub_f64_x(pg1, t4364, s3011);
        t4367 = svsub_f64_x(pg1, t4363, s3010);
        t4368 = svadd_f64_x(pg1, t4364, s3011);
        s3014 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4366, D92[21]), t4365, D92[20]);
        s3015 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4366, D92[20]), t4365, D92[21]);
        s3016 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4368, D92[23]), t4367, D92[22]);
        s3017 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4368, D92[22]), t4367, D92[23]);
        t4369 = svadd_f64_x(pg1, s2947, s2968);
        t4370 = svadd_f64_x(pg1, s2948, s2969);
        t4371 = svadd_f64_x(pg1, s2926, t4369);
        t4372 = svadd_f64_x(pg1, s2927, t4370);
        t4373 = svmls_n_f64_x(pg1, s2926, t4369, 0.5);
        t4374 = svmls_n_f64_x(pg1, s2927, t4370, 0.5);
        s3018 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2948, s2969), 0.8660254037844386);
        s3019 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2947, s2968), 0.8660254037844386);
        s3020 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4372, D91[13]), t4371, D91[12]);
        s3021 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4372, D91[12]), t4371, D91[13]);
        t4375 = svadd_f64_x(pg1, t4373, s3018);
        t4376 = svsub_f64_x(pg1, t4374, s3019);
        t4377 = svsub_f64_x(pg1, t4373, s3018);
        t4378 = svadd_f64_x(pg1, t4374, s3019);
        s3022 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4376, D92[25]), t4375, D92[24]);
        s3023 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4376, D92[24]), t4375, D92[25]);
        s3024 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4378, D92[27]), t4377, D92[26]);
        s3025 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4378, D92[26]), t4377, D92[27]);
        t4379 = svadd_f64_x(pg1, s2988, s3004);
        t4380 = svadd_f64_x(pg1, s2989, s3005);
        t4381 = svadd_f64_x(pg1, s2980, t4379);
        t4382 = svadd_f64_x(pg1, s2981, t4380);
        t4383 = svmls_n_f64_x(pg1, s2980, t4379, 0.5);
        t4384 = svmls_n_f64_x(pg1, s2981, t4380, 0.5);
        s3026 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2989, s3005), 0.8660254037844386);
        s3027 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2988, s3004), 0.8660254037844386);
        t4385 = svadd_f64_x(pg1, t4383, s3026);
        t4386 = svsub_f64_x(pg1, t4384, s3027);
        t4387 = svsub_f64_x(pg1, t4383, s3026);
        t4388 = svadd_f64_x(pg1, t4384, s3027);
        t4389 = svadd_f64_x(pg1, s3020, s3012);
        t4390 = svadd_f64_x(pg1, s3021, s3013);
        t4391 = svadd_f64_x(pg1, s2996, t4389);
        t4392 = svadd_f64_x(pg1, s2997, t4390);
        t4393 = svmls_n_f64_x(pg1, s2996, t4389, 0.5);
        t4394 = svmls_n_f64_x(pg1, s2997, t4390, 0.5);
        s3028 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3021, s3013), 0.8660254037844386);
        s3029 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3020, s3012), 0.8660254037844386);
        t4395 = svadd_f64_x(pg1, t4393, s3028);
        t4396 = svsub_f64_x(pg1, t4394, s3029);
        t4397 = svsub_f64_x(pg1, t4393, s3028);
        t4398 = svadd_f64_x(pg1, t4394, s3029);
        s3186 = svmla_n_f64_x(pg1, t4395, t4396, 1.7320508075688772);
        s3030 = svmul_n_f64_x(pg1, s3186, 0.5);
        s3187 = svmls_n_f64_x(pg1, t4396, t4395, 1.7320508075688772);
        s3031 = svmul_n_f64_x(pg1, s3187, 0.5);
        s3188 = svmls_n_f64_x(pg1, t4398, t4397, 0.57735026918962584);
        s3032 = svmul_n_f64_x(pg1, s3188, 0.8660254037844386);
        s3189 = svmla_n_f64_x(pg1, t4397, t4398, 0.57735026918962584);
        s3033 = svmul_n_f64_x(pg1, s3189, 0.8660254037844386);
        t4399 = svadd_f64_x(pg1, t4381, t4391);
        t4400 = svadd_f64_x(pg1, t4382, t4392);
        t4401 = svadd_f64_x(pg1, t4385, s3030);
        t4402 = svadd_f64_x(pg1, t4386, s3031);
        t4403 = svsub_f64_x(pg1, t4385, s3030);
        t4404 = svsub_f64_x(pg1, t4386, s3031);
        t4405 = svadd_f64_x(pg1, t4387, s3032);
        t4406 = svsub_f64_x(pg1, t4388, s3033);
        t4407 = svsub_f64_x(pg1, t4387, s3032);
        t4408 = svadd_f64_x(pg1, t4388, s3033);
        t4409 = svmls_n_f64_x(pg1, s2972, t4399, 0.16666666666666666);
        t4410 = svmls_n_f64_x(pg1, s2973, t4400, 0.16666666666666666);
        s3190 = svmla_n_f64_x(pg1, t4401, t4402, 0.41908315722758349);
        s3034 = svmul_n_f64_x(pg1, s3190, 0.4066888930575896);
        s3191 = svmls_n_f64_x(pg1, t4402, t4401, 0.41908315722758349);
        s3035 = svmul_n_f64_x(pg1, s3191, 0.4066888930575896);
        s3192 = svmla_n_f64_x(pg1, t4405, t4406, 0.49572725516748389);
        s3036 = svmul_n_f64_x(pg1, s3192, 0.39507823426270006);
        s3193 = svmls_n_f64_x(pg1, t4406, t4405, 0.49572725516748389);
        s3037 = svmul_n_f64_x(pg1, s3193, 0.39507823426270006);
        s3038 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4382, t4392), 0.44095855184409843);
        s3039 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4381, t4391), 0.44095855184409843);
        s3194 = svmls_n_f64_x(pg1, t4403, t4404, 0.49572725516748389);
        s3040 = svmul_n_f64_x(pg1, s3194, 0.39507823426270006);
        s3195 = svmla_n_f64_x(pg1, t4403, t4404, 2.0172382889501304);
        s3041 = svmul_n_f64_x(pg1, s3195, 0.1958510486474645);
        s3196 = svmls_n_f64_x(pg1, t4408, t4407, 2.386161273135941);
        s3042 = svmul_n_f64_x(pg1, s3196, 0.17043646531196566);
        s3197 = svmla_n_f64_x(pg1, t4407, t4408, 2.386161273135941);
        s3043 = svmul_n_f64_x(pg1, s3197, 0.17043646531196566);
        s3044 = svadd_f64_x(pg1, s2972, t4399);
        s3045 = svadd_f64_x(pg1, s2973, t4400);
        t4411 = svadd_f64_x(pg1, s3036, s3040);
        t4412 = svadd_f64_x(pg1, s3037, s3041);
        t4413 = svadd_f64_x(pg1, t4409, t4411);
        t4414 = svadd_f64_x(pg1, t4410, t4412);
        t4415 = svmls_n_f64_x(pg1, t4409, t4411, 0.5);
        t4416 = svmls_n_f64_x(pg1, t4410, t4412, 0.5);
        s3046 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3037, s3041), 0.8660254037844386);
        s3047 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3036, s3040), 0.8660254037844386);
        t4417 = svadd_f64_x(pg1, t4415, s3046);
        t4418 = svsub_f64_x(pg1, t4416, s3047);
        t4419 = svsub_f64_x(pg1, t4415, s3046);
        t4420 = svadd_f64_x(pg1, t4416, s3047);
        t4421 = svadd_f64_x(pg1, s3038, s3042);
        t4422 = svadd_f64_x(pg1, s3039, s3043);
        t4423 = svadd_f64_x(pg1, s3034, t4421);
        t4424 = svsub_f64_x(pg1, s3035, t4422);
        t4425 = svmls_n_f64_x(pg1, s3034, t4421, 0.5);
        t4426 = svmla_n_f64_x(pg1, s3035, t4422, 0.5);
        s3048 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3043, s3039), 0.8660254037844386);
        s3049 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3038, s3042), 0.8660254037844386);
        t4427 = svadd_f64_x(pg1, t4425, s3048);
        t4428 = svsub_f64_x(pg1, t4426, s3049);
        t4429 = svsub_f64_x(pg1, t4425, s3048);
        t4430 = svadd_f64_x(pg1, t4426, s3049);
        s3198 = svmla_n_f64_x(pg1, t4427, t4428, 1.7320508075688772);
        s3050 = svmul_n_f64_x(pg1, s3198, 0.5);
        s3199 = svmls_n_f64_x(pg1, t4428, t4427, 1.7320508075688772);
        s3051 = svmul_n_f64_x(pg1, s3199, 0.5);
        s3200 = svmls_n_f64_x(pg1, t4430, t4429, 0.57735026918962584);
        s3052 = svmul_n_f64_x(pg1, s3200, 0.8660254037844386);
        s3201 = svmla_n_f64_x(pg1, t4429, t4430, 0.57735026918962584);
        s3053 = svmul_n_f64_x(pg1, s3201, 0.8660254037844386);
        s3054 = svadd_f64_x(pg1, t4413, t4423);
        s3055 = svadd_f64_x(pg1, t4414, t4424);
        s3056 = svsub_f64_x(pg1, t4413, t4423);
        s3057 = svsub_f64_x(pg1, t4414, t4424);
        s3058 = svadd_f64_x(pg1, t4417, s3050);
        s3059 = svadd_f64_x(pg1, t4418, s3051);
        s3060 = svsub_f64_x(pg1, t4417, s3050);
        s3061 = svsub_f64_x(pg1, t4418, s3051);
        s3062 = svadd_f64_x(pg1, t4419, s3052);
        s3063 = svsub_f64_x(pg1, t4420, s3053);
        s3064 = svsub_f64_x(pg1, t4419, s3052);
        s3065 = svadd_f64_x(pg1, t4420, s3053);
        t4431 = svadd_f64_x(pg1, s2990, s3006);
        t4432 = svadd_f64_x(pg1, s2991, s3007);
        t4433 = svadd_f64_x(pg1, s2982, t4431);
        t4434 = svadd_f64_x(pg1, s2983, t4432);
        t4435 = svmls_n_f64_x(pg1, s2982, t4431, 0.5);
        t4436 = svmls_n_f64_x(pg1, s2983, t4432, 0.5);
        s3066 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2991, s3007), 0.8660254037844386);
        s3067 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2990, s3006), 0.8660254037844386);
        t4437 = svadd_f64_x(pg1, t4435, s3066);
        t4438 = svsub_f64_x(pg1, t4436, s3067);
        t4439 = svsub_f64_x(pg1, t4435, s3066);
        t4440 = svadd_f64_x(pg1, t4436, s3067);
        t4441 = svadd_f64_x(pg1, s3022, s3014);
        t4442 = svadd_f64_x(pg1, s3023, s3015);
        t4443 = svadd_f64_x(pg1, s2998, t4441);
        t4444 = svadd_f64_x(pg1, s2999, t4442);
        t4445 = svmls_n_f64_x(pg1, s2998, t4441, 0.5);
        t4446 = svmls_n_f64_x(pg1, s2999, t4442, 0.5);
        s3068 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3023, s3015), 0.8660254037844386);
        s3069 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3022, s3014), 0.8660254037844386);
        t4447 = svadd_f64_x(pg1, t4445, s3068);
        t4448 = svsub_f64_x(pg1, t4446, s3069);
        t4449 = svsub_f64_x(pg1, t4445, s3068);
        t4450 = svadd_f64_x(pg1, t4446, s3069);
        s3202 = svmla_n_f64_x(pg1, t4447, t4448, 1.7320508075688772);
        s3070 = svmul_n_f64_x(pg1, s3202, 0.5);
        s3203 = svmls_n_f64_x(pg1, t4448, t4447, 1.7320508075688772);
        s3071 = svmul_n_f64_x(pg1, s3203, 0.5);
        s3204 = svmls_n_f64_x(pg1, t4450, t4449, 0.57735026918962584);
        s3072 = svmul_n_f64_x(pg1, s3204, 0.8660254037844386);
        s3205 = svmla_n_f64_x(pg1, t4449, t4450, 0.57735026918962584);
        s3073 = svmul_n_f64_x(pg1, s3205, 0.8660254037844386);
        t4451 = svadd_f64_x(pg1, t4433, t4443);
        t4452 = svadd_f64_x(pg1, t4434, t4444);
        t4453 = svadd_f64_x(pg1, t4437, s3070);
        t4454 = svadd_f64_x(pg1, t4438, s3071);
        t4455 = svsub_f64_x(pg1, t4437, s3070);
        t4456 = svsub_f64_x(pg1, t4438, s3071);
        t4457 = svadd_f64_x(pg1, t4439, s3072);
        t4458 = svsub_f64_x(pg1, t4440, s3073);
        t4459 = svsub_f64_x(pg1, t4439, s3072);
        t4460 = svadd_f64_x(pg1, t4440, s3073);
        t4461 = svmls_n_f64_x(pg1, s2974, t4451, 0.16666666666666666);
        t4462 = svmls_n_f64_x(pg1, s2975, t4452, 0.16666666666666666);
        s3206 = svmla_n_f64_x(pg1, t4453, t4454, 0.41908315722758349);
        s3074 = svmul_n_f64_x(pg1, s3206, 0.4066888930575896);
        s3207 = svmls_n_f64_x(pg1, t4454, t4453, 0.41908315722758349);
        s3075 = svmul_n_f64_x(pg1, s3207, 0.4066888930575896);
        s3208 = svmla_n_f64_x(pg1, t4457, t4458, 0.49572725516748389);
        s3076 = svmul_n_f64_x(pg1, s3208, 0.39507823426270006);
        s3209 = svmls_n_f64_x(pg1, t4458, t4457, 0.49572725516748389);
        s3077 = svmul_n_f64_x(pg1, s3209, 0.39507823426270006);
        s3078 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4434, t4444), 0.44095855184409843);
        s3079 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4433, t4443), 0.44095855184409843);
        s3210 = svmls_n_f64_x(pg1, t4455, t4456, 0.49572725516748389);
        s3080 = svmul_n_f64_x(pg1, s3210, 0.39507823426270006);
        s3211 = svmla_n_f64_x(pg1, t4455, t4456, 2.0172382889501304);
        s3081 = svmul_n_f64_x(pg1, s3211, 0.1958510486474645);
        s3212 = svmls_n_f64_x(pg1, t4460, t4459, 2.386161273135941);
        s3082 = svmul_n_f64_x(pg1, s3212, 0.17043646531196566);
        s3213 = svmla_n_f64_x(pg1, t4459, t4460, 2.386161273135941);
        s3083 = svmul_n_f64_x(pg1, s3213, 0.17043646531196566);
        s3084 = svadd_f64_x(pg1, s2974, t4451);
        s3085 = svadd_f64_x(pg1, s2975, t4452);
        t4463 = svadd_f64_x(pg1, s3076, s3080);
        t4464 = svadd_f64_x(pg1, s3077, s3081);
        t4465 = svadd_f64_x(pg1, t4461, t4463);
        t4466 = svadd_f64_x(pg1, t4462, t4464);
        t4467 = svmls_n_f64_x(pg1, t4461, t4463, 0.5);
        t4468 = svmls_n_f64_x(pg1, t4462, t4464, 0.5);
        s3086 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3077, s3081), 0.8660254037844386);
        s3087 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3076, s3080), 0.8660254037844386);
        t4469 = svadd_f64_x(pg1, t4467, s3086);
        t4470 = svsub_f64_x(pg1, t4468, s3087);
        t4471 = svsub_f64_x(pg1, t4467, s3086);
        t4472 = svadd_f64_x(pg1, t4468, s3087);
        t4473 = svadd_f64_x(pg1, s3078, s3082);
        t4474 = svadd_f64_x(pg1, s3079, s3083);
        t4475 = svadd_f64_x(pg1, s3074, t4473);
        t4476 = svsub_f64_x(pg1, s3075, t4474);
        t4477 = svmls_n_f64_x(pg1, s3074, t4473, 0.5);
        t4478 = svmla_n_f64_x(pg1, s3075, t4474, 0.5);
        s3088 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3083, s3079), 0.8660254037844386);
        s3089 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3078, s3082), 0.8660254037844386);
        t4479 = svadd_f64_x(pg1, t4477, s3088);
        t4480 = svsub_f64_x(pg1, t4478, s3089);
        t4481 = svsub_f64_x(pg1, t4477, s3088);
        t4482 = svadd_f64_x(pg1, t4478, s3089);
        s3214 = svmla_n_f64_x(pg1, t4479, t4480, 1.7320508075688772);
        s3090 = svmul_n_f64_x(pg1, s3214, 0.5);
        s3215 = svmls_n_f64_x(pg1, t4480, t4479, 1.7320508075688772);
        s3091 = svmul_n_f64_x(pg1, s3215, 0.5);
        s3216 = svmls_n_f64_x(pg1, t4482, t4481, 0.57735026918962584);
        s3092 = svmul_n_f64_x(pg1, s3216, 0.8660254037844386);
        s3217 = svmla_n_f64_x(pg1, t4481, t4482, 0.57735026918962584);
        s3093 = svmul_n_f64_x(pg1, s3217, 0.8660254037844386);
        s3094 = svadd_f64_x(pg1, t4465, t4475);
        s3095 = svadd_f64_x(pg1, t4466, t4476);
        s3096 = svsub_f64_x(pg1, t4465, t4475);
        s3097 = svsub_f64_x(pg1, t4466, t4476);
        s3098 = svadd_f64_x(pg1, t4469, s3090);
        s3099 = svadd_f64_x(pg1, t4470, s3091);
        s3100 = svsub_f64_x(pg1, t4469, s3090);
        s3101 = svsub_f64_x(pg1, t4470, s3091);
        s3102 = svadd_f64_x(pg1, t4471, s3092);
        s3103 = svsub_f64_x(pg1, t4472, s3093);
        s3104 = svsub_f64_x(pg1, t4471, s3092);
        s3105 = svadd_f64_x(pg1, t4472, s3093);
        t4483 = svadd_f64_x(pg1, s2992, s3008);
        t4484 = svadd_f64_x(pg1, s2993, s3009);
        t4485 = svadd_f64_x(pg1, s2984, t4483);
        t4486 = svadd_f64_x(pg1, s2985, t4484);
        t4487 = svmls_n_f64_x(pg1, s2984, t4483, 0.5);
        t4488 = svmls_n_f64_x(pg1, s2985, t4484, 0.5);
        s3106 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2993, s3009), 0.8660254037844386);
        s3107 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2992, s3008), 0.8660254037844386);
        t4489 = svadd_f64_x(pg1, t4487, s3106);
        t4490 = svsub_f64_x(pg1, t4488, s3107);
        t4491 = svsub_f64_x(pg1, t4487, s3106);
        t4492 = svadd_f64_x(pg1, t4488, s3107);
        t4493 = svadd_f64_x(pg1, s3024, s3016);
        t4494 = svadd_f64_x(pg1, s3025, s3017);
        t4495 = svadd_f64_x(pg1, s3000, t4493);
        t4496 = svadd_f64_x(pg1, s3001, t4494);
        t4497 = svmls_n_f64_x(pg1, s3000, t4493, 0.5);
        t4498 = svmls_n_f64_x(pg1, s3001, t4494, 0.5);
        s3108 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3025, s3017), 0.8660254037844386);
        s3109 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3024, s3016), 0.8660254037844386);
        t4499 = svadd_f64_x(pg1, t4497, s3108);
        t4500 = svsub_f64_x(pg1, t4498, s3109);
        t4501 = svsub_f64_x(pg1, t4497, s3108);
        t4502 = svadd_f64_x(pg1, t4498, s3109);
        s3218 = svmla_n_f64_x(pg1, t4499, t4500, 1.7320508075688772);
        s3110 = svmul_n_f64_x(pg1, s3218, 0.5);
        s3219 = svmls_n_f64_x(pg1, t4500, t4499, 1.7320508075688772);
        s3111 = svmul_n_f64_x(pg1, s3219, 0.5);
        s3220 = svmls_n_f64_x(pg1, t4502, t4501, 0.57735026918962584);
        s3112 = svmul_n_f64_x(pg1, s3220, 0.8660254037844386);
        s3221 = svmla_n_f64_x(pg1, t4501, t4502, 0.57735026918962584);
        s3113 = svmul_n_f64_x(pg1, s3221, 0.8660254037844386);
        t4503 = svadd_f64_x(pg1, t4485, t4495);
        t4504 = svadd_f64_x(pg1, t4486, t4496);
        t4505 = svadd_f64_x(pg1, t4489, s3110);
        t4506 = svadd_f64_x(pg1, t4490, s3111);
        t4507 = svsub_f64_x(pg1, t4489, s3110);
        t4508 = svsub_f64_x(pg1, t4490, s3111);
        t4509 = svadd_f64_x(pg1, t4491, s3112);
        t4510 = svsub_f64_x(pg1, t4492, s3113);
        t4511 = svsub_f64_x(pg1, t4491, s3112);
        t4512 = svadd_f64_x(pg1, t4492, s3113);
        t4513 = svmls_n_f64_x(pg1, s2976, t4503, 0.16666666666666666);
        t4514 = svmls_n_f64_x(pg1, s2977, t4504, 0.16666666666666666);
        s3222 = svmla_n_f64_x(pg1, t4505, t4506, 0.41908315722758349);
        s3114 = svmul_n_f64_x(pg1, s3222, 0.4066888930575896);
        s3223 = svmls_n_f64_x(pg1, t4506, t4505, 0.41908315722758349);
        s3115 = svmul_n_f64_x(pg1, s3223, 0.4066888930575896);
        s3224 = svmla_n_f64_x(pg1, t4509, t4510, 0.49572725516748389);
        s3116 = svmul_n_f64_x(pg1, s3224, 0.39507823426270006);
        s3225 = svmls_n_f64_x(pg1, t4510, t4509, 0.49572725516748389);
        s3117 = svmul_n_f64_x(pg1, s3225, 0.39507823426270006);
        s3118 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4486, t4496), 0.44095855184409843);
        s3119 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4485, t4495), 0.44095855184409843);
        s3226 = svmls_n_f64_x(pg1, t4507, t4508, 0.49572725516748389);
        s3120 = svmul_n_f64_x(pg1, s3226, 0.39507823426270006);
        s3227 = svmla_n_f64_x(pg1, t4507, t4508, 2.0172382889501304);
        s3121 = svmul_n_f64_x(pg1, s3227, 0.1958510486474645);
        s3228 = svmls_n_f64_x(pg1, t4512, t4511, 2.386161273135941);
        s3122 = svmul_n_f64_x(pg1, s3228, 0.17043646531196566);
        s3229 = svmla_n_f64_x(pg1, t4511, t4512, 2.386161273135941);
        s3123 = svmul_n_f64_x(pg1, s3229, 0.17043646531196566);
        s3124 = svadd_f64_x(pg1, s2976, t4503);
        s3125 = svadd_f64_x(pg1, s2977, t4504);
        t4515 = svadd_f64_x(pg1, s3116, s3120);
        t4516 = svadd_f64_x(pg1, s3117, s3121);
        t4517 = svadd_f64_x(pg1, t4513, t4515);
        t4518 = svadd_f64_x(pg1, t4514, t4516);
        t4519 = svmls_n_f64_x(pg1, t4513, t4515, 0.5);
        t4520 = svmls_n_f64_x(pg1, t4514, t4516, 0.5);
        s3126 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3117, s3121), 0.8660254037844386);
        s3127 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3116, s3120), 0.8660254037844386);
        t4521 = svadd_f64_x(pg1, t4519, s3126);
        t4522 = svsub_f64_x(pg1, t4520, s3127);
        t4523 = svsub_f64_x(pg1, t4519, s3126);
        t4524 = svadd_f64_x(pg1, t4520, s3127);
        t4525 = svadd_f64_x(pg1, s3118, s3122);
        t4526 = svadd_f64_x(pg1, s3119, s3123);
        t4527 = svadd_f64_x(pg1, s3114, t4525);
        t4528 = svsub_f64_x(pg1, s3115, t4526);
        t4529 = svmls_n_f64_x(pg1, s3114, t4525, 0.5);
        t4530 = svmla_n_f64_x(pg1, s3115, t4526, 0.5);
        s3128 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3123, s3119), 0.8660254037844386);
        s3129 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s3118, s3122), 0.8660254037844386);
        t4531 = svadd_f64_x(pg1, t4529, s3128);
        t4532 = svsub_f64_x(pg1, t4530, s3129);
        t4533 = svsub_f64_x(pg1, t4529, s3128);
        t4534 = svadd_f64_x(pg1, t4530, s3129);
        s3230 = svmla_n_f64_x(pg1, t4531, t4532, 1.7320508075688772);
        s3130 = svmul_n_f64_x(pg1, s3230, 0.5);
        s3231 = svmls_n_f64_x(pg1, t4532, t4531, 1.7320508075688772);
        s3131 = svmul_n_f64_x(pg1, s3231, 0.5);
        s3232 = svmls_n_f64_x(pg1, t4534, t4533, 0.57735026918962584);
        s3132 = svmul_n_f64_x(pg1, s3232, 0.8660254037844386);
        s3233 = svmla_n_f64_x(pg1, t4533, t4534, 0.57735026918962584);
        s3133 = svmul_n_f64_x(pg1, s3233, 0.8660254037844386);
        s3134 = svadd_f64_x(pg1, t4517, t4527);
        s3135 = svadd_f64_x(pg1, t4518, t4528);
        s3136 = svsub_f64_x(pg1, t4517, t4527);
        s3137 = svsub_f64_x(pg1, t4518, t4528);
        s3138 = svadd_f64_x(pg1, t4521, s3130);
        s3139 = svadd_f64_x(pg1, t4522, s3131);
        s3140 = svsub_f64_x(pg1, t4521, s3130);
        s3141 = svsub_f64_x(pg1, t4522, s3131);
        s3142 = svadd_f64_x(pg1, t4523, s3132);
        s3143 = svsub_f64_x(pg1, t4524, s3133);
        s3144 = svsub_f64_x(pg1, t4523, s3132);
        s3145 = svadd_f64_x(pg1, t4524, s3133);
        a5104 = (TW1 + ((40)*(j1)));
        a5105 = svld1_gather_u64offset_f64(pg1, a5104, svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5106 = svld1_gather_u64offset_f64(pg1, (a5104 + 1), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3146 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5106, s3085), a5105, s3084);
        s3147 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5105, s3085), a5106, s3084);
        a5107 = svld1_gather_u64offset_f64(pg1, (a5104 + 2), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5108 = svld1_gather_u64offset_f64(pg1, (a5104 + 3), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3148 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5108, s3125), a5107, s3124);
        s3149 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5107, s3125), a5108, s3124);
        a5109 = svld1_gather_u64offset_f64(pg1, (a5104 + 4), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5110 = svld1_gather_u64offset_f64(pg1, (a5104 + 5), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3150 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5110, s3055), a5109, s3054);
        s3151 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5109, s3055), a5110, s3054);
        a5111 = svld1_gather_u64offset_f64(pg1, (a5104 + 6), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5112 = svld1_gather_u64offset_f64(pg1, (a5104 + 7), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3152 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5112, s3095), a5111, s3094);
        s3153 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5111, s3095), a5112, s3094);
        a5113 = svld1_gather_u64offset_f64(pg1, (a5104 + 8), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5114 = svld1_gather_u64offset_f64(pg1, (a5104 + 9), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3154 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5114, s3135), a5113, s3134);
        s3155 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5113, s3135), a5114, s3134);
        a5115 = svld1_gather_u64offset_f64(pg1, (a5104 + 10), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5116 = svld1_gather_u64offset_f64(pg1, (a5104 + 11), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3156 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5116, s3063), a5115, s3062);
        s3157 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5115, s3063), a5116, s3062);
        a5117 = svld1_gather_u64offset_f64(pg1, (a5104 + 12), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5118 = svld1_gather_u64offset_f64(pg1, (a5104 + 13), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3158 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5118, s3103), a5117, s3102);
        s3159 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5117, s3103), a5118, s3102);
        a5119 = svld1_gather_u64offset_f64(pg1, (a5104 + 14), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5120 = svld1_gather_u64offset_f64(pg1, (a5104 + 15), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3160 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5120, s3143), a5119, s3142);
        s3161 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5119, s3143), a5120, s3142);
        a5121 = svld1_gather_u64offset_f64(pg1, (a5104 + 16), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5122 = svld1_gather_u64offset_f64(pg1, (a5104 + 17), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3162 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5122, s3059), a5121, s3058);
        s3163 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5121, s3059), a5122, s3058);
        a5123 = svld1_gather_u64offset_f64(pg1, (a5104 + 18), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5124 = svld1_gather_u64offset_f64(pg1, (a5104 + 19), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3164 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5124, s3099), a5123, s3098);
        s3165 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5123, s3099), a5124, s3098);
        a5125 = svld1_gather_u64offset_f64(pg1, (a5104 + 20), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5126 = svld1_gather_u64offset_f64(pg1, (a5104 + 21), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3166 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5126, s3139), a5125, s3138);
        s3167 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5125, s3139), a5126, s3138);
        a5127 = svld1_gather_u64offset_f64(pg1, (a5104 + 22), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5128 = svld1_gather_u64offset_f64(pg1, (a5104 + 23), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3168 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5128, s3061), a5127, s3060);
        s3169 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5127, s3061), a5128, s3060);
        a5129 = svld1_gather_u64offset_f64(pg1, (a5104 + 24), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5130 = svld1_gather_u64offset_f64(pg1, (a5104 + 25), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3170 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5130, s3101), a5129, s3100);
        s3171 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5129, s3101), a5130, s3100);
        a5131 = svld1_gather_u64offset_f64(pg1, (a5104 + 26), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5132 = svld1_gather_u64offset_f64(pg1, (a5104 + 27), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3172 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5132, s3141), a5131, s3140);
        s3173 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5131, s3141), a5132, s3140);
        a5133 = svld1_gather_u64offset_f64(pg1, (a5104 + 28), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5134 = svld1_gather_u64offset_f64(pg1, (a5104 + 29), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3174 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5134, s3065), a5133, s3064);
        s3175 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5133, s3065), a5134, s3064);
        a5135 = svld1_gather_u64offset_f64(pg1, (a5104 + 30), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5136 = svld1_gather_u64offset_f64(pg1, (a5104 + 31), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3176 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5136, s3105), a5135, s3104);
        s3177 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5135, s3105), a5136, s3104);
        a5137 = svld1_gather_u64offset_f64(pg1, (a5104 + 32), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5138 = svld1_gather_u64offset_f64(pg1, (a5104 + 33), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3178 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5138, s3145), a5137, s3144);
        s3179 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5137, s3145), a5138, s3144);
        a5139 = svld1_gather_u64offset_f64(pg1, (a5104 + 34), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5140 = svld1_gather_u64offset_f64(pg1, (a5104 + 35), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3180 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5140, s3057), a5139, s3056);
        s3181 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5139, s3057), a5140, s3056);
        a5141 = svld1_gather_u64offset_f64(pg1, (a5104 + 36), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5142 = svld1_gather_u64offset_f64(pg1, (a5104 + 37), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3182 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5142, s3097), a5141, s3096);
        s3183 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5141, s3097), a5142, s3096);
        a5143 = svld1_gather_u64offset_f64(pg1, (a5104 + 38), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        a5144 = svld1_gather_u64offset_f64(pg1, (a5104 + 39), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))));
        s3184 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a5144, s3137), a5143, s3136);
        s3185 = svmla_f64_x(pg1, svmul_f64_x(pg1, a5143, s3137), a5144, s3136);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3044);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3045);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3146);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3147);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3148);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3149);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3150);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3151);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3152);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3153);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3154);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3155);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3156);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3157);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3158);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3159);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3160);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3161);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3162);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3163);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3164);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3165);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3166);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3167);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3168);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3169);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3170);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3171);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3172);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3173);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3174);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3175);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3176);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3177);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3178);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3179);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3180);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3181);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3182);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3183);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(40 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3184);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(41 + Y + ((42)*(j1)))), svindex_u64(0, (int64_t)(42 * sizeof(float64_t))), s3185);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
