/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft24a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D68[16];
    static float64_t D69[32];
    int l1;
    float64_t  *a10152;
    svfloat64x2_t s4812, s4815, s4818, s4821, s4824, s4827, s4830, s4833, 
            s4836, s4839, s4842, s4845, s4848, s4851, s4854, s4857, 
            s4860, s4863, s4866, s4869, s4872, s4875, s4878, s4881;
    svfloat64_t a10140, a10141, a10142, a10143, a10144, a10145, a10146, a10147, 
            a10148, a10149, a10150, a10151, a10153, a10154, a10155, a10156, 
            a10157, a10158, a10159, a10160, a10161, a10162, a10163, a10164, 
            a10165, a10166, a10167, a10168, a10169, a10170, a10171, a10172, 
            a10173, a10174, a10175, a10176, a10177, a10178, a10179, a10180, 
            a10181, a10182, a10183, a10184, a10185, a10186, a10187, a10188, 
            a10189, a10190, a10191, a10192, a10193, a10194, a10195, a10196, 
            a10197, a10198, s4813, s4814, s4816, s4817, s4819, s4820, 
            s4822, s4823, s4825, s4826, s4828, s4829, s4831, s4832, 
            s4834, s4835, s4837, s4838, s4840, s4841, s4843, s4844, 
            s4846, s4847, s4849, s4850, s4852, s4853, s4855, s4856, 
            s4858, s4859, s4861, s4862, s4864, s4865, s4867, s4868, 
            s4870, s4871, s4873, s4874, s4876, s4877, s4879, s4880, 
            s4882, s4883, s4884, s4885, s4886, s4887, s4888, s4889, 
            s4890, s4891, s4892, s4893, s4894, s4895, s4896, s4897, 
            s4898, s4899, s4900, s4901, s4902, s4903, s4904, s4905, 
            s4906, s4907, s4908, s4909, s4910, s4911, s4912, s4913, 
            s4914, s4915, s4916, s4917, s4918, s4919, s4920, s4921, 
            s4922, s4923, s4924, s4925, s4926, s4927, s4928, s4929, 
            s4930, s4931, s4932, s4933, s4934, s4935, s4936, s4937, 
            s4938, s4939, s4940, s4941, s4942, s4943, s4944, s4945, 
            s4946, s4947, s4948, s4949, s4950, s4951, s4952, s4953, 
            s4954, s4955, s4956, s4957, s4958, s4959, s4960, s4961, 
            s4962, s4963, s4964, s4965, s4966, s4967, s4968, s4969, 
            s4970, s4971, s4972, s4973, s4974, s4975, s4976, s4977, 
            s4978, s4979, s4980, s4981, s4982, s4983, s4984, s4985, 
            s4986, s4987, s4988, s4989, s4990, s4991, s4992, s4993, 
            s4994, s4995, s4996, s4997, s4998, s4999, s5000, s5001, 
            s5002, s5003, s5004, s5005, s5006, s5007, s5008, s5009, 
            s5010, s5011, s5012, s5013, s5014, s5015, s5016, s5017, 
            s5018, s5019, s5020, s5021, s5022, s5023, s5024, s5025, 
            s5026, s5027, s5028, s5029, s5030, s5031, s5032, s5033, 
            s5034, s5035, s5036, s5037, s5038, s5039, s5040, s5041, 
            s5042, s5043, s5044, s5045, s5046, s5047, s5048, s5049, 
            s5050, s5051, s5052, s5053, t7515, t7516, t7517, t7518, 
            t7519, t7520, t7521, t7522, t7523, t7524, t7525, t7526, 
            t7527, t7528, t7529, t7530, t7531, t7532, t7533, t7534, 
            t7535, t7536, t7537, t7538, t7539, t7540, t7541, t7542, 
            t7543, t7544, t7545, t7546, t7547, t7548, t7549, t7550, 
            t7551, t7552, t7553, t7554, t7555, t7556, t7557, t7558, 
            t7559, t7560, t7561, t7562, t7563, t7564, t7565, t7566, 
            t7567, t7568, t7569, t7570, t7571, t7572, t7573, t7574, 
            t7575, t7576, t7577, t7578, t7579, t7580, t7581, t7582, 
            t7583, t7584, t7585, t7586, t7587, t7588, t7589, t7590, 
            t7591, t7592, t7593, t7594, t7595, t7596, t7597, t7598, 
            t7599, t7600, t7601, t7602, t7603, t7604, t7605, t7606, 
            t7607, t7608, t7609, t7610, t7611, t7612, t7613, t7614, 
            t7615, t7616, t7617, t7618, t7619, t7620, t7621, t7622, 
            t7623, t7624, t7625, t7626, t7627, t7628, t7629, t7630, 
            t7631, t7632, t7633, t7634, t7635, t7636, t7637, t7638, 
            t7639, t7640, t7641, t7642, t7643, t7644, t7645, t7646, 
            t7647, t7648, t7649, t7650, t7651, t7652, t7653, t7654, 
            t7655, t7656, t7657, t7658, t7659, t7660, t7661, t7662, 
            t7663, t7664, t7665, t7666, t7667, t7668, t7669, t7670, 
            t7671, t7672, t7673, t7674, t7675, t7676, t7677, t7678;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s4812 = svld2_f64(pg1, (X + ((2)*(j1))));
        s4813 = s4812.v0;
        s4814 = s4812.v1;
        s4815 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s4816 = s4815.v0;
        s4817 = s4815.v1;
        s4818 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s4819 = s4818.v0;
        s4820 = s4818.v1;
        s4821 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s4822 = s4821.v0;
        s4823 = s4821.v1;
        s4824 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s4825 = s4824.v0;
        s4826 = s4824.v1;
        s4827 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s4828 = s4827.v0;
        s4829 = s4827.v1;
        s4830 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s4831 = s4830.v0;
        s4832 = s4830.v1;
        s4833 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s4834 = s4833.v0;
        s4835 = s4833.v1;
        s4836 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s4837 = s4836.v0;
        s4838 = s4836.v1;
        s4839 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s4840 = s4839.v0;
        s4841 = s4839.v1;
        s4842 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s4843 = s4842.v0;
        s4844 = s4842.v1;
        s4845 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s4846 = s4845.v0;
        s4847 = s4845.v1;
        s4848 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s4849 = s4848.v0;
        s4850 = s4848.v1;
        s4851 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s4852 = s4851.v0;
        s4853 = s4851.v1;
        s4854 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s4855 = s4854.v0;
        s4856 = s4854.v1;
        s4857 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s4858 = s4857.v0;
        s4859 = s4857.v1;
        s4860 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s4861 = s4860.v0;
        s4862 = s4860.v1;
        s4863 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s4864 = s4863.v0;
        s4865 = s4863.v1;
        s4866 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s4867 = s4866.v0;
        s4868 = s4866.v1;
        s4869 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s4870 = s4869.v0;
        s4871 = s4869.v1;
        s4872 = svld2_f64(pg1, (X + ((2)*((j1 + ((20)*(l1)))))));
        s4873 = s4872.v0;
        s4874 = s4872.v1;
        s4875 = svld2_f64(pg1, (X + ((2)*((j1 + ((21)*(l1)))))));
        s4876 = s4875.v0;
        s4877 = s4875.v1;
        s4878 = svld2_f64(pg1, (X + ((2)*((j1 + ((22)*(l1)))))));
        s4879 = s4878.v0;
        s4880 = s4878.v1;
        s4881 = svld2_f64(pg1, (X + ((2)*((j1 + ((23)*(l1)))))));
        s4882 = s4881.v0;
        s4883 = s4881.v1;
        t7515 = svadd_f64_x(pg1, s4837, s4861);
        t7516 = svadd_f64_x(pg1, s4838, s4862);
        t7517 = svadd_f64_x(pg1, s4813, t7515);
        t7518 = svadd_f64_x(pg1, s4814, t7516);
        t7519 = svmls_n_f64_x(pg1, s4813, t7515, 0.5);
        t7520 = svmls_n_f64_x(pg1, s4814, t7516, 0.5);
        s4884 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4838, s4862), 0.8660254037844386);
        s4885 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4837, s4861), 0.8660254037844386);
        s4886 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7518, D68[1]), t7517, D68[0]);
        s4887 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7518, D68[0]), t7517, D68[1]);
        t7521 = svadd_f64_x(pg1, t7519, s4884);
        t7522 = svsub_f64_x(pg1, t7520, s4885);
        t7523 = svsub_f64_x(pg1, t7519, s4884);
        t7524 = svadd_f64_x(pg1, t7520, s4885);
        s4888 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7522, D69[1]), t7521, D69[0]);
        s4889 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7522, D69[0]), t7521, D69[1]);
        s4890 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7524, D69[3]), t7523, D69[2]);
        s4891 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7524, D69[2]), t7523, D69[3]);
        t7525 = svadd_f64_x(pg1, s4840, s4864);
        t7526 = svadd_f64_x(pg1, s4841, s4865);
        t7527 = svadd_f64_x(pg1, s4816, t7525);
        t7528 = svadd_f64_x(pg1, s4817, t7526);
        t7529 = svmls_n_f64_x(pg1, s4816, t7525, 0.5);
        t7530 = svmls_n_f64_x(pg1, s4817, t7526, 0.5);
        s4892 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4841, s4865), 0.8660254037844386);
        s4893 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4840, s4864), 0.8660254037844386);
        s4894 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7528, D68[3]), t7527, D68[2]);
        s4895 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7528, D68[2]), t7527, D68[3]);
        t7531 = svadd_f64_x(pg1, t7529, s4892);
        t7532 = svsub_f64_x(pg1, t7530, s4893);
        t7533 = svsub_f64_x(pg1, t7529, s4892);
        t7534 = svadd_f64_x(pg1, t7530, s4893);
        s4896 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7532, D69[5]), t7531, D69[4]);
        s4897 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7532, D69[4]), t7531, D69[5]);
        s4898 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7534, D69[7]), t7533, D69[6]);
        s4899 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7534, D69[6]), t7533, D69[7]);
        t7535 = svadd_f64_x(pg1, s4843, s4867);
        t7536 = svadd_f64_x(pg1, s4844, s4868);
        t7537 = svadd_f64_x(pg1, s4819, t7535);
        t7538 = svadd_f64_x(pg1, s4820, t7536);
        t7539 = svmls_n_f64_x(pg1, s4819, t7535, 0.5);
        t7540 = svmls_n_f64_x(pg1, s4820, t7536, 0.5);
        s4900 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4844, s4868), 0.8660254037844386);
        s4901 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4843, s4867), 0.8660254037844386);
        s4902 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7538, D68[5]), t7537, D68[4]);
        s4903 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7538, D68[4]), t7537, D68[5]);
        t7541 = svadd_f64_x(pg1, t7539, s4900);
        t7542 = svsub_f64_x(pg1, t7540, s4901);
        t7543 = svsub_f64_x(pg1, t7539, s4900);
        t7544 = svadd_f64_x(pg1, t7540, s4901);
        s4904 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7542, D69[9]), t7541, D69[8]);
        s4905 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7542, D69[8]), t7541, D69[9]);
        s4906 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7544, D69[11]), t7543, D69[10]);
        s4907 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7544, D69[10]), t7543, D69[11]);
        t7545 = svadd_f64_x(pg1, s4846, s4870);
        t7546 = svadd_f64_x(pg1, s4847, s4871);
        t7547 = svadd_f64_x(pg1, s4822, t7545);
        t7548 = svadd_f64_x(pg1, s4823, t7546);
        t7549 = svmls_n_f64_x(pg1, s4822, t7545, 0.5);
        t7550 = svmls_n_f64_x(pg1, s4823, t7546, 0.5);
        s4908 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4847, s4871), 0.8660254037844386);
        s4909 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4846, s4870), 0.8660254037844386);
        s4910 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7548, D68[7]), t7547, D68[6]);
        s4911 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7548, D68[6]), t7547, D68[7]);
        t7551 = svadd_f64_x(pg1, t7549, s4908);
        t7552 = svsub_f64_x(pg1, t7550, s4909);
        t7553 = svsub_f64_x(pg1, t7549, s4908);
        t7554 = svadd_f64_x(pg1, t7550, s4909);
        s4912 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7552, D69[13]), t7551, D69[12]);
        s4913 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7552, D69[12]), t7551, D69[13]);
        s4914 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7554, D69[15]), t7553, D69[14]);
        s4915 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7554, D69[14]), t7553, D69[15]);
        t7555 = svadd_f64_x(pg1, s4849, s4873);
        t7556 = svadd_f64_x(pg1, s4850, s4874);
        t7557 = svadd_f64_x(pg1, s4825, t7555);
        t7558 = svadd_f64_x(pg1, s4826, t7556);
        t7559 = svmls_n_f64_x(pg1, s4825, t7555, 0.5);
        t7560 = svmls_n_f64_x(pg1, s4826, t7556, 0.5);
        s4916 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4850, s4874), 0.8660254037844386);
        s4917 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4849, s4873), 0.8660254037844386);
        s4918 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7558, D68[9]), t7557, D68[8]);
        s4919 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7558, D68[8]), t7557, D68[9]);
        t7561 = svadd_f64_x(pg1, t7559, s4916);
        t7562 = svsub_f64_x(pg1, t7560, s4917);
        t7563 = svsub_f64_x(pg1, t7559, s4916);
        t7564 = svadd_f64_x(pg1, t7560, s4917);
        s4920 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7562, D69[17]), t7561, D69[16]);
        s4921 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7562, D69[16]), t7561, D69[17]);
        s4922 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7564, D69[19]), t7563, D69[18]);
        s4923 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7564, D69[18]), t7563, D69[19]);
        t7565 = svadd_f64_x(pg1, s4852, s4876);
        t7566 = svadd_f64_x(pg1, s4853, s4877);
        t7567 = svadd_f64_x(pg1, s4828, t7565);
        t7568 = svadd_f64_x(pg1, s4829, t7566);
        t7569 = svmls_n_f64_x(pg1, s4828, t7565, 0.5);
        t7570 = svmls_n_f64_x(pg1, s4829, t7566, 0.5);
        s4924 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4853, s4877), 0.8660254037844386);
        s4925 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4852, s4876), 0.8660254037844386);
        s4926 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7568, D68[11]), t7567, D68[10]);
        s4927 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7568, D68[10]), t7567, D68[11]);
        t7571 = svadd_f64_x(pg1, t7569, s4924);
        t7572 = svsub_f64_x(pg1, t7570, s4925);
        t7573 = svsub_f64_x(pg1, t7569, s4924);
        t7574 = svadd_f64_x(pg1, t7570, s4925);
        s4928 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7572, D69[21]), t7571, D69[20]);
        s4929 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7572, D69[20]), t7571, D69[21]);
        s4930 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7574, D69[23]), t7573, D69[22]);
        s4931 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7574, D69[22]), t7573, D69[23]);
        t7575 = svadd_f64_x(pg1, s4855, s4879);
        t7576 = svadd_f64_x(pg1, s4856, s4880);
        t7577 = svadd_f64_x(pg1, s4831, t7575);
        t7578 = svadd_f64_x(pg1, s4832, t7576);
        t7579 = svmls_n_f64_x(pg1, s4831, t7575, 0.5);
        t7580 = svmls_n_f64_x(pg1, s4832, t7576, 0.5);
        s4932 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4856, s4880), 0.8660254037844386);
        s4933 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4855, s4879), 0.8660254037844386);
        s4934 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7578, D68[13]), t7577, D68[12]);
        s4935 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7578, D68[12]), t7577, D68[13]);
        t7581 = svadd_f64_x(pg1, t7579, s4932);
        t7582 = svsub_f64_x(pg1, t7580, s4933);
        t7583 = svsub_f64_x(pg1, t7579, s4932);
        t7584 = svadd_f64_x(pg1, t7580, s4933);
        s4936 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7582, D69[25]), t7581, D69[24]);
        s4937 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7582, D69[24]), t7581, D69[25]);
        s4938 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7584, D69[27]), t7583, D69[26]);
        s4939 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7584, D69[26]), t7583, D69[27]);
        t7585 = svadd_f64_x(pg1, s4858, s4882);
        t7586 = svadd_f64_x(pg1, s4859, s4883);
        t7587 = svadd_f64_x(pg1, s4834, t7585);
        t7588 = svadd_f64_x(pg1, s4835, t7586);
        t7589 = svmls_n_f64_x(pg1, s4834, t7585, 0.5);
        t7590 = svmls_n_f64_x(pg1, s4835, t7586, 0.5);
        s4940 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4859, s4883), 0.8660254037844386);
        s4941 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4858, s4882), 0.8660254037844386);
        s4942 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7588, D68[15]), t7587, D68[14]);
        s4943 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7588, D68[14]), t7587, D68[15]);
        t7591 = svadd_f64_x(pg1, t7589, s4940);
        t7592 = svsub_f64_x(pg1, t7590, s4941);
        t7593 = svsub_f64_x(pg1, t7589, s4940);
        t7594 = svadd_f64_x(pg1, t7590, s4941);
        s4944 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7592, D69[29]), t7591, D69[28]);
        s4945 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7592, D69[28]), t7591, D69[29]);
        s4946 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7594, D69[31]), t7593, D69[30]);
        s4947 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7594, D69[30]), t7593, D69[31]);
        t7595 = svadd_f64_x(pg1, s4886, s4918);
        t7596 = svadd_f64_x(pg1, s4887, s4919);
        t7597 = svsub_f64_x(pg1, s4886, s4918);
        t7598 = svsub_f64_x(pg1, s4887, s4919);
        t7599 = svadd_f64_x(pg1, s4902, s4934);
        t7600 = svadd_f64_x(pg1, s4903, s4935);
        t7601 = svsub_f64_x(pg1, s4902, s4934);
        t7602 = svsub_f64_x(pg1, s4903, s4935);
        t7603 = svadd_f64_x(pg1, t7595, t7599);
        t7604 = svadd_f64_x(pg1, t7596, t7600);
        t7605 = svsub_f64_x(pg1, t7595, t7599);
        t7606 = svsub_f64_x(pg1, t7596, t7600);
        t7607 = svadd_f64_x(pg1, t7597, t7602);
        t7608 = svsub_f64_x(pg1, t7598, t7601);
        t7609 = svsub_f64_x(pg1, t7597, t7602);
        t7610 = svadd_f64_x(pg1, t7598, t7601);
        t7611 = svadd_f64_x(pg1, s4894, s4926);
        t7612 = svadd_f64_x(pg1, s4895, s4927);
        t7613 = svsub_f64_x(pg1, s4894, s4926);
        t7614 = svsub_f64_x(pg1, s4895, s4927);
        t7615 = svadd_f64_x(pg1, s4910, s4942);
        t7616 = svadd_f64_x(pg1, s4911, s4943);
        t7617 = svsub_f64_x(pg1, s4910, s4942);
        t7618 = svsub_f64_x(pg1, s4911, s4943);
        t7619 = svadd_f64_x(pg1, t7611, t7615);
        t7620 = svadd_f64_x(pg1, t7612, t7616);
        t7621 = svsub_f64_x(pg1, t7611, t7615);
        t7622 = svsub_f64_x(pg1, t7612, t7616);
        a10140 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7613, t7618), 0.70710678118654757);
        a10141 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7614, t7617), 0.70710678118654757);
        s4948 = svadd_f64_x(pg1, a10140, a10141);
        s4949 = svsub_f64_x(pg1, a10141, a10140);
        a10142 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7614, t7617), 0.70710678118654757);
        a10143 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7613, t7618), 0.70710678118654757);
        s4950 = svsub_f64_x(pg1, a10142, a10143);
        s4951 = svadd_f64_x(pg1, a10143, a10142);
        s4952 = svadd_f64_x(pg1, t7603, t7619);
        s4953 = svadd_f64_x(pg1, t7604, t7620);
        s4954 = svsub_f64_x(pg1, t7603, t7619);
        s4955 = svsub_f64_x(pg1, t7604, t7620);
        s4956 = svadd_f64_x(pg1, t7607, s4948);
        s4957 = svadd_f64_x(pg1, t7608, s4949);
        s4958 = svsub_f64_x(pg1, t7607, s4948);
        s4959 = svsub_f64_x(pg1, t7608, s4949);
        s4960 = svadd_f64_x(pg1, t7605, t7622);
        s4961 = svsub_f64_x(pg1, t7606, t7621);
        s4962 = svsub_f64_x(pg1, t7605, t7622);
        s4963 = svadd_f64_x(pg1, t7606, t7621);
        s4964 = svadd_f64_x(pg1, t7609, s4950);
        s4965 = svsub_f64_x(pg1, t7610, s4951);
        s4966 = svsub_f64_x(pg1, t7609, s4950);
        s4967 = svadd_f64_x(pg1, t7610, s4951);
        t7623 = svadd_f64_x(pg1, s4888, s4920);
        t7624 = svadd_f64_x(pg1, s4889, s4921);
        t7625 = svsub_f64_x(pg1, s4888, s4920);
        t7626 = svsub_f64_x(pg1, s4889, s4921);
        t7627 = svadd_f64_x(pg1, s4904, s4936);
        t7628 = svadd_f64_x(pg1, s4905, s4937);
        t7629 = svsub_f64_x(pg1, s4904, s4936);
        t7630 = svsub_f64_x(pg1, s4905, s4937);
        t7631 = svadd_f64_x(pg1, t7623, t7627);
        t7632 = svadd_f64_x(pg1, t7624, t7628);
        t7633 = svsub_f64_x(pg1, t7623, t7627);
        t7634 = svsub_f64_x(pg1, t7624, t7628);
        t7635 = svadd_f64_x(pg1, t7625, t7630);
        t7636 = svsub_f64_x(pg1, t7626, t7629);
        t7637 = svsub_f64_x(pg1, t7625, t7630);
        t7638 = svadd_f64_x(pg1, t7626, t7629);
        t7639 = svadd_f64_x(pg1, s4896, s4928);
        t7640 = svadd_f64_x(pg1, s4897, s4929);
        t7641 = svsub_f64_x(pg1, s4896, s4928);
        t7642 = svsub_f64_x(pg1, s4897, s4929);
        t7643 = svadd_f64_x(pg1, s4912, s4944);
        t7644 = svadd_f64_x(pg1, s4913, s4945);
        t7645 = svsub_f64_x(pg1, s4912, s4944);
        t7646 = svsub_f64_x(pg1, s4913, s4945);
        t7647 = svadd_f64_x(pg1, t7639, t7643);
        t7648 = svadd_f64_x(pg1, t7640, t7644);
        t7649 = svsub_f64_x(pg1, t7639, t7643);
        t7650 = svsub_f64_x(pg1, t7640, t7644);
        a10144 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7641, t7646), 0.70710678118654757);
        a10145 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7642, t7645), 0.70710678118654757);
        s4968 = svadd_f64_x(pg1, a10144, a10145);
        s4969 = svsub_f64_x(pg1, a10145, a10144);
        a10146 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7642, t7645), 0.70710678118654757);
        a10147 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7641, t7646), 0.70710678118654757);
        s4970 = svsub_f64_x(pg1, a10146, a10147);
        s4971 = svadd_f64_x(pg1, a10147, a10146);
        s4972 = svadd_f64_x(pg1, t7631, t7647);
        s4973 = svadd_f64_x(pg1, t7632, t7648);
        s4974 = svsub_f64_x(pg1, t7631, t7647);
        s4975 = svsub_f64_x(pg1, t7632, t7648);
        s4976 = svadd_f64_x(pg1, t7635, s4968);
        s4977 = svadd_f64_x(pg1, t7636, s4969);
        s4978 = svsub_f64_x(pg1, t7635, s4968);
        s4979 = svsub_f64_x(pg1, t7636, s4969);
        s4980 = svadd_f64_x(pg1, t7633, t7650);
        s4981 = svsub_f64_x(pg1, t7634, t7649);
        s4982 = svsub_f64_x(pg1, t7633, t7650);
        s4983 = svadd_f64_x(pg1, t7634, t7649);
        s4984 = svadd_f64_x(pg1, t7637, s4970);
        s4985 = svsub_f64_x(pg1, t7638, s4971);
        s4986 = svsub_f64_x(pg1, t7637, s4970);
        s4987 = svadd_f64_x(pg1, t7638, s4971);
        t7651 = svadd_f64_x(pg1, s4890, s4922);
        t7652 = svadd_f64_x(pg1, s4891, s4923);
        t7653 = svsub_f64_x(pg1, s4890, s4922);
        t7654 = svsub_f64_x(pg1, s4891, s4923);
        t7655 = svadd_f64_x(pg1, s4906, s4938);
        t7656 = svadd_f64_x(pg1, s4907, s4939);
        t7657 = svsub_f64_x(pg1, s4906, s4938);
        t7658 = svsub_f64_x(pg1, s4907, s4939);
        t7659 = svadd_f64_x(pg1, t7651, t7655);
        t7660 = svadd_f64_x(pg1, t7652, t7656);
        t7661 = svsub_f64_x(pg1, t7651, t7655);
        t7662 = svsub_f64_x(pg1, t7652, t7656);
        t7663 = svadd_f64_x(pg1, t7653, t7658);
        t7664 = svsub_f64_x(pg1, t7654, t7657);
        t7665 = svsub_f64_x(pg1, t7653, t7658);
        t7666 = svadd_f64_x(pg1, t7654, t7657);
        t7667 = svadd_f64_x(pg1, s4898, s4930);
        t7668 = svadd_f64_x(pg1, s4899, s4931);
        t7669 = svsub_f64_x(pg1, s4898, s4930);
        t7670 = svsub_f64_x(pg1, s4899, s4931);
        t7671 = svadd_f64_x(pg1, s4914, s4946);
        t7672 = svadd_f64_x(pg1, s4915, s4947);
        t7673 = svsub_f64_x(pg1, s4914, s4946);
        t7674 = svsub_f64_x(pg1, s4915, s4947);
        t7675 = svadd_f64_x(pg1, t7667, t7671);
        t7676 = svadd_f64_x(pg1, t7668, t7672);
        t7677 = svsub_f64_x(pg1, t7667, t7671);
        t7678 = svsub_f64_x(pg1, t7668, t7672);
        a10148 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7669, t7674), 0.70710678118654757);
        a10149 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7670, t7673), 0.70710678118654757);
        s4988 = svadd_f64_x(pg1, a10148, a10149);
        s4989 = svsub_f64_x(pg1, a10149, a10148);
        a10150 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7670, t7673), 0.70710678118654757);
        a10151 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7669, t7674), 0.70710678118654757);
        s4990 = svsub_f64_x(pg1, a10150, a10151);
        s4991 = svadd_f64_x(pg1, a10151, a10150);
        s4992 = svadd_f64_x(pg1, t7659, t7675);
        s4993 = svadd_f64_x(pg1, t7660, t7676);
        s4994 = svsub_f64_x(pg1, t7659, t7675);
        s4995 = svsub_f64_x(pg1, t7660, t7676);
        s4996 = svadd_f64_x(pg1, t7663, s4988);
        s4997 = svadd_f64_x(pg1, t7664, s4989);
        s4998 = svsub_f64_x(pg1, t7663, s4988);
        s4999 = svsub_f64_x(pg1, t7664, s4989);
        s5000 = svadd_f64_x(pg1, t7661, t7678);
        s5001 = svsub_f64_x(pg1, t7662, t7677);
        s5002 = svsub_f64_x(pg1, t7661, t7678);
        s5003 = svadd_f64_x(pg1, t7662, t7677);
        s5004 = svadd_f64_x(pg1, t7665, s4990);
        s5005 = svsub_f64_x(pg1, t7666, s4991);
        s5006 = svsub_f64_x(pg1, t7665, s4990);
        s5007 = svadd_f64_x(pg1, t7666, s4991);
        a10152 = (TW1 + ((46)*(j1)));
        a10153 = svld1_gather_u64offset_f64(pg1, a10152, svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10154 = svld1_gather_u64offset_f64(pg1, (a10152 + 1), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5008 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10154, s4973), a10153, s4972);
        s5009 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10153, s4973), a10154, s4972);
        a10155 = svld1_gather_u64offset_f64(pg1, (a10152 + 2), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10156 = svld1_gather_u64offset_f64(pg1, (a10152 + 3), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5010 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10156, s4993), a10155, s4992);
        s5011 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10155, s4993), a10156, s4992);
        a10157 = svld1_gather_u64offset_f64(pg1, (a10152 + 4), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10158 = svld1_gather_u64offset_f64(pg1, (a10152 + 5), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5012 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10158, s4957), a10157, s4956);
        s5013 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10157, s4957), a10158, s4956);
        a10159 = svld1_gather_u64offset_f64(pg1, (a10152 + 6), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10160 = svld1_gather_u64offset_f64(pg1, (a10152 + 7), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5014 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10160, s4977), a10159, s4976);
        s5015 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10159, s4977), a10160, s4976);
        a10161 = svld1_gather_u64offset_f64(pg1, (a10152 + 8), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10162 = svld1_gather_u64offset_f64(pg1, (a10152 + 9), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5016 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10162, s4997), a10161, s4996);
        s5017 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10161, s4997), a10162, s4996);
        a10163 = svld1_gather_u64offset_f64(pg1, (a10152 + 10), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10164 = svld1_gather_u64offset_f64(pg1, (a10152 + 11), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5018 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10164, s4961), a10163, s4960);
        s5019 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10163, s4961), a10164, s4960);
        a10165 = svld1_gather_u64offset_f64(pg1, (a10152 + 12), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10166 = svld1_gather_u64offset_f64(pg1, (a10152 + 13), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5020 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10166, s4981), a10165, s4980);
        s5021 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10165, s4981), a10166, s4980);
        a10167 = svld1_gather_u64offset_f64(pg1, (a10152 + 14), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10168 = svld1_gather_u64offset_f64(pg1, (a10152 + 15), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5022 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10168, s5001), a10167, s5000);
        s5023 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10167, s5001), a10168, s5000);
        a10169 = svld1_gather_u64offset_f64(pg1, (a10152 + 16), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10170 = svld1_gather_u64offset_f64(pg1, (a10152 + 17), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5024 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10170, s4965), a10169, s4964);
        s5025 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10169, s4965), a10170, s4964);
        a10171 = svld1_gather_u64offset_f64(pg1, (a10152 + 18), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10172 = svld1_gather_u64offset_f64(pg1, (a10152 + 19), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5026 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10172, s4985), a10171, s4984);
        s5027 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10171, s4985), a10172, s4984);
        a10173 = svld1_gather_u64offset_f64(pg1, (a10152 + 20), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10174 = svld1_gather_u64offset_f64(pg1, (a10152 + 21), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5028 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10174, s5005), a10173, s5004);
        s5029 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10173, s5005), a10174, s5004);
        a10175 = svld1_gather_u64offset_f64(pg1, (a10152 + 22), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10176 = svld1_gather_u64offset_f64(pg1, (a10152 + 23), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5030 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10176, s4955), a10175, s4954);
        s5031 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10175, s4955), a10176, s4954);
        a10177 = svld1_gather_u64offset_f64(pg1, (a10152 + 24), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10178 = svld1_gather_u64offset_f64(pg1, (a10152 + 25), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5032 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10178, s4975), a10177, s4974);
        s5033 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10177, s4975), a10178, s4974);
        a10179 = svld1_gather_u64offset_f64(pg1, (a10152 + 26), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10180 = svld1_gather_u64offset_f64(pg1, (a10152 + 27), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5034 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10180, s4995), a10179, s4994);
        s5035 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10179, s4995), a10180, s4994);
        a10181 = svld1_gather_u64offset_f64(pg1, (a10152 + 28), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10182 = svld1_gather_u64offset_f64(pg1, (a10152 + 29), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5036 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10182, s4959), a10181, s4958);
        s5037 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10181, s4959), a10182, s4958);
        a10183 = svld1_gather_u64offset_f64(pg1, (a10152 + 30), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10184 = svld1_gather_u64offset_f64(pg1, (a10152 + 31), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5038 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10184, s4979), a10183, s4978);
        s5039 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10183, s4979), a10184, s4978);
        a10185 = svld1_gather_u64offset_f64(pg1, (a10152 + 32), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10186 = svld1_gather_u64offset_f64(pg1, (a10152 + 33), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5040 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10186, s4999), a10185, s4998);
        s5041 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10185, s4999), a10186, s4998);
        a10187 = svld1_gather_u64offset_f64(pg1, (a10152 + 34), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10188 = svld1_gather_u64offset_f64(pg1, (a10152 + 35), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5042 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10188, s4963), a10187, s4962);
        s5043 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10187, s4963), a10188, s4962);
        a10189 = svld1_gather_u64offset_f64(pg1, (a10152 + 36), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10190 = svld1_gather_u64offset_f64(pg1, (a10152 + 37), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5044 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10190, s4983), a10189, s4982);
        s5045 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10189, s4983), a10190, s4982);
        a10191 = svld1_gather_u64offset_f64(pg1, (a10152 + 38), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10192 = svld1_gather_u64offset_f64(pg1, (a10152 + 39), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5046 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10192, s5003), a10191, s5002);
        s5047 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10191, s5003), a10192, s5002);
        a10193 = svld1_gather_u64offset_f64(pg1, (a10152 + 40), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10194 = svld1_gather_u64offset_f64(pg1, (a10152 + 41), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5048 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10194, s4967), a10193, s4966);
        s5049 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10193, s4967), a10194, s4966);
        a10195 = svld1_gather_u64offset_f64(pg1, (a10152 + 42), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10196 = svld1_gather_u64offset_f64(pg1, (a10152 + 43), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5050 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10196, s4987), a10195, s4986);
        s5051 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10195, s4987), a10196, s4986);
        a10197 = svld1_gather_u64offset_f64(pg1, (a10152 + 44), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        a10198 = svld1_gather_u64offset_f64(pg1, (a10152 + 45), svindex_u64(0, (int64_t)(46 * sizeof(float64_t))));
        s5052 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10198, s5007), a10197, s5006);
        s5053 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10197, s5007), a10198, s5006);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s4952);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s4953);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5008);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5009);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5010);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5011);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5012);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5013);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5014);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5015);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5016);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5017);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5018);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5019);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5020);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5021);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5022);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5023);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5024);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5025);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5026);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5027);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5028);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5029);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5030);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5031);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5032);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5033);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5034);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5035);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5036);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5037);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5038);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5039);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5040);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5041);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5042);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5043);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5044);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5045);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(40 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5046);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(41 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5047);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(42 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5048);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(43 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5049);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(44 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5050);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(45 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5051);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(46 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5052);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(47 + Y + ((48)*(j1)))), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))), s5053);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
