/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft20c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D23[40];
    int l1, m1;
    svfloat64x2_t s1754, s1757, s1760, s1763, s1766, s1769, s1772, s1775, 
            s1778, s1781, s1784, s1787, s1790, s1793, s1796, s1799, 
            s1802, s1805, s1808, s1811, svex2_21, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40;
    svfloat64_t s1755, s1756, s1758, s1759, s1761, s1762, s1764, s1765, 
            s1767, s1768, s1770, s1771, s1773, s1774, s1776, s1777, 
            s1779, s1780, s1782, s1783, s1785, s1786, s1788, s1789, 
            s1791, s1792, s1794, s1795, s1797, s1798, s1800, s1801, 
            s1803, s1804, s1806, s1807, s1809, s1810, s1812, s1813, 
            s1814, s1815, s1816, s1817, s1818, s1819, s1820, s1821, 
            s1822, s1823, s1824, s1825, s1826, s1827, s1828, s1829, 
            s1830, s1831, s1832, s1833, s1834, s1835, s1836, s1837, 
            s1838, s1839, s1840, s1841, s1842, s1843, s1844, s1845, 
            s1846, s1847, s1848, s1849, s1850, s1851, s1852, s1853, 
            s1854, s1855, s1856, s1857, s1858, s1859, s1860, s1861, 
            s1862, s1863, s1864, s1865, s1866, s1867, s1868, s1869, 
            s1870, s1871, s1872, s1873, s1874, s1875, s1876, s1877, 
            s1878, s1879, s1880, s1881, s1882, s1883, s1884, s1885, 
            s1886, s1887, s1888, s1889, s1890, s1891, s1892, s1893, 
            t2886, t2887, t2888, t2889, t2890, t2891, t2892, t2893, 
            t2894, t2895, t2896, t2897, t2898, t2899, t2900, t2901, 
            t2902, t2903, t2904, t2905, t2906, t2907, t2908, t2909, 
            t2910, t2911, t2912, t2913, t2914, t2915, t2916, t2917, 
            t2918, t2919, t2920, t2921, t2922, t2923, t2924, t2925, 
            t2926, t2927, t2928, t2929, t2930, t2931, t2932, t2933, 
            t2934, t2935, t2936, t2937, t2938, t2939, t2940, t2941, 
            t2942, t2943, t2944, t2945, t2946, t2947, t2948, t2949, 
            t2950, t2951, t2952, t2953, t2954, t2955, t2956, t2957, 
            t2958, t2959, t2960, t2961, t2962, t2963, t2964, t2965, 
            t2966, t2967, t2968, t2969, t2970, t2971, t2972, t2973, 
            t2974, t2975, t2976, t2977, t2978, t2979, t2980, t2981, 
            t2982, t2983, t2984, t2985, t2986, t2987, t2988, t2989, 
            t2990, t2991, t2992, t2993, t2994, t2995, t2996, t2997, 
            t2998, t2999, t3000, t3001, t3002, t3003, t3004, t3005, 
            t3006, t3007, t3008, t3009, t3010, t3011, t3012, t3013, 
            t3014, t3015, t3016, t3017, t3018, t3019, t3020, t3021, 
            t3022, t3023, t3024, t3025, t3026, t3027, t3028, t3029, 
            t3030, t3031, t3032, t3033, t3034, t3035, t3036, t3037, 
            t3038, t3039, t3040, t3041, t3042, t3043, t3044, t3045, 
            t3046, t3047, t3048, t3049, t3050, t3051, t3052, t3053, 
            t3054, t3055, t3056, t3057, t3058, t3059, t3060, t3061;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s1754 = svld2_f64(pg1, (X + ((2)*(k1))));
        s1755 = s1754.v0;
        s1756 = s1754.v1;
        s1757 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s1758 = s1757.v0;
        s1759 = s1757.v1;
        s1760 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s1761 = s1760.v0;
        s1762 = s1760.v1;
        s1763 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s1764 = s1763.v0;
        s1765 = s1763.v1;
        s1766 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s1767 = s1766.v0;
        s1768 = s1766.v1;
        s1769 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s1770 = s1769.v0;
        s1771 = s1769.v1;
        s1772 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s1773 = s1772.v0;
        s1774 = s1772.v1;
        s1775 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s1776 = s1775.v0;
        s1777 = s1775.v1;
        s1778 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s1779 = s1778.v0;
        s1780 = s1778.v1;
        s1781 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s1782 = s1781.v0;
        s1783 = s1781.v1;
        s1784 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s1785 = s1784.v0;
        s1786 = s1784.v1;
        s1787 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s1788 = s1787.v0;
        s1789 = s1787.v1;
        s1790 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s1791 = s1790.v0;
        s1792 = s1790.v1;
        s1793 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s1794 = s1793.v0;
        s1795 = s1793.v1;
        s1796 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s1797 = s1796.v0;
        s1798 = s1796.v1;
        s1799 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s1800 = s1799.v0;
        s1801 = s1799.v1;
        s1802 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s1803 = s1802.v0;
        s1804 = s1802.v1;
        s1805 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s1806 = s1805.v0;
        s1807 = s1805.v1;
        s1808 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s1809 = s1808.v0;
        s1810 = s1808.v1;
        s1811 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s1812 = s1811.v0;
        s1813 = s1811.v1;
        t2886 = svadd_f64_x(pg1, s1755, s1785);
        t2887 = svadd_f64_x(pg1, s1756, s1786);
        t2888 = svsub_f64_x(pg1, s1755, s1785);
        t2889 = svsub_f64_x(pg1, s1756, s1786);
        t2890 = svadd_f64_x(pg1, s1770, s1800);
        t2891 = svadd_f64_x(pg1, s1771, s1801);
        t2892 = svsub_f64_x(pg1, s1770, s1800);
        t2893 = svsub_f64_x(pg1, s1771, s1801);
        t2894 = svadd_f64_x(pg1, t2886, t2890);
        t2895 = svadd_f64_x(pg1, t2887, t2891);
        t2896 = svsub_f64_x(pg1, t2886, t2890);
        t2897 = svsub_f64_x(pg1, t2887, t2891);
        s1814 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2895, D23[1]), t2894, D23[0]);
        s1815 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2895, D23[0]), t2894, D23[1]);
        s1816 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2897, D23[3]), t2896, D23[2]);
        s1817 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2897, D23[2]), t2896, D23[3]);
        t2898 = svadd_f64_x(pg1, t2888, t2893);
        t2899 = svsub_f64_x(pg1, t2889, t2892);
        t2900 = svsub_f64_x(pg1, t2888, t2893);
        t2901 = svadd_f64_x(pg1, t2889, t2892);
        s1818 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2899, D23[5]), t2898, D23[4]);
        s1819 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2899, D23[4]), t2898, D23[5]);
        s1820 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2901, D23[7]), t2900, D23[6]);
        s1821 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2901, D23[6]), t2900, D23[7]);
        t2902 = svadd_f64_x(pg1, s1758, s1788);
        t2903 = svadd_f64_x(pg1, s1759, s1789);
        t2904 = svsub_f64_x(pg1, s1758, s1788);
        t2905 = svsub_f64_x(pg1, s1759, s1789);
        t2906 = svadd_f64_x(pg1, s1773, s1803);
        t2907 = svadd_f64_x(pg1, s1774, s1804);
        t2908 = svsub_f64_x(pg1, s1773, s1803);
        t2909 = svsub_f64_x(pg1, s1774, s1804);
        t2910 = svadd_f64_x(pg1, t2902, t2906);
        t2911 = svadd_f64_x(pg1, t2903, t2907);
        t2912 = svsub_f64_x(pg1, t2902, t2906);
        t2913 = svsub_f64_x(pg1, t2903, t2907);
        s1822 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2911, D23[9]), t2910, D23[8]);
        s1823 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2911, D23[8]), t2910, D23[9]);
        s1824 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2913, D23[11]), t2912, D23[10]);
        s1825 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2913, D23[10]), t2912, D23[11]);
        t2914 = svadd_f64_x(pg1, t2904, t2909);
        t2915 = svsub_f64_x(pg1, t2905, t2908);
        t2916 = svsub_f64_x(pg1, t2904, t2909);
        t2917 = svadd_f64_x(pg1, t2905, t2908);
        s1826 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2915, D23[13]), t2914, D23[12]);
        s1827 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2915, D23[12]), t2914, D23[13]);
        s1828 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2917, D23[15]), t2916, D23[14]);
        s1829 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2917, D23[14]), t2916, D23[15]);
        t2918 = svadd_f64_x(pg1, s1761, s1791);
        t2919 = svadd_f64_x(pg1, s1762, s1792);
        t2920 = svsub_f64_x(pg1, s1761, s1791);
        t2921 = svsub_f64_x(pg1, s1762, s1792);
        t2922 = svadd_f64_x(pg1, s1776, s1806);
        t2923 = svadd_f64_x(pg1, s1777, s1807);
        t2924 = svsub_f64_x(pg1, s1776, s1806);
        t2925 = svsub_f64_x(pg1, s1777, s1807);
        t2926 = svadd_f64_x(pg1, t2918, t2922);
        t2927 = svadd_f64_x(pg1, t2919, t2923);
        t2928 = svsub_f64_x(pg1, t2918, t2922);
        t2929 = svsub_f64_x(pg1, t2919, t2923);
        s1830 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2927, D23[17]), t2926, D23[16]);
        s1831 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2927, D23[16]), t2926, D23[17]);
        s1832 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2929, D23[19]), t2928, D23[18]);
        s1833 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2929, D23[18]), t2928, D23[19]);
        t2930 = svadd_f64_x(pg1, t2920, t2925);
        t2931 = svsub_f64_x(pg1, t2921, t2924);
        t2932 = svsub_f64_x(pg1, t2920, t2925);
        t2933 = svadd_f64_x(pg1, t2921, t2924);
        s1834 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2931, D23[21]), t2930, D23[20]);
        s1835 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2931, D23[20]), t2930, D23[21]);
        s1836 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2933, D23[23]), t2932, D23[22]);
        s1837 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2933, D23[22]), t2932, D23[23]);
        t2934 = svadd_f64_x(pg1, s1764, s1794);
        t2935 = svadd_f64_x(pg1, s1765, s1795);
        t2936 = svsub_f64_x(pg1, s1764, s1794);
        t2937 = svsub_f64_x(pg1, s1765, s1795);
        t2938 = svadd_f64_x(pg1, s1779, s1809);
        t2939 = svadd_f64_x(pg1, s1780, s1810);
        t2940 = svsub_f64_x(pg1, s1779, s1809);
        t2941 = svsub_f64_x(pg1, s1780, s1810);
        t2942 = svadd_f64_x(pg1, t2934, t2938);
        t2943 = svadd_f64_x(pg1, t2935, t2939);
        t2944 = svsub_f64_x(pg1, t2934, t2938);
        t2945 = svsub_f64_x(pg1, t2935, t2939);
        s1838 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2943, D23[25]), t2942, D23[24]);
        s1839 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2943, D23[24]), t2942, D23[25]);
        s1840 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2945, D23[27]), t2944, D23[26]);
        s1841 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2945, D23[26]), t2944, D23[27]);
        t2946 = svadd_f64_x(pg1, t2936, t2941);
        t2947 = svsub_f64_x(pg1, t2937, t2940);
        t2948 = svsub_f64_x(pg1, t2936, t2941);
        t2949 = svadd_f64_x(pg1, t2937, t2940);
        s1842 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2947, D23[29]), t2946, D23[28]);
        s1843 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2947, D23[28]), t2946, D23[29]);
        s1844 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2949, D23[31]), t2948, D23[30]);
        s1845 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2949, D23[30]), t2948, D23[31]);
        t2950 = svadd_f64_x(pg1, s1767, s1797);
        t2951 = svadd_f64_x(pg1, s1768, s1798);
        t2952 = svsub_f64_x(pg1, s1767, s1797);
        t2953 = svsub_f64_x(pg1, s1768, s1798);
        t2954 = svadd_f64_x(pg1, s1782, s1812);
        t2955 = svadd_f64_x(pg1, s1783, s1813);
        t2956 = svsub_f64_x(pg1, s1782, s1812);
        t2957 = svsub_f64_x(pg1, s1783, s1813);
        t2958 = svadd_f64_x(pg1, t2950, t2954);
        t2959 = svadd_f64_x(pg1, t2951, t2955);
        t2960 = svsub_f64_x(pg1, t2950, t2954);
        t2961 = svsub_f64_x(pg1, t2951, t2955);
        s1846 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2959, D23[33]), t2958, D23[32]);
        s1847 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2959, D23[32]), t2958, D23[33]);
        s1848 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2961, D23[35]), t2960, D23[34]);
        s1849 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2961, D23[34]), t2960, D23[35]);
        t2962 = svadd_f64_x(pg1, t2952, t2957);
        t2963 = svsub_f64_x(pg1, t2953, t2956);
        t2964 = svsub_f64_x(pg1, t2952, t2957);
        t2965 = svadd_f64_x(pg1, t2953, t2956);
        s1850 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2963, D23[37]), t2962, D23[36]);
        s1851 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2963, D23[36]), t2962, D23[37]);
        s1852 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2965, D23[39]), t2964, D23[38]);
        s1853 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2965, D23[38]), t2964, D23[39]);
        t2966 = svadd_f64_x(pg1, s1822, s1846);
        t2967 = svadd_f64_x(pg1, s1823, s1847);
        t2968 = svsub_f64_x(pg1, s1822, s1846);
        t2969 = svsub_f64_x(pg1, s1823, s1847);
        t2970 = svadd_f64_x(pg1, s1830, s1838);
        t2971 = svadd_f64_x(pg1, s1831, s1839);
        t2972 = svsub_f64_x(pg1, s1830, s1838);
        t2973 = svsub_f64_x(pg1, s1831, s1839);
        t2974 = svadd_f64_x(pg1, t2966, t2970);
        t2975 = svadd_f64_x(pg1, t2967, t2971);
        t2976 = svadd_f64_x(pg1, t2968, t2973);
        t2977 = svsub_f64_x(pg1, t2969, t2972);
        t2978 = svsub_f64_x(pg1, t2968, t2973);
        t2979 = svadd_f64_x(pg1, t2969, t2972);
        t2980 = svmls_n_f64_x(pg1, s1814, t2974, 0.25);
        t2981 = svmls_n_f64_x(pg1, s1815, t2975, 0.25);
        s1878 = svmla_n_f64_x(pg1, t2976, t2977, 1.6180339887498947);
        s1854 = svmul_n_f64_x(pg1, s1878, 0.29389262614623657);
        s1879 = svmls_n_f64_x(pg1, t2977, t2976, 1.6180339887498947);
        s1855 = svmul_n_f64_x(pg1, s1879, 0.29389262614623657);
        s1856 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2966, t2970), 0.55901699437494745);
        s1857 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2967, t2971), 0.55901699437494745);
        s1880 = svmls_n_f64_x(pg1, t2979, t2978, 0.61803398874989479);
        s1858 = svmul_n_f64_x(pg1, s1880, 0.47552825814757682);
        s1881 = svmla_n_f64_x(pg1, t2978, t2979, 0.61803398874989479);
        s1859 = svmul_n_f64_x(pg1, s1881, 0.47552825814757682);
        t2982 = svadd_f64_x(pg1, t2980, s1856);
        t2983 = svadd_f64_x(pg1, t2981, s1857);
        t2984 = svsub_f64_x(pg1, t2980, s1856);
        t2985 = svsub_f64_x(pg1, t2981, s1857);
        t2986 = svadd_f64_x(pg1, s1854, s1858);
        t2987 = svsub_f64_x(pg1, s1855, s1859);
        t2988 = svsub_f64_x(pg1, s1854, s1858);
        t2989 = svadd_f64_x(pg1, s1855, s1859);
        t2990 = svadd_f64_x(pg1, s1826, s1850);
        t2991 = svadd_f64_x(pg1, s1827, s1851);
        t2992 = svsub_f64_x(pg1, s1826, s1850);
        t2993 = svsub_f64_x(pg1, s1827, s1851);
        t2994 = svadd_f64_x(pg1, s1834, s1842);
        t2995 = svadd_f64_x(pg1, s1835, s1843);
        t2996 = svsub_f64_x(pg1, s1834, s1842);
        t2997 = svsub_f64_x(pg1, s1835, s1843);
        t2998 = svadd_f64_x(pg1, t2990, t2994);
        t2999 = svadd_f64_x(pg1, t2991, t2995);
        t3000 = svadd_f64_x(pg1, t2992, t2997);
        t3001 = svsub_f64_x(pg1, t2993, t2996);
        t3002 = svsub_f64_x(pg1, t2992, t2997);
        t3003 = svadd_f64_x(pg1, t2993, t2996);
        t3004 = svmls_n_f64_x(pg1, s1818, t2998, 0.25);
        t3005 = svmls_n_f64_x(pg1, s1819, t2999, 0.25);
        s1882 = svmla_n_f64_x(pg1, t3000, t3001, 1.6180339887498947);
        s1860 = svmul_n_f64_x(pg1, s1882, 0.29389262614623657);
        s1883 = svmls_n_f64_x(pg1, t3001, t3000, 1.6180339887498947);
        s1861 = svmul_n_f64_x(pg1, s1883, 0.29389262614623657);
        s1862 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2990, t2994), 0.55901699437494745);
        s1863 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2991, t2995), 0.55901699437494745);
        s1884 = svmls_n_f64_x(pg1, t3003, t3002, 0.61803398874989479);
        s1864 = svmul_n_f64_x(pg1, s1884, 0.47552825814757682);
        s1885 = svmla_n_f64_x(pg1, t3002, t3003, 0.61803398874989479);
        s1865 = svmul_n_f64_x(pg1, s1885, 0.47552825814757682);
        t3006 = svadd_f64_x(pg1, t3004, s1862);
        t3007 = svadd_f64_x(pg1, t3005, s1863);
        t3008 = svsub_f64_x(pg1, t3004, s1862);
        t3009 = svsub_f64_x(pg1, t3005, s1863);
        t3010 = svadd_f64_x(pg1, s1860, s1864);
        t3011 = svsub_f64_x(pg1, s1861, s1865);
        t3012 = svsub_f64_x(pg1, s1860, s1864);
        t3013 = svadd_f64_x(pg1, s1861, s1865);
        t3014 = svadd_f64_x(pg1, s1824, s1848);
        t3015 = svadd_f64_x(pg1, s1825, s1849);
        t3016 = svsub_f64_x(pg1, s1824, s1848);
        t3017 = svsub_f64_x(pg1, s1825, s1849);
        t3018 = svadd_f64_x(pg1, s1832, s1840);
        t3019 = svadd_f64_x(pg1, s1833, s1841);
        t3020 = svsub_f64_x(pg1, s1832, s1840);
        t3021 = svsub_f64_x(pg1, s1833, s1841);
        t3022 = svadd_f64_x(pg1, t3014, t3018);
        t3023 = svadd_f64_x(pg1, t3015, t3019);
        t3024 = svadd_f64_x(pg1, t3016, t3021);
        t3025 = svsub_f64_x(pg1, t3017, t3020);
        t3026 = svsub_f64_x(pg1, t3016, t3021);
        t3027 = svadd_f64_x(pg1, t3017, t3020);
        t3028 = svmls_n_f64_x(pg1, s1816, t3022, 0.25);
        t3029 = svmls_n_f64_x(pg1, s1817, t3023, 0.25);
        s1886 = svmla_n_f64_x(pg1, t3024, t3025, 1.6180339887498947);
        s1866 = svmul_n_f64_x(pg1, s1886, 0.29389262614623657);
        s1887 = svmls_n_f64_x(pg1, t3025, t3024, 1.6180339887498947);
        s1867 = svmul_n_f64_x(pg1, s1887, 0.29389262614623657);
        s1868 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3014, t3018), 0.55901699437494745);
        s1869 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3015, t3019), 0.55901699437494745);
        s1888 = svmls_n_f64_x(pg1, t3027, t3026, 0.61803398874989479);
        s1870 = svmul_n_f64_x(pg1, s1888, 0.47552825814757682);
        s1889 = svmla_n_f64_x(pg1, t3026, t3027, 0.61803398874989479);
        s1871 = svmul_n_f64_x(pg1, s1889, 0.47552825814757682);
        t3030 = svadd_f64_x(pg1, t3028, s1868);
        t3031 = svadd_f64_x(pg1, t3029, s1869);
        t3032 = svsub_f64_x(pg1, t3028, s1868);
        t3033 = svsub_f64_x(pg1, t3029, s1869);
        t3034 = svadd_f64_x(pg1, s1866, s1870);
        t3035 = svsub_f64_x(pg1, s1867, s1871);
        t3036 = svsub_f64_x(pg1, s1866, s1870);
        t3037 = svadd_f64_x(pg1, s1867, s1871);
        t3038 = svadd_f64_x(pg1, s1828, s1852);
        t3039 = svadd_f64_x(pg1, s1829, s1853);
        t3040 = svsub_f64_x(pg1, s1828, s1852);
        t3041 = svsub_f64_x(pg1, s1829, s1853);
        t3042 = svadd_f64_x(pg1, s1836, s1844);
        t3043 = svadd_f64_x(pg1, s1837, s1845);
        t3044 = svsub_f64_x(pg1, s1836, s1844);
        t3045 = svsub_f64_x(pg1, s1837, s1845);
        t3046 = svadd_f64_x(pg1, t3038, t3042);
        t3047 = svadd_f64_x(pg1, t3039, t3043);
        t3048 = svadd_f64_x(pg1, t3040, t3045);
        t3049 = svsub_f64_x(pg1, t3041, t3044);
        t3050 = svsub_f64_x(pg1, t3040, t3045);
        t3051 = svadd_f64_x(pg1, t3041, t3044);
        t3052 = svmls_n_f64_x(pg1, s1820, t3046, 0.25);
        t3053 = svmls_n_f64_x(pg1, s1821, t3047, 0.25);
        s1890 = svmla_n_f64_x(pg1, t3048, t3049, 1.6180339887498947);
        s1872 = svmul_n_f64_x(pg1, s1890, 0.29389262614623657);
        s1891 = svmls_n_f64_x(pg1, t3049, t3048, 1.6180339887498947);
        s1873 = svmul_n_f64_x(pg1, s1891, 0.29389262614623657);
        s1874 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3038, t3042), 0.55901699437494745);
        s1875 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3039, t3043), 0.55901699437494745);
        s1892 = svmls_n_f64_x(pg1, t3051, t3050, 0.61803398874989479);
        s1876 = svmul_n_f64_x(pg1, s1892, 0.47552825814757682);
        s1893 = svmla_n_f64_x(pg1, t3050, t3051, 0.61803398874989479);
        s1877 = svmul_n_f64_x(pg1, s1893, 0.47552825814757682);
        t3054 = svadd_f64_x(pg1, t3052, s1874);
        t3055 = svadd_f64_x(pg1, t3053, s1875);
        t3056 = svsub_f64_x(pg1, t3052, s1874);
        t3057 = svsub_f64_x(pg1, t3053, s1875);
        t3058 = svadd_f64_x(pg1, s1872, s1876);
        t3059 = svsub_f64_x(pg1, s1873, s1877);
        t3060 = svsub_f64_x(pg1, s1872, s1876);
        t3061 = svadd_f64_x(pg1, s1873, s1877);
        svex2_21.v0 = svadd_f64_x(pg1, s1814, t2974);
        svex2_21.v1 = svadd_f64_x(pg1, s1815, t2975);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_21);
        svex2_22.v0 = svadd_f64_x(pg1, s1818, t2998);
        svex2_22.v1 = svadd_f64_x(pg1, s1819, t2999);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_22);
        svex2_23.v0 = svadd_f64_x(pg1, s1816, t3022);
        svex2_23.v1 = svadd_f64_x(pg1, s1817, t3023);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_23);
        svex2_24.v0 = svadd_f64_x(pg1, s1820, t3046);
        svex2_24.v1 = svadd_f64_x(pg1, s1821, t3047);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_24);
        svex2_25.v0 = svadd_f64_x(pg1, t2982, t2986);
        svex2_25.v1 = svadd_f64_x(pg1, t2983, t2987);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_25);
        svex2_26.v0 = svadd_f64_x(pg1, t3006, t3010);
        svex2_26.v1 = svadd_f64_x(pg1, t3007, t3011);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_26);
        svex2_27.v0 = svadd_f64_x(pg1, t3030, t3034);
        svex2_27.v1 = svadd_f64_x(pg1, t3031, t3035);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_27);
        svex2_28.v0 = svadd_f64_x(pg1, t3054, t3058);
        svex2_28.v1 = svadd_f64_x(pg1, t3055, t3059);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_28);
        svex2_29.v0 = svadd_f64_x(pg1, t2984, t2989);
        svex2_29.v1 = svsub_f64_x(pg1, t2985, t2988);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_29);
        svex2_30.v0 = svadd_f64_x(pg1, t3008, t3013);
        svex2_30.v1 = svsub_f64_x(pg1, t3009, t3012);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_30);
        svex2_31.v0 = svadd_f64_x(pg1, t3032, t3037);
        svex2_31.v1 = svsub_f64_x(pg1, t3033, t3036);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_31);
        svex2_32.v0 = svadd_f64_x(pg1, t3056, t3061);
        svex2_32.v1 = svsub_f64_x(pg1, t3057, t3060);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_32);
        svex2_33.v0 = svsub_f64_x(pg1, t2984, t2989);
        svex2_33.v1 = svadd_f64_x(pg1, t2985, t2988);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_33);
        svex2_34.v0 = svsub_f64_x(pg1, t3008, t3013);
        svex2_34.v1 = svadd_f64_x(pg1, t3009, t3012);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_34);
        svex2_35.v0 = svsub_f64_x(pg1, t3032, t3037);
        svex2_35.v1 = svadd_f64_x(pg1, t3033, t3036);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_35);
        svex2_36.v0 = svsub_f64_x(pg1, t3056, t3061);
        svex2_36.v1 = svadd_f64_x(pg1, t3057, t3060);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_36);
        svex2_37.v0 = svsub_f64_x(pg1, t2982, t2986);
        svex2_37.v1 = svsub_f64_x(pg1, t2983, t2987);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_37);
        svex2_38.v0 = svsub_f64_x(pg1, t3006, t3010);
        svex2_38.v1 = svsub_f64_x(pg1, t3007, t3011);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_38);
        svex2_39.v0 = svsub_f64_x(pg1, t3030, t3034);
        svex2_39.v1 = svsub_f64_x(pg1, t3031, t3035);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_39);
        svex2_40.v0 = svsub_f64_x(pg1, t3054, t3058);
        svex2_40.v1 = svsub_f64_x(pg1, t3055, t3059);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_40);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
