/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft20b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    static float64_t D23[40];
    float64_t a4087, a4088, a4089, a4090, a4091, a4092, a4093, a4094, 
            a4095, a4096, a4097, a4098, a4099, a4100, a4101, a4102, 
            a4103, a4104, a4105, a4106, a4107, a4108, a4109, a4110, 
            a4111, a4112, a4113, a4114, a4115, a4116, a4117, a4118, 
            a4119, a4120, a4121, a4122, a4123, a4124;
    int a4085, a4086, j1, l1, m1;
    svfloat64x2_t s1868, s1871, s1874, s1877, s1880, s1883, s1886, s1889, 
            s1892, s1895, s1898, s1901, s1904, s1907, s1910, s1913, 
            s1916, s1919, s1922, s1925, svex2_21, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40;
    svfloat64_t s1869, s1870, s1872, s1873, s1875, s1876, s1878, s1879, 
            s1881, s1882, s1884, s1885, s1887, s1888, s1890, s1891, 
            s1893, s1894, s1896, s1897, s1899, s1900, s1902, s1903, 
            s1905, s1906, s1908, s1909, s1911, s1912, s1914, s1915, 
            s1917, s1918, s1920, s1921, s1923, s1924, s1926, s1927, 
            s1928, s1929, s1930, s1931, s1932, s1933, s1934, s1935, 
            s1936, s1937, s1938, s1939, s1940, s1941, s1942, s1943, 
            s1944, s1945, s1946, s1947, s1948, s1949, s1950, s1951, 
            s1952, s1953, s1954, s1955, s1956, s1957, s1958, s1959, 
            s1960, s1961, s1962, s1963, s1964, s1965, s1966, s1967, 
            s1968, s1969, s1970, s1971, s1972, s1973, s1974, s1975, 
            s1976, s1977, s1978, s1979, s1980, s1981, s1982, s1983, 
            s1984, s1985, s1986, s1987, s1988, s1989, s1990, s1991, 
            s1992, s1993, s1994, s1995, s1996, s1997, s1998, s1999, 
            s2000, s2001, s2002, s2003, s2004, s2005, s2006, s2007, 
            s2008, s2009, s2010, s2011, s2012, s2013, s2014, s2015, 
            s2016, s2017, s2018, s2019, s2020, s2021, s2022, s2023, 
            s2024, s2025, s2026, s2027, s2028, s2029, s2030, s2031, 
            s2032, s2033, s2034, s2035, s2036, s2037, s2038, s2039, 
            s2040, s2041, s2042, s2043, s2044, s2045, t2887, t2888, 
            t2889, t2890, t2891, t2892, t2893, t2894, t2895, t2896, 
            t2897, t2898, t2899, t2900, t2901, t2902, t2903, t2904, 
            t2905, t2906, t2907, t2908, t2909, t2910, t2911, t2912, 
            t2913, t2914, t2915, t2916, t2917, t2918, t2919, t2920, 
            t2921, t2922, t2923, t2924, t2925, t2926, t2927, t2928, 
            t2929, t2930, t2931, t2932, t2933, t2934, t2935, t2936, 
            t2937, t2938, t2939, t2940, t2941, t2942, t2943, t2944, 
            t2945, t2946, t2947, t2948, t2949, t2950, t2951, t2952, 
            t2953, t2954, t2955, t2956, t2957, t2958, t2959, t2960, 
            t2961, t2962, t2963, t2964, t2965, t2966, t2967, t2968, 
            t2969, t2970, t2971, t2972, t2973, t2974, t2975, t2976, 
            t2977, t2978, t2979, t2980, t2981, t2982, t2983, t2984, 
            t2985, t2986, t2987, t2988, t2989, t2990, t2991, t2992, 
            t2993, t2994, t2995, t2996, t2997, t2998, t2999, t3000, 
            t3001, t3002, t3003, t3004, t3005, t3006, t3007, t3008, 
            t3009, t3010, t3011, t3012, t3013, t3014, t3015, t3016, 
            t3017, t3018, t3019, t3020, t3021, t3022, t3023, t3024, 
            t3025, t3026, t3027, t3028, t3029, t3030, t3031, t3032, 
            t3033, t3034, t3035, t3036, t3037, t3038, t3039, t3040, 
            t3041, t3042, t3043, t3044, t3045, t3046, t3047, t3048, 
            t3049, t3050, t3051, t3052, t3053, t3054, t3055, t3056, 
            t3057, t3058, t3059, t3060, t3061, t3062;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a4085 = (k1 + ((j1)*(m1)));
            s1868 = svld2_f64(pg1, (X + ((2)*(a4085))));
            s1869 = s1868.v0;
            s1870 = s1868.v1;
            s1871 = svld2_f64(pg1, (X + ((2)*((a4085 + ((l1)*(m1)))))));
            s1872 = s1871.v0;
            s1873 = s1871.v1;
            s1874 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((2)*(l1)))*(m1)))))));
            s1875 = s1874.v0;
            s1876 = s1874.v1;
            s1877 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((3)*(l1)))*(m1)))))));
            s1878 = s1877.v0;
            s1879 = s1877.v1;
            s1880 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((4)*(l1)))*(m1)))))));
            s1881 = s1880.v0;
            s1882 = s1880.v1;
            s1883 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((5)*(l1)))*(m1)))))));
            s1884 = s1883.v0;
            s1885 = s1883.v1;
            s1886 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((6)*(l1)))*(m1)))))));
            s1887 = s1886.v0;
            s1888 = s1886.v1;
            s1889 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((7)*(l1)))*(m1)))))));
            s1890 = s1889.v0;
            s1891 = s1889.v1;
            s1892 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((8)*(l1)))*(m1)))))));
            s1893 = s1892.v0;
            s1894 = s1892.v1;
            s1895 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((9)*(l1)))*(m1)))))));
            s1896 = s1895.v0;
            s1897 = s1895.v1;
            s1898 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((10)*(l1)))*(m1)))))));
            s1899 = s1898.v0;
            s1900 = s1898.v1;
            s1901 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((11)*(l1)))*(m1)))))));
            s1902 = s1901.v0;
            s1903 = s1901.v1;
            s1904 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((12)*(l1)))*(m1)))))));
            s1905 = s1904.v0;
            s1906 = s1904.v1;
            s1907 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((13)*(l1)))*(m1)))))));
            s1908 = s1907.v0;
            s1909 = s1907.v1;
            s1910 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((14)*(l1)))*(m1)))))));
            s1911 = s1910.v0;
            s1912 = s1910.v1;
            s1913 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((15)*(l1)))*(m1)))))));
            s1914 = s1913.v0;
            s1915 = s1913.v1;
            s1916 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((16)*(l1)))*(m1)))))));
            s1917 = s1916.v0;
            s1918 = s1916.v1;
            s1919 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((17)*(l1)))*(m1)))))));
            s1920 = s1919.v0;
            s1921 = s1919.v1;
            s1922 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((18)*(l1)))*(m1)))))));
            s1923 = s1922.v0;
            s1924 = s1922.v1;
            s1925 = svld2_f64(pg1, (X + ((2)*((a4085 + ((((19)*(l1)))*(m1)))))));
            s1926 = s1925.v0;
            s1927 = s1925.v1;
            t2887 = svadd_f64_x(pg1, s1869, s1899);
            t2888 = svadd_f64_x(pg1, s1870, s1900);
            t2889 = svsub_f64_x(pg1, s1869, s1899);
            t2890 = svsub_f64_x(pg1, s1870, s1900);
            t2891 = svadd_f64_x(pg1, s1884, s1914);
            t2892 = svadd_f64_x(pg1, s1885, s1915);
            t2893 = svsub_f64_x(pg1, s1884, s1914);
            t2894 = svsub_f64_x(pg1, s1885, s1915);
            t2895 = svadd_f64_x(pg1, t2887, t2891);
            t2896 = svadd_f64_x(pg1, t2888, t2892);
            t2897 = svsub_f64_x(pg1, t2887, t2891);
            t2898 = svsub_f64_x(pg1, t2888, t2892);
            s1928 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2896, D23[1]), t2895, D23[0]);
            s1929 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2896, D23[0]), t2895, D23[1]);
            s1930 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2898, D23[3]), t2897, D23[2]);
            s1931 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2898, D23[2]), t2897, D23[3]);
            t2899 = svadd_f64_x(pg1, t2889, t2894);
            t2900 = svsub_f64_x(pg1, t2890, t2893);
            t2901 = svsub_f64_x(pg1, t2889, t2894);
            t2902 = svadd_f64_x(pg1, t2890, t2893);
            s1932 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2900, D23[5]), t2899, D23[4]);
            s1933 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2900, D23[4]), t2899, D23[5]);
            s1934 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2902, D23[7]), t2901, D23[6]);
            s1935 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2902, D23[6]), t2901, D23[7]);
            t2903 = svadd_f64_x(pg1, s1872, s1902);
            t2904 = svadd_f64_x(pg1, s1873, s1903);
            t2905 = svsub_f64_x(pg1, s1872, s1902);
            t2906 = svsub_f64_x(pg1, s1873, s1903);
            t2907 = svadd_f64_x(pg1, s1887, s1917);
            t2908 = svadd_f64_x(pg1, s1888, s1918);
            t2909 = svsub_f64_x(pg1, s1887, s1917);
            t2910 = svsub_f64_x(pg1, s1888, s1918);
            t2911 = svadd_f64_x(pg1, t2903, t2907);
            t2912 = svadd_f64_x(pg1, t2904, t2908);
            t2913 = svsub_f64_x(pg1, t2903, t2907);
            t2914 = svsub_f64_x(pg1, t2904, t2908);
            s1936 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2912, D23[9]), t2911, D23[8]);
            s1937 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2912, D23[8]), t2911, D23[9]);
            s1938 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2914, D23[11]), t2913, D23[10]);
            s1939 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2914, D23[10]), t2913, D23[11]);
            t2915 = svadd_f64_x(pg1, t2905, t2910);
            t2916 = svsub_f64_x(pg1, t2906, t2909);
            t2917 = svsub_f64_x(pg1, t2905, t2910);
            t2918 = svadd_f64_x(pg1, t2906, t2909);
            s1940 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2916, D23[13]), t2915, D23[12]);
            s1941 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2916, D23[12]), t2915, D23[13]);
            s1942 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2918, D23[15]), t2917, D23[14]);
            s1943 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2918, D23[14]), t2917, D23[15]);
            t2919 = svadd_f64_x(pg1, s1875, s1905);
            t2920 = svadd_f64_x(pg1, s1876, s1906);
            t2921 = svsub_f64_x(pg1, s1875, s1905);
            t2922 = svsub_f64_x(pg1, s1876, s1906);
            t2923 = svadd_f64_x(pg1, s1890, s1920);
            t2924 = svadd_f64_x(pg1, s1891, s1921);
            t2925 = svsub_f64_x(pg1, s1890, s1920);
            t2926 = svsub_f64_x(pg1, s1891, s1921);
            t2927 = svadd_f64_x(pg1, t2919, t2923);
            t2928 = svadd_f64_x(pg1, t2920, t2924);
            t2929 = svsub_f64_x(pg1, t2919, t2923);
            t2930 = svsub_f64_x(pg1, t2920, t2924);
            s1944 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2928, D23[17]), t2927, D23[16]);
            s1945 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2928, D23[16]), t2927, D23[17]);
            s1946 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2930, D23[19]), t2929, D23[18]);
            s1947 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2930, D23[18]), t2929, D23[19]);
            t2931 = svadd_f64_x(pg1, t2921, t2926);
            t2932 = svsub_f64_x(pg1, t2922, t2925);
            t2933 = svsub_f64_x(pg1, t2921, t2926);
            t2934 = svadd_f64_x(pg1, t2922, t2925);
            s1948 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2932, D23[21]), t2931, D23[20]);
            s1949 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2932, D23[20]), t2931, D23[21]);
            s1950 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2934, D23[23]), t2933, D23[22]);
            s1951 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2934, D23[22]), t2933, D23[23]);
            t2935 = svadd_f64_x(pg1, s1878, s1908);
            t2936 = svadd_f64_x(pg1, s1879, s1909);
            t2937 = svsub_f64_x(pg1, s1878, s1908);
            t2938 = svsub_f64_x(pg1, s1879, s1909);
            t2939 = svadd_f64_x(pg1, s1893, s1923);
            t2940 = svadd_f64_x(pg1, s1894, s1924);
            t2941 = svsub_f64_x(pg1, s1893, s1923);
            t2942 = svsub_f64_x(pg1, s1894, s1924);
            t2943 = svadd_f64_x(pg1, t2935, t2939);
            t2944 = svadd_f64_x(pg1, t2936, t2940);
            t2945 = svsub_f64_x(pg1, t2935, t2939);
            t2946 = svsub_f64_x(pg1, t2936, t2940);
            s1952 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2944, D23[25]), t2943, D23[24]);
            s1953 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2944, D23[24]), t2943, D23[25]);
            s1954 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2946, D23[27]), t2945, D23[26]);
            s1955 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2946, D23[26]), t2945, D23[27]);
            t2947 = svadd_f64_x(pg1, t2937, t2942);
            t2948 = svsub_f64_x(pg1, t2938, t2941);
            t2949 = svsub_f64_x(pg1, t2937, t2942);
            t2950 = svadd_f64_x(pg1, t2938, t2941);
            s1956 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2948, D23[29]), t2947, D23[28]);
            s1957 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2948, D23[28]), t2947, D23[29]);
            s1958 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2950, D23[31]), t2949, D23[30]);
            s1959 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2950, D23[30]), t2949, D23[31]);
            t2951 = svadd_f64_x(pg1, s1881, s1911);
            t2952 = svadd_f64_x(pg1, s1882, s1912);
            t2953 = svsub_f64_x(pg1, s1881, s1911);
            t2954 = svsub_f64_x(pg1, s1882, s1912);
            t2955 = svadd_f64_x(pg1, s1896, s1926);
            t2956 = svadd_f64_x(pg1, s1897, s1927);
            t2957 = svsub_f64_x(pg1, s1896, s1926);
            t2958 = svsub_f64_x(pg1, s1897, s1927);
            t2959 = svadd_f64_x(pg1, t2951, t2955);
            t2960 = svadd_f64_x(pg1, t2952, t2956);
            t2961 = svsub_f64_x(pg1, t2951, t2955);
            t2962 = svsub_f64_x(pg1, t2952, t2956);
            s1960 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2960, D23[33]), t2959, D23[32]);
            s1961 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2960, D23[32]), t2959, D23[33]);
            s1962 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2962, D23[35]), t2961, D23[34]);
            s1963 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2962, D23[34]), t2961, D23[35]);
            t2963 = svadd_f64_x(pg1, t2953, t2958);
            t2964 = svsub_f64_x(pg1, t2954, t2957);
            t2965 = svsub_f64_x(pg1, t2953, t2958);
            t2966 = svadd_f64_x(pg1, t2954, t2957);
            s1964 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2964, D23[37]), t2963, D23[36]);
            s1965 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2964, D23[36]), t2963, D23[37]);
            s1966 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2966, D23[39]), t2965, D23[38]);
            s1967 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2966, D23[38]), t2965, D23[39]);
            t2967 = svadd_f64_x(pg1, s1936, s1960);
            t2968 = svadd_f64_x(pg1, s1937, s1961);
            t2969 = svsub_f64_x(pg1, s1936, s1960);
            t2970 = svsub_f64_x(pg1, s1937, s1961);
            t2971 = svadd_f64_x(pg1, s1944, s1952);
            t2972 = svadd_f64_x(pg1, s1945, s1953);
            t2973 = svsub_f64_x(pg1, s1944, s1952);
            t2974 = svsub_f64_x(pg1, s1945, s1953);
            t2975 = svadd_f64_x(pg1, t2967, t2971);
            t2976 = svadd_f64_x(pg1, t2968, t2972);
            t2977 = svadd_f64_x(pg1, t2969, t2974);
            t2978 = svsub_f64_x(pg1, t2970, t2973);
            t2979 = svsub_f64_x(pg1, t2969, t2974);
            t2980 = svadd_f64_x(pg1, t2970, t2973);
            t2981 = svmls_n_f64_x(pg1, s1928, t2975, 0.25);
            t2982 = svmls_n_f64_x(pg1, s1929, t2976, 0.25);
            s2030 = svmla_n_f64_x(pg1, t2977, t2978, 1.6180339887498947);
            s1968 = svmul_n_f64_x(pg1, s2030, 0.29389262614623657);
            s2031 = svmls_n_f64_x(pg1, t2978, t2977, 1.6180339887498947);
            s1969 = svmul_n_f64_x(pg1, s2031, 0.29389262614623657);
            s1970 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2967, t2971), 0.55901699437494745);
            s1971 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2968, t2972), 0.55901699437494745);
            s2032 = svmls_n_f64_x(pg1, t2980, t2979, 0.61803398874989479);
            s1972 = svmul_n_f64_x(pg1, s2032, 0.47552825814757682);
            s2033 = svmla_n_f64_x(pg1, t2979, t2980, 0.61803398874989479);
            s1973 = svmul_n_f64_x(pg1, s2033, 0.47552825814757682);
            t2983 = svadd_f64_x(pg1, t2981, s1970);
            t2984 = svadd_f64_x(pg1, t2982, s1971);
            t2985 = svsub_f64_x(pg1, t2981, s1970);
            t2986 = svsub_f64_x(pg1, t2982, s1971);
            t2987 = svadd_f64_x(pg1, s1968, s1972);
            t2988 = svsub_f64_x(pg1, s1969, s1973);
            t2989 = svsub_f64_x(pg1, s1968, s1972);
            t2990 = svadd_f64_x(pg1, s1969, s1973);
            s1974 = svadd_f64_x(pg1, t2983, t2987);
            s1975 = svadd_f64_x(pg1, t2984, t2988);
            s1976 = svsub_f64_x(pg1, t2983, t2987);
            s1977 = svsub_f64_x(pg1, t2984, t2988);
            s1978 = svadd_f64_x(pg1, t2985, t2990);
            s1979 = svsub_f64_x(pg1, t2986, t2989);
            s1980 = svsub_f64_x(pg1, t2985, t2990);
            s1981 = svadd_f64_x(pg1, t2986, t2989);
            t2991 = svadd_f64_x(pg1, s1940, s1964);
            t2992 = svadd_f64_x(pg1, s1941, s1965);
            t2993 = svsub_f64_x(pg1, s1940, s1964);
            t2994 = svsub_f64_x(pg1, s1941, s1965);
            t2995 = svadd_f64_x(pg1, s1948, s1956);
            t2996 = svadd_f64_x(pg1, s1949, s1957);
            t2997 = svsub_f64_x(pg1, s1948, s1956);
            t2998 = svsub_f64_x(pg1, s1949, s1957);
            t2999 = svadd_f64_x(pg1, t2991, t2995);
            t3000 = svadd_f64_x(pg1, t2992, t2996);
            t3001 = svadd_f64_x(pg1, t2993, t2998);
            t3002 = svsub_f64_x(pg1, t2994, t2997);
            t3003 = svsub_f64_x(pg1, t2993, t2998);
            t3004 = svadd_f64_x(pg1, t2994, t2997);
            t3005 = svmls_n_f64_x(pg1, s1932, t2999, 0.25);
            t3006 = svmls_n_f64_x(pg1, s1933, t3000, 0.25);
            s2034 = svmla_n_f64_x(pg1, t3001, t3002, 1.6180339887498947);
            s1982 = svmul_n_f64_x(pg1, s2034, 0.29389262614623657);
            s2035 = svmls_n_f64_x(pg1, t3002, t3001, 1.6180339887498947);
            s1983 = svmul_n_f64_x(pg1, s2035, 0.29389262614623657);
            s1984 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2991, t2995), 0.55901699437494745);
            s1985 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2992, t2996), 0.55901699437494745);
            s2036 = svmls_n_f64_x(pg1, t3004, t3003, 0.61803398874989479);
            s1986 = svmul_n_f64_x(pg1, s2036, 0.47552825814757682);
            s2037 = svmla_n_f64_x(pg1, t3003, t3004, 0.61803398874989479);
            s1987 = svmul_n_f64_x(pg1, s2037, 0.47552825814757682);
            s1988 = svadd_f64_x(pg1, s1932, t2999);
            s1989 = svadd_f64_x(pg1, s1933, t3000);
            t3007 = svadd_f64_x(pg1, t3005, s1984);
            t3008 = svadd_f64_x(pg1, t3006, s1985);
            t3009 = svsub_f64_x(pg1, t3005, s1984);
            t3010 = svsub_f64_x(pg1, t3006, s1985);
            t3011 = svadd_f64_x(pg1, s1982, s1986);
            t3012 = svsub_f64_x(pg1, s1983, s1987);
            t3013 = svsub_f64_x(pg1, s1982, s1986);
            t3014 = svadd_f64_x(pg1, s1983, s1987);
            s1990 = svadd_f64_x(pg1, t3007, t3011);
            s1991 = svadd_f64_x(pg1, t3008, t3012);
            s1992 = svsub_f64_x(pg1, t3007, t3011);
            s1993 = svsub_f64_x(pg1, t3008, t3012);
            s1994 = svadd_f64_x(pg1, t3009, t3014);
            s1995 = svsub_f64_x(pg1, t3010, t3013);
            s1996 = svsub_f64_x(pg1, t3009, t3014);
            s1997 = svadd_f64_x(pg1, t3010, t3013);
            t3015 = svadd_f64_x(pg1, s1938, s1962);
            t3016 = svadd_f64_x(pg1, s1939, s1963);
            t3017 = svsub_f64_x(pg1, s1938, s1962);
            t3018 = svsub_f64_x(pg1, s1939, s1963);
            t3019 = svadd_f64_x(pg1, s1946, s1954);
            t3020 = svadd_f64_x(pg1, s1947, s1955);
            t3021 = svsub_f64_x(pg1, s1946, s1954);
            t3022 = svsub_f64_x(pg1, s1947, s1955);
            t3023 = svadd_f64_x(pg1, t3015, t3019);
            t3024 = svadd_f64_x(pg1, t3016, t3020);
            t3025 = svadd_f64_x(pg1, t3017, t3022);
            t3026 = svsub_f64_x(pg1, t3018, t3021);
            t3027 = svsub_f64_x(pg1, t3017, t3022);
            t3028 = svadd_f64_x(pg1, t3018, t3021);
            t3029 = svmls_n_f64_x(pg1, s1930, t3023, 0.25);
            t3030 = svmls_n_f64_x(pg1, s1931, t3024, 0.25);
            s2038 = svmla_n_f64_x(pg1, t3025, t3026, 1.6180339887498947);
            s1998 = svmul_n_f64_x(pg1, s2038, 0.29389262614623657);
            s2039 = svmls_n_f64_x(pg1, t3026, t3025, 1.6180339887498947);
            s1999 = svmul_n_f64_x(pg1, s2039, 0.29389262614623657);
            s2000 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3015, t3019), 0.55901699437494745);
            s2001 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3016, t3020), 0.55901699437494745);
            s2040 = svmls_n_f64_x(pg1, t3028, t3027, 0.61803398874989479);
            s2002 = svmul_n_f64_x(pg1, s2040, 0.47552825814757682);
            s2041 = svmla_n_f64_x(pg1, t3027, t3028, 0.61803398874989479);
            s2003 = svmul_n_f64_x(pg1, s2041, 0.47552825814757682);
            s2004 = svadd_f64_x(pg1, s1930, t3023);
            s2005 = svadd_f64_x(pg1, s1931, t3024);
            t3031 = svadd_f64_x(pg1, t3029, s2000);
            t3032 = svadd_f64_x(pg1, t3030, s2001);
            t3033 = svsub_f64_x(pg1, t3029, s2000);
            t3034 = svsub_f64_x(pg1, t3030, s2001);
            t3035 = svadd_f64_x(pg1, s1998, s2002);
            t3036 = svsub_f64_x(pg1, s1999, s2003);
            t3037 = svsub_f64_x(pg1, s1998, s2002);
            t3038 = svadd_f64_x(pg1, s1999, s2003);
            s2006 = svadd_f64_x(pg1, t3031, t3035);
            s2007 = svadd_f64_x(pg1, t3032, t3036);
            s2008 = svsub_f64_x(pg1, t3031, t3035);
            s2009 = svsub_f64_x(pg1, t3032, t3036);
            s2010 = svadd_f64_x(pg1, t3033, t3038);
            s2011 = svsub_f64_x(pg1, t3034, t3037);
            s2012 = svsub_f64_x(pg1, t3033, t3038);
            s2013 = svadd_f64_x(pg1, t3034, t3037);
            t3039 = svadd_f64_x(pg1, s1942, s1966);
            t3040 = svadd_f64_x(pg1, s1943, s1967);
            t3041 = svsub_f64_x(pg1, s1942, s1966);
            t3042 = svsub_f64_x(pg1, s1943, s1967);
            t3043 = svadd_f64_x(pg1, s1950, s1958);
            t3044 = svadd_f64_x(pg1, s1951, s1959);
            t3045 = svsub_f64_x(pg1, s1950, s1958);
            t3046 = svsub_f64_x(pg1, s1951, s1959);
            t3047 = svadd_f64_x(pg1, t3039, t3043);
            t3048 = svadd_f64_x(pg1, t3040, t3044);
            t3049 = svadd_f64_x(pg1, t3041, t3046);
            t3050 = svsub_f64_x(pg1, t3042, t3045);
            t3051 = svsub_f64_x(pg1, t3041, t3046);
            t3052 = svadd_f64_x(pg1, t3042, t3045);
            t3053 = svmls_n_f64_x(pg1, s1934, t3047, 0.25);
            t3054 = svmls_n_f64_x(pg1, s1935, t3048, 0.25);
            s2042 = svmla_n_f64_x(pg1, t3049, t3050, 1.6180339887498947);
            s2014 = svmul_n_f64_x(pg1, s2042, 0.29389262614623657);
            s2043 = svmls_n_f64_x(pg1, t3050, t3049, 1.6180339887498947);
            s2015 = svmul_n_f64_x(pg1, s2043, 0.29389262614623657);
            s2016 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3039, t3043), 0.55901699437494745);
            s2017 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3040, t3044), 0.55901699437494745);
            s2044 = svmls_n_f64_x(pg1, t3052, t3051, 0.61803398874989479);
            s2018 = svmul_n_f64_x(pg1, s2044, 0.47552825814757682);
            s2045 = svmla_n_f64_x(pg1, t3051, t3052, 0.61803398874989479);
            s2019 = svmul_n_f64_x(pg1, s2045, 0.47552825814757682);
            s2020 = svadd_f64_x(pg1, s1934, t3047);
            s2021 = svadd_f64_x(pg1, s1935, t3048);
            t3055 = svadd_f64_x(pg1, t3053, s2016);
            t3056 = svadd_f64_x(pg1, t3054, s2017);
            t3057 = svsub_f64_x(pg1, t3053, s2016);
            t3058 = svsub_f64_x(pg1, t3054, s2017);
            t3059 = svadd_f64_x(pg1, s2014, s2018);
            t3060 = svsub_f64_x(pg1, s2015, s2019);
            t3061 = svsub_f64_x(pg1, s2014, s2018);
            t3062 = svadd_f64_x(pg1, s2015, s2019);
            s2022 = svadd_f64_x(pg1, t3055, t3059);
            s2023 = svadd_f64_x(pg1, t3056, t3060);
            s2024 = svsub_f64_x(pg1, t3055, t3059);
            s2025 = svsub_f64_x(pg1, t3056, t3060);
            s2026 = svadd_f64_x(pg1, t3057, t3062);
            s2027 = svsub_f64_x(pg1, t3058, t3061);
            s2028 = svsub_f64_x(pg1, t3057, t3062);
            s2029 = svadd_f64_x(pg1, t3058, t3061);
            a4086 = ((38)*(j1));
            a4087 = TW1[a4086];
            a4088 = TW1[(a4086 + 1)];
            a4089 = TW1[(a4086 + 2)];
            a4090 = TW1[(a4086 + 3)];
            a4091 = TW1[(a4086 + 4)];
            a4092 = TW1[(a4086 + 5)];
            a4093 = TW1[(a4086 + 6)];
            a4094 = TW1[(a4086 + 7)];
            a4095 = TW1[(a4086 + 8)];
            a4096 = TW1[(a4086 + 9)];
            a4097 = TW1[(a4086 + 10)];
            a4098 = TW1[(a4086 + 11)];
            a4099 = TW1[(a4086 + 12)];
            a4100 = TW1[(a4086 + 13)];
            a4101 = TW1[(a4086 + 14)];
            a4102 = TW1[(a4086 + 15)];
            a4103 = TW1[(a4086 + 16)];
            a4104 = TW1[(a4086 + 17)];
            a4105 = TW1[(a4086 + 18)];
            a4106 = TW1[(a4086 + 19)];
            a4107 = TW1[(a4086 + 20)];
            a4108 = TW1[(a4086 + 21)];
            a4109 = TW1[(a4086 + 22)];
            a4110 = TW1[(a4086 + 23)];
            a4111 = TW1[(a4086 + 24)];
            a4112 = TW1[(a4086 + 25)];
            a4113 = TW1[(a4086 + 26)];
            a4114 = TW1[(a4086 + 27)];
            a4115 = TW1[(a4086 + 28)];
            a4116 = TW1[(a4086 + 29)];
            a4117 = TW1[(a4086 + 30)];
            a4118 = TW1[(a4086 + 31)];
            a4119 = TW1[(a4086 + 32)];
            a4120 = TW1[(a4086 + 33)];
            a4121 = TW1[(a4086 + 34)];
            a4122 = TW1[(a4086 + 35)];
            a4123 = TW1[(a4086 + 36)];
            a4124 = TW1[(a4086 + 37)];
            svex2_21.v0 = svadd_f64_x(pg1, s1928, t2975);
            svex2_21.v1 = svadd_f64_x(pg1, s1929, t2976);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)))))), svex2_21);
            svex2_22.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1989, a4088), s1988, a4087);
            svex2_22.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1989, a4087), s1988, a4088);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + m1)))), svex2_22);
            svex2_23.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2005, a4090), s2004, a4089);
            svex2_23.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2005, a4089), s2004, a4090);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_23);
            svex2_24.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2021, a4092), s2020, a4091);
            svex2_24.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2021, a4091), s2020, a4092);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_24);
            svex2_25.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1975, a4094), s1974, a4093);
            svex2_25.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1975, a4093), s1974, a4094);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_25);
            svex2_26.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1991, a4096), s1990, a4095);
            svex2_26.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1991, a4095), s1990, a4096);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_26);
            svex2_27.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2007, a4098), s2006, a4097);
            svex2_27.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2007, a4097), s2006, a4098);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_27);
            svex2_28.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2023, a4100), s2022, a4099);
            svex2_28.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2023, a4099), s2022, a4100);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_28);
            svex2_29.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1979, a4102), s1978, a4101);
            svex2_29.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1979, a4101), s1978, a4102);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_29);
            svex2_30.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1995, a4104), s1994, a4103);
            svex2_30.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1995, a4103), s1994, a4104);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((9)*(m1)))))), svex2_30);
            svex2_31.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2011, a4106), s2010, a4105);
            svex2_31.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2011, a4105), s2010, a4106);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((10)*(m1)))))), svex2_31);
            svex2_32.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2027, a4108), s2026, a4107);
            svex2_32.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2027, a4107), s2026, a4108);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((11)*(m1)))))), svex2_32);
            svex2_33.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1981, a4110), s1980, a4109);
            svex2_33.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1981, a4109), s1980, a4110);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((12)*(m1)))))), svex2_33);
            svex2_34.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1997, a4112), s1996, a4111);
            svex2_34.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1997, a4111), s1996, a4112);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((13)*(m1)))))), svex2_34);
            svex2_35.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2013, a4114), s2012, a4113);
            svex2_35.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2013, a4113), s2012, a4114);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((14)*(m1)))))), svex2_35);
            svex2_36.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2029, a4116), s2028, a4115);
            svex2_36.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2029, a4115), s2028, a4116);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((15)*(m1)))))), svex2_36);
            svex2_37.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1977, a4118), s1976, a4117);
            svex2_37.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1977, a4117), s1976, a4118);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((16)*(m1)))))), svex2_37);
            svex2_38.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s1993, a4120), s1992, a4119);
            svex2_38.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s1993, a4119), s1992, a4120);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((17)*(m1)))))), svex2_38);
            svex2_39.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2009, a4122), s2008, a4121);
            svex2_39.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2009, a4121), s2008, a4122);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((18)*(m1)))))), svex2_39);
            svex2_40.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s2025, a4124), s2024, a4123);
            svex2_40.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s2025, a4123), s2024, a4124);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((20)*(j1)))*(m1)) + ((19)*(m1)))))), svex2_40);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
