/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft21c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D91[14];
    static float64_t D92[28];
    int l1, m1;
    svfloat64x2_t s2745, s2748, s2751, s2754, s2757, s2760, s2763, s2766, 
            s2769, s2772, s2775, s2778, s2781, s2784, s2787, s2790, 
            s2793, s2796, s2799, s2802, s2805, svex2_22, svex2_23, svex2_24, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42;
    svfloat64_t s2746, s2747, s2749, s2750, s2752, s2753, s2755, s2756, 
            s2758, s2759, s2761, s2762, s2764, s2765, s2767, s2768, 
            s2770, s2771, s2773, s2774, s2776, s2777, s2779, s2780, 
            s2782, s2783, s2785, s2786, s2788, s2789, s2791, s2792, 
            s2794, s2795, s2797, s2798, s2800, s2801, s2803, s2804, 
            s2806, s2807, s2808, s2809, s2810, s2811, s2812, s2813, 
            s2814, s2815, s2816, s2817, s2818, s2819, s2820, s2821, 
            s2822, s2823, s2824, s2825, s2826, s2827, s2828, s2829, 
            s2830, s2831, s2832, s2833, s2834, s2835, s2836, s2837, 
            s2838, s2839, s2840, s2841, s2842, s2843, s2844, s2845, 
            s2846, s2847, s2848, s2849, s2850, s2851, s2852, s2853, 
            s2854, s2855, s2856, s2857, s2858, s2859, s2860, s2861, 
            s2862, s2863, s2864, s2865, s2866, s2867, s2868, s2869, 
            s2870, s2871, s2872, s2873, s2874, s2875, s2876, s2877, 
            s2878, s2879, s2880, s2881, s2882, s2883, s2884, s2885, 
            s2886, s2887, s2888, s2889, s2890, s2891, s2892, s2893, 
            s2894, s2895, s2896, s2897, s2898, s2899, s2900, s2901, 
            s2902, s2903, s2904, s2905, s2906, s2907, s2908, s2909, 
            s2910, s2911, s2912, s2913, s2914, s2915, s2916, s2917, 
            s2918, s2919, s2920, s2921, s2922, s2923, s2924, s2925, 
            s2926, s2927, s2928, s2929, s2930, s2931, s2932, s2933, 
            s2934, s2935, s2936, s2937, s2938, s2939, s2940, s2941, 
            s2942, s2943, s2944, s2945, s2946, s2947, s2948, s2949, 
            s2950, s2951, s2952, s2953, s2954, s2955, s2956, s2957, 
            s2958, s2959, s2960, s2961, s2962, s2963, s2964, s2965, 
            s2966, s2967, s2968, s2969, s2970, s2971, s2972, s2973, 
            s2974, s2975, s2976, s2977, s2978, s2979, s2980, s2981, 
            s2982, s2983, s2984, s2985, s2986, s2987, s2988, s2989, 
            t4308, t4309, t4310, t4311, t4312, t4313, t4314, t4315, 
            t4316, t4317, t4318, t4319, t4320, t4321, t4322, t4323, 
            t4324, t4325, t4326, t4327, t4328, t4329, t4330, t4331, 
            t4332, t4333, t4334, t4335, t4336, t4337, t4338, t4339, 
            t4340, t4341, t4342, t4343, t4344, t4345, t4346, t4347, 
            t4348, t4349, t4350, t4351, t4352, t4353, t4354, t4355, 
            t4356, t4357, t4358, t4359, t4360, t4361, t4362, t4363, 
            t4364, t4365, t4366, t4367, t4368, t4369, t4370, t4371, 
            t4372, t4373, t4374, t4375, t4376, t4377, t4378, t4379, 
            t4380, t4381, t4382, t4383, t4384, t4385, t4386, t4387, 
            t4388, t4389, t4390, t4391, t4392, t4393, t4394, t4395, 
            t4396, t4397, t4398, t4399, t4400, t4401, t4402, t4403, 
            t4404, t4405, t4406, t4407, t4408, t4409, t4410, t4411, 
            t4412, t4413, t4414, t4415, t4416, t4417, t4418, t4419, 
            t4420, t4421, t4422, t4423, t4424, t4425, t4426, t4427, 
            t4428, t4429, t4430, t4431, t4432, t4433, t4434, t4435, 
            t4436, t4437, t4438, t4439, t4440, t4441, t4442, t4443, 
            t4444, t4445, t4446, t4447, t4448, t4449, t4450, t4451, 
            t4452, t4453, t4454, t4455, t4456, t4457, t4458, t4459, 
            t4460, t4461, t4462, t4463, t4464, t4465, t4466, t4467, 
            t4468, t4469, t4470, t4471, t4472, t4473, t4474, t4475, 
            t4476, t4477, t4478, t4479, t4480, t4481, t4482, t4483, 
            t4484, t4485, t4486, t4487, t4488, t4489, t4490, t4491, 
            t4492, t4493, t4494, t4495, t4496, t4497, t4498, t4499, 
            t4500, t4501, t4502, t4503, t4504, t4505, t4506, t4507, 
            t4508, t4509, t4510, t4511, t4512, t4513, t4514, t4515, 
            t4516, t4517, t4518, t4519, t4520, t4521, t4522, t4523, 
            t4524, t4525, t4526, t4527, t4528, t4529, t4530, t4531, 
            t4532, t4533;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s2745 = svld2_f64(pg1, (X + ((2)*(k1))));
        s2746 = s2745.v0;
        s2747 = s2745.v1;
        s2748 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s2749 = s2748.v0;
        s2750 = s2748.v1;
        s2751 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s2752 = s2751.v0;
        s2753 = s2751.v1;
        s2754 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s2755 = s2754.v0;
        s2756 = s2754.v1;
        s2757 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s2758 = s2757.v0;
        s2759 = s2757.v1;
        s2760 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s2761 = s2760.v0;
        s2762 = s2760.v1;
        s2763 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s2764 = s2763.v0;
        s2765 = s2763.v1;
        s2766 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s2767 = s2766.v0;
        s2768 = s2766.v1;
        s2769 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s2770 = s2769.v0;
        s2771 = s2769.v1;
        s2772 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s2773 = s2772.v0;
        s2774 = s2772.v1;
        s2775 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s2776 = s2775.v0;
        s2777 = s2775.v1;
        s2778 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s2779 = s2778.v0;
        s2780 = s2778.v1;
        s2781 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s2782 = s2781.v0;
        s2783 = s2781.v1;
        s2784 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s2785 = s2784.v0;
        s2786 = s2784.v1;
        s2787 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s2788 = s2787.v0;
        s2789 = s2787.v1;
        s2790 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s2791 = s2790.v0;
        s2792 = s2790.v1;
        s2793 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s2794 = s2793.v0;
        s2795 = s2793.v1;
        s2796 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s2797 = s2796.v0;
        s2798 = s2796.v1;
        s2799 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s2800 = s2799.v0;
        s2801 = s2799.v1;
        s2802 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s2803 = s2802.v0;
        s2804 = s2802.v1;
        s2805 = svld2_f64(pg1, (X + ((2)*((k1 + ((((20)*(l1)))*(m1)))))));
        s2806 = s2805.v0;
        s2807 = s2805.v1;
        t4308 = svadd_f64_x(pg1, s2767, s2788);
        t4309 = svadd_f64_x(pg1, s2768, s2789);
        t4310 = svadd_f64_x(pg1, s2746, t4308);
        t4311 = svadd_f64_x(pg1, s2747, t4309);
        t4312 = svmls_n_f64_x(pg1, s2746, t4308, 0.5);
        t4313 = svmls_n_f64_x(pg1, s2747, t4309, 0.5);
        s2808 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2768, s2789), 0.8660254037844386);
        s2809 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2767, s2788), 0.8660254037844386);
        s2810 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4311, D91[1]), t4310, D91[0]);
        s2811 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4311, D91[0]), t4310, D91[1]);
        t4314 = svadd_f64_x(pg1, t4312, s2808);
        t4315 = svsub_f64_x(pg1, t4313, s2809);
        t4316 = svsub_f64_x(pg1, t4312, s2808);
        t4317 = svadd_f64_x(pg1, t4313, s2809);
        s2812 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4315, D92[1]), t4314, D92[0]);
        s2813 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4315, D92[0]), t4314, D92[1]);
        s2814 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4317, D92[3]), t4316, D92[2]);
        s2815 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4317, D92[2]), t4316, D92[3]);
        t4318 = svadd_f64_x(pg1, s2770, s2791);
        t4319 = svadd_f64_x(pg1, s2771, s2792);
        t4320 = svadd_f64_x(pg1, s2749, t4318);
        t4321 = svadd_f64_x(pg1, s2750, t4319);
        t4322 = svmls_n_f64_x(pg1, s2749, t4318, 0.5);
        t4323 = svmls_n_f64_x(pg1, s2750, t4319, 0.5);
        s2816 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2771, s2792), 0.8660254037844386);
        s2817 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2770, s2791), 0.8660254037844386);
        s2818 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4321, D91[3]), t4320, D91[2]);
        s2819 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4321, D91[2]), t4320, D91[3]);
        t4324 = svadd_f64_x(pg1, t4322, s2816);
        t4325 = svsub_f64_x(pg1, t4323, s2817);
        t4326 = svsub_f64_x(pg1, t4322, s2816);
        t4327 = svadd_f64_x(pg1, t4323, s2817);
        s2820 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4325, D92[5]), t4324, D92[4]);
        s2821 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4325, D92[4]), t4324, D92[5]);
        s2822 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4327, D92[7]), t4326, D92[6]);
        s2823 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4327, D92[6]), t4326, D92[7]);
        t4328 = svadd_f64_x(pg1, s2773, s2794);
        t4329 = svadd_f64_x(pg1, s2774, s2795);
        t4330 = svadd_f64_x(pg1, s2752, t4328);
        t4331 = svadd_f64_x(pg1, s2753, t4329);
        t4332 = svmls_n_f64_x(pg1, s2752, t4328, 0.5);
        t4333 = svmls_n_f64_x(pg1, s2753, t4329, 0.5);
        s2824 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2774, s2795), 0.8660254037844386);
        s2825 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2773, s2794), 0.8660254037844386);
        s2826 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4331, D91[5]), t4330, D91[4]);
        s2827 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4331, D91[4]), t4330, D91[5]);
        t4334 = svadd_f64_x(pg1, t4332, s2824);
        t4335 = svsub_f64_x(pg1, t4333, s2825);
        t4336 = svsub_f64_x(pg1, t4332, s2824);
        t4337 = svadd_f64_x(pg1, t4333, s2825);
        s2828 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4335, D92[9]), t4334, D92[8]);
        s2829 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4335, D92[8]), t4334, D92[9]);
        s2830 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4337, D92[11]), t4336, D92[10]);
        s2831 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4337, D92[10]), t4336, D92[11]);
        t4338 = svadd_f64_x(pg1, s2776, s2797);
        t4339 = svadd_f64_x(pg1, s2777, s2798);
        t4340 = svadd_f64_x(pg1, s2755, t4338);
        t4341 = svadd_f64_x(pg1, s2756, t4339);
        t4342 = svmls_n_f64_x(pg1, s2755, t4338, 0.5);
        t4343 = svmls_n_f64_x(pg1, s2756, t4339, 0.5);
        s2832 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2777, s2798), 0.8660254037844386);
        s2833 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2776, s2797), 0.8660254037844386);
        s2834 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4341, D91[7]), t4340, D91[6]);
        s2835 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4341, D91[6]), t4340, D91[7]);
        t4344 = svadd_f64_x(pg1, t4342, s2832);
        t4345 = svsub_f64_x(pg1, t4343, s2833);
        t4346 = svsub_f64_x(pg1, t4342, s2832);
        t4347 = svadd_f64_x(pg1, t4343, s2833);
        s2836 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4345, D92[13]), t4344, D92[12]);
        s2837 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4345, D92[12]), t4344, D92[13]);
        s2838 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4347, D92[15]), t4346, D92[14]);
        s2839 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4347, D92[14]), t4346, D92[15]);
        t4348 = svadd_f64_x(pg1, s2779, s2800);
        t4349 = svadd_f64_x(pg1, s2780, s2801);
        t4350 = svadd_f64_x(pg1, s2758, t4348);
        t4351 = svadd_f64_x(pg1, s2759, t4349);
        t4352 = svmls_n_f64_x(pg1, s2758, t4348, 0.5);
        t4353 = svmls_n_f64_x(pg1, s2759, t4349, 0.5);
        s2840 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2780, s2801), 0.8660254037844386);
        s2841 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2779, s2800), 0.8660254037844386);
        s2842 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4351, D91[9]), t4350, D91[8]);
        s2843 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4351, D91[8]), t4350, D91[9]);
        t4354 = svadd_f64_x(pg1, t4352, s2840);
        t4355 = svsub_f64_x(pg1, t4353, s2841);
        t4356 = svsub_f64_x(pg1, t4352, s2840);
        t4357 = svadd_f64_x(pg1, t4353, s2841);
        s2844 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4355, D92[17]), t4354, D92[16]);
        s2845 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4355, D92[16]), t4354, D92[17]);
        s2846 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4357, D92[19]), t4356, D92[18]);
        s2847 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4357, D92[18]), t4356, D92[19]);
        t4358 = svadd_f64_x(pg1, s2782, s2803);
        t4359 = svadd_f64_x(pg1, s2783, s2804);
        t4360 = svadd_f64_x(pg1, s2761, t4358);
        t4361 = svadd_f64_x(pg1, s2762, t4359);
        t4362 = svmls_n_f64_x(pg1, s2761, t4358, 0.5);
        t4363 = svmls_n_f64_x(pg1, s2762, t4359, 0.5);
        s2848 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2783, s2804), 0.8660254037844386);
        s2849 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2782, s2803), 0.8660254037844386);
        s2850 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4361, D91[11]), t4360, D91[10]);
        s2851 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4361, D91[10]), t4360, D91[11]);
        t4364 = svadd_f64_x(pg1, t4362, s2848);
        t4365 = svsub_f64_x(pg1, t4363, s2849);
        t4366 = svsub_f64_x(pg1, t4362, s2848);
        t4367 = svadd_f64_x(pg1, t4363, s2849);
        s2852 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4365, D92[21]), t4364, D92[20]);
        s2853 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4365, D92[20]), t4364, D92[21]);
        s2854 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4367, D92[23]), t4366, D92[22]);
        s2855 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4367, D92[22]), t4366, D92[23]);
        t4368 = svadd_f64_x(pg1, s2785, s2806);
        t4369 = svadd_f64_x(pg1, s2786, s2807);
        t4370 = svadd_f64_x(pg1, s2764, t4368);
        t4371 = svadd_f64_x(pg1, s2765, t4369);
        t4372 = svmls_n_f64_x(pg1, s2764, t4368, 0.5);
        t4373 = svmls_n_f64_x(pg1, s2765, t4369, 0.5);
        s2856 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2786, s2807), 0.8660254037844386);
        s2857 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2785, s2806), 0.8660254037844386);
        s2858 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4371, D91[13]), t4370, D91[12]);
        s2859 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4371, D91[12]), t4370, D91[13]);
        t4374 = svadd_f64_x(pg1, t4372, s2856);
        t4375 = svsub_f64_x(pg1, t4373, s2857);
        t4376 = svsub_f64_x(pg1, t4372, s2856);
        t4377 = svadd_f64_x(pg1, t4373, s2857);
        s2860 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4375, D92[25]), t4374, D92[24]);
        s2861 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4375, D92[24]), t4374, D92[25]);
        s2862 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t4377, D92[27]), t4376, D92[26]);
        s2863 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t4377, D92[26]), t4376, D92[27]);
        t4378 = svadd_f64_x(pg1, s2826, s2842);
        t4379 = svadd_f64_x(pg1, s2827, s2843);
        t4380 = svadd_f64_x(pg1, s2818, t4378);
        t4381 = svadd_f64_x(pg1, s2819, t4379);
        t4382 = svmls_n_f64_x(pg1, s2818, t4378, 0.5);
        t4383 = svmls_n_f64_x(pg1, s2819, t4379, 0.5);
        s2864 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2827, s2843), 0.8660254037844386);
        s2865 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2826, s2842), 0.8660254037844386);
        t4384 = svadd_f64_x(pg1, t4382, s2864);
        t4385 = svsub_f64_x(pg1, t4383, s2865);
        t4386 = svsub_f64_x(pg1, t4382, s2864);
        t4387 = svadd_f64_x(pg1, t4383, s2865);
        t4388 = svadd_f64_x(pg1, s2858, s2850);
        t4389 = svadd_f64_x(pg1, s2859, s2851);
        t4390 = svadd_f64_x(pg1, s2834, t4388);
        t4391 = svadd_f64_x(pg1, s2835, t4389);
        t4392 = svmls_n_f64_x(pg1, s2834, t4388, 0.5);
        t4393 = svmls_n_f64_x(pg1, s2835, t4389, 0.5);
        s2866 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2859, s2851), 0.8660254037844386);
        s2867 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2858, s2850), 0.8660254037844386);
        t4394 = svadd_f64_x(pg1, t4392, s2866);
        t4395 = svsub_f64_x(pg1, t4393, s2867);
        t4396 = svsub_f64_x(pg1, t4392, s2866);
        t4397 = svadd_f64_x(pg1, t4393, s2867);
        s2942 = svmla_n_f64_x(pg1, t4394, t4395, 1.7320508075688772);
        s2868 = svmul_n_f64_x(pg1, s2942, 0.5);
        s2943 = svmls_n_f64_x(pg1, t4395, t4394, 1.7320508075688772);
        s2869 = svmul_n_f64_x(pg1, s2943, 0.5);
        s2944 = svmls_n_f64_x(pg1, t4397, t4396, 0.57735026918962584);
        s2870 = svmul_n_f64_x(pg1, s2944, 0.8660254037844386);
        s2945 = svmla_n_f64_x(pg1, t4396, t4397, 0.57735026918962584);
        s2871 = svmul_n_f64_x(pg1, s2945, 0.8660254037844386);
        t4398 = svadd_f64_x(pg1, t4380, t4390);
        t4399 = svadd_f64_x(pg1, t4381, t4391);
        t4400 = svadd_f64_x(pg1, t4384, s2868);
        t4401 = svadd_f64_x(pg1, t4385, s2869);
        t4402 = svsub_f64_x(pg1, t4384, s2868);
        t4403 = svsub_f64_x(pg1, t4385, s2869);
        t4404 = svadd_f64_x(pg1, t4386, s2870);
        t4405 = svsub_f64_x(pg1, t4387, s2871);
        t4406 = svsub_f64_x(pg1, t4386, s2870);
        t4407 = svadd_f64_x(pg1, t4387, s2871);
        t4408 = svmls_n_f64_x(pg1, s2810, t4398, 0.16666666666666666);
        t4409 = svmls_n_f64_x(pg1, s2811, t4399, 0.16666666666666666);
        s2946 = svmla_n_f64_x(pg1, t4400, t4401, 0.41908315722758349);
        s2872 = svmul_n_f64_x(pg1, s2946, 0.4066888930575896);
        s2947 = svmls_n_f64_x(pg1, t4401, t4400, 0.41908315722758349);
        s2873 = svmul_n_f64_x(pg1, s2947, 0.4066888930575896);
        s2948 = svmla_n_f64_x(pg1, t4404, t4405, 0.49572725516748389);
        s2874 = svmul_n_f64_x(pg1, s2948, 0.39507823426270006);
        s2949 = svmls_n_f64_x(pg1, t4405, t4404, 0.49572725516748389);
        s2875 = svmul_n_f64_x(pg1, s2949, 0.39507823426270006);
        s2876 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4381, t4391), 0.44095855184409843);
        s2877 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4380, t4390), 0.44095855184409843);
        s2950 = svmls_n_f64_x(pg1, t4402, t4403, 0.49572725516748389);
        s2878 = svmul_n_f64_x(pg1, s2950, 0.39507823426270006);
        s2951 = svmla_n_f64_x(pg1, t4402, t4403, 2.0172382889501304);
        s2879 = svmul_n_f64_x(pg1, s2951, 0.1958510486474645);
        s2952 = svmls_n_f64_x(pg1, t4407, t4406, 2.386161273135941);
        s2880 = svmul_n_f64_x(pg1, s2952, 0.17043646531196566);
        s2953 = svmla_n_f64_x(pg1, t4406, t4407, 2.386161273135941);
        s2881 = svmul_n_f64_x(pg1, s2953, 0.17043646531196566);
        t4410 = svadd_f64_x(pg1, s2874, s2878);
        t4411 = svadd_f64_x(pg1, s2875, s2879);
        t4412 = svadd_f64_x(pg1, t4408, t4410);
        t4413 = svadd_f64_x(pg1, t4409, t4411);
        t4414 = svmls_n_f64_x(pg1, t4408, t4410, 0.5);
        t4415 = svmls_n_f64_x(pg1, t4409, t4411, 0.5);
        s2882 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2875, s2879), 0.8660254037844386);
        s2883 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2874, s2878), 0.8660254037844386);
        t4416 = svadd_f64_x(pg1, t4414, s2882);
        t4417 = svsub_f64_x(pg1, t4415, s2883);
        t4418 = svsub_f64_x(pg1, t4414, s2882);
        t4419 = svadd_f64_x(pg1, t4415, s2883);
        t4420 = svadd_f64_x(pg1, s2876, s2880);
        t4421 = svadd_f64_x(pg1, s2877, s2881);
        t4422 = svadd_f64_x(pg1, s2872, t4420);
        t4423 = svsub_f64_x(pg1, s2873, t4421);
        t4424 = svmls_n_f64_x(pg1, s2872, t4420, 0.5);
        t4425 = svmla_n_f64_x(pg1, s2873, t4421, 0.5);
        s2884 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2881, s2877), 0.8660254037844386);
        s2885 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2876, s2880), 0.8660254037844386);
        t4426 = svadd_f64_x(pg1, t4424, s2884);
        t4427 = svsub_f64_x(pg1, t4425, s2885);
        t4428 = svsub_f64_x(pg1, t4424, s2884);
        t4429 = svadd_f64_x(pg1, t4425, s2885);
        s2954 = svmla_n_f64_x(pg1, t4426, t4427, 1.7320508075688772);
        s2886 = svmul_n_f64_x(pg1, s2954, 0.5);
        s2955 = svmls_n_f64_x(pg1, t4427, t4426, 1.7320508075688772);
        s2887 = svmul_n_f64_x(pg1, s2955, 0.5);
        s2956 = svmls_n_f64_x(pg1, t4429, t4428, 0.57735026918962584);
        s2888 = svmul_n_f64_x(pg1, s2956, 0.8660254037844386);
        s2957 = svmla_n_f64_x(pg1, t4428, t4429, 0.57735026918962584);
        s2889 = svmul_n_f64_x(pg1, s2957, 0.8660254037844386);
        t4430 = svadd_f64_x(pg1, s2828, s2844);
        t4431 = svadd_f64_x(pg1, s2829, s2845);
        t4432 = svadd_f64_x(pg1, s2820, t4430);
        t4433 = svadd_f64_x(pg1, s2821, t4431);
        t4434 = svmls_n_f64_x(pg1, s2820, t4430, 0.5);
        t4435 = svmls_n_f64_x(pg1, s2821, t4431, 0.5);
        s2890 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2829, s2845), 0.8660254037844386);
        s2891 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2828, s2844), 0.8660254037844386);
        t4436 = svadd_f64_x(pg1, t4434, s2890);
        t4437 = svsub_f64_x(pg1, t4435, s2891);
        t4438 = svsub_f64_x(pg1, t4434, s2890);
        t4439 = svadd_f64_x(pg1, t4435, s2891);
        t4440 = svadd_f64_x(pg1, s2860, s2852);
        t4441 = svadd_f64_x(pg1, s2861, s2853);
        t4442 = svadd_f64_x(pg1, s2836, t4440);
        t4443 = svadd_f64_x(pg1, s2837, t4441);
        t4444 = svmls_n_f64_x(pg1, s2836, t4440, 0.5);
        t4445 = svmls_n_f64_x(pg1, s2837, t4441, 0.5);
        s2892 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2861, s2853), 0.8660254037844386);
        s2893 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2860, s2852), 0.8660254037844386);
        t4446 = svadd_f64_x(pg1, t4444, s2892);
        t4447 = svsub_f64_x(pg1, t4445, s2893);
        t4448 = svsub_f64_x(pg1, t4444, s2892);
        t4449 = svadd_f64_x(pg1, t4445, s2893);
        s2958 = svmla_n_f64_x(pg1, t4446, t4447, 1.7320508075688772);
        s2894 = svmul_n_f64_x(pg1, s2958, 0.5);
        s2959 = svmls_n_f64_x(pg1, t4447, t4446, 1.7320508075688772);
        s2895 = svmul_n_f64_x(pg1, s2959, 0.5);
        s2960 = svmls_n_f64_x(pg1, t4449, t4448, 0.57735026918962584);
        s2896 = svmul_n_f64_x(pg1, s2960, 0.8660254037844386);
        s2961 = svmla_n_f64_x(pg1, t4448, t4449, 0.57735026918962584);
        s2897 = svmul_n_f64_x(pg1, s2961, 0.8660254037844386);
        t4450 = svadd_f64_x(pg1, t4432, t4442);
        t4451 = svadd_f64_x(pg1, t4433, t4443);
        t4452 = svadd_f64_x(pg1, t4436, s2894);
        t4453 = svadd_f64_x(pg1, t4437, s2895);
        t4454 = svsub_f64_x(pg1, t4436, s2894);
        t4455 = svsub_f64_x(pg1, t4437, s2895);
        t4456 = svadd_f64_x(pg1, t4438, s2896);
        t4457 = svsub_f64_x(pg1, t4439, s2897);
        t4458 = svsub_f64_x(pg1, t4438, s2896);
        t4459 = svadd_f64_x(pg1, t4439, s2897);
        t4460 = svmls_n_f64_x(pg1, s2812, t4450, 0.16666666666666666);
        t4461 = svmls_n_f64_x(pg1, s2813, t4451, 0.16666666666666666);
        s2962 = svmla_n_f64_x(pg1, t4452, t4453, 0.41908315722758349);
        s2898 = svmul_n_f64_x(pg1, s2962, 0.4066888930575896);
        s2963 = svmls_n_f64_x(pg1, t4453, t4452, 0.41908315722758349);
        s2899 = svmul_n_f64_x(pg1, s2963, 0.4066888930575896);
        s2964 = svmla_n_f64_x(pg1, t4456, t4457, 0.49572725516748389);
        s2900 = svmul_n_f64_x(pg1, s2964, 0.39507823426270006);
        s2965 = svmls_n_f64_x(pg1, t4457, t4456, 0.49572725516748389);
        s2901 = svmul_n_f64_x(pg1, s2965, 0.39507823426270006);
        s2902 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4433, t4443), 0.44095855184409843);
        s2903 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4432, t4442), 0.44095855184409843);
        s2966 = svmls_n_f64_x(pg1, t4454, t4455, 0.49572725516748389);
        s2904 = svmul_n_f64_x(pg1, s2966, 0.39507823426270006);
        s2967 = svmla_n_f64_x(pg1, t4454, t4455, 2.0172382889501304);
        s2905 = svmul_n_f64_x(pg1, s2967, 0.1958510486474645);
        s2968 = svmls_n_f64_x(pg1, t4459, t4458, 2.386161273135941);
        s2906 = svmul_n_f64_x(pg1, s2968, 0.17043646531196566);
        s2969 = svmla_n_f64_x(pg1, t4458, t4459, 2.386161273135941);
        s2907 = svmul_n_f64_x(pg1, s2969, 0.17043646531196566);
        t4462 = svadd_f64_x(pg1, s2900, s2904);
        t4463 = svadd_f64_x(pg1, s2901, s2905);
        t4464 = svadd_f64_x(pg1, t4460, t4462);
        t4465 = svadd_f64_x(pg1, t4461, t4463);
        t4466 = svmls_n_f64_x(pg1, t4460, t4462, 0.5);
        t4467 = svmls_n_f64_x(pg1, t4461, t4463, 0.5);
        s2908 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2901, s2905), 0.8660254037844386);
        s2909 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2900, s2904), 0.8660254037844386);
        t4468 = svadd_f64_x(pg1, t4466, s2908);
        t4469 = svsub_f64_x(pg1, t4467, s2909);
        t4470 = svsub_f64_x(pg1, t4466, s2908);
        t4471 = svadd_f64_x(pg1, t4467, s2909);
        t4472 = svadd_f64_x(pg1, s2902, s2906);
        t4473 = svadd_f64_x(pg1, s2903, s2907);
        t4474 = svadd_f64_x(pg1, s2898, t4472);
        t4475 = svsub_f64_x(pg1, s2899, t4473);
        t4476 = svmls_n_f64_x(pg1, s2898, t4472, 0.5);
        t4477 = svmla_n_f64_x(pg1, s2899, t4473, 0.5);
        s2910 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2907, s2903), 0.8660254037844386);
        s2911 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2902, s2906), 0.8660254037844386);
        t4478 = svadd_f64_x(pg1, t4476, s2910);
        t4479 = svsub_f64_x(pg1, t4477, s2911);
        t4480 = svsub_f64_x(pg1, t4476, s2910);
        t4481 = svadd_f64_x(pg1, t4477, s2911);
        s2970 = svmla_n_f64_x(pg1, t4478, t4479, 1.7320508075688772);
        s2912 = svmul_n_f64_x(pg1, s2970, 0.5);
        s2971 = svmls_n_f64_x(pg1, t4479, t4478, 1.7320508075688772);
        s2913 = svmul_n_f64_x(pg1, s2971, 0.5);
        s2972 = svmls_n_f64_x(pg1, t4481, t4480, 0.57735026918962584);
        s2914 = svmul_n_f64_x(pg1, s2972, 0.8660254037844386);
        s2973 = svmla_n_f64_x(pg1, t4480, t4481, 0.57735026918962584);
        s2915 = svmul_n_f64_x(pg1, s2973, 0.8660254037844386);
        t4482 = svadd_f64_x(pg1, s2830, s2846);
        t4483 = svadd_f64_x(pg1, s2831, s2847);
        t4484 = svadd_f64_x(pg1, s2822, t4482);
        t4485 = svadd_f64_x(pg1, s2823, t4483);
        t4486 = svmls_n_f64_x(pg1, s2822, t4482, 0.5);
        t4487 = svmls_n_f64_x(pg1, s2823, t4483, 0.5);
        s2916 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2831, s2847), 0.8660254037844386);
        s2917 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2830, s2846), 0.8660254037844386);
        t4488 = svadd_f64_x(pg1, t4486, s2916);
        t4489 = svsub_f64_x(pg1, t4487, s2917);
        t4490 = svsub_f64_x(pg1, t4486, s2916);
        t4491 = svadd_f64_x(pg1, t4487, s2917);
        t4492 = svadd_f64_x(pg1, s2862, s2854);
        t4493 = svadd_f64_x(pg1, s2863, s2855);
        t4494 = svadd_f64_x(pg1, s2838, t4492);
        t4495 = svadd_f64_x(pg1, s2839, t4493);
        t4496 = svmls_n_f64_x(pg1, s2838, t4492, 0.5);
        t4497 = svmls_n_f64_x(pg1, s2839, t4493, 0.5);
        s2918 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2863, s2855), 0.8660254037844386);
        s2919 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2862, s2854), 0.8660254037844386);
        t4498 = svadd_f64_x(pg1, t4496, s2918);
        t4499 = svsub_f64_x(pg1, t4497, s2919);
        t4500 = svsub_f64_x(pg1, t4496, s2918);
        t4501 = svadd_f64_x(pg1, t4497, s2919);
        s2974 = svmla_n_f64_x(pg1, t4498, t4499, 1.7320508075688772);
        s2920 = svmul_n_f64_x(pg1, s2974, 0.5);
        s2975 = svmls_n_f64_x(pg1, t4499, t4498, 1.7320508075688772);
        s2921 = svmul_n_f64_x(pg1, s2975, 0.5);
        s2976 = svmls_n_f64_x(pg1, t4501, t4500, 0.57735026918962584);
        s2922 = svmul_n_f64_x(pg1, s2976, 0.8660254037844386);
        s2977 = svmla_n_f64_x(pg1, t4500, t4501, 0.57735026918962584);
        s2923 = svmul_n_f64_x(pg1, s2977, 0.8660254037844386);
        t4502 = svadd_f64_x(pg1, t4484, t4494);
        t4503 = svadd_f64_x(pg1, t4485, t4495);
        t4504 = svadd_f64_x(pg1, t4488, s2920);
        t4505 = svadd_f64_x(pg1, t4489, s2921);
        t4506 = svsub_f64_x(pg1, t4488, s2920);
        t4507 = svsub_f64_x(pg1, t4489, s2921);
        t4508 = svadd_f64_x(pg1, t4490, s2922);
        t4509 = svsub_f64_x(pg1, t4491, s2923);
        t4510 = svsub_f64_x(pg1, t4490, s2922);
        t4511 = svadd_f64_x(pg1, t4491, s2923);
        t4512 = svmls_n_f64_x(pg1, s2814, t4502, 0.16666666666666666);
        t4513 = svmls_n_f64_x(pg1, s2815, t4503, 0.16666666666666666);
        s2978 = svmla_n_f64_x(pg1, t4504, t4505, 0.41908315722758349);
        s2924 = svmul_n_f64_x(pg1, s2978, 0.4066888930575896);
        s2979 = svmls_n_f64_x(pg1, t4505, t4504, 0.41908315722758349);
        s2925 = svmul_n_f64_x(pg1, s2979, 0.4066888930575896);
        s2980 = svmla_n_f64_x(pg1, t4508, t4509, 0.49572725516748389);
        s2926 = svmul_n_f64_x(pg1, s2980, 0.39507823426270006);
        s2981 = svmls_n_f64_x(pg1, t4509, t4508, 0.49572725516748389);
        s2927 = svmul_n_f64_x(pg1, s2981, 0.39507823426270006);
        s2928 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4485, t4495), 0.44095855184409843);
        s2929 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t4484, t4494), 0.44095855184409843);
        s2982 = svmls_n_f64_x(pg1, t4506, t4507, 0.49572725516748389);
        s2930 = svmul_n_f64_x(pg1, s2982, 0.39507823426270006);
        s2983 = svmla_n_f64_x(pg1, t4506, t4507, 2.0172382889501304);
        s2931 = svmul_n_f64_x(pg1, s2983, 0.1958510486474645);
        s2984 = svmls_n_f64_x(pg1, t4511, t4510, 2.386161273135941);
        s2932 = svmul_n_f64_x(pg1, s2984, 0.17043646531196566);
        s2985 = svmla_n_f64_x(pg1, t4510, t4511, 2.386161273135941);
        s2933 = svmul_n_f64_x(pg1, s2985, 0.17043646531196566);
        t4514 = svadd_f64_x(pg1, s2926, s2930);
        t4515 = svadd_f64_x(pg1, s2927, s2931);
        t4516 = svadd_f64_x(pg1, t4512, t4514);
        t4517 = svadd_f64_x(pg1, t4513, t4515);
        t4518 = svmls_n_f64_x(pg1, t4512, t4514, 0.5);
        t4519 = svmls_n_f64_x(pg1, t4513, t4515, 0.5);
        s2934 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2927, s2931), 0.8660254037844386);
        s2935 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2926, s2930), 0.8660254037844386);
        t4520 = svadd_f64_x(pg1, t4518, s2934);
        t4521 = svsub_f64_x(pg1, t4519, s2935);
        t4522 = svsub_f64_x(pg1, t4518, s2934);
        t4523 = svadd_f64_x(pg1, t4519, s2935);
        t4524 = svadd_f64_x(pg1, s2928, s2932);
        t4525 = svadd_f64_x(pg1, s2929, s2933);
        t4526 = svadd_f64_x(pg1, s2924, t4524);
        t4527 = svsub_f64_x(pg1, s2925, t4525);
        t4528 = svmls_n_f64_x(pg1, s2924, t4524, 0.5);
        t4529 = svmla_n_f64_x(pg1, s2925, t4525, 0.5);
        s2936 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2933, s2929), 0.8660254037844386);
        s2937 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2928, s2932), 0.8660254037844386);
        t4530 = svadd_f64_x(pg1, t4528, s2936);
        t4531 = svsub_f64_x(pg1, t4529, s2937);
        t4532 = svsub_f64_x(pg1, t4528, s2936);
        t4533 = svadd_f64_x(pg1, t4529, s2937);
        s2986 = svmla_n_f64_x(pg1, t4530, t4531, 1.7320508075688772);
        s2938 = svmul_n_f64_x(pg1, s2986, 0.5);
        s2987 = svmls_n_f64_x(pg1, t4531, t4530, 1.7320508075688772);
        s2939 = svmul_n_f64_x(pg1, s2987, 0.5);
        s2988 = svmls_n_f64_x(pg1, t4533, t4532, 0.57735026918962584);
        s2940 = svmul_n_f64_x(pg1, s2988, 0.8660254037844386);
        s2989 = svmla_n_f64_x(pg1, t4532, t4533, 0.57735026918962584);
        s2941 = svmul_n_f64_x(pg1, s2989, 0.8660254037844386);
        svex2_22.v0 = svadd_f64_x(pg1, s2810, t4398);
        svex2_22.v1 = svadd_f64_x(pg1, s2811, t4399);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_22);
        svex2_23.v0 = svadd_f64_x(pg1, s2812, t4450);
        svex2_23.v1 = svadd_f64_x(pg1, s2813, t4451);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_23);
        svex2_24.v0 = svadd_f64_x(pg1, s2814, t4502);
        svex2_24.v1 = svadd_f64_x(pg1, s2815, t4503);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_24);
        svex2_25.v0 = svadd_f64_x(pg1, t4412, t4422);
        svex2_25.v1 = svadd_f64_x(pg1, t4413, t4423);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_25);
        svex2_26.v0 = svadd_f64_x(pg1, t4464, t4474);
        svex2_26.v1 = svadd_f64_x(pg1, t4465, t4475);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_26);
        svex2_27.v0 = svadd_f64_x(pg1, t4516, t4526);
        svex2_27.v1 = svadd_f64_x(pg1, t4517, t4527);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_27);
        svex2_28.v0 = svadd_f64_x(pg1, t4418, s2888);
        svex2_28.v1 = svsub_f64_x(pg1, t4419, s2889);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_28);
        svex2_29.v0 = svadd_f64_x(pg1, t4470, s2914);
        svex2_29.v1 = svsub_f64_x(pg1, t4471, s2915);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_29);
        svex2_30.v0 = svadd_f64_x(pg1, t4522, s2940);
        svex2_30.v1 = svsub_f64_x(pg1, t4523, s2941);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_30);
        svex2_31.v0 = svadd_f64_x(pg1, t4416, s2886);
        svex2_31.v1 = svadd_f64_x(pg1, t4417, s2887);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_31);
        svex2_32.v0 = svadd_f64_x(pg1, t4468, s2912);
        svex2_32.v1 = svadd_f64_x(pg1, t4469, s2913);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_32);
        svex2_33.v0 = svadd_f64_x(pg1, t4520, s2938);
        svex2_33.v1 = svadd_f64_x(pg1, t4521, s2939);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_33);
        svex2_34.v0 = svsub_f64_x(pg1, t4416, s2886);
        svex2_34.v1 = svsub_f64_x(pg1, t4417, s2887);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_34);
        svex2_35.v0 = svsub_f64_x(pg1, t4468, s2912);
        svex2_35.v1 = svsub_f64_x(pg1, t4469, s2913);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_35);
        svex2_36.v0 = svsub_f64_x(pg1, t4520, s2938);
        svex2_36.v1 = svsub_f64_x(pg1, t4521, s2939);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_36);
        svex2_37.v0 = svsub_f64_x(pg1, t4418, s2888);
        svex2_37.v1 = svadd_f64_x(pg1, t4419, s2889);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_37);
        svex2_38.v0 = svsub_f64_x(pg1, t4470, s2914);
        svex2_38.v1 = svadd_f64_x(pg1, t4471, s2915);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_38);
        svex2_39.v0 = svsub_f64_x(pg1, t4522, s2940);
        svex2_39.v1 = svadd_f64_x(pg1, t4523, s2941);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_39);
        svex2_40.v0 = svsub_f64_x(pg1, t4412, t4422);
        svex2_40.v1 = svsub_f64_x(pg1, t4413, t4423);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_40);
        svex2_41.v0 = svsub_f64_x(pg1, t4464, t4474);
        svex2_41.v1 = svsub_f64_x(pg1, t4465, t4475);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_41);
        svex2_42.v0 = svsub_f64_x(pg1, t4516, t4526);
        svex2_42.v1 = svsub_f64_x(pg1, t4517, t4527);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((20)*(m1)))))), svex2_42);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
