/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft25a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D11[10];
    static float64_t D12[40];
    int l1;
    float64_t  *a2752;
    svfloat64x2_t s1347, s1350, s1353, s1356, s1359, s1362, s1365, s1368, 
            s1371, s1374, s1377, s1380, s1383, s1386, s1389, s1392, 
            s1395, s1398, s1401, s1404, s1407, s1410, s1413, s1416, 
            s1419;
    svfloat64_t a2753, a2754, a2755, a2756, a2757, a2758, a2759, a2760, 
            a2761, a2762, a2763, a2764, a2765, a2766, a2767, a2768, 
            a2769, a2770, a2771, a2772, a2773, a2774, a2775, a2776, 
            a2777, a2778, a2779, a2780, a2781, a2782, a2783, a2784, 
            a2785, a2786, a2787, a2788, a2789, a2790, a2791, a2792, 
            a2793, a2794, a2795, a2796, a2797, a2798, a2799, a2800, 
            s1348, s1349, s1351, s1352, s1354, s1355, s1357, s1358, 
            s1360, s1361, s1363, s1364, s1366, s1367, s1369, s1370, 
            s1372, s1373, s1375, s1376, s1378, s1379, s1381, s1382, 
            s1384, s1385, s1387, s1388, s1390, s1391, s1393, s1394, 
            s1396, s1397, s1399, s1400, s1402, s1403, s1405, s1406, 
            s1408, s1409, s1411, s1412, s1414, s1415, s1417, s1418, 
            s1420, s1421, s1422, s1423, s1424, s1425, s1426, s1427, 
            s1428, s1429, s1430, s1431, s1432, s1433, s1434, s1435, 
            s1436, s1437, s1438, s1439, s1440, s1441, s1442, s1443, 
            s1444, s1445, s1446, s1447, s1448, s1449, s1450, s1451, 
            s1452, s1453, s1454, s1455, s1456, s1457, s1458, s1459, 
            s1460, s1461, s1462, s1463, s1464, s1465, s1466, s1467, 
            s1468, s1469, s1470, s1471, s1472, s1473, s1474, s1475, 
            s1476, s1477, s1478, s1479, s1480, s1481, s1482, s1483, 
            s1484, s1485, s1486, s1487, s1488, s1489, s1490, s1491, 
            s1492, s1493, s1494, s1495, s1496, s1497, s1498, s1499, 
            s1500, s1501, s1502, s1503, s1504, s1505, s1506, s1507, 
            s1508, s1509, s1510, s1511, s1512, s1513, s1514, s1515, 
            s1516, s1517, s1518, s1519, s1520, s1521, s1522, s1523, 
            s1524, s1525, s1526, s1527, s1528, s1529, s1530, s1531, 
            s1532, s1533, s1534, s1535, s1536, s1537, s1538, s1539, 
            s1540, s1541, s1542, s1543, s1544, s1545, s1546, s1547, 
            s1548, s1549, s1550, s1551, s1552, s1553, s1554, s1555, 
            s1556, s1557, s1558, s1559, s1560, s1561, s1562, s1563, 
            s1564, s1565, s1566, s1567, s1568, s1569, s1570, s1571, 
            s1572, s1573, s1574, s1575, s1576, s1577, s1578, s1579, 
            s1580, s1581, s1582, s1583, s1584, s1585, s1586, s1587, 
            s1588, s1589, s1590, s1591, s1592, s1593, s1594, s1595, 
            s1596, s1597, s1598, s1599, s1600, s1601, s1602, s1603, 
            s1604, s1605, s1606, s1607, s1608, s1609, s1610, s1611, 
            s1612, s1613, s1614, s1615, s1616, s1617, s1618, s1619, 
            s1620, s1621, s1622, s1623, s1624, s1625, s1626, s1627, 
            s1628, s1629, s1630, s1631, s1632, s1633, s1634, s1635, 
            s1636, s1637, s1638, s1639, s1640, s1641, s1642, s1643, 
            s1644, s1645, s1646, s1647, s1648, s1649, s1650, s1651, 
            s1652, s1653, s1654, s1655, s1656, s1657, s1658, s1659, 
            s1660, s1661, s1662, s1663, s1664, s1665, s1666, s1667, 
            s1668, s1669, t1553, t1554, t1555, t1556, t1557, t1558, 
            t1559, t1560, t1561, t1562, t1563, t1564, t1565, t1566, 
            t1567, t1568, t1569, t1570, t1571, t1572, t1573, t1574, 
            t1575, t1576, t1577, t1578, t1579, t1580, t1581, t1582, 
            t1583, t1584, t1585, t1586, t1587, t1588, t1589, t1590, 
            t1591, t1592, t1593, t1594, t1595, t1596, t1597, t1598, 
            t1599, t1600, t1601, t1602, t1603, t1604, t1605, t1606, 
            t1607, t1608, t1609, t1610, t1611, t1612, t1613, t1614, 
            t1615, t1616, t1617, t1618, t1619, t1620, t1621, t1622, 
            t1623, t1624, t1625, t1626, t1627, t1628, t1629, t1630, 
            t1631, t1632, t1633, t1634, t1635, t1636, t1637, t1638, 
            t1639, t1640, t1641, t1642, t1643, t1644, t1645, t1646, 
            t1647, t1648, t1649, t1650, t1651, t1652, t1653, t1654, 
            t1655, t1656, t1657, t1658, t1659, t1660, t1661, t1662, 
            t1663, t1664, t1665, t1666, t1667, t1668, t1669, t1670, 
            t1671, t1672, t1673, t1674, t1675, t1676, t1677, t1678, 
            t1679, t1680, t1681, t1682, t1683, t1684, t1685, t1686, 
            t1687, t1688, t1689, t1690, t1691, t1692, t1693, t1694, 
            t1695, t1696, t1697, t1698, t1699, t1700, t1701, t1702, 
            t1703, t1704, t1705, t1706, t1707, t1708, t1709, t1710, 
            t1711, t1712, t1713, t1714, t1715, t1716, t1717, t1718, 
            t1719, t1720, t1721, t1722, t1723, t1724, t1725, t1726, 
            t1727, t1728, t1729, t1730, t1731, t1732, t1733, t1734, 
            t1735, t1736, t1737, t1738, t1739, t1740, t1741, t1742, 
            t1743, t1744, t1745, t1746, t1747, t1748, t1749, t1750, 
            t1751, t1752, t1753, t1754, t1755, t1756, t1757, t1758, 
            t1759, t1760, t1761, t1762, t1763, t1764, t1765, t1766, 
            t1767, t1768, t1769, t1770, t1771, t1772, t1773, t1774, 
            t1775, t1776, t1777, t1778, t1779, t1780, t1781, t1782, 
            t1783, t1784, t1785, t1786, t1787, t1788, t1789, t1790, 
            t1791, t1792, t1793, t1794, t1795, t1796, t1797, t1798, 
            t1799, t1800, t1801, t1802, t1803, t1804, t1805, t1806, 
            t1807, t1808, t1809, t1810, t1811, t1812, t1813, t1814, 
            t1815, t1816, t1817, t1818, t1819, t1820, t1821, t1822, 
            t1823, t1824, t1825, t1826, t1827, t1828, t1829, t1830, 
            t1831, t1832, t1833, t1834, t1835, t1836, t1837, t1838, 
            t1839, t1840, t1841, t1842;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s1347 = svld2_f64(pg1, (X + ((2)*(j1))));
        s1348 = s1347.v0;
        s1349 = s1347.v1;
        s1350 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s1351 = s1350.v0;
        s1352 = s1350.v1;
        s1353 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s1354 = s1353.v0;
        s1355 = s1353.v1;
        s1356 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s1357 = s1356.v0;
        s1358 = s1356.v1;
        s1359 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s1360 = s1359.v0;
        s1361 = s1359.v1;
        s1362 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s1363 = s1362.v0;
        s1364 = s1362.v1;
        s1365 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s1366 = s1365.v0;
        s1367 = s1365.v1;
        s1368 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s1369 = s1368.v0;
        s1370 = s1368.v1;
        s1371 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s1372 = s1371.v0;
        s1373 = s1371.v1;
        s1374 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s1375 = s1374.v0;
        s1376 = s1374.v1;
        s1377 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s1378 = s1377.v0;
        s1379 = s1377.v1;
        s1380 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s1381 = s1380.v0;
        s1382 = s1380.v1;
        s1383 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s1384 = s1383.v0;
        s1385 = s1383.v1;
        s1386 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s1387 = s1386.v0;
        s1388 = s1386.v1;
        s1389 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s1390 = s1389.v0;
        s1391 = s1389.v1;
        s1392 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s1393 = s1392.v0;
        s1394 = s1392.v1;
        s1395 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s1396 = s1395.v0;
        s1397 = s1395.v1;
        s1398 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s1399 = s1398.v0;
        s1400 = s1398.v1;
        s1401 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s1402 = s1401.v0;
        s1403 = s1401.v1;
        s1404 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s1405 = s1404.v0;
        s1406 = s1404.v1;
        s1407 = svld2_f64(pg1, (X + ((2)*((j1 + ((20)*(l1)))))));
        s1408 = s1407.v0;
        s1409 = s1407.v1;
        s1410 = svld2_f64(pg1, (X + ((2)*((j1 + ((21)*(l1)))))));
        s1411 = s1410.v0;
        s1412 = s1410.v1;
        s1413 = svld2_f64(pg1, (X + ((2)*((j1 + ((22)*(l1)))))));
        s1414 = s1413.v0;
        s1415 = s1413.v1;
        s1416 = svld2_f64(pg1, (X + ((2)*((j1 + ((23)*(l1)))))));
        s1417 = s1416.v0;
        s1418 = s1416.v1;
        s1419 = svld2_f64(pg1, (X + ((2)*((j1 + ((24)*(l1)))))));
        s1420 = s1419.v0;
        s1421 = s1419.v1;
        t1553 = svadd_f64_x(pg1, s1363, s1408);
        t1554 = svadd_f64_x(pg1, s1364, s1409);
        t1555 = svsub_f64_x(pg1, s1363, s1408);
        t1556 = svsub_f64_x(pg1, s1364, s1409);
        t1557 = svadd_f64_x(pg1, s1378, s1393);
        t1558 = svadd_f64_x(pg1, s1379, s1394);
        t1559 = svsub_f64_x(pg1, s1378, s1393);
        t1560 = svsub_f64_x(pg1, s1379, s1394);
        t1561 = svadd_f64_x(pg1, t1553, t1557);
        t1562 = svadd_f64_x(pg1, t1554, t1558);
        t1563 = svadd_f64_x(pg1, t1555, t1560);
        t1564 = svsub_f64_x(pg1, t1556, t1559);
        t1565 = svsub_f64_x(pg1, t1555, t1560);
        t1566 = svadd_f64_x(pg1, t1556, t1559);
        t1567 = svadd_f64_x(pg1, s1348, t1561);
        t1568 = svadd_f64_x(pg1, s1349, t1562);
        t1569 = svmls_n_f64_x(pg1, s1348, t1561, 0.25);
        t1570 = svmls_n_f64_x(pg1, s1349, t1562, 0.25);
        s1630 = svmla_n_f64_x(pg1, t1563, t1564, 1.6180339887498947);
        s1422 = svmul_n_f64_x(pg1, s1630, 0.29389262614623657);
        s1631 = svmls_n_f64_x(pg1, t1564, t1563, 1.6180339887498947);
        s1423 = svmul_n_f64_x(pg1, s1631, 0.29389262614623657);
        s1424 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1553, t1557), 0.55901699437494745);
        s1425 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1554, t1558), 0.55901699437494745);
        s1632 = svmls_n_f64_x(pg1, t1566, t1565, 0.61803398874989479);
        s1426 = svmul_n_f64_x(pg1, s1632, 0.47552825814757682);
        s1633 = svmla_n_f64_x(pg1, t1565, t1566, 0.61803398874989479);
        s1427 = svmul_n_f64_x(pg1, s1633, 0.47552825814757682);
        s1428 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1568, D11[1]), t1567, D11[0]);
        s1429 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1568, D11[0]), t1567, D11[1]);
        t1571 = svadd_f64_x(pg1, t1569, s1424);
        t1572 = svadd_f64_x(pg1, t1570, s1425);
        t1573 = svsub_f64_x(pg1, t1569, s1424);
        t1574 = svsub_f64_x(pg1, t1570, s1425);
        t1575 = svadd_f64_x(pg1, s1422, s1426);
        t1576 = svsub_f64_x(pg1, s1423, s1427);
        t1577 = svsub_f64_x(pg1, s1422, s1426);
        t1578 = svadd_f64_x(pg1, s1423, s1427);
        t1579 = svadd_f64_x(pg1, t1571, t1575);
        t1580 = svadd_f64_x(pg1, t1572, t1576);
        t1581 = svsub_f64_x(pg1, t1571, t1575);
        t1582 = svsub_f64_x(pg1, t1572, t1576);
        s1430 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1580, D12[1]), t1579, D12[0]);
        s1431 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1580, D12[0]), t1579, D12[1]);
        s1432 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1582, D12[3]), t1581, D12[2]);
        s1433 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1582, D12[2]), t1581, D12[3]);
        t1583 = svadd_f64_x(pg1, t1573, t1578);
        t1584 = svsub_f64_x(pg1, t1574, t1577);
        t1585 = svsub_f64_x(pg1, t1573, t1578);
        t1586 = svadd_f64_x(pg1, t1574, t1577);
        s1434 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1584, D12[5]), t1583, D12[4]);
        s1435 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1584, D12[4]), t1583, D12[5]);
        s1436 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1586, D12[7]), t1585, D12[6]);
        s1437 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1586, D12[6]), t1585, D12[7]);
        t1587 = svadd_f64_x(pg1, s1366, s1411);
        t1588 = svadd_f64_x(pg1, s1367, s1412);
        t1589 = svsub_f64_x(pg1, s1366, s1411);
        t1590 = svsub_f64_x(pg1, s1367, s1412);
        t1591 = svadd_f64_x(pg1, s1381, s1396);
        t1592 = svadd_f64_x(pg1, s1382, s1397);
        t1593 = svsub_f64_x(pg1, s1381, s1396);
        t1594 = svsub_f64_x(pg1, s1382, s1397);
        t1595 = svadd_f64_x(pg1, t1587, t1591);
        t1596 = svadd_f64_x(pg1, t1588, t1592);
        t1597 = svadd_f64_x(pg1, t1589, t1594);
        t1598 = svsub_f64_x(pg1, t1590, t1593);
        t1599 = svsub_f64_x(pg1, t1589, t1594);
        t1600 = svadd_f64_x(pg1, t1590, t1593);
        t1601 = svadd_f64_x(pg1, s1351, t1595);
        t1602 = svadd_f64_x(pg1, s1352, t1596);
        t1603 = svmls_n_f64_x(pg1, s1351, t1595, 0.25);
        t1604 = svmls_n_f64_x(pg1, s1352, t1596, 0.25);
        s1634 = svmla_n_f64_x(pg1, t1597, t1598, 1.6180339887498947);
        s1438 = svmul_n_f64_x(pg1, s1634, 0.29389262614623657);
        s1635 = svmls_n_f64_x(pg1, t1598, t1597, 1.6180339887498947);
        s1439 = svmul_n_f64_x(pg1, s1635, 0.29389262614623657);
        s1440 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1587, t1591), 0.55901699437494745);
        s1441 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1588, t1592), 0.55901699437494745);
        s1636 = svmls_n_f64_x(pg1, t1600, t1599, 0.61803398874989479);
        s1442 = svmul_n_f64_x(pg1, s1636, 0.47552825814757682);
        s1637 = svmla_n_f64_x(pg1, t1599, t1600, 0.61803398874989479);
        s1443 = svmul_n_f64_x(pg1, s1637, 0.47552825814757682);
        s1444 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1602, D11[3]), t1601, D11[2]);
        s1445 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1602, D11[2]), t1601, D11[3]);
        t1605 = svadd_f64_x(pg1, t1603, s1440);
        t1606 = svadd_f64_x(pg1, t1604, s1441);
        t1607 = svsub_f64_x(pg1, t1603, s1440);
        t1608 = svsub_f64_x(pg1, t1604, s1441);
        t1609 = svadd_f64_x(pg1, s1438, s1442);
        t1610 = svsub_f64_x(pg1, s1439, s1443);
        t1611 = svsub_f64_x(pg1, s1438, s1442);
        t1612 = svadd_f64_x(pg1, s1439, s1443);
        t1613 = svadd_f64_x(pg1, t1605, t1609);
        t1614 = svadd_f64_x(pg1, t1606, t1610);
        t1615 = svsub_f64_x(pg1, t1605, t1609);
        t1616 = svsub_f64_x(pg1, t1606, t1610);
        s1446 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1614, D12[9]), t1613, D12[8]);
        s1447 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1614, D12[8]), t1613, D12[9]);
        s1448 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1616, D12[11]), t1615, D12[10]);
        s1449 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1616, D12[10]), t1615, D12[11]);
        t1617 = svadd_f64_x(pg1, t1607, t1612);
        t1618 = svsub_f64_x(pg1, t1608, t1611);
        t1619 = svsub_f64_x(pg1, t1607, t1612);
        t1620 = svadd_f64_x(pg1, t1608, t1611);
        s1450 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1618, D12[13]), t1617, D12[12]);
        s1451 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1618, D12[12]), t1617, D12[13]);
        s1452 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1620, D12[15]), t1619, D12[14]);
        s1453 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1620, D12[14]), t1619, D12[15]);
        t1621 = svadd_f64_x(pg1, s1369, s1414);
        t1622 = svadd_f64_x(pg1, s1370, s1415);
        t1623 = svsub_f64_x(pg1, s1369, s1414);
        t1624 = svsub_f64_x(pg1, s1370, s1415);
        t1625 = svadd_f64_x(pg1, s1384, s1399);
        t1626 = svadd_f64_x(pg1, s1385, s1400);
        t1627 = svsub_f64_x(pg1, s1384, s1399);
        t1628 = svsub_f64_x(pg1, s1385, s1400);
        t1629 = svadd_f64_x(pg1, t1621, t1625);
        t1630 = svadd_f64_x(pg1, t1622, t1626);
        t1631 = svadd_f64_x(pg1, t1623, t1628);
        t1632 = svsub_f64_x(pg1, t1624, t1627);
        t1633 = svsub_f64_x(pg1, t1623, t1628);
        t1634 = svadd_f64_x(pg1, t1624, t1627);
        t1635 = svadd_f64_x(pg1, s1354, t1629);
        t1636 = svadd_f64_x(pg1, s1355, t1630);
        t1637 = svmls_n_f64_x(pg1, s1354, t1629, 0.25);
        t1638 = svmls_n_f64_x(pg1, s1355, t1630, 0.25);
        s1638 = svmla_n_f64_x(pg1, t1631, t1632, 1.6180339887498947);
        s1454 = svmul_n_f64_x(pg1, s1638, 0.29389262614623657);
        s1639 = svmls_n_f64_x(pg1, t1632, t1631, 1.6180339887498947);
        s1455 = svmul_n_f64_x(pg1, s1639, 0.29389262614623657);
        s1456 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1621, t1625), 0.55901699437494745);
        s1457 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1622, t1626), 0.55901699437494745);
        s1640 = svmls_n_f64_x(pg1, t1634, t1633, 0.61803398874989479);
        s1458 = svmul_n_f64_x(pg1, s1640, 0.47552825814757682);
        s1641 = svmla_n_f64_x(pg1, t1633, t1634, 0.61803398874989479);
        s1459 = svmul_n_f64_x(pg1, s1641, 0.47552825814757682);
        s1460 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1636, D11[5]), t1635, D11[4]);
        s1461 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1636, D11[4]), t1635, D11[5]);
        t1639 = svadd_f64_x(pg1, t1637, s1456);
        t1640 = svadd_f64_x(pg1, t1638, s1457);
        t1641 = svsub_f64_x(pg1, t1637, s1456);
        t1642 = svsub_f64_x(pg1, t1638, s1457);
        t1643 = svadd_f64_x(pg1, s1454, s1458);
        t1644 = svsub_f64_x(pg1, s1455, s1459);
        t1645 = svsub_f64_x(pg1, s1454, s1458);
        t1646 = svadd_f64_x(pg1, s1455, s1459);
        t1647 = svadd_f64_x(pg1, t1639, t1643);
        t1648 = svadd_f64_x(pg1, t1640, t1644);
        t1649 = svsub_f64_x(pg1, t1639, t1643);
        t1650 = svsub_f64_x(pg1, t1640, t1644);
        s1462 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1648, D12[17]), t1647, D12[16]);
        s1463 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1648, D12[16]), t1647, D12[17]);
        s1464 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1650, D12[19]), t1649, D12[18]);
        s1465 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1650, D12[18]), t1649, D12[19]);
        t1651 = svadd_f64_x(pg1, t1641, t1646);
        t1652 = svsub_f64_x(pg1, t1642, t1645);
        t1653 = svsub_f64_x(pg1, t1641, t1646);
        t1654 = svadd_f64_x(pg1, t1642, t1645);
        s1466 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1652, D12[21]), t1651, D12[20]);
        s1467 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1652, D12[20]), t1651, D12[21]);
        s1468 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1654, D12[23]), t1653, D12[22]);
        s1469 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1654, D12[22]), t1653, D12[23]);
        t1655 = svadd_f64_x(pg1, s1372, s1417);
        t1656 = svadd_f64_x(pg1, s1373, s1418);
        t1657 = svsub_f64_x(pg1, s1372, s1417);
        t1658 = svsub_f64_x(pg1, s1373, s1418);
        t1659 = svadd_f64_x(pg1, s1387, s1402);
        t1660 = svadd_f64_x(pg1, s1388, s1403);
        t1661 = svsub_f64_x(pg1, s1387, s1402);
        t1662 = svsub_f64_x(pg1, s1388, s1403);
        t1663 = svadd_f64_x(pg1, t1655, t1659);
        t1664 = svadd_f64_x(pg1, t1656, t1660);
        t1665 = svadd_f64_x(pg1, t1657, t1662);
        t1666 = svsub_f64_x(pg1, t1658, t1661);
        t1667 = svsub_f64_x(pg1, t1657, t1662);
        t1668 = svadd_f64_x(pg1, t1658, t1661);
        t1669 = svadd_f64_x(pg1, s1357, t1663);
        t1670 = svadd_f64_x(pg1, s1358, t1664);
        t1671 = svmls_n_f64_x(pg1, s1357, t1663, 0.25);
        t1672 = svmls_n_f64_x(pg1, s1358, t1664, 0.25);
        s1642 = svmla_n_f64_x(pg1, t1665, t1666, 1.6180339887498947);
        s1470 = svmul_n_f64_x(pg1, s1642, 0.29389262614623657);
        s1643 = svmls_n_f64_x(pg1, t1666, t1665, 1.6180339887498947);
        s1471 = svmul_n_f64_x(pg1, s1643, 0.29389262614623657);
        s1472 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1655, t1659), 0.55901699437494745);
        s1473 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1656, t1660), 0.55901699437494745);
        s1644 = svmls_n_f64_x(pg1, t1668, t1667, 0.61803398874989479);
        s1474 = svmul_n_f64_x(pg1, s1644, 0.47552825814757682);
        s1645 = svmla_n_f64_x(pg1, t1667, t1668, 0.61803398874989479);
        s1475 = svmul_n_f64_x(pg1, s1645, 0.47552825814757682);
        s1476 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1670, D11[7]), t1669, D11[6]);
        s1477 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1670, D11[6]), t1669, D11[7]);
        t1673 = svadd_f64_x(pg1, t1671, s1472);
        t1674 = svadd_f64_x(pg1, t1672, s1473);
        t1675 = svsub_f64_x(pg1, t1671, s1472);
        t1676 = svsub_f64_x(pg1, t1672, s1473);
        t1677 = svadd_f64_x(pg1, s1470, s1474);
        t1678 = svsub_f64_x(pg1, s1471, s1475);
        t1679 = svsub_f64_x(pg1, s1470, s1474);
        t1680 = svadd_f64_x(pg1, s1471, s1475);
        t1681 = svadd_f64_x(pg1, t1673, t1677);
        t1682 = svadd_f64_x(pg1, t1674, t1678);
        t1683 = svsub_f64_x(pg1, t1673, t1677);
        t1684 = svsub_f64_x(pg1, t1674, t1678);
        s1478 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1682, D12[25]), t1681, D12[24]);
        s1479 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1682, D12[24]), t1681, D12[25]);
        s1480 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1684, D12[27]), t1683, D12[26]);
        s1481 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1684, D12[26]), t1683, D12[27]);
        t1685 = svadd_f64_x(pg1, t1675, t1680);
        t1686 = svsub_f64_x(pg1, t1676, t1679);
        t1687 = svsub_f64_x(pg1, t1675, t1680);
        t1688 = svadd_f64_x(pg1, t1676, t1679);
        s1482 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1686, D12[29]), t1685, D12[28]);
        s1483 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1686, D12[28]), t1685, D12[29]);
        s1484 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1688, D12[31]), t1687, D12[30]);
        s1485 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1688, D12[30]), t1687, D12[31]);
        t1689 = svadd_f64_x(pg1, s1375, s1420);
        t1690 = svadd_f64_x(pg1, s1376, s1421);
        t1691 = svsub_f64_x(pg1, s1375, s1420);
        t1692 = svsub_f64_x(pg1, s1376, s1421);
        t1693 = svadd_f64_x(pg1, s1390, s1405);
        t1694 = svadd_f64_x(pg1, s1391, s1406);
        t1695 = svsub_f64_x(pg1, s1390, s1405);
        t1696 = svsub_f64_x(pg1, s1391, s1406);
        t1697 = svadd_f64_x(pg1, t1689, t1693);
        t1698 = svadd_f64_x(pg1, t1690, t1694);
        t1699 = svadd_f64_x(pg1, t1691, t1696);
        t1700 = svsub_f64_x(pg1, t1692, t1695);
        t1701 = svsub_f64_x(pg1, t1691, t1696);
        t1702 = svadd_f64_x(pg1, t1692, t1695);
        t1703 = svadd_f64_x(pg1, s1360, t1697);
        t1704 = svadd_f64_x(pg1, s1361, t1698);
        t1705 = svmls_n_f64_x(pg1, s1360, t1697, 0.25);
        t1706 = svmls_n_f64_x(pg1, s1361, t1698, 0.25);
        s1646 = svmla_n_f64_x(pg1, t1699, t1700, 1.6180339887498947);
        s1486 = svmul_n_f64_x(pg1, s1646, 0.29389262614623657);
        s1647 = svmls_n_f64_x(pg1, t1700, t1699, 1.6180339887498947);
        s1487 = svmul_n_f64_x(pg1, s1647, 0.29389262614623657);
        s1488 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1689, t1693), 0.55901699437494745);
        s1489 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1690, t1694), 0.55901699437494745);
        s1648 = svmls_n_f64_x(pg1, t1702, t1701, 0.61803398874989479);
        s1490 = svmul_n_f64_x(pg1, s1648, 0.47552825814757682);
        s1649 = svmla_n_f64_x(pg1, t1701, t1702, 0.61803398874989479);
        s1491 = svmul_n_f64_x(pg1, s1649, 0.47552825814757682);
        s1492 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1704, D11[9]), t1703, D11[8]);
        s1493 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1704, D11[8]), t1703, D11[9]);
        t1707 = svadd_f64_x(pg1, t1705, s1488);
        t1708 = svadd_f64_x(pg1, t1706, s1489);
        t1709 = svsub_f64_x(pg1, t1705, s1488);
        t1710 = svsub_f64_x(pg1, t1706, s1489);
        t1711 = svadd_f64_x(pg1, s1486, s1490);
        t1712 = svsub_f64_x(pg1, s1487, s1491);
        t1713 = svsub_f64_x(pg1, s1486, s1490);
        t1714 = svadd_f64_x(pg1, s1487, s1491);
        t1715 = svadd_f64_x(pg1, t1707, t1711);
        t1716 = svadd_f64_x(pg1, t1708, t1712);
        t1717 = svsub_f64_x(pg1, t1707, t1711);
        t1718 = svsub_f64_x(pg1, t1708, t1712);
        s1494 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1716, D12[33]), t1715, D12[32]);
        s1495 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1716, D12[32]), t1715, D12[33]);
        s1496 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1718, D12[35]), t1717, D12[34]);
        s1497 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1718, D12[34]), t1717, D12[35]);
        t1719 = svadd_f64_x(pg1, t1709, t1714);
        t1720 = svsub_f64_x(pg1, t1710, t1713);
        t1721 = svsub_f64_x(pg1, t1709, t1714);
        t1722 = svadd_f64_x(pg1, t1710, t1713);
        s1498 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1720, D12[37]), t1719, D12[36]);
        s1499 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1720, D12[36]), t1719, D12[37]);
        s1500 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1722, D12[39]), t1721, D12[38]);
        s1501 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1722, D12[38]), t1721, D12[39]);
        t1723 = svadd_f64_x(pg1, s1444, s1492);
        t1724 = svadd_f64_x(pg1, s1445, s1493);
        t1725 = svsub_f64_x(pg1, s1444, s1492);
        t1726 = svsub_f64_x(pg1, s1445, s1493);
        t1727 = svadd_f64_x(pg1, s1460, s1476);
        t1728 = svadd_f64_x(pg1, s1461, s1477);
        t1729 = svsub_f64_x(pg1, s1460, s1476);
        t1730 = svsub_f64_x(pg1, s1461, s1477);
        t1731 = svadd_f64_x(pg1, t1723, t1727);
        t1732 = svadd_f64_x(pg1, t1724, t1728);
        t1733 = svadd_f64_x(pg1, t1725, t1730);
        t1734 = svsub_f64_x(pg1, t1726, t1729);
        t1735 = svsub_f64_x(pg1, t1725, t1730);
        t1736 = svadd_f64_x(pg1, t1726, t1729);
        t1737 = svmls_n_f64_x(pg1, s1428, t1731, 0.25);
        t1738 = svmls_n_f64_x(pg1, s1429, t1732, 0.25);
        s1650 = svmla_n_f64_x(pg1, t1733, t1734, 1.6180339887498947);
        s1502 = svmul_n_f64_x(pg1, s1650, 0.29389262614623657);
        s1651 = svmls_n_f64_x(pg1, t1734, t1733, 1.6180339887498947);
        s1503 = svmul_n_f64_x(pg1, s1651, 0.29389262614623657);
        s1504 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1723, t1727), 0.55901699437494745);
        s1505 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1724, t1728), 0.55901699437494745);
        s1652 = svmls_n_f64_x(pg1, t1736, t1735, 0.61803398874989479);
        s1506 = svmul_n_f64_x(pg1, s1652, 0.47552825814757682);
        s1653 = svmla_n_f64_x(pg1, t1735, t1736, 0.61803398874989479);
        s1507 = svmul_n_f64_x(pg1, s1653, 0.47552825814757682);
        s1508 = svadd_f64_x(pg1, s1428, t1731);
        s1509 = svadd_f64_x(pg1, s1429, t1732);
        t1739 = svadd_f64_x(pg1, t1737, s1504);
        t1740 = svadd_f64_x(pg1, t1738, s1505);
        t1741 = svsub_f64_x(pg1, t1737, s1504);
        t1742 = svsub_f64_x(pg1, t1738, s1505);
        t1743 = svadd_f64_x(pg1, s1502, s1506);
        t1744 = svsub_f64_x(pg1, s1503, s1507);
        t1745 = svsub_f64_x(pg1, s1502, s1506);
        t1746 = svadd_f64_x(pg1, s1503, s1507);
        s1510 = svadd_f64_x(pg1, t1739, t1743);
        s1511 = svadd_f64_x(pg1, t1740, t1744);
        s1512 = svsub_f64_x(pg1, t1739, t1743);
        s1513 = svsub_f64_x(pg1, t1740, t1744);
        s1514 = svadd_f64_x(pg1, t1741, t1746);
        s1515 = svsub_f64_x(pg1, t1742, t1745);
        s1516 = svsub_f64_x(pg1, t1741, t1746);
        s1517 = svadd_f64_x(pg1, t1742, t1745);
        t1747 = svadd_f64_x(pg1, s1446, s1494);
        t1748 = svadd_f64_x(pg1, s1447, s1495);
        t1749 = svsub_f64_x(pg1, s1446, s1494);
        t1750 = svsub_f64_x(pg1, s1447, s1495);
        t1751 = svadd_f64_x(pg1, s1462, s1478);
        t1752 = svadd_f64_x(pg1, s1463, s1479);
        t1753 = svsub_f64_x(pg1, s1462, s1478);
        t1754 = svsub_f64_x(pg1, s1463, s1479);
        t1755 = svadd_f64_x(pg1, t1747, t1751);
        t1756 = svadd_f64_x(pg1, t1748, t1752);
        t1757 = svadd_f64_x(pg1, t1749, t1754);
        t1758 = svsub_f64_x(pg1, t1750, t1753);
        t1759 = svsub_f64_x(pg1, t1749, t1754);
        t1760 = svadd_f64_x(pg1, t1750, t1753);
        t1761 = svmls_n_f64_x(pg1, s1430, t1755, 0.25);
        t1762 = svmls_n_f64_x(pg1, s1431, t1756, 0.25);
        s1654 = svmla_n_f64_x(pg1, t1757, t1758, 1.6180339887498947);
        s1518 = svmul_n_f64_x(pg1, s1654, 0.29389262614623657);
        s1655 = svmls_n_f64_x(pg1, t1758, t1757, 1.6180339887498947);
        s1519 = svmul_n_f64_x(pg1, s1655, 0.29389262614623657);
        s1520 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1747, t1751), 0.55901699437494745);
        s1521 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1748, t1752), 0.55901699437494745);
        s1656 = svmls_n_f64_x(pg1, t1760, t1759, 0.61803398874989479);
        s1522 = svmul_n_f64_x(pg1, s1656, 0.47552825814757682);
        s1657 = svmla_n_f64_x(pg1, t1759, t1760, 0.61803398874989479);
        s1523 = svmul_n_f64_x(pg1, s1657, 0.47552825814757682);
        s1524 = svadd_f64_x(pg1, s1430, t1755);
        s1525 = svadd_f64_x(pg1, s1431, t1756);
        t1763 = svadd_f64_x(pg1, t1761, s1520);
        t1764 = svadd_f64_x(pg1, t1762, s1521);
        t1765 = svsub_f64_x(pg1, t1761, s1520);
        t1766 = svsub_f64_x(pg1, t1762, s1521);
        t1767 = svadd_f64_x(pg1, s1518, s1522);
        t1768 = svsub_f64_x(pg1, s1519, s1523);
        t1769 = svsub_f64_x(pg1, s1518, s1522);
        t1770 = svadd_f64_x(pg1, s1519, s1523);
        s1526 = svadd_f64_x(pg1, t1763, t1767);
        s1527 = svadd_f64_x(pg1, t1764, t1768);
        s1528 = svsub_f64_x(pg1, t1763, t1767);
        s1529 = svsub_f64_x(pg1, t1764, t1768);
        s1530 = svadd_f64_x(pg1, t1765, t1770);
        s1531 = svsub_f64_x(pg1, t1766, t1769);
        s1532 = svsub_f64_x(pg1, t1765, t1770);
        s1533 = svadd_f64_x(pg1, t1766, t1769);
        t1771 = svadd_f64_x(pg1, s1450, s1498);
        t1772 = svadd_f64_x(pg1, s1451, s1499);
        t1773 = svsub_f64_x(pg1, s1450, s1498);
        t1774 = svsub_f64_x(pg1, s1451, s1499);
        t1775 = svadd_f64_x(pg1, s1466, s1482);
        t1776 = svadd_f64_x(pg1, s1467, s1483);
        t1777 = svsub_f64_x(pg1, s1466, s1482);
        t1778 = svsub_f64_x(pg1, s1467, s1483);
        t1779 = svadd_f64_x(pg1, t1771, t1775);
        t1780 = svadd_f64_x(pg1, t1772, t1776);
        t1781 = svadd_f64_x(pg1, t1773, t1778);
        t1782 = svsub_f64_x(pg1, t1774, t1777);
        t1783 = svsub_f64_x(pg1, t1773, t1778);
        t1784 = svadd_f64_x(pg1, t1774, t1777);
        t1785 = svmls_n_f64_x(pg1, s1434, t1779, 0.25);
        t1786 = svmls_n_f64_x(pg1, s1435, t1780, 0.25);
        s1658 = svmla_n_f64_x(pg1, t1781, t1782, 1.6180339887498947);
        s1534 = svmul_n_f64_x(pg1, s1658, 0.29389262614623657);
        s1659 = svmls_n_f64_x(pg1, t1782, t1781, 1.6180339887498947);
        s1535 = svmul_n_f64_x(pg1, s1659, 0.29389262614623657);
        s1536 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1771, t1775), 0.55901699437494745);
        s1537 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1772, t1776), 0.55901699437494745);
        s1660 = svmls_n_f64_x(pg1, t1784, t1783, 0.61803398874989479);
        s1538 = svmul_n_f64_x(pg1, s1660, 0.47552825814757682);
        s1661 = svmla_n_f64_x(pg1, t1783, t1784, 0.61803398874989479);
        s1539 = svmul_n_f64_x(pg1, s1661, 0.47552825814757682);
        s1540 = svadd_f64_x(pg1, s1434, t1779);
        s1541 = svadd_f64_x(pg1, s1435, t1780);
        t1787 = svadd_f64_x(pg1, t1785, s1536);
        t1788 = svadd_f64_x(pg1, t1786, s1537);
        t1789 = svsub_f64_x(pg1, t1785, s1536);
        t1790 = svsub_f64_x(pg1, t1786, s1537);
        t1791 = svadd_f64_x(pg1, s1534, s1538);
        t1792 = svsub_f64_x(pg1, s1535, s1539);
        t1793 = svsub_f64_x(pg1, s1534, s1538);
        t1794 = svadd_f64_x(pg1, s1535, s1539);
        s1542 = svadd_f64_x(pg1, t1787, t1791);
        s1543 = svadd_f64_x(pg1, t1788, t1792);
        s1544 = svsub_f64_x(pg1, t1787, t1791);
        s1545 = svsub_f64_x(pg1, t1788, t1792);
        s1546 = svadd_f64_x(pg1, t1789, t1794);
        s1547 = svsub_f64_x(pg1, t1790, t1793);
        s1548 = svsub_f64_x(pg1, t1789, t1794);
        s1549 = svadd_f64_x(pg1, t1790, t1793);
        t1795 = svadd_f64_x(pg1, s1452, s1500);
        t1796 = svadd_f64_x(pg1, s1453, s1501);
        t1797 = svsub_f64_x(pg1, s1452, s1500);
        t1798 = svsub_f64_x(pg1, s1453, s1501);
        t1799 = svadd_f64_x(pg1, s1468, s1484);
        t1800 = svadd_f64_x(pg1, s1469, s1485);
        t1801 = svsub_f64_x(pg1, s1468, s1484);
        t1802 = svsub_f64_x(pg1, s1469, s1485);
        t1803 = svadd_f64_x(pg1, t1795, t1799);
        t1804 = svadd_f64_x(pg1, t1796, t1800);
        t1805 = svadd_f64_x(pg1, t1797, t1802);
        t1806 = svsub_f64_x(pg1, t1798, t1801);
        t1807 = svsub_f64_x(pg1, t1797, t1802);
        t1808 = svadd_f64_x(pg1, t1798, t1801);
        t1809 = svmls_n_f64_x(pg1, s1436, t1803, 0.25);
        t1810 = svmls_n_f64_x(pg1, s1437, t1804, 0.25);
        s1662 = svmla_n_f64_x(pg1, t1805, t1806, 1.6180339887498947);
        s1550 = svmul_n_f64_x(pg1, s1662, 0.29389262614623657);
        s1663 = svmls_n_f64_x(pg1, t1806, t1805, 1.6180339887498947);
        s1551 = svmul_n_f64_x(pg1, s1663, 0.29389262614623657);
        s1552 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1795, t1799), 0.55901699437494745);
        s1553 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1796, t1800), 0.55901699437494745);
        s1664 = svmls_n_f64_x(pg1, t1808, t1807, 0.61803398874989479);
        s1554 = svmul_n_f64_x(pg1, s1664, 0.47552825814757682);
        s1665 = svmla_n_f64_x(pg1, t1807, t1808, 0.61803398874989479);
        s1555 = svmul_n_f64_x(pg1, s1665, 0.47552825814757682);
        s1556 = svadd_f64_x(pg1, s1436, t1803);
        s1557 = svadd_f64_x(pg1, s1437, t1804);
        t1811 = svadd_f64_x(pg1, t1809, s1552);
        t1812 = svadd_f64_x(pg1, t1810, s1553);
        t1813 = svsub_f64_x(pg1, t1809, s1552);
        t1814 = svsub_f64_x(pg1, t1810, s1553);
        t1815 = svadd_f64_x(pg1, s1550, s1554);
        t1816 = svsub_f64_x(pg1, s1551, s1555);
        t1817 = svsub_f64_x(pg1, s1550, s1554);
        t1818 = svadd_f64_x(pg1, s1551, s1555);
        s1558 = svadd_f64_x(pg1, t1811, t1815);
        s1559 = svadd_f64_x(pg1, t1812, t1816);
        s1560 = svsub_f64_x(pg1, t1811, t1815);
        s1561 = svsub_f64_x(pg1, t1812, t1816);
        s1562 = svadd_f64_x(pg1, t1813, t1818);
        s1563 = svsub_f64_x(pg1, t1814, t1817);
        s1564 = svsub_f64_x(pg1, t1813, t1818);
        s1565 = svadd_f64_x(pg1, t1814, t1817);
        t1819 = svadd_f64_x(pg1, s1448, s1496);
        t1820 = svadd_f64_x(pg1, s1449, s1497);
        t1821 = svsub_f64_x(pg1, s1448, s1496);
        t1822 = svsub_f64_x(pg1, s1449, s1497);
        t1823 = svadd_f64_x(pg1, s1464, s1480);
        t1824 = svadd_f64_x(pg1, s1465, s1481);
        t1825 = svsub_f64_x(pg1, s1464, s1480);
        t1826 = svsub_f64_x(pg1, s1465, s1481);
        t1827 = svadd_f64_x(pg1, t1819, t1823);
        t1828 = svadd_f64_x(pg1, t1820, t1824);
        t1829 = svadd_f64_x(pg1, t1821, t1826);
        t1830 = svsub_f64_x(pg1, t1822, t1825);
        t1831 = svsub_f64_x(pg1, t1821, t1826);
        t1832 = svadd_f64_x(pg1, t1822, t1825);
        t1833 = svmls_n_f64_x(pg1, s1432, t1827, 0.25);
        t1834 = svmls_n_f64_x(pg1, s1433, t1828, 0.25);
        s1666 = svmla_n_f64_x(pg1, t1829, t1830, 1.6180339887498947);
        s1566 = svmul_n_f64_x(pg1, s1666, 0.29389262614623657);
        s1667 = svmls_n_f64_x(pg1, t1830, t1829, 1.6180339887498947);
        s1567 = svmul_n_f64_x(pg1, s1667, 0.29389262614623657);
        s1568 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1819, t1823), 0.55901699437494745);
        s1569 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1820, t1824), 0.55901699437494745);
        s1668 = svmls_n_f64_x(pg1, t1832, t1831, 0.61803398874989479);
        s1570 = svmul_n_f64_x(pg1, s1668, 0.47552825814757682);
        s1669 = svmla_n_f64_x(pg1, t1831, t1832, 0.61803398874989479);
        s1571 = svmul_n_f64_x(pg1, s1669, 0.47552825814757682);
        s1572 = svadd_f64_x(pg1, s1432, t1827);
        s1573 = svadd_f64_x(pg1, s1433, t1828);
        t1835 = svadd_f64_x(pg1, t1833, s1568);
        t1836 = svadd_f64_x(pg1, t1834, s1569);
        t1837 = svsub_f64_x(pg1, t1833, s1568);
        t1838 = svsub_f64_x(pg1, t1834, s1569);
        t1839 = svadd_f64_x(pg1, s1566, s1570);
        t1840 = svsub_f64_x(pg1, s1567, s1571);
        t1841 = svsub_f64_x(pg1, s1566, s1570);
        t1842 = svadd_f64_x(pg1, s1567, s1571);
        s1574 = svadd_f64_x(pg1, t1835, t1839);
        s1575 = svadd_f64_x(pg1, t1836, t1840);
        s1576 = svsub_f64_x(pg1, t1835, t1839);
        s1577 = svsub_f64_x(pg1, t1836, t1840);
        s1578 = svadd_f64_x(pg1, t1837, t1842);
        s1579 = svsub_f64_x(pg1, t1838, t1841);
        s1580 = svsub_f64_x(pg1, t1837, t1842);
        s1581 = svadd_f64_x(pg1, t1838, t1841);
        a2752 = (TW1 + ((48)*(j1)));
        a2753 = svld1_gather_u64offset_f64(pg1, a2752, svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2754 = svld1_gather_u64offset_f64(pg1, (a2752 + 1), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1582 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2754, s1525), a2753, s1524);
        s1583 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2753, s1525), a2754, s1524);
        a2755 = svld1_gather_u64offset_f64(pg1, (a2752 + 2), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2756 = svld1_gather_u64offset_f64(pg1, (a2752 + 3), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1584 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2756, s1541), a2755, s1540);
        s1585 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2755, s1541), a2756, s1540);
        a2757 = svld1_gather_u64offset_f64(pg1, (a2752 + 4), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2758 = svld1_gather_u64offset_f64(pg1, (a2752 + 5), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1586 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2758, s1557), a2757, s1556);
        s1587 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2757, s1557), a2758, s1556);
        a2759 = svld1_gather_u64offset_f64(pg1, (a2752 + 6), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2760 = svld1_gather_u64offset_f64(pg1, (a2752 + 7), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1588 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2760, s1573), a2759, s1572);
        s1589 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2759, s1573), a2760, s1572);
        a2761 = svld1_gather_u64offset_f64(pg1, (a2752 + 8), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2762 = svld1_gather_u64offset_f64(pg1, (a2752 + 9), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1590 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2762, s1511), a2761, s1510);
        s1591 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2761, s1511), a2762, s1510);
        a2763 = svld1_gather_u64offset_f64(pg1, (a2752 + 10), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2764 = svld1_gather_u64offset_f64(pg1, (a2752 + 11), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1592 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2764, s1527), a2763, s1526);
        s1593 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2763, s1527), a2764, s1526);
        a2765 = svld1_gather_u64offset_f64(pg1, (a2752 + 12), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2766 = svld1_gather_u64offset_f64(pg1, (a2752 + 13), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1594 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2766, s1543), a2765, s1542);
        s1595 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2765, s1543), a2766, s1542);
        a2767 = svld1_gather_u64offset_f64(pg1, (a2752 + 14), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2768 = svld1_gather_u64offset_f64(pg1, (a2752 + 15), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1596 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2768, s1559), a2767, s1558);
        s1597 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2767, s1559), a2768, s1558);
        a2769 = svld1_gather_u64offset_f64(pg1, (a2752 + 16), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2770 = svld1_gather_u64offset_f64(pg1, (a2752 + 17), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1598 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2770, s1575), a2769, s1574);
        s1599 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2769, s1575), a2770, s1574);
        a2771 = svld1_gather_u64offset_f64(pg1, (a2752 + 18), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2772 = svld1_gather_u64offset_f64(pg1, (a2752 + 19), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1600 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2772, s1515), a2771, s1514);
        s1601 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2771, s1515), a2772, s1514);
        a2773 = svld1_gather_u64offset_f64(pg1, (a2752 + 20), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2774 = svld1_gather_u64offset_f64(pg1, (a2752 + 21), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1602 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2774, s1531), a2773, s1530);
        s1603 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2773, s1531), a2774, s1530);
        a2775 = svld1_gather_u64offset_f64(pg1, (a2752 + 22), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2776 = svld1_gather_u64offset_f64(pg1, (a2752 + 23), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1604 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2776, s1547), a2775, s1546);
        s1605 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2775, s1547), a2776, s1546);
        a2777 = svld1_gather_u64offset_f64(pg1, (a2752 + 24), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2778 = svld1_gather_u64offset_f64(pg1, (a2752 + 25), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1606 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2778, s1563), a2777, s1562);
        s1607 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2777, s1563), a2778, s1562);
        a2779 = svld1_gather_u64offset_f64(pg1, (a2752 + 26), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2780 = svld1_gather_u64offset_f64(pg1, (a2752 + 27), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1608 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2780, s1579), a2779, s1578);
        s1609 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2779, s1579), a2780, s1578);
        a2781 = svld1_gather_u64offset_f64(pg1, (a2752 + 28), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2782 = svld1_gather_u64offset_f64(pg1, (a2752 + 29), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1610 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2782, s1517), a2781, s1516);
        s1611 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2781, s1517), a2782, s1516);
        a2783 = svld1_gather_u64offset_f64(pg1, (a2752 + 30), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2784 = svld1_gather_u64offset_f64(pg1, (a2752 + 31), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1612 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2784, s1533), a2783, s1532);
        s1613 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2783, s1533), a2784, s1532);
        a2785 = svld1_gather_u64offset_f64(pg1, (a2752 + 32), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2786 = svld1_gather_u64offset_f64(pg1, (a2752 + 33), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1614 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2786, s1549), a2785, s1548);
        s1615 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2785, s1549), a2786, s1548);
        a2787 = svld1_gather_u64offset_f64(pg1, (a2752 + 34), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2788 = svld1_gather_u64offset_f64(pg1, (a2752 + 35), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1616 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2788, s1565), a2787, s1564);
        s1617 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2787, s1565), a2788, s1564);
        a2789 = svld1_gather_u64offset_f64(pg1, (a2752 + 36), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2790 = svld1_gather_u64offset_f64(pg1, (a2752 + 37), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1618 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2790, s1581), a2789, s1580);
        s1619 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2789, s1581), a2790, s1580);
        a2791 = svld1_gather_u64offset_f64(pg1, (a2752 + 38), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2792 = svld1_gather_u64offset_f64(pg1, (a2752 + 39), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1620 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2792, s1513), a2791, s1512);
        s1621 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2791, s1513), a2792, s1512);
        a2793 = svld1_gather_u64offset_f64(pg1, (a2752 + 40), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2794 = svld1_gather_u64offset_f64(pg1, (a2752 + 41), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1622 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2794, s1529), a2793, s1528);
        s1623 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2793, s1529), a2794, s1528);
        a2795 = svld1_gather_u64offset_f64(pg1, (a2752 + 42), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2796 = svld1_gather_u64offset_f64(pg1, (a2752 + 43), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1624 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2796, s1545), a2795, s1544);
        s1625 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2795, s1545), a2796, s1544);
        a2797 = svld1_gather_u64offset_f64(pg1, (a2752 + 44), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2798 = svld1_gather_u64offset_f64(pg1, (a2752 + 45), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1626 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2798, s1561), a2797, s1560);
        s1627 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2797, s1561), a2798, s1560);
        a2799 = svld1_gather_u64offset_f64(pg1, (a2752 + 46), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        a2800 = svld1_gather_u64offset_f64(pg1, (a2752 + 47), svindex_u64(0, (int64_t)(48 * sizeof(float64_t))));
        s1628 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a2800, s1577), a2799, s1576);
        s1629 = svmla_f64_x(pg1, svmul_f64_x(pg1, a2799, s1577), a2800, s1576);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1508);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1509);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1582);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1583);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1584);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1585);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1586);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1587);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1588);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1589);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1590);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1591);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1592);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1593);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1594);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1595);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1596);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1597);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1598);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1599);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1600);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1601);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1602);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1603);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1604);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1605);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1606);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1607);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1608);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1609);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1610);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1611);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1612);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1613);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1614);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1615);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1616);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1617);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1618);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1619);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(40 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1620);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(41 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1621);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(42 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1622);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(43 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1623);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(44 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1624);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(45 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1625);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(46 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1626);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(47 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1627);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(48 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1628);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(49 + Y + ((50)*(j1)))), svindex_u64(0, (int64_t)(50 * sizeof(float64_t))), s1629);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
