/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft24b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    static float64_t D68[16];
    static float64_t D69[32];
    float64_t a10275, a10276, a10277, a10278, a10279, a10280, a10281, a10282, 
            a10283, a10284, a10285, a10286, a10287, a10288, a10289, a10290, 
            a10291, a10292, a10293, a10294, a10295, a10296, a10297, a10298, 
            a10299, a10300, a10301, a10302, a10303, a10304, a10305, a10306, 
            a10307, a10308, a10309, a10310, a10311, a10312, a10313, a10314, 
            a10315, a10316, a10317, a10318, a10319, a10320;
    int a10261, a10274, j1, l1, m1;
    svfloat64x2_t s4764, s4767, s4770, s4773, s4776, s4779, s4782, s4785, 
            s4788, s4791, s4794, s4797, s4800, s4803, s4806, s4809, 
            s4812, s4815, s4818, s4821, s4824, s4827, s4830, s4833, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48;
    svfloat64_t a10262, a10263, a10264, a10265, a10266, a10267, a10268, a10269, 
            a10270, a10271, a10272, a10273, s4765, s4766, s4768, s4769, 
            s4771, s4772, s4774, s4775, s4777, s4778, s4780, s4781, 
            s4783, s4784, s4786, s4787, s4789, s4790, s4792, s4793, 
            s4795, s4796, s4798, s4799, s4801, s4802, s4804, s4805, 
            s4807, s4808, s4810, s4811, s4813, s4814, s4816, s4817, 
            s4819, s4820, s4822, s4823, s4825, s4826, s4828, s4829, 
            s4831, s4832, s4834, s4835, s4836, s4837, s4838, s4839, 
            s4840, s4841, s4842, s4843, s4844, s4845, s4846, s4847, 
            s4848, s4849, s4850, s4851, s4852, s4853, s4854, s4855, 
            s4856, s4857, s4858, s4859, s4860, s4861, s4862, s4863, 
            s4864, s4865, s4866, s4867, s4868, s4869, s4870, s4871, 
            s4872, s4873, s4874, s4875, s4876, s4877, s4878, s4879, 
            s4880, s4881, s4882, s4883, s4884, s4885, s4886, s4887, 
            s4888, s4889, s4890, s4891, s4892, s4893, s4894, s4895, 
            s4896, s4897, s4898, s4899, s4900, s4901, s4902, s4903, 
            s4904, s4905, s4906, s4907, s4908, s4909, s4910, s4911, 
            s4912, s4913, s4914, s4915, s4916, s4917, s4918, s4919, 
            s4920, s4921, s4922, s4923, s4924, s4925, s4926, s4927, 
            s4928, s4929, s4930, s4931, s4932, s4933, s4934, s4935, 
            s4936, s4937, s4938, s4939, s4940, s4941, s4942, s4943, 
            s4944, s4945, s4946, s4947, s4948, s4949, s4950, s4951, 
            s4952, s4953, s4954, s4955, s4956, s4957, t7515, t7516, 
            t7517, t7518, t7519, t7520, t7521, t7522, t7523, t7524, 
            t7525, t7526, t7527, t7528, t7529, t7530, t7531, t7532, 
            t7533, t7534, t7535, t7536, t7537, t7538, t7539, t7540, 
            t7541, t7542, t7543, t7544, t7545, t7546, t7547, t7548, 
            t7549, t7550, t7551, t7552, t7553, t7554, t7555, t7556, 
            t7557, t7558, t7559, t7560, t7561, t7562, t7563, t7564, 
            t7565, t7566, t7567, t7568, t7569, t7570, t7571, t7572, 
            t7573, t7574, t7575, t7576, t7577, t7578, t7579, t7580, 
            t7581, t7582, t7583, t7584, t7585, t7586, t7587, t7588, 
            t7589, t7590, t7591, t7592, t7593, t7594, t7595, t7596, 
            t7597, t7598, t7599, t7600, t7601, t7602, t7603, t7604, 
            t7605, t7606, t7607, t7608, t7609, t7610, t7611, t7612, 
            t7613, t7614, t7615, t7616, t7617, t7618, t7619, t7620, 
            t7621, t7622, t7623, t7624, t7625, t7626, t7627, t7628, 
            t7629, t7630, t7631, t7632, t7633, t7634, t7635, t7636, 
            t7637, t7638, t7639, t7640, t7641, t7642, t7643, t7644, 
            t7645, t7646, t7647, t7648, t7649, t7650, t7651, t7652, 
            t7653, t7654, t7655, t7656, t7657, t7658, t7659, t7660, 
            t7661, t7662, t7663, t7664, t7665, t7666, t7667, t7668, 
            t7669, t7670, t7671, t7672, t7673, t7674, t7675, t7676, 
            t7677, t7678;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a10261 = (k1 + ((j1)*(m1)));
            s4764 = svld2_f64(pg1, (X + ((2)*(a10261))));
            s4765 = s4764.v0;
            s4766 = s4764.v1;
            s4767 = svld2_f64(pg1, (X + ((2)*((a10261 + ((l1)*(m1)))))));
            s4768 = s4767.v0;
            s4769 = s4767.v1;
            s4770 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((2)*(l1)))*(m1)))))));
            s4771 = s4770.v0;
            s4772 = s4770.v1;
            s4773 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((3)*(l1)))*(m1)))))));
            s4774 = s4773.v0;
            s4775 = s4773.v1;
            s4776 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((4)*(l1)))*(m1)))))));
            s4777 = s4776.v0;
            s4778 = s4776.v1;
            s4779 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((5)*(l1)))*(m1)))))));
            s4780 = s4779.v0;
            s4781 = s4779.v1;
            s4782 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((6)*(l1)))*(m1)))))));
            s4783 = s4782.v0;
            s4784 = s4782.v1;
            s4785 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((7)*(l1)))*(m1)))))));
            s4786 = s4785.v0;
            s4787 = s4785.v1;
            s4788 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((8)*(l1)))*(m1)))))));
            s4789 = s4788.v0;
            s4790 = s4788.v1;
            s4791 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((9)*(l1)))*(m1)))))));
            s4792 = s4791.v0;
            s4793 = s4791.v1;
            s4794 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((10)*(l1)))*(m1)))))));
            s4795 = s4794.v0;
            s4796 = s4794.v1;
            s4797 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((11)*(l1)))*(m1)))))));
            s4798 = s4797.v0;
            s4799 = s4797.v1;
            s4800 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((12)*(l1)))*(m1)))))));
            s4801 = s4800.v0;
            s4802 = s4800.v1;
            s4803 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((13)*(l1)))*(m1)))))));
            s4804 = s4803.v0;
            s4805 = s4803.v1;
            s4806 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((14)*(l1)))*(m1)))))));
            s4807 = s4806.v0;
            s4808 = s4806.v1;
            s4809 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((15)*(l1)))*(m1)))))));
            s4810 = s4809.v0;
            s4811 = s4809.v1;
            s4812 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((16)*(l1)))*(m1)))))));
            s4813 = s4812.v0;
            s4814 = s4812.v1;
            s4815 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((17)*(l1)))*(m1)))))));
            s4816 = s4815.v0;
            s4817 = s4815.v1;
            s4818 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((18)*(l1)))*(m1)))))));
            s4819 = s4818.v0;
            s4820 = s4818.v1;
            s4821 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((19)*(l1)))*(m1)))))));
            s4822 = s4821.v0;
            s4823 = s4821.v1;
            s4824 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((20)*(l1)))*(m1)))))));
            s4825 = s4824.v0;
            s4826 = s4824.v1;
            s4827 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((21)*(l1)))*(m1)))))));
            s4828 = s4827.v0;
            s4829 = s4827.v1;
            s4830 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((22)*(l1)))*(m1)))))));
            s4831 = s4830.v0;
            s4832 = s4830.v1;
            s4833 = svld2_f64(pg1, (X + ((2)*((a10261 + ((((23)*(l1)))*(m1)))))));
            s4834 = s4833.v0;
            s4835 = s4833.v1;
            t7515 = svadd_f64_x(pg1, s4789, s4813);
            t7516 = svadd_f64_x(pg1, s4790, s4814);
            t7517 = svadd_f64_x(pg1, s4765, t7515);
            t7518 = svadd_f64_x(pg1, s4766, t7516);
            t7519 = svmls_n_f64_x(pg1, s4765, t7515, 0.5);
            t7520 = svmls_n_f64_x(pg1, s4766, t7516, 0.5);
            s4836 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4790, s4814), 0.8660254037844386);
            s4837 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4789, s4813), 0.8660254037844386);
            s4838 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7518, D68[1]), t7517, D68[0]);
            s4839 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7518, D68[0]), t7517, D68[1]);
            t7521 = svadd_f64_x(pg1, t7519, s4836);
            t7522 = svsub_f64_x(pg1, t7520, s4837);
            t7523 = svsub_f64_x(pg1, t7519, s4836);
            t7524 = svadd_f64_x(pg1, t7520, s4837);
            s4840 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7522, D69[1]), t7521, D69[0]);
            s4841 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7522, D69[0]), t7521, D69[1]);
            s4842 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7524, D69[3]), t7523, D69[2]);
            s4843 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7524, D69[2]), t7523, D69[3]);
            t7525 = svadd_f64_x(pg1, s4792, s4816);
            t7526 = svadd_f64_x(pg1, s4793, s4817);
            t7527 = svadd_f64_x(pg1, s4768, t7525);
            t7528 = svadd_f64_x(pg1, s4769, t7526);
            t7529 = svmls_n_f64_x(pg1, s4768, t7525, 0.5);
            t7530 = svmls_n_f64_x(pg1, s4769, t7526, 0.5);
            s4844 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4793, s4817), 0.8660254037844386);
            s4845 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4792, s4816), 0.8660254037844386);
            s4846 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7528, D68[3]), t7527, D68[2]);
            s4847 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7528, D68[2]), t7527, D68[3]);
            t7531 = svadd_f64_x(pg1, t7529, s4844);
            t7532 = svsub_f64_x(pg1, t7530, s4845);
            t7533 = svsub_f64_x(pg1, t7529, s4844);
            t7534 = svadd_f64_x(pg1, t7530, s4845);
            s4848 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7532, D69[5]), t7531, D69[4]);
            s4849 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7532, D69[4]), t7531, D69[5]);
            s4850 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7534, D69[7]), t7533, D69[6]);
            s4851 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7534, D69[6]), t7533, D69[7]);
            t7535 = svadd_f64_x(pg1, s4795, s4819);
            t7536 = svadd_f64_x(pg1, s4796, s4820);
            t7537 = svadd_f64_x(pg1, s4771, t7535);
            t7538 = svadd_f64_x(pg1, s4772, t7536);
            t7539 = svmls_n_f64_x(pg1, s4771, t7535, 0.5);
            t7540 = svmls_n_f64_x(pg1, s4772, t7536, 0.5);
            s4852 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4796, s4820), 0.8660254037844386);
            s4853 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4795, s4819), 0.8660254037844386);
            s4854 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7538, D68[5]), t7537, D68[4]);
            s4855 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7538, D68[4]), t7537, D68[5]);
            t7541 = svadd_f64_x(pg1, t7539, s4852);
            t7542 = svsub_f64_x(pg1, t7540, s4853);
            t7543 = svsub_f64_x(pg1, t7539, s4852);
            t7544 = svadd_f64_x(pg1, t7540, s4853);
            s4856 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7542, D69[9]), t7541, D69[8]);
            s4857 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7542, D69[8]), t7541, D69[9]);
            s4858 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7544, D69[11]), t7543, D69[10]);
            s4859 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7544, D69[10]), t7543, D69[11]);
            t7545 = svadd_f64_x(pg1, s4798, s4822);
            t7546 = svadd_f64_x(pg1, s4799, s4823);
            t7547 = svadd_f64_x(pg1, s4774, t7545);
            t7548 = svadd_f64_x(pg1, s4775, t7546);
            t7549 = svmls_n_f64_x(pg1, s4774, t7545, 0.5);
            t7550 = svmls_n_f64_x(pg1, s4775, t7546, 0.5);
            s4860 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4799, s4823), 0.8660254037844386);
            s4861 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4798, s4822), 0.8660254037844386);
            s4862 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7548, D68[7]), t7547, D68[6]);
            s4863 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7548, D68[6]), t7547, D68[7]);
            t7551 = svadd_f64_x(pg1, t7549, s4860);
            t7552 = svsub_f64_x(pg1, t7550, s4861);
            t7553 = svsub_f64_x(pg1, t7549, s4860);
            t7554 = svadd_f64_x(pg1, t7550, s4861);
            s4864 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7552, D69[13]), t7551, D69[12]);
            s4865 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7552, D69[12]), t7551, D69[13]);
            s4866 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7554, D69[15]), t7553, D69[14]);
            s4867 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7554, D69[14]), t7553, D69[15]);
            t7555 = svadd_f64_x(pg1, s4801, s4825);
            t7556 = svadd_f64_x(pg1, s4802, s4826);
            t7557 = svadd_f64_x(pg1, s4777, t7555);
            t7558 = svadd_f64_x(pg1, s4778, t7556);
            t7559 = svmls_n_f64_x(pg1, s4777, t7555, 0.5);
            t7560 = svmls_n_f64_x(pg1, s4778, t7556, 0.5);
            s4868 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4802, s4826), 0.8660254037844386);
            s4869 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4801, s4825), 0.8660254037844386);
            s4870 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7558, D68[9]), t7557, D68[8]);
            s4871 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7558, D68[8]), t7557, D68[9]);
            t7561 = svadd_f64_x(pg1, t7559, s4868);
            t7562 = svsub_f64_x(pg1, t7560, s4869);
            t7563 = svsub_f64_x(pg1, t7559, s4868);
            t7564 = svadd_f64_x(pg1, t7560, s4869);
            s4872 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7562, D69[17]), t7561, D69[16]);
            s4873 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7562, D69[16]), t7561, D69[17]);
            s4874 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7564, D69[19]), t7563, D69[18]);
            s4875 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7564, D69[18]), t7563, D69[19]);
            t7565 = svadd_f64_x(pg1, s4804, s4828);
            t7566 = svadd_f64_x(pg1, s4805, s4829);
            t7567 = svadd_f64_x(pg1, s4780, t7565);
            t7568 = svadd_f64_x(pg1, s4781, t7566);
            t7569 = svmls_n_f64_x(pg1, s4780, t7565, 0.5);
            t7570 = svmls_n_f64_x(pg1, s4781, t7566, 0.5);
            s4876 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4805, s4829), 0.8660254037844386);
            s4877 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4804, s4828), 0.8660254037844386);
            s4878 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7568, D68[11]), t7567, D68[10]);
            s4879 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7568, D68[10]), t7567, D68[11]);
            t7571 = svadd_f64_x(pg1, t7569, s4876);
            t7572 = svsub_f64_x(pg1, t7570, s4877);
            t7573 = svsub_f64_x(pg1, t7569, s4876);
            t7574 = svadd_f64_x(pg1, t7570, s4877);
            s4880 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7572, D69[21]), t7571, D69[20]);
            s4881 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7572, D69[20]), t7571, D69[21]);
            s4882 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7574, D69[23]), t7573, D69[22]);
            s4883 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7574, D69[22]), t7573, D69[23]);
            t7575 = svadd_f64_x(pg1, s4807, s4831);
            t7576 = svadd_f64_x(pg1, s4808, s4832);
            t7577 = svadd_f64_x(pg1, s4783, t7575);
            t7578 = svadd_f64_x(pg1, s4784, t7576);
            t7579 = svmls_n_f64_x(pg1, s4783, t7575, 0.5);
            t7580 = svmls_n_f64_x(pg1, s4784, t7576, 0.5);
            s4884 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4808, s4832), 0.8660254037844386);
            s4885 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4807, s4831), 0.8660254037844386);
            s4886 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7578, D68[13]), t7577, D68[12]);
            s4887 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7578, D68[12]), t7577, D68[13]);
            t7581 = svadd_f64_x(pg1, t7579, s4884);
            t7582 = svsub_f64_x(pg1, t7580, s4885);
            t7583 = svsub_f64_x(pg1, t7579, s4884);
            t7584 = svadd_f64_x(pg1, t7580, s4885);
            s4888 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7582, D69[25]), t7581, D69[24]);
            s4889 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7582, D69[24]), t7581, D69[25]);
            s4890 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7584, D69[27]), t7583, D69[26]);
            s4891 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7584, D69[26]), t7583, D69[27]);
            t7585 = svadd_f64_x(pg1, s4810, s4834);
            t7586 = svadd_f64_x(pg1, s4811, s4835);
            t7587 = svadd_f64_x(pg1, s4786, t7585);
            t7588 = svadd_f64_x(pg1, s4787, t7586);
            t7589 = svmls_n_f64_x(pg1, s4786, t7585, 0.5);
            t7590 = svmls_n_f64_x(pg1, s4787, t7586, 0.5);
            s4892 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4811, s4835), 0.8660254037844386);
            s4893 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4810, s4834), 0.8660254037844386);
            s4894 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7588, D68[15]), t7587, D68[14]);
            s4895 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7588, D68[14]), t7587, D68[15]);
            t7591 = svadd_f64_x(pg1, t7589, s4892);
            t7592 = svsub_f64_x(pg1, t7590, s4893);
            t7593 = svsub_f64_x(pg1, t7589, s4892);
            t7594 = svadd_f64_x(pg1, t7590, s4893);
            s4896 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7592, D69[29]), t7591, D69[28]);
            s4897 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7592, D69[28]), t7591, D69[29]);
            s4898 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7594, D69[31]), t7593, D69[30]);
            s4899 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7594, D69[30]), t7593, D69[31]);
            t7595 = svadd_f64_x(pg1, s4838, s4870);
            t7596 = svadd_f64_x(pg1, s4839, s4871);
            t7597 = svsub_f64_x(pg1, s4838, s4870);
            t7598 = svsub_f64_x(pg1, s4839, s4871);
            t7599 = svadd_f64_x(pg1, s4854, s4886);
            t7600 = svadd_f64_x(pg1, s4855, s4887);
            t7601 = svsub_f64_x(pg1, s4854, s4886);
            t7602 = svsub_f64_x(pg1, s4855, s4887);
            t7603 = svadd_f64_x(pg1, t7595, t7599);
            t7604 = svadd_f64_x(pg1, t7596, t7600);
            t7605 = svsub_f64_x(pg1, t7595, t7599);
            t7606 = svsub_f64_x(pg1, t7596, t7600);
            t7607 = svadd_f64_x(pg1, t7597, t7602);
            t7608 = svsub_f64_x(pg1, t7598, t7601);
            t7609 = svsub_f64_x(pg1, t7597, t7602);
            t7610 = svadd_f64_x(pg1, t7598, t7601);
            t7611 = svadd_f64_x(pg1, s4846, s4878);
            t7612 = svadd_f64_x(pg1, s4847, s4879);
            t7613 = svsub_f64_x(pg1, s4846, s4878);
            t7614 = svsub_f64_x(pg1, s4847, s4879);
            t7615 = svadd_f64_x(pg1, s4862, s4894);
            t7616 = svadd_f64_x(pg1, s4863, s4895);
            t7617 = svsub_f64_x(pg1, s4862, s4894);
            t7618 = svsub_f64_x(pg1, s4863, s4895);
            t7619 = svadd_f64_x(pg1, t7611, t7615);
            t7620 = svadd_f64_x(pg1, t7612, t7616);
            t7621 = svsub_f64_x(pg1, t7611, t7615);
            t7622 = svsub_f64_x(pg1, t7612, t7616);
            a10262 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7613, t7618), 0.70710678118654757);
            a10263 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7614, t7617), 0.70710678118654757);
            s4900 = svadd_f64_x(pg1, a10262, a10263);
            s4901 = svsub_f64_x(pg1, a10263, a10262);
            a10264 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7614, t7617), 0.70710678118654757);
            a10265 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7613, t7618), 0.70710678118654757);
            s4902 = svsub_f64_x(pg1, a10264, a10265);
            s4903 = svadd_f64_x(pg1, a10265, a10264);
            s4904 = svsub_f64_x(pg1, t7603, t7619);
            s4905 = svsub_f64_x(pg1, t7604, t7620);
            s4906 = svadd_f64_x(pg1, t7607, s4900);
            s4907 = svadd_f64_x(pg1, t7608, s4901);
            s4908 = svsub_f64_x(pg1, t7607, s4900);
            s4909 = svsub_f64_x(pg1, t7608, s4901);
            s4910 = svadd_f64_x(pg1, t7605, t7622);
            s4911 = svsub_f64_x(pg1, t7606, t7621);
            s4912 = svsub_f64_x(pg1, t7605, t7622);
            s4913 = svadd_f64_x(pg1, t7606, t7621);
            s4914 = svadd_f64_x(pg1, t7609, s4902);
            s4915 = svsub_f64_x(pg1, t7610, s4903);
            s4916 = svsub_f64_x(pg1, t7609, s4902);
            s4917 = svadd_f64_x(pg1, t7610, s4903);
            t7623 = svadd_f64_x(pg1, s4840, s4872);
            t7624 = svadd_f64_x(pg1, s4841, s4873);
            t7625 = svsub_f64_x(pg1, s4840, s4872);
            t7626 = svsub_f64_x(pg1, s4841, s4873);
            t7627 = svadd_f64_x(pg1, s4856, s4888);
            t7628 = svadd_f64_x(pg1, s4857, s4889);
            t7629 = svsub_f64_x(pg1, s4856, s4888);
            t7630 = svsub_f64_x(pg1, s4857, s4889);
            t7631 = svadd_f64_x(pg1, t7623, t7627);
            t7632 = svadd_f64_x(pg1, t7624, t7628);
            t7633 = svsub_f64_x(pg1, t7623, t7627);
            t7634 = svsub_f64_x(pg1, t7624, t7628);
            t7635 = svadd_f64_x(pg1, t7625, t7630);
            t7636 = svsub_f64_x(pg1, t7626, t7629);
            t7637 = svsub_f64_x(pg1, t7625, t7630);
            t7638 = svadd_f64_x(pg1, t7626, t7629);
            t7639 = svadd_f64_x(pg1, s4848, s4880);
            t7640 = svadd_f64_x(pg1, s4849, s4881);
            t7641 = svsub_f64_x(pg1, s4848, s4880);
            t7642 = svsub_f64_x(pg1, s4849, s4881);
            t7643 = svadd_f64_x(pg1, s4864, s4896);
            t7644 = svadd_f64_x(pg1, s4865, s4897);
            t7645 = svsub_f64_x(pg1, s4864, s4896);
            t7646 = svsub_f64_x(pg1, s4865, s4897);
            t7647 = svadd_f64_x(pg1, t7639, t7643);
            t7648 = svadd_f64_x(pg1, t7640, t7644);
            t7649 = svsub_f64_x(pg1, t7639, t7643);
            t7650 = svsub_f64_x(pg1, t7640, t7644);
            a10266 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7641, t7646), 0.70710678118654757);
            a10267 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7642, t7645), 0.70710678118654757);
            s4918 = svadd_f64_x(pg1, a10266, a10267);
            s4919 = svsub_f64_x(pg1, a10267, a10266);
            a10268 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7642, t7645), 0.70710678118654757);
            a10269 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7641, t7646), 0.70710678118654757);
            s4920 = svsub_f64_x(pg1, a10268, a10269);
            s4921 = svadd_f64_x(pg1, a10269, a10268);
            s4922 = svadd_f64_x(pg1, t7631, t7647);
            s4923 = svadd_f64_x(pg1, t7632, t7648);
            s4924 = svsub_f64_x(pg1, t7631, t7647);
            s4925 = svsub_f64_x(pg1, t7632, t7648);
            s4926 = svadd_f64_x(pg1, t7635, s4918);
            s4927 = svadd_f64_x(pg1, t7636, s4919);
            s4928 = svsub_f64_x(pg1, t7635, s4918);
            s4929 = svsub_f64_x(pg1, t7636, s4919);
            s4930 = svadd_f64_x(pg1, t7633, t7650);
            s4931 = svsub_f64_x(pg1, t7634, t7649);
            s4932 = svsub_f64_x(pg1, t7633, t7650);
            s4933 = svadd_f64_x(pg1, t7634, t7649);
            s4934 = svadd_f64_x(pg1, t7637, s4920);
            s4935 = svsub_f64_x(pg1, t7638, s4921);
            s4936 = svsub_f64_x(pg1, t7637, s4920);
            s4937 = svadd_f64_x(pg1, t7638, s4921);
            t7651 = svadd_f64_x(pg1, s4842, s4874);
            t7652 = svadd_f64_x(pg1, s4843, s4875);
            t7653 = svsub_f64_x(pg1, s4842, s4874);
            t7654 = svsub_f64_x(pg1, s4843, s4875);
            t7655 = svadd_f64_x(pg1, s4858, s4890);
            t7656 = svadd_f64_x(pg1, s4859, s4891);
            t7657 = svsub_f64_x(pg1, s4858, s4890);
            t7658 = svsub_f64_x(pg1, s4859, s4891);
            t7659 = svadd_f64_x(pg1, t7651, t7655);
            t7660 = svadd_f64_x(pg1, t7652, t7656);
            t7661 = svsub_f64_x(pg1, t7651, t7655);
            t7662 = svsub_f64_x(pg1, t7652, t7656);
            t7663 = svadd_f64_x(pg1, t7653, t7658);
            t7664 = svsub_f64_x(pg1, t7654, t7657);
            t7665 = svsub_f64_x(pg1, t7653, t7658);
            t7666 = svadd_f64_x(pg1, t7654, t7657);
            t7667 = svadd_f64_x(pg1, s4850, s4882);
            t7668 = svadd_f64_x(pg1, s4851, s4883);
            t7669 = svsub_f64_x(pg1, s4850, s4882);
            t7670 = svsub_f64_x(pg1, s4851, s4883);
            t7671 = svadd_f64_x(pg1, s4866, s4898);
            t7672 = svadd_f64_x(pg1, s4867, s4899);
            t7673 = svsub_f64_x(pg1, s4866, s4898);
            t7674 = svsub_f64_x(pg1, s4867, s4899);
            t7675 = svadd_f64_x(pg1, t7667, t7671);
            t7676 = svadd_f64_x(pg1, t7668, t7672);
            t7677 = svsub_f64_x(pg1, t7667, t7671);
            t7678 = svsub_f64_x(pg1, t7668, t7672);
            a10270 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7669, t7674), 0.70710678118654757);
            a10271 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7670, t7673), 0.70710678118654757);
            s4938 = svadd_f64_x(pg1, a10270, a10271);
            s4939 = svsub_f64_x(pg1, a10271, a10270);
            a10272 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7670, t7673), 0.70710678118654757);
            a10273 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7669, t7674), 0.70710678118654757);
            s4940 = svsub_f64_x(pg1, a10272, a10273);
            s4941 = svadd_f64_x(pg1, a10273, a10272);
            s4942 = svadd_f64_x(pg1, t7659, t7675);
            s4943 = svadd_f64_x(pg1, t7660, t7676);
            s4944 = svsub_f64_x(pg1, t7659, t7675);
            s4945 = svsub_f64_x(pg1, t7660, t7676);
            s4946 = svadd_f64_x(pg1, t7663, s4938);
            s4947 = svadd_f64_x(pg1, t7664, s4939);
            s4948 = svsub_f64_x(pg1, t7663, s4938);
            s4949 = svsub_f64_x(pg1, t7664, s4939);
            s4950 = svadd_f64_x(pg1, t7661, t7678);
            s4951 = svsub_f64_x(pg1, t7662, t7677);
            s4952 = svsub_f64_x(pg1, t7661, t7678);
            s4953 = svadd_f64_x(pg1, t7662, t7677);
            s4954 = svadd_f64_x(pg1, t7665, s4940);
            s4955 = svsub_f64_x(pg1, t7666, s4941);
            s4956 = svsub_f64_x(pg1, t7665, s4940);
            s4957 = svadd_f64_x(pg1, t7666, s4941);
            a10274 = ((46)*(j1));
            a10275 = TW1[a10274];
            a10276 = TW1[(a10274 + 1)];
            a10277 = TW1[(a10274 + 2)];
            a10278 = TW1[(a10274 + 3)];
            a10279 = TW1[(a10274 + 4)];
            a10280 = TW1[(a10274 + 5)];
            a10281 = TW1[(a10274 + 6)];
            a10282 = TW1[(a10274 + 7)];
            a10283 = TW1[(a10274 + 8)];
            a10284 = TW1[(a10274 + 9)];
            a10285 = TW1[(a10274 + 10)];
            a10286 = TW1[(a10274 + 11)];
            a10287 = TW1[(a10274 + 12)];
            a10288 = TW1[(a10274 + 13)];
            a10289 = TW1[(a10274 + 14)];
            a10290 = TW1[(a10274 + 15)];
            a10291 = TW1[(a10274 + 16)];
            a10292 = TW1[(a10274 + 17)];
            a10293 = TW1[(a10274 + 18)];
            a10294 = TW1[(a10274 + 19)];
            a10295 = TW1[(a10274 + 20)];
            a10296 = TW1[(a10274 + 21)];
            a10297 = TW1[(a10274 + 22)];
            a10298 = TW1[(a10274 + 23)];
            a10299 = TW1[(a10274 + 24)];
            a10300 = TW1[(a10274 + 25)];
            a10301 = TW1[(a10274 + 26)];
            a10302 = TW1[(a10274 + 27)];
            a10303 = TW1[(a10274 + 28)];
            a10304 = TW1[(a10274 + 29)];
            a10305 = TW1[(a10274 + 30)];
            a10306 = TW1[(a10274 + 31)];
            a10307 = TW1[(a10274 + 32)];
            a10308 = TW1[(a10274 + 33)];
            a10309 = TW1[(a10274 + 34)];
            a10310 = TW1[(a10274 + 35)];
            a10311 = TW1[(a10274 + 36)];
            a10312 = TW1[(a10274 + 37)];
            a10313 = TW1[(a10274 + 38)];
            a10314 = TW1[(a10274 + 39)];
            a10315 = TW1[(a10274 + 40)];
            a10316 = TW1[(a10274 + 41)];
            a10317 = TW1[(a10274 + 42)];
            a10318 = TW1[(a10274 + 43)];
            a10319 = TW1[(a10274 + 44)];
            a10320 = TW1[(a10274 + 45)];
            svex2_25.v0 = svadd_f64_x(pg1, t7603, t7619);
            svex2_25.v1 = svadd_f64_x(pg1, t7604, t7620);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)))))), svex2_25);
            svex2_26.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4923, a10276), s4922, a10275);
            svex2_26.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4923, a10275), s4922, a10276);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + m1)))), svex2_26);
            svex2_27.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4943, a10278), s4942, a10277);
            svex2_27.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4943, a10277), s4942, a10278);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_27);
            svex2_28.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4907, a10280), s4906, a10279);
            svex2_28.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4907, a10279), s4906, a10280);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_28);
            svex2_29.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4927, a10282), s4926, a10281);
            svex2_29.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4927, a10281), s4926, a10282);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_29);
            svex2_30.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4947, a10284), s4946, a10283);
            svex2_30.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4947, a10283), s4946, a10284);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_30);
            svex2_31.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4911, a10286), s4910, a10285);
            svex2_31.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4911, a10285), s4910, a10286);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_31);
            svex2_32.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4931, a10288), s4930, a10287);
            svex2_32.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4931, a10287), s4930, a10288);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_32);
            svex2_33.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4951, a10290), s4950, a10289);
            svex2_33.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4951, a10289), s4950, a10290);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_33);
            svex2_34.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4915, a10292), s4914, a10291);
            svex2_34.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4915, a10291), s4914, a10292);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((9)*(m1)))))), svex2_34);
            svex2_35.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4935, a10294), s4934, a10293);
            svex2_35.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4935, a10293), s4934, a10294);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((10)*(m1)))))), svex2_35);
            svex2_36.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4955, a10296), s4954, a10295);
            svex2_36.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4955, a10295), s4954, a10296);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((11)*(m1)))))), svex2_36);
            svex2_37.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4905, a10298), s4904, a10297);
            svex2_37.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4905, a10297), s4904, a10298);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((12)*(m1)))))), svex2_37);
            svex2_38.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4925, a10300), s4924, a10299);
            svex2_38.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4925, a10299), s4924, a10300);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((13)*(m1)))))), svex2_38);
            svex2_39.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4945, a10302), s4944, a10301);
            svex2_39.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4945, a10301), s4944, a10302);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((14)*(m1)))))), svex2_39);
            svex2_40.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4909, a10304), s4908, a10303);
            svex2_40.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4909, a10303), s4908, a10304);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((15)*(m1)))))), svex2_40);
            svex2_41.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4929, a10306), s4928, a10305);
            svex2_41.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4929, a10305), s4928, a10306);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((16)*(m1)))))), svex2_41);
            svex2_42.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4949, a10308), s4948, a10307);
            svex2_42.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4949, a10307), s4948, a10308);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((17)*(m1)))))), svex2_42);
            svex2_43.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4913, a10310), s4912, a10309);
            svex2_43.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4913, a10309), s4912, a10310);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((18)*(m1)))))), svex2_43);
            svex2_44.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4933, a10312), s4932, a10311);
            svex2_44.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4933, a10311), s4932, a10312);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((19)*(m1)))))), svex2_44);
            svex2_45.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4953, a10314), s4952, a10313);
            svex2_45.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4953, a10313), s4952, a10314);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((20)*(m1)))))), svex2_45);
            svex2_46.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4917, a10316), s4916, a10315);
            svex2_46.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4917, a10315), s4916, a10316);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((21)*(m1)))))), svex2_46);
            svex2_47.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4937, a10318), s4936, a10317);
            svex2_47.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4937, a10317), s4936, a10318);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((22)*(m1)))))), svex2_47);
            svex2_48.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4957, a10320), s4956, a10319);
            svex2_48.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4957, a10319), s4956, a10320);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((24)*(j1)))*(m1)) + ((23)*(m1)))))), svex2_48);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
