/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft2b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    float64_t a106, a107;
    int a104, a105, j1, l1, m1;
    svfloat64x2_t s49, s52, svex2_3, svex2_4;
    svfloat64_t s50, s51, s53, s54, s55, s56;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a104 = (k1 + ((j1)*(m1)));
            s49 = svld2_f64(pg1, (X + ((2)*(a104))));
            s50 = s49.v0;
            s51 = s49.v1;
            s52 = svld2_f64(pg1, (X + ((2)*((a104 + ((l1)*(m1)))))));
            s53 = s52.v0;
            s54 = s52.v1;
            s55 = svsub_f64_x(pg1, s50, s53);
            s56 = svsub_f64_x(pg1, s51, s54);
            a105 = ((2)*(j1));
            a106 = TW1[a105];
            a107 = TW1[(a105 + 1)];
            svex2_3.v0 = svadd_f64_x(pg1, s50, s53);
            svex2_3.v1 = svadd_f64_x(pg1, s51, s54);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((2)*(j1)))*(m1)))))), svex2_3);
            svex2_4.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s56, a107), s55, a106);
            svex2_4.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s56, a106), s55, a107);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((2)*(j1)))*(m1)) + m1)))), svex2_4);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
