/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft24c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D68[16];
    static float64_t D69[32];
    int l1, m1;
    svfloat64x2_t s4626, s4629, s4632, s4635, s4638, s4641, s4644, s4647, 
            s4650, s4653, s4656, s4659, s4662, s4665, s4668, s4671, 
            s4674, s4677, s4680, s4683, s4686, s4689, s4692, s4695, 
            svex2_25, svex2_26, svex2_27, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48;
    svfloat64_t a9076, a9077, a9078, a9079, a9080, a9081, a9082, a9083, 
            a9084, a9085, a9086, a9087, s4627, s4628, s4630, s4631, 
            s4633, s4634, s4636, s4637, s4639, s4640, s4642, s4643, 
            s4645, s4646, s4648, s4649, s4651, s4652, s4654, s4655, 
            s4657, s4658, s4660, s4661, s4663, s4664, s4666, s4667, 
            s4669, s4670, s4672, s4673, s4675, s4676, s4678, s4679, 
            s4681, s4682, s4684, s4685, s4687, s4688, s4690, s4691, 
            s4693, s4694, s4696, s4697, s4698, s4699, s4700, s4701, 
            s4702, s4703, s4704, s4705, s4706, s4707, s4708, s4709, 
            s4710, s4711, s4712, s4713, s4714, s4715, s4716, s4717, 
            s4718, s4719, s4720, s4721, s4722, s4723, s4724, s4725, 
            s4726, s4727, s4728, s4729, s4730, s4731, s4732, s4733, 
            s4734, s4735, s4736, s4737, s4738, s4739, s4740, s4741, 
            s4742, s4743, s4744, s4745, s4746, s4747, s4748, s4749, 
            s4750, s4751, s4752, s4753, s4754, s4755, s4756, s4757, 
            s4758, s4759, s4760, s4761, s4762, s4763, s4764, s4765, 
            s4766, s4767, s4768, s4769, s4770, s4771, s4772, s4773, 
            t7514, t7515, t7516, t7517, t7518, t7519, t7520, t7521, 
            t7522, t7523, t7524, t7525, t7526, t7527, t7528, t7529, 
            t7530, t7531, t7532, t7533, t7534, t7535, t7536, t7537, 
            t7538, t7539, t7540, t7541, t7542, t7543, t7544, t7545, 
            t7546, t7547, t7548, t7549, t7550, t7551, t7552, t7553, 
            t7554, t7555, t7556, t7557, t7558, t7559, t7560, t7561, 
            t7562, t7563, t7564, t7565, t7566, t7567, t7568, t7569, 
            t7570, t7571, t7572, t7573, t7574, t7575, t7576, t7577, 
            t7578, t7579, t7580, t7581, t7582, t7583, t7584, t7585, 
            t7586, t7587, t7588, t7589, t7590, t7591, t7592, t7593, 
            t7594, t7595, t7596, t7597, t7598, t7599, t7600, t7601, 
            t7602, t7603, t7604, t7605, t7606, t7607, t7608, t7609, 
            t7610, t7611, t7612, t7613, t7614, t7615, t7616, t7617, 
            t7618, t7619, t7620, t7621, t7622, t7623, t7624, t7625, 
            t7626, t7627, t7628, t7629, t7630, t7631, t7632, t7633, 
            t7634, t7635, t7636, t7637, t7638, t7639, t7640, t7641, 
            t7642, t7643, t7644, t7645, t7646, t7647, t7648, t7649, 
            t7650, t7651, t7652, t7653, t7654, t7655, t7656, t7657, 
            t7658, t7659, t7660, t7661, t7662, t7663, t7664, t7665, 
            t7666, t7667, t7668, t7669, t7670, t7671, t7672, t7673, 
            t7674, t7675, t7676, t7677;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s4626 = svld2_f64(pg1, (X + ((2)*(k1))));
        s4627 = s4626.v0;
        s4628 = s4626.v1;
        s4629 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s4630 = s4629.v0;
        s4631 = s4629.v1;
        s4632 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s4633 = s4632.v0;
        s4634 = s4632.v1;
        s4635 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s4636 = s4635.v0;
        s4637 = s4635.v1;
        s4638 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s4639 = s4638.v0;
        s4640 = s4638.v1;
        s4641 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s4642 = s4641.v0;
        s4643 = s4641.v1;
        s4644 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s4645 = s4644.v0;
        s4646 = s4644.v1;
        s4647 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s4648 = s4647.v0;
        s4649 = s4647.v1;
        s4650 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s4651 = s4650.v0;
        s4652 = s4650.v1;
        s4653 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s4654 = s4653.v0;
        s4655 = s4653.v1;
        s4656 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s4657 = s4656.v0;
        s4658 = s4656.v1;
        s4659 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s4660 = s4659.v0;
        s4661 = s4659.v1;
        s4662 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s4663 = s4662.v0;
        s4664 = s4662.v1;
        s4665 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s4666 = s4665.v0;
        s4667 = s4665.v1;
        s4668 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s4669 = s4668.v0;
        s4670 = s4668.v1;
        s4671 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s4672 = s4671.v0;
        s4673 = s4671.v1;
        s4674 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s4675 = s4674.v0;
        s4676 = s4674.v1;
        s4677 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s4678 = s4677.v0;
        s4679 = s4677.v1;
        s4680 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s4681 = s4680.v0;
        s4682 = s4680.v1;
        s4683 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s4684 = s4683.v0;
        s4685 = s4683.v1;
        s4686 = svld2_f64(pg1, (X + ((2)*((k1 + ((((20)*(l1)))*(m1)))))));
        s4687 = s4686.v0;
        s4688 = s4686.v1;
        s4689 = svld2_f64(pg1, (X + ((2)*((k1 + ((((21)*(l1)))*(m1)))))));
        s4690 = s4689.v0;
        s4691 = s4689.v1;
        s4692 = svld2_f64(pg1, (X + ((2)*((k1 + ((((22)*(l1)))*(m1)))))));
        s4693 = s4692.v0;
        s4694 = s4692.v1;
        s4695 = svld2_f64(pg1, (X + ((2)*((k1 + ((((23)*(l1)))*(m1)))))));
        s4696 = s4695.v0;
        s4697 = s4695.v1;
        t7514 = svadd_f64_x(pg1, s4651, s4675);
        t7515 = svadd_f64_x(pg1, s4652, s4676);
        t7516 = svadd_f64_x(pg1, s4627, t7514);
        t7517 = svadd_f64_x(pg1, s4628, t7515);
        t7518 = svmls_n_f64_x(pg1, s4627, t7514, 0.5);
        t7519 = svmls_n_f64_x(pg1, s4628, t7515, 0.5);
        s4698 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4652, s4676), 0.8660254037844386);
        s4699 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4651, s4675), 0.8660254037844386);
        s4700 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7517, D68[1]), t7516, D68[0]);
        s4701 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7517, D68[0]), t7516, D68[1]);
        t7520 = svadd_f64_x(pg1, t7518, s4698);
        t7521 = svsub_f64_x(pg1, t7519, s4699);
        t7522 = svsub_f64_x(pg1, t7518, s4698);
        t7523 = svadd_f64_x(pg1, t7519, s4699);
        s4702 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7521, D69[1]), t7520, D69[0]);
        s4703 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7521, D69[0]), t7520, D69[1]);
        s4704 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7523, D69[3]), t7522, D69[2]);
        s4705 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7523, D69[2]), t7522, D69[3]);
        t7524 = svadd_f64_x(pg1, s4654, s4678);
        t7525 = svadd_f64_x(pg1, s4655, s4679);
        t7526 = svadd_f64_x(pg1, s4630, t7524);
        t7527 = svadd_f64_x(pg1, s4631, t7525);
        t7528 = svmls_n_f64_x(pg1, s4630, t7524, 0.5);
        t7529 = svmls_n_f64_x(pg1, s4631, t7525, 0.5);
        s4706 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4655, s4679), 0.8660254037844386);
        s4707 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4654, s4678), 0.8660254037844386);
        s4708 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7527, D68[3]), t7526, D68[2]);
        s4709 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7527, D68[2]), t7526, D68[3]);
        t7530 = svadd_f64_x(pg1, t7528, s4706);
        t7531 = svsub_f64_x(pg1, t7529, s4707);
        t7532 = svsub_f64_x(pg1, t7528, s4706);
        t7533 = svadd_f64_x(pg1, t7529, s4707);
        s4710 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7531, D69[5]), t7530, D69[4]);
        s4711 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7531, D69[4]), t7530, D69[5]);
        s4712 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7533, D69[7]), t7532, D69[6]);
        s4713 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7533, D69[6]), t7532, D69[7]);
        t7534 = svadd_f64_x(pg1, s4657, s4681);
        t7535 = svadd_f64_x(pg1, s4658, s4682);
        t7536 = svadd_f64_x(pg1, s4633, t7534);
        t7537 = svadd_f64_x(pg1, s4634, t7535);
        t7538 = svmls_n_f64_x(pg1, s4633, t7534, 0.5);
        t7539 = svmls_n_f64_x(pg1, s4634, t7535, 0.5);
        s4714 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4658, s4682), 0.8660254037844386);
        s4715 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4657, s4681), 0.8660254037844386);
        s4716 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7537, D68[5]), t7536, D68[4]);
        s4717 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7537, D68[4]), t7536, D68[5]);
        t7540 = svadd_f64_x(pg1, t7538, s4714);
        t7541 = svsub_f64_x(pg1, t7539, s4715);
        t7542 = svsub_f64_x(pg1, t7538, s4714);
        t7543 = svadd_f64_x(pg1, t7539, s4715);
        s4718 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7541, D69[9]), t7540, D69[8]);
        s4719 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7541, D69[8]), t7540, D69[9]);
        s4720 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7543, D69[11]), t7542, D69[10]);
        s4721 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7543, D69[10]), t7542, D69[11]);
        t7544 = svadd_f64_x(pg1, s4660, s4684);
        t7545 = svadd_f64_x(pg1, s4661, s4685);
        t7546 = svadd_f64_x(pg1, s4636, t7544);
        t7547 = svadd_f64_x(pg1, s4637, t7545);
        t7548 = svmls_n_f64_x(pg1, s4636, t7544, 0.5);
        t7549 = svmls_n_f64_x(pg1, s4637, t7545, 0.5);
        s4722 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4661, s4685), 0.8660254037844386);
        s4723 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4660, s4684), 0.8660254037844386);
        s4724 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7547, D68[7]), t7546, D68[6]);
        s4725 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7547, D68[6]), t7546, D68[7]);
        t7550 = svadd_f64_x(pg1, t7548, s4722);
        t7551 = svsub_f64_x(pg1, t7549, s4723);
        t7552 = svsub_f64_x(pg1, t7548, s4722);
        t7553 = svadd_f64_x(pg1, t7549, s4723);
        s4726 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7551, D69[13]), t7550, D69[12]);
        s4727 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7551, D69[12]), t7550, D69[13]);
        s4728 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7553, D69[15]), t7552, D69[14]);
        s4729 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7553, D69[14]), t7552, D69[15]);
        t7554 = svadd_f64_x(pg1, s4663, s4687);
        t7555 = svadd_f64_x(pg1, s4664, s4688);
        t7556 = svadd_f64_x(pg1, s4639, t7554);
        t7557 = svadd_f64_x(pg1, s4640, t7555);
        t7558 = svmls_n_f64_x(pg1, s4639, t7554, 0.5);
        t7559 = svmls_n_f64_x(pg1, s4640, t7555, 0.5);
        s4730 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4664, s4688), 0.8660254037844386);
        s4731 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4663, s4687), 0.8660254037844386);
        s4732 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7557, D68[9]), t7556, D68[8]);
        s4733 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7557, D68[8]), t7556, D68[9]);
        t7560 = svadd_f64_x(pg1, t7558, s4730);
        t7561 = svsub_f64_x(pg1, t7559, s4731);
        t7562 = svsub_f64_x(pg1, t7558, s4730);
        t7563 = svadd_f64_x(pg1, t7559, s4731);
        s4734 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7561, D69[17]), t7560, D69[16]);
        s4735 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7561, D69[16]), t7560, D69[17]);
        s4736 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7563, D69[19]), t7562, D69[18]);
        s4737 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7563, D69[18]), t7562, D69[19]);
        t7564 = svadd_f64_x(pg1, s4666, s4690);
        t7565 = svadd_f64_x(pg1, s4667, s4691);
        t7566 = svadd_f64_x(pg1, s4642, t7564);
        t7567 = svadd_f64_x(pg1, s4643, t7565);
        t7568 = svmls_n_f64_x(pg1, s4642, t7564, 0.5);
        t7569 = svmls_n_f64_x(pg1, s4643, t7565, 0.5);
        s4738 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4667, s4691), 0.8660254037844386);
        s4739 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4666, s4690), 0.8660254037844386);
        s4740 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7567, D68[11]), t7566, D68[10]);
        s4741 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7567, D68[10]), t7566, D68[11]);
        t7570 = svadd_f64_x(pg1, t7568, s4738);
        t7571 = svsub_f64_x(pg1, t7569, s4739);
        t7572 = svsub_f64_x(pg1, t7568, s4738);
        t7573 = svadd_f64_x(pg1, t7569, s4739);
        s4742 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7571, D69[21]), t7570, D69[20]);
        s4743 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7571, D69[20]), t7570, D69[21]);
        s4744 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7573, D69[23]), t7572, D69[22]);
        s4745 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7573, D69[22]), t7572, D69[23]);
        t7574 = svadd_f64_x(pg1, s4669, s4693);
        t7575 = svadd_f64_x(pg1, s4670, s4694);
        t7576 = svadd_f64_x(pg1, s4645, t7574);
        t7577 = svadd_f64_x(pg1, s4646, t7575);
        t7578 = svmls_n_f64_x(pg1, s4645, t7574, 0.5);
        t7579 = svmls_n_f64_x(pg1, s4646, t7575, 0.5);
        s4746 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4670, s4694), 0.8660254037844386);
        s4747 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4669, s4693), 0.8660254037844386);
        s4748 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7577, D68[13]), t7576, D68[12]);
        s4749 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7577, D68[12]), t7576, D68[13]);
        t7580 = svadd_f64_x(pg1, t7578, s4746);
        t7581 = svsub_f64_x(pg1, t7579, s4747);
        t7582 = svsub_f64_x(pg1, t7578, s4746);
        t7583 = svadd_f64_x(pg1, t7579, s4747);
        s4750 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7581, D69[25]), t7580, D69[24]);
        s4751 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7581, D69[24]), t7580, D69[25]);
        s4752 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7583, D69[27]), t7582, D69[26]);
        s4753 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7583, D69[26]), t7582, D69[27]);
        t7584 = svadd_f64_x(pg1, s4672, s4696);
        t7585 = svadd_f64_x(pg1, s4673, s4697);
        t7586 = svadd_f64_x(pg1, s4648, t7584);
        t7587 = svadd_f64_x(pg1, s4649, t7585);
        t7588 = svmls_n_f64_x(pg1, s4648, t7584, 0.5);
        t7589 = svmls_n_f64_x(pg1, s4649, t7585, 0.5);
        s4754 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4673, s4697), 0.8660254037844386);
        s4755 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4672, s4696), 0.8660254037844386);
        s4756 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7587, D68[15]), t7586, D68[14]);
        s4757 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7587, D68[14]), t7586, D68[15]);
        t7590 = svadd_f64_x(pg1, t7588, s4754);
        t7591 = svsub_f64_x(pg1, t7589, s4755);
        t7592 = svsub_f64_x(pg1, t7588, s4754);
        t7593 = svadd_f64_x(pg1, t7589, s4755);
        s4758 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7591, D69[29]), t7590, D69[28]);
        s4759 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7591, D69[28]), t7590, D69[29]);
        s4760 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7593, D69[31]), t7592, D69[30]);
        s4761 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7593, D69[30]), t7592, D69[31]);
        t7594 = svadd_f64_x(pg1, s4700, s4732);
        t7595 = svadd_f64_x(pg1, s4701, s4733);
        t7596 = svsub_f64_x(pg1, s4700, s4732);
        t7597 = svsub_f64_x(pg1, s4701, s4733);
        t7598 = svadd_f64_x(pg1, s4716, s4748);
        t7599 = svadd_f64_x(pg1, s4717, s4749);
        t7600 = svsub_f64_x(pg1, s4716, s4748);
        t7601 = svsub_f64_x(pg1, s4717, s4749);
        t7602 = svadd_f64_x(pg1, t7594, t7598);
        t7603 = svadd_f64_x(pg1, t7595, t7599);
        t7604 = svsub_f64_x(pg1, t7594, t7598);
        t7605 = svsub_f64_x(pg1, t7595, t7599);
        t7606 = svadd_f64_x(pg1, t7596, t7601);
        t7607 = svsub_f64_x(pg1, t7597, t7600);
        t7608 = svsub_f64_x(pg1, t7596, t7601);
        t7609 = svadd_f64_x(pg1, t7597, t7600);
        t7610 = svadd_f64_x(pg1, s4708, s4740);
        t7611 = svadd_f64_x(pg1, s4709, s4741);
        t7612 = svsub_f64_x(pg1, s4708, s4740);
        t7613 = svsub_f64_x(pg1, s4709, s4741);
        t7614 = svadd_f64_x(pg1, s4724, s4756);
        t7615 = svadd_f64_x(pg1, s4725, s4757);
        t7616 = svsub_f64_x(pg1, s4724, s4756);
        t7617 = svsub_f64_x(pg1, s4725, s4757);
        t7618 = svadd_f64_x(pg1, t7610, t7614);
        t7619 = svadd_f64_x(pg1, t7611, t7615);
        t7620 = svsub_f64_x(pg1, t7610, t7614);
        t7621 = svsub_f64_x(pg1, t7611, t7615);
        a9076 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7612, t7617), 0.70710678118654757);
        a9077 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7613, t7616), 0.70710678118654757);
        s4762 = svadd_f64_x(pg1, a9076, a9077);
        s4763 = svsub_f64_x(pg1, a9077, a9076);
        a9078 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7613, t7616), 0.70710678118654757);
        a9079 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7612, t7617), 0.70710678118654757);
        s4764 = svsub_f64_x(pg1, a9078, a9079);
        s4765 = svadd_f64_x(pg1, a9079, a9078);
        t7622 = svadd_f64_x(pg1, s4702, s4734);
        t7623 = svadd_f64_x(pg1, s4703, s4735);
        t7624 = svsub_f64_x(pg1, s4702, s4734);
        t7625 = svsub_f64_x(pg1, s4703, s4735);
        t7626 = svadd_f64_x(pg1, s4718, s4750);
        t7627 = svadd_f64_x(pg1, s4719, s4751);
        t7628 = svsub_f64_x(pg1, s4718, s4750);
        t7629 = svsub_f64_x(pg1, s4719, s4751);
        t7630 = svadd_f64_x(pg1, t7622, t7626);
        t7631 = svadd_f64_x(pg1, t7623, t7627);
        t7632 = svsub_f64_x(pg1, t7622, t7626);
        t7633 = svsub_f64_x(pg1, t7623, t7627);
        t7634 = svadd_f64_x(pg1, t7624, t7629);
        t7635 = svsub_f64_x(pg1, t7625, t7628);
        t7636 = svsub_f64_x(pg1, t7624, t7629);
        t7637 = svadd_f64_x(pg1, t7625, t7628);
        t7638 = svadd_f64_x(pg1, s4710, s4742);
        t7639 = svadd_f64_x(pg1, s4711, s4743);
        t7640 = svsub_f64_x(pg1, s4710, s4742);
        t7641 = svsub_f64_x(pg1, s4711, s4743);
        t7642 = svadd_f64_x(pg1, s4726, s4758);
        t7643 = svadd_f64_x(pg1, s4727, s4759);
        t7644 = svsub_f64_x(pg1, s4726, s4758);
        t7645 = svsub_f64_x(pg1, s4727, s4759);
        t7646 = svadd_f64_x(pg1, t7638, t7642);
        t7647 = svadd_f64_x(pg1, t7639, t7643);
        t7648 = svsub_f64_x(pg1, t7638, t7642);
        t7649 = svsub_f64_x(pg1, t7639, t7643);
        a9080 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7640, t7645), 0.70710678118654757);
        a9081 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7641, t7644), 0.70710678118654757);
        s4766 = svadd_f64_x(pg1, a9080, a9081);
        s4767 = svsub_f64_x(pg1, a9081, a9080);
        a9082 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7641, t7644), 0.70710678118654757);
        a9083 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7640, t7645), 0.70710678118654757);
        s4768 = svsub_f64_x(pg1, a9082, a9083);
        s4769 = svadd_f64_x(pg1, a9083, a9082);
        t7650 = svadd_f64_x(pg1, s4704, s4736);
        t7651 = svadd_f64_x(pg1, s4705, s4737);
        t7652 = svsub_f64_x(pg1, s4704, s4736);
        t7653 = svsub_f64_x(pg1, s4705, s4737);
        t7654 = svadd_f64_x(pg1, s4720, s4752);
        t7655 = svadd_f64_x(pg1, s4721, s4753);
        t7656 = svsub_f64_x(pg1, s4720, s4752);
        t7657 = svsub_f64_x(pg1, s4721, s4753);
        t7658 = svadd_f64_x(pg1, t7650, t7654);
        t7659 = svadd_f64_x(pg1, t7651, t7655);
        t7660 = svsub_f64_x(pg1, t7650, t7654);
        t7661 = svsub_f64_x(pg1, t7651, t7655);
        t7662 = svadd_f64_x(pg1, t7652, t7657);
        t7663 = svsub_f64_x(pg1, t7653, t7656);
        t7664 = svsub_f64_x(pg1, t7652, t7657);
        t7665 = svadd_f64_x(pg1, t7653, t7656);
        t7666 = svadd_f64_x(pg1, s4712, s4744);
        t7667 = svadd_f64_x(pg1, s4713, s4745);
        t7668 = svsub_f64_x(pg1, s4712, s4744);
        t7669 = svsub_f64_x(pg1, s4713, s4745);
        t7670 = svadd_f64_x(pg1, s4728, s4760);
        t7671 = svadd_f64_x(pg1, s4729, s4761);
        t7672 = svsub_f64_x(pg1, s4728, s4760);
        t7673 = svsub_f64_x(pg1, s4729, s4761);
        t7674 = svadd_f64_x(pg1, t7666, t7670);
        t7675 = svadd_f64_x(pg1, t7667, t7671);
        t7676 = svsub_f64_x(pg1, t7666, t7670);
        t7677 = svsub_f64_x(pg1, t7667, t7671);
        a9084 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7668, t7673), 0.70710678118654757);
        a9085 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7669, t7672), 0.70710678118654757);
        s4770 = svadd_f64_x(pg1, a9084, a9085);
        s4771 = svsub_f64_x(pg1, a9085, a9084);
        a9086 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7669, t7672), 0.70710678118654757);
        a9087 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7668, t7673), 0.70710678118654757);
        s4772 = svsub_f64_x(pg1, a9086, a9087);
        s4773 = svadd_f64_x(pg1, a9087, a9086);
        svex2_25.v0 = svadd_f64_x(pg1, t7602, t7618);
        svex2_25.v1 = svadd_f64_x(pg1, t7603, t7619);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_25);
        svex2_26.v0 = svadd_f64_x(pg1, t7630, t7646);
        svex2_26.v1 = svadd_f64_x(pg1, t7631, t7647);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_26);
        svex2_27.v0 = svadd_f64_x(pg1, t7658, t7674);
        svex2_27.v1 = svadd_f64_x(pg1, t7659, t7675);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_27);
        svex2_28.v0 = svadd_f64_x(pg1, t7606, s4762);
        svex2_28.v1 = svadd_f64_x(pg1, t7607, s4763);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_28);
        svex2_29.v0 = svadd_f64_x(pg1, t7634, s4766);
        svex2_29.v1 = svadd_f64_x(pg1, t7635, s4767);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_29);
        svex2_30.v0 = svadd_f64_x(pg1, t7662, s4770);
        svex2_30.v1 = svadd_f64_x(pg1, t7663, s4771);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_30);
        svex2_31.v0 = svadd_f64_x(pg1, t7604, t7621);
        svex2_31.v1 = svsub_f64_x(pg1, t7605, t7620);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_31);
        svex2_32.v0 = svadd_f64_x(pg1, t7632, t7649);
        svex2_32.v1 = svsub_f64_x(pg1, t7633, t7648);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_32);
        svex2_33.v0 = svadd_f64_x(pg1, t7660, t7677);
        svex2_33.v1 = svsub_f64_x(pg1, t7661, t7676);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_33);
        svex2_34.v0 = svadd_f64_x(pg1, t7608, s4764);
        svex2_34.v1 = svsub_f64_x(pg1, t7609, s4765);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_34);
        svex2_35.v0 = svadd_f64_x(pg1, t7636, s4768);
        svex2_35.v1 = svsub_f64_x(pg1, t7637, s4769);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_35);
        svex2_36.v0 = svadd_f64_x(pg1, t7664, s4772);
        svex2_36.v1 = svsub_f64_x(pg1, t7665, s4773);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_36);
        svex2_37.v0 = svsub_f64_x(pg1, t7602, t7618);
        svex2_37.v1 = svsub_f64_x(pg1, t7603, t7619);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_37);
        svex2_38.v0 = svsub_f64_x(pg1, t7630, t7646);
        svex2_38.v1 = svsub_f64_x(pg1, t7631, t7647);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_38);
        svex2_39.v0 = svsub_f64_x(pg1, t7658, t7674);
        svex2_39.v1 = svsub_f64_x(pg1, t7659, t7675);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_39);
        svex2_40.v0 = svsub_f64_x(pg1, t7606, s4762);
        svex2_40.v1 = svsub_f64_x(pg1, t7607, s4763);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_40);
        svex2_41.v0 = svsub_f64_x(pg1, t7634, s4766);
        svex2_41.v1 = svsub_f64_x(pg1, t7635, s4767);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_41);
        svex2_42.v0 = svsub_f64_x(pg1, t7662, s4770);
        svex2_42.v1 = svsub_f64_x(pg1, t7663, s4771);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_42);
        svex2_43.v0 = svsub_f64_x(pg1, t7604, t7621);
        svex2_43.v1 = svadd_f64_x(pg1, t7605, t7620);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_43);
        svex2_44.v0 = svsub_f64_x(pg1, t7632, t7649);
        svex2_44.v1 = svadd_f64_x(pg1, t7633, t7648);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_44);
        svex2_45.v0 = svsub_f64_x(pg1, t7660, t7677);
        svex2_45.v1 = svadd_f64_x(pg1, t7661, t7676);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((20)*(m1)))))), svex2_45);
        svex2_46.v0 = svsub_f64_x(pg1, t7608, s4764);
        svex2_46.v1 = svadd_f64_x(pg1, t7609, s4765);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((21)*(m1)))))), svex2_46);
        svex2_47.v0 = svsub_f64_x(pg1, t7636, s4768);
        svex2_47.v1 = svadd_f64_x(pg1, t7637, s4769);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((22)*(m1)))))), svex2_47);
        svex2_48.v0 = svsub_f64_x(pg1, t7664, s4772);
        svex2_48.v1 = svadd_f64_x(pg1, t7665, s4773);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((23)*(m1)))))), svex2_48);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
