/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft27c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D23[18];
    static float64_t D24[36];
    int l1, m1;
    svfloat64x2_t s1577, s1580, s1583, s1586, s1589, s1592, s1595, s1598, 
            s1601, s1604, s1607, s1610, s1613, s1616, s1619, s1622, 
            s1625, s1628, s1631, s1634, s1637, s1640, s1643, s1646, 
            s1649, s1652, s1655, svex2_28, svex2_29, svex2_30, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48, 
            svex2_49, svex2_50, svex2_51, svex2_52, svex2_53, svex2_54;
    svfloat64_t s1578, s1579, s1581, s1582, s1584, s1585, s1587, s1588, 
            s1590, s1591, s1593, s1594, s1596, s1597, s1599, s1600, 
            s1602, s1603, s1605, s1606, s1608, s1609, s1611, s1612, 
            s1614, s1615, s1617, s1618, s1620, s1621, s1623, s1624, 
            s1626, s1627, s1629, s1630, s1632, s1633, s1635, s1636, 
            s1638, s1639, s1641, s1642, s1644, s1645, s1647, s1648, 
            s1650, s1651, s1653, s1654, s1656, s1657, s1658, s1659, 
            s1660, s1661, s1662, s1663, s1664, s1665, s1666, s1667, 
            s1668, s1669, s1670, s1671, s1672, s1673, s1674, s1675, 
            s1676, s1677, s1678, s1679, s1680, s1681, s1682, s1683, 
            s1684, s1685, s1686, s1687, s1688, s1689, s1690, s1691, 
            s1692, s1693, s1694, s1695, s1696, s1697, s1698, s1699, 
            s1700, s1701, s1702, s1703, s1704, s1705, s1706, s1707, 
            s1708, s1709, s1710, s1711, s1712, s1713, s1714, s1715, 
            s1716, s1717, s1718, s1719, s1720, s1721, s1722, s1723, 
            s1724, s1725, s1726, s1727, s1728, s1729, s1730, s1731, 
            s1732, s1733, s1734, s1735, s1736, s1737, s1738, s1739, 
            s1740, s1741, s1742, s1743, s1744, s1745, s1746, s1747, 
            s1748, s1749, s1750, s1751, s1752, s1753, s1754, s1755, 
            s1756, s1757, s1758, s1759, s1760, s1761, s1762, s1763, 
            s1764, s1765, s1766, s1767, s1768, s1769, s1770, s1771, 
            s1772, s1773, s1774, s1775, s1776, s1777, s1778, s1779, 
            s1780, s1781, s1782, s1783, s1784, s1785, s1786, s1787, 
            s1788, s1789, s1790, s1791, s1792, s1793, s1794, s1795, 
            s1796, s1797, s1798, s1799, s1800, s1801, s1802, s1803, 
            s1804, s1805, s1806, s1807, s1808, s1809, s1810, s1811, 
            s1812, s1813, t1706, t1707, t1708, t1709, t1710, t1711, 
            t1712, t1713, t1714, t1715, t1716, t1717, t1718, t1719, 
            t1720, t1721, t1722, t1723, t1724, t1725, t1726, t1727, 
            t1728, t1729, t1730, t1731, t1732, t1733, t1734, t1735, 
            t1736, t1737, t1738, t1739, t1740, t1741, t1742, t1743, 
            t1744, t1745, t1746, t1747, t1748, t1749, t1750, t1751, 
            t1752, t1753, t1754, t1755, t1756, t1757, t1758, t1759, 
            t1760, t1761, t1762, t1763, t1764, t1765, t1766, t1767, 
            t1768, t1769, t1770, t1771, t1772, t1773, t1774, t1775, 
            t1776, t1777, t1778, t1779, t1780, t1781, t1782, t1783, 
            t1784, t1785, t1786, t1787, t1788, t1789, t1790, t1791, 
            t1792, t1793, t1794, t1795, t1796, t1797, t1798, t1799, 
            t1800, t1801, t1802, t1803, t1804, t1805, t1806, t1807, 
            t1808, t1809, t1810, t1811, t1812, t1813, t1814, t1815, 
            t1816, t1817, t1818, t1819, t1820, t1821, t1822, t1823, 
            t1824, t1825, t1826, t1827, t1828, t1829, t1830, t1831, 
            t1832, t1833, t1834, t1835, t1836, t1837, t1838, t1839, 
            t1840, t1841, t1842, t1843, t1844, t1845, t1846, t1847, 
            t1848, t1849, t1850, t1851, t1852, t1853, t1854, t1855, 
            t1856, t1857, t1858, t1859, t1860, t1861, t1862, t1863, 
            t1864, t1865, t1866, t1867, t1868, t1869, t1870, t1871, 
            t1872, t1873, t1874, t1875, t1876, t1877, t1878, t1879, 
            t1880, t1881, t1882, t1883, t1884, t1885, t1886, t1887, 
            t1888, t1889, t1890, t1891, t1892, t1893, t1894, t1895, 
            t1896, t1897, t1898, t1899, t1900, t1901, t1902, t1903, 
            t1904, t1905, t1906, t1907, t1908, t1909, t1910, t1911, 
            t1912, t1913, t1914, t1915, t1916, t1917, t1918, t1919, 
            t1920, t1921;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s1577 = svld2_f64(pg1, (X + ((2)*(k1))));
        s1578 = s1577.v0;
        s1579 = s1577.v1;
        s1580 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s1581 = s1580.v0;
        s1582 = s1580.v1;
        s1583 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s1584 = s1583.v0;
        s1585 = s1583.v1;
        s1586 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s1587 = s1586.v0;
        s1588 = s1586.v1;
        s1589 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s1590 = s1589.v0;
        s1591 = s1589.v1;
        s1592 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s1593 = s1592.v0;
        s1594 = s1592.v1;
        s1595 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s1596 = s1595.v0;
        s1597 = s1595.v1;
        s1598 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s1599 = s1598.v0;
        s1600 = s1598.v1;
        s1601 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s1602 = s1601.v0;
        s1603 = s1601.v1;
        s1604 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s1605 = s1604.v0;
        s1606 = s1604.v1;
        s1607 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s1608 = s1607.v0;
        s1609 = s1607.v1;
        s1610 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s1611 = s1610.v0;
        s1612 = s1610.v1;
        s1613 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s1614 = s1613.v0;
        s1615 = s1613.v1;
        s1616 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s1617 = s1616.v0;
        s1618 = s1616.v1;
        s1619 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s1620 = s1619.v0;
        s1621 = s1619.v1;
        s1622 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s1623 = s1622.v0;
        s1624 = s1622.v1;
        s1625 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s1626 = s1625.v0;
        s1627 = s1625.v1;
        s1628 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s1629 = s1628.v0;
        s1630 = s1628.v1;
        s1631 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s1632 = s1631.v0;
        s1633 = s1631.v1;
        s1634 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s1635 = s1634.v0;
        s1636 = s1634.v1;
        s1637 = svld2_f64(pg1, (X + ((2)*((k1 + ((((20)*(l1)))*(m1)))))));
        s1638 = s1637.v0;
        s1639 = s1637.v1;
        s1640 = svld2_f64(pg1, (X + ((2)*((k1 + ((((21)*(l1)))*(m1)))))));
        s1641 = s1640.v0;
        s1642 = s1640.v1;
        s1643 = svld2_f64(pg1, (X + ((2)*((k1 + ((((22)*(l1)))*(m1)))))));
        s1644 = s1643.v0;
        s1645 = s1643.v1;
        s1646 = svld2_f64(pg1, (X + ((2)*((k1 + ((((23)*(l1)))*(m1)))))));
        s1647 = s1646.v0;
        s1648 = s1646.v1;
        s1649 = svld2_f64(pg1, (X + ((2)*((k1 + ((((24)*(l1)))*(m1)))))));
        s1650 = s1649.v0;
        s1651 = s1649.v1;
        s1652 = svld2_f64(pg1, (X + ((2)*((k1 + ((((25)*(l1)))*(m1)))))));
        s1653 = s1652.v0;
        s1654 = s1652.v1;
        s1655 = svld2_f64(pg1, (X + ((2)*((k1 + ((((26)*(l1)))*(m1)))))));
        s1656 = s1655.v0;
        s1657 = s1655.v1;
        t1706 = svadd_f64_x(pg1, s1605, s1632);
        t1707 = svadd_f64_x(pg1, s1606, s1633);
        t1708 = svadd_f64_x(pg1, s1578, t1706);
        t1709 = svadd_f64_x(pg1, s1579, t1707);
        t1710 = svmls_n_f64_x(pg1, s1578, t1706, 0.5);
        t1711 = svmls_n_f64_x(pg1, s1579, t1707, 0.5);
        s1658 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1606, s1633), 0.8660254037844386);
        s1659 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1605, s1632), 0.8660254037844386);
        s1660 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1709, D23[1]), t1708, D23[0]);
        s1661 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1709, D23[0]), t1708, D23[1]);
        t1712 = svadd_f64_x(pg1, t1710, s1658);
        t1713 = svsub_f64_x(pg1, t1711, s1659);
        t1714 = svsub_f64_x(pg1, t1710, s1658);
        t1715 = svadd_f64_x(pg1, t1711, s1659);
        s1662 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1713, D24[1]), t1712, D24[0]);
        s1663 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1713, D24[0]), t1712, D24[1]);
        s1664 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1715, D24[3]), t1714, D24[2]);
        s1665 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1715, D24[2]), t1714, D24[3]);
        t1716 = svadd_f64_x(pg1, s1608, s1635);
        t1717 = svadd_f64_x(pg1, s1609, s1636);
        t1718 = svadd_f64_x(pg1, s1581, t1716);
        t1719 = svadd_f64_x(pg1, s1582, t1717);
        t1720 = svmls_n_f64_x(pg1, s1581, t1716, 0.5);
        t1721 = svmls_n_f64_x(pg1, s1582, t1717, 0.5);
        s1666 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1609, s1636), 0.8660254037844386);
        s1667 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1608, s1635), 0.8660254037844386);
        s1668 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1719, D23[3]), t1718, D23[2]);
        s1669 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1719, D23[2]), t1718, D23[3]);
        t1722 = svadd_f64_x(pg1, t1720, s1666);
        t1723 = svsub_f64_x(pg1, t1721, s1667);
        t1724 = svsub_f64_x(pg1, t1720, s1666);
        t1725 = svadd_f64_x(pg1, t1721, s1667);
        s1670 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1723, D24[5]), t1722, D24[4]);
        s1671 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1723, D24[4]), t1722, D24[5]);
        s1672 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1725, D24[7]), t1724, D24[6]);
        s1673 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1725, D24[6]), t1724, D24[7]);
        t1726 = svadd_f64_x(pg1, s1611, s1638);
        t1727 = svadd_f64_x(pg1, s1612, s1639);
        t1728 = svadd_f64_x(pg1, s1584, t1726);
        t1729 = svadd_f64_x(pg1, s1585, t1727);
        t1730 = svmls_n_f64_x(pg1, s1584, t1726, 0.5);
        t1731 = svmls_n_f64_x(pg1, s1585, t1727, 0.5);
        s1674 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1612, s1639), 0.8660254037844386);
        s1675 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1611, s1638), 0.8660254037844386);
        s1676 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1729, D23[5]), t1728, D23[4]);
        s1677 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1729, D23[4]), t1728, D23[5]);
        t1732 = svadd_f64_x(pg1, t1730, s1674);
        t1733 = svsub_f64_x(pg1, t1731, s1675);
        t1734 = svsub_f64_x(pg1, t1730, s1674);
        t1735 = svadd_f64_x(pg1, t1731, s1675);
        s1678 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1733, D24[9]), t1732, D24[8]);
        s1679 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1733, D24[8]), t1732, D24[9]);
        s1680 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1735, D24[11]), t1734, D24[10]);
        s1681 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1735, D24[10]), t1734, D24[11]);
        t1736 = svadd_f64_x(pg1, s1614, s1641);
        t1737 = svadd_f64_x(pg1, s1615, s1642);
        t1738 = svadd_f64_x(pg1, s1587, t1736);
        t1739 = svadd_f64_x(pg1, s1588, t1737);
        t1740 = svmls_n_f64_x(pg1, s1587, t1736, 0.5);
        t1741 = svmls_n_f64_x(pg1, s1588, t1737, 0.5);
        s1682 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1615, s1642), 0.8660254037844386);
        s1683 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1614, s1641), 0.8660254037844386);
        s1684 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1739, D23[7]), t1738, D23[6]);
        s1685 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1739, D23[6]), t1738, D23[7]);
        t1742 = svadd_f64_x(pg1, t1740, s1682);
        t1743 = svsub_f64_x(pg1, t1741, s1683);
        t1744 = svsub_f64_x(pg1, t1740, s1682);
        t1745 = svadd_f64_x(pg1, t1741, s1683);
        s1686 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1743, D24[13]), t1742, D24[12]);
        s1687 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1743, D24[12]), t1742, D24[13]);
        s1688 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1745, D24[15]), t1744, D24[14]);
        s1689 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1745, D24[14]), t1744, D24[15]);
        t1746 = svadd_f64_x(pg1, s1617, s1644);
        t1747 = svadd_f64_x(pg1, s1618, s1645);
        t1748 = svadd_f64_x(pg1, s1590, t1746);
        t1749 = svadd_f64_x(pg1, s1591, t1747);
        t1750 = svmls_n_f64_x(pg1, s1590, t1746, 0.5);
        t1751 = svmls_n_f64_x(pg1, s1591, t1747, 0.5);
        s1690 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1618, s1645), 0.8660254037844386);
        s1691 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1617, s1644), 0.8660254037844386);
        s1692 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1749, D23[9]), t1748, D23[8]);
        s1693 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1749, D23[8]), t1748, D23[9]);
        t1752 = svadd_f64_x(pg1, t1750, s1690);
        t1753 = svsub_f64_x(pg1, t1751, s1691);
        t1754 = svsub_f64_x(pg1, t1750, s1690);
        t1755 = svadd_f64_x(pg1, t1751, s1691);
        s1694 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1753, D24[17]), t1752, D24[16]);
        s1695 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1753, D24[16]), t1752, D24[17]);
        s1696 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1755, D24[19]), t1754, D24[18]);
        s1697 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1755, D24[18]), t1754, D24[19]);
        t1756 = svadd_f64_x(pg1, s1620, s1647);
        t1757 = svadd_f64_x(pg1, s1621, s1648);
        t1758 = svadd_f64_x(pg1, s1593, t1756);
        t1759 = svadd_f64_x(pg1, s1594, t1757);
        t1760 = svmls_n_f64_x(pg1, s1593, t1756, 0.5);
        t1761 = svmls_n_f64_x(pg1, s1594, t1757, 0.5);
        s1698 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1621, s1648), 0.8660254037844386);
        s1699 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1620, s1647), 0.8660254037844386);
        s1700 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1759, D23[11]), t1758, D23[10]);
        s1701 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1759, D23[10]), t1758, D23[11]);
        t1762 = svadd_f64_x(pg1, t1760, s1698);
        t1763 = svsub_f64_x(pg1, t1761, s1699);
        t1764 = svsub_f64_x(pg1, t1760, s1698);
        t1765 = svadd_f64_x(pg1, t1761, s1699);
        s1702 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1763, D24[21]), t1762, D24[20]);
        s1703 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1763, D24[20]), t1762, D24[21]);
        s1704 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1765, D24[23]), t1764, D24[22]);
        s1705 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1765, D24[22]), t1764, D24[23]);
        t1766 = svadd_f64_x(pg1, s1623, s1650);
        t1767 = svadd_f64_x(pg1, s1624, s1651);
        t1768 = svadd_f64_x(pg1, s1596, t1766);
        t1769 = svadd_f64_x(pg1, s1597, t1767);
        t1770 = svmls_n_f64_x(pg1, s1596, t1766, 0.5);
        t1771 = svmls_n_f64_x(pg1, s1597, t1767, 0.5);
        s1706 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1624, s1651), 0.8660254037844386);
        s1707 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1623, s1650), 0.8660254037844386);
        s1708 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1769, D23[13]), t1768, D23[12]);
        s1709 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1769, D23[12]), t1768, D23[13]);
        t1772 = svadd_f64_x(pg1, t1770, s1706);
        t1773 = svsub_f64_x(pg1, t1771, s1707);
        t1774 = svsub_f64_x(pg1, t1770, s1706);
        t1775 = svadd_f64_x(pg1, t1771, s1707);
        s1710 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1773, D24[25]), t1772, D24[24]);
        s1711 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1773, D24[24]), t1772, D24[25]);
        s1712 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1775, D24[27]), t1774, D24[26]);
        s1713 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1775, D24[26]), t1774, D24[27]);
        t1776 = svadd_f64_x(pg1, s1626, s1653);
        t1777 = svadd_f64_x(pg1, s1627, s1654);
        t1778 = svadd_f64_x(pg1, s1599, t1776);
        t1779 = svadd_f64_x(pg1, s1600, t1777);
        t1780 = svmls_n_f64_x(pg1, s1599, t1776, 0.5);
        t1781 = svmls_n_f64_x(pg1, s1600, t1777, 0.5);
        s1714 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1627, s1654), 0.8660254037844386);
        s1715 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1626, s1653), 0.8660254037844386);
        s1716 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1779, D23[15]), t1778, D23[14]);
        s1717 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1779, D23[14]), t1778, D23[15]);
        t1782 = svadd_f64_x(pg1, t1780, s1714);
        t1783 = svsub_f64_x(pg1, t1781, s1715);
        t1784 = svsub_f64_x(pg1, t1780, s1714);
        t1785 = svadd_f64_x(pg1, t1781, s1715);
        s1718 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1783, D24[29]), t1782, D24[28]);
        s1719 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1783, D24[28]), t1782, D24[29]);
        s1720 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1785, D24[31]), t1784, D24[30]);
        s1721 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1785, D24[30]), t1784, D24[31]);
        t1786 = svadd_f64_x(pg1, s1629, s1656);
        t1787 = svadd_f64_x(pg1, s1630, s1657);
        t1788 = svadd_f64_x(pg1, s1602, t1786);
        t1789 = svadd_f64_x(pg1, s1603, t1787);
        t1790 = svmls_n_f64_x(pg1, s1602, t1786, 0.5);
        t1791 = svmls_n_f64_x(pg1, s1603, t1787, 0.5);
        s1722 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1630, s1657), 0.8660254037844386);
        s1723 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1629, s1656), 0.8660254037844386);
        s1724 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1789, D23[17]), t1788, D23[16]);
        s1725 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1789, D23[16]), t1788, D23[17]);
        t1792 = svadd_f64_x(pg1, t1790, s1722);
        t1793 = svsub_f64_x(pg1, t1791, s1723);
        t1794 = svsub_f64_x(pg1, t1790, s1722);
        t1795 = svadd_f64_x(pg1, t1791, s1723);
        s1726 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1793, D24[33]), t1792, D24[32]);
        s1727 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1793, D24[32]), t1792, D24[33]);
        s1728 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1795, D24[35]), t1794, D24[34]);
        s1729 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1795, D24[34]), t1794, D24[35]);
        t1796 = svadd_f64_x(pg1, s1684, s1708);
        t1797 = svadd_f64_x(pg1, s1685, s1709);
        t1798 = svadd_f64_x(pg1, s1660, t1796);
        t1799 = svadd_f64_x(pg1, s1661, t1797);
        t1800 = svmls_n_f64_x(pg1, s1660, t1796, 0.5);
        t1801 = svmls_n_f64_x(pg1, s1661, t1797, 0.5);
        s1730 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1685, s1709), 0.8660254037844386);
        s1731 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1684, s1708), 0.8660254037844386);
        t1802 = svadd_f64_x(pg1, t1800, s1730);
        t1803 = svsub_f64_x(pg1, t1801, s1731);
        t1804 = svsub_f64_x(pg1, t1800, s1730);
        t1805 = svadd_f64_x(pg1, t1801, s1731);
        t1806 = svadd_f64_x(pg1, s1692, s1716);
        t1807 = svadd_f64_x(pg1, s1693, s1717);
        t1808 = svadd_f64_x(pg1, s1668, t1806);
        t1809 = svadd_f64_x(pg1, s1669, t1807);
        t1810 = svmls_n_f64_x(pg1, s1668, t1806, 0.5);
        t1811 = svmls_n_f64_x(pg1, s1669, t1807, 0.5);
        s1732 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1693, s1717), 0.8660254037844386);
        s1733 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1692, s1716), 0.8660254037844386);
        t1812 = svadd_f64_x(pg1, t1810, s1732);
        t1813 = svsub_f64_x(pg1, t1811, s1733);
        t1814 = svsub_f64_x(pg1, t1810, s1732);
        t1815 = svadd_f64_x(pg1, t1811, s1733);
        s1790 = svmla_n_f64_x(pg1, t1812, t1813, 0.83909963117727981);
        s1734 = svmul_n_f64_x(pg1, s1790, 0.76604444311897812);
        s1791 = svmls_n_f64_x(pg1, t1813, t1812, 0.83909963117727981);
        s1735 = svmul_n_f64_x(pg1, s1791, 0.76604444311897812);
        s1792 = svmla_n_f64_x(pg1, t1814, t1815, 5.6712818196177102);
        s1736 = svmul_n_f64_x(pg1, s1792, 0.17364817766693033);
        s1793 = svmls_n_f64_x(pg1, t1815, t1814, 5.6712818196177102);
        s1737 = svmul_n_f64_x(pg1, s1793, 0.17364817766693033);
        t1816 = svadd_f64_x(pg1, s1700, s1724);
        t1817 = svadd_f64_x(pg1, s1701, s1725);
        t1818 = svadd_f64_x(pg1, s1676, t1816);
        t1819 = svadd_f64_x(pg1, s1677, t1817);
        t1820 = svmls_n_f64_x(pg1, s1676, t1816, 0.5);
        t1821 = svmls_n_f64_x(pg1, s1677, t1817, 0.5);
        s1738 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1701, s1725), 0.8660254037844386);
        s1739 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1700, s1724), 0.8660254037844386);
        t1822 = svadd_f64_x(pg1, t1820, s1738);
        t1823 = svsub_f64_x(pg1, t1821, s1739);
        t1824 = svsub_f64_x(pg1, t1820, s1738);
        t1825 = svadd_f64_x(pg1, t1821, s1739);
        s1794 = svmla_n_f64_x(pg1, t1822, t1823, 5.6712818196177102);
        s1740 = svmul_n_f64_x(pg1, s1794, 0.17364817766693033);
        s1795 = svmls_n_f64_x(pg1, t1823, t1822, 5.6712818196177102);
        s1741 = svmul_n_f64_x(pg1, s1795, 0.17364817766693033);
        s1796 = svmls_n_f64_x(pg1, t1825, t1824, 2.7474774194546225);
        s1742 = svmul_n_f64_x(pg1, s1796, 0.34202014332566871);
        s1797 = svmla_n_f64_x(pg1, t1824, t1825, 2.7474774194546225);
        s1743 = svmul_n_f64_x(pg1, s1797, 0.34202014332566871);
        t1826 = svadd_f64_x(pg1, t1808, t1818);
        t1827 = svadd_f64_x(pg1, t1809, t1819);
        t1828 = svmls_n_f64_x(pg1, t1798, t1826, 0.5);
        t1829 = svmls_n_f64_x(pg1, t1799, t1827, 0.5);
        s1744 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1809, t1819), 0.8660254037844386);
        s1745 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1808, t1818), 0.8660254037844386);
        t1830 = svadd_f64_x(pg1, s1734, s1740);
        t1831 = svadd_f64_x(pg1, s1735, s1741);
        t1832 = svmls_n_f64_x(pg1, t1802, t1830, 0.5);
        t1833 = svmls_n_f64_x(pg1, t1803, t1831, 0.5);
        s1746 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1735, s1741), 0.8660254037844386);
        s1747 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1734, s1740), 0.8660254037844386);
        t1834 = svadd_f64_x(pg1, s1736, s1742);
        t1835 = svsub_f64_x(pg1, s1737, s1743);
        t1836 = svmls_n_f64_x(pg1, t1804, t1834, 0.5);
        t1837 = svmls_n_f64_x(pg1, t1805, t1835, 0.5);
        s1748 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1737, s1743), 0.8660254037844386);
        s1749 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1736, s1742), 0.8660254037844386);
        t1838 = svadd_f64_x(pg1, s1686, s1710);
        t1839 = svadd_f64_x(pg1, s1687, s1711);
        t1840 = svadd_f64_x(pg1, s1662, t1838);
        t1841 = svadd_f64_x(pg1, s1663, t1839);
        t1842 = svmls_n_f64_x(pg1, s1662, t1838, 0.5);
        t1843 = svmls_n_f64_x(pg1, s1663, t1839, 0.5);
        s1750 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1687, s1711), 0.8660254037844386);
        s1751 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1686, s1710), 0.8660254037844386);
        t1844 = svadd_f64_x(pg1, t1842, s1750);
        t1845 = svsub_f64_x(pg1, t1843, s1751);
        t1846 = svsub_f64_x(pg1, t1842, s1750);
        t1847 = svadd_f64_x(pg1, t1843, s1751);
        t1848 = svadd_f64_x(pg1, s1694, s1718);
        t1849 = svadd_f64_x(pg1, s1695, s1719);
        t1850 = svadd_f64_x(pg1, s1670, t1848);
        t1851 = svadd_f64_x(pg1, s1671, t1849);
        t1852 = svmls_n_f64_x(pg1, s1670, t1848, 0.5);
        t1853 = svmls_n_f64_x(pg1, s1671, t1849, 0.5);
        s1752 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1695, s1719), 0.8660254037844386);
        s1753 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1694, s1718), 0.8660254037844386);
        t1854 = svadd_f64_x(pg1, t1852, s1752);
        t1855 = svsub_f64_x(pg1, t1853, s1753);
        t1856 = svsub_f64_x(pg1, t1852, s1752);
        t1857 = svadd_f64_x(pg1, t1853, s1753);
        s1798 = svmla_n_f64_x(pg1, t1854, t1855, 0.83909963117727981);
        s1754 = svmul_n_f64_x(pg1, s1798, 0.76604444311897812);
        s1799 = svmls_n_f64_x(pg1, t1855, t1854, 0.83909963117727981);
        s1755 = svmul_n_f64_x(pg1, s1799, 0.76604444311897812);
        s1800 = svmla_n_f64_x(pg1, t1856, t1857, 5.6712818196177102);
        s1756 = svmul_n_f64_x(pg1, s1800, 0.17364817766693033);
        s1801 = svmls_n_f64_x(pg1, t1857, t1856, 5.6712818196177102);
        s1757 = svmul_n_f64_x(pg1, s1801, 0.17364817766693033);
        t1858 = svadd_f64_x(pg1, s1702, s1726);
        t1859 = svadd_f64_x(pg1, s1703, s1727);
        t1860 = svadd_f64_x(pg1, s1678, t1858);
        t1861 = svadd_f64_x(pg1, s1679, t1859);
        t1862 = svmls_n_f64_x(pg1, s1678, t1858, 0.5);
        t1863 = svmls_n_f64_x(pg1, s1679, t1859, 0.5);
        s1758 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1703, s1727), 0.8660254037844386);
        s1759 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1702, s1726), 0.8660254037844386);
        t1864 = svadd_f64_x(pg1, t1862, s1758);
        t1865 = svsub_f64_x(pg1, t1863, s1759);
        t1866 = svsub_f64_x(pg1, t1862, s1758);
        t1867 = svadd_f64_x(pg1, t1863, s1759);
        s1802 = svmla_n_f64_x(pg1, t1864, t1865, 5.6712818196177102);
        s1760 = svmul_n_f64_x(pg1, s1802, 0.17364817766693033);
        s1803 = svmls_n_f64_x(pg1, t1865, t1864, 5.6712818196177102);
        s1761 = svmul_n_f64_x(pg1, s1803, 0.17364817766693033);
        s1804 = svmls_n_f64_x(pg1, t1867, t1866, 2.7474774194546225);
        s1762 = svmul_n_f64_x(pg1, s1804, 0.34202014332566871);
        s1805 = svmla_n_f64_x(pg1, t1866, t1867, 2.7474774194546225);
        s1763 = svmul_n_f64_x(pg1, s1805, 0.34202014332566871);
        t1868 = svadd_f64_x(pg1, t1850, t1860);
        t1869 = svadd_f64_x(pg1, t1851, t1861);
        t1870 = svmls_n_f64_x(pg1, t1840, t1868, 0.5);
        t1871 = svmls_n_f64_x(pg1, t1841, t1869, 0.5);
        s1764 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1851, t1861), 0.8660254037844386);
        s1765 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1850, t1860), 0.8660254037844386);
        t1872 = svadd_f64_x(pg1, s1754, s1760);
        t1873 = svadd_f64_x(pg1, s1755, s1761);
        t1874 = svmls_n_f64_x(pg1, t1844, t1872, 0.5);
        t1875 = svmls_n_f64_x(pg1, t1845, t1873, 0.5);
        s1766 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1755, s1761), 0.8660254037844386);
        s1767 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1754, s1760), 0.8660254037844386);
        t1876 = svadd_f64_x(pg1, s1756, s1762);
        t1877 = svsub_f64_x(pg1, s1757, s1763);
        t1878 = svmls_n_f64_x(pg1, t1846, t1876, 0.5);
        t1879 = svmls_n_f64_x(pg1, t1847, t1877, 0.5);
        s1768 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1757, s1763), 0.8660254037844386);
        s1769 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1756, s1762), 0.8660254037844386);
        t1880 = svadd_f64_x(pg1, s1688, s1712);
        t1881 = svadd_f64_x(pg1, s1689, s1713);
        t1882 = svadd_f64_x(pg1, s1664, t1880);
        t1883 = svadd_f64_x(pg1, s1665, t1881);
        t1884 = svmls_n_f64_x(pg1, s1664, t1880, 0.5);
        t1885 = svmls_n_f64_x(pg1, s1665, t1881, 0.5);
        s1770 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1689, s1713), 0.8660254037844386);
        s1771 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1688, s1712), 0.8660254037844386);
        t1886 = svadd_f64_x(pg1, t1884, s1770);
        t1887 = svsub_f64_x(pg1, t1885, s1771);
        t1888 = svsub_f64_x(pg1, t1884, s1770);
        t1889 = svadd_f64_x(pg1, t1885, s1771);
        t1890 = svadd_f64_x(pg1, s1696, s1720);
        t1891 = svadd_f64_x(pg1, s1697, s1721);
        t1892 = svadd_f64_x(pg1, s1672, t1890);
        t1893 = svadd_f64_x(pg1, s1673, t1891);
        t1894 = svmls_n_f64_x(pg1, s1672, t1890, 0.5);
        t1895 = svmls_n_f64_x(pg1, s1673, t1891, 0.5);
        s1772 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1697, s1721), 0.8660254037844386);
        s1773 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1696, s1720), 0.8660254037844386);
        t1896 = svadd_f64_x(pg1, t1894, s1772);
        t1897 = svsub_f64_x(pg1, t1895, s1773);
        t1898 = svsub_f64_x(pg1, t1894, s1772);
        t1899 = svadd_f64_x(pg1, t1895, s1773);
        s1806 = svmla_n_f64_x(pg1, t1896, t1897, 0.83909963117727981);
        s1774 = svmul_n_f64_x(pg1, s1806, 0.76604444311897812);
        s1807 = svmls_n_f64_x(pg1, t1897, t1896, 0.83909963117727981);
        s1775 = svmul_n_f64_x(pg1, s1807, 0.76604444311897812);
        s1808 = svmla_n_f64_x(pg1, t1898, t1899, 5.6712818196177102);
        s1776 = svmul_n_f64_x(pg1, s1808, 0.17364817766693033);
        s1809 = svmls_n_f64_x(pg1, t1899, t1898, 5.6712818196177102);
        s1777 = svmul_n_f64_x(pg1, s1809, 0.17364817766693033);
        t1900 = svadd_f64_x(pg1, s1704, s1728);
        t1901 = svadd_f64_x(pg1, s1705, s1729);
        t1902 = svadd_f64_x(pg1, s1680, t1900);
        t1903 = svadd_f64_x(pg1, s1681, t1901);
        t1904 = svmls_n_f64_x(pg1, s1680, t1900, 0.5);
        t1905 = svmls_n_f64_x(pg1, s1681, t1901, 0.5);
        s1778 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1705, s1729), 0.8660254037844386);
        s1779 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1704, s1728), 0.8660254037844386);
        t1906 = svadd_f64_x(pg1, t1904, s1778);
        t1907 = svsub_f64_x(pg1, t1905, s1779);
        t1908 = svsub_f64_x(pg1, t1904, s1778);
        t1909 = svadd_f64_x(pg1, t1905, s1779);
        s1810 = svmla_n_f64_x(pg1, t1906, t1907, 5.6712818196177102);
        s1780 = svmul_n_f64_x(pg1, s1810, 0.17364817766693033);
        s1811 = svmls_n_f64_x(pg1, t1907, t1906, 5.6712818196177102);
        s1781 = svmul_n_f64_x(pg1, s1811, 0.17364817766693033);
        s1812 = svmls_n_f64_x(pg1, t1909, t1908, 2.7474774194546225);
        s1782 = svmul_n_f64_x(pg1, s1812, 0.34202014332566871);
        s1813 = svmla_n_f64_x(pg1, t1908, t1909, 2.7474774194546225);
        s1783 = svmul_n_f64_x(pg1, s1813, 0.34202014332566871);
        t1910 = svadd_f64_x(pg1, t1892, t1902);
        t1911 = svadd_f64_x(pg1, t1893, t1903);
        t1912 = svmls_n_f64_x(pg1, t1882, t1910, 0.5);
        t1913 = svmls_n_f64_x(pg1, t1883, t1911, 0.5);
        s1784 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1893, t1903), 0.8660254037844386);
        s1785 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1892, t1902), 0.8660254037844386);
        t1914 = svadd_f64_x(pg1, s1774, s1780);
        t1915 = svadd_f64_x(pg1, s1775, s1781);
        t1916 = svmls_n_f64_x(pg1, t1886, t1914, 0.5);
        t1917 = svmls_n_f64_x(pg1, t1887, t1915, 0.5);
        s1786 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1775, s1781), 0.8660254037844386);
        s1787 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1774, s1780), 0.8660254037844386);
        t1918 = svadd_f64_x(pg1, s1776, s1782);
        t1919 = svsub_f64_x(pg1, s1777, s1783);
        t1920 = svmls_n_f64_x(pg1, t1888, t1918, 0.5);
        t1921 = svmls_n_f64_x(pg1, t1889, t1919, 0.5);
        s1788 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1777, s1783), 0.8660254037844386);
        s1789 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1776, s1782), 0.8660254037844386);
        svex2_28.v0 = svadd_f64_x(pg1, t1798, t1826);
        svex2_28.v1 = svadd_f64_x(pg1, t1799, t1827);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_28);
        svex2_29.v0 = svadd_f64_x(pg1, t1840, t1868);
        svex2_29.v1 = svadd_f64_x(pg1, t1841, t1869);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_29);
        svex2_30.v0 = svadd_f64_x(pg1, t1882, t1910);
        svex2_30.v1 = svadd_f64_x(pg1, t1883, t1911);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_30);
        svex2_31.v0 = svadd_f64_x(pg1, t1802, t1830);
        svex2_31.v1 = svadd_f64_x(pg1, t1803, t1831);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_31);
        svex2_32.v0 = svadd_f64_x(pg1, t1844, t1872);
        svex2_32.v1 = svadd_f64_x(pg1, t1845, t1873);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_32);
        svex2_33.v0 = svadd_f64_x(pg1, t1886, t1914);
        svex2_33.v1 = svadd_f64_x(pg1, t1887, t1915);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_33);
        svex2_34.v0 = svadd_f64_x(pg1, t1804, t1834);
        svex2_34.v1 = svadd_f64_x(pg1, t1805, t1835);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_34);
        svex2_35.v0 = svadd_f64_x(pg1, t1846, t1876);
        svex2_35.v1 = svadd_f64_x(pg1, t1847, t1877);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_35);
        svex2_36.v0 = svadd_f64_x(pg1, t1888, t1918);
        svex2_36.v1 = svadd_f64_x(pg1, t1889, t1919);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_36);
        svex2_37.v0 = svadd_f64_x(pg1, t1828, s1744);
        svex2_37.v1 = svsub_f64_x(pg1, t1829, s1745);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_37);
        svex2_38.v0 = svadd_f64_x(pg1, t1870, s1764);
        svex2_38.v1 = svsub_f64_x(pg1, t1871, s1765);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_38);
        svex2_39.v0 = svadd_f64_x(pg1, t1912, s1784);
        svex2_39.v1 = svsub_f64_x(pg1, t1913, s1785);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_39);
        svex2_40.v0 = svadd_f64_x(pg1, t1832, s1746);
        svex2_40.v1 = svsub_f64_x(pg1, t1833, s1747);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_40);
        svex2_41.v0 = svadd_f64_x(pg1, t1874, s1766);
        svex2_41.v1 = svsub_f64_x(pg1, t1875, s1767);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_41);
        svex2_42.v0 = svadd_f64_x(pg1, t1916, s1786);
        svex2_42.v1 = svsub_f64_x(pg1, t1917, s1787);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_42);
        svex2_43.v0 = svadd_f64_x(pg1, t1836, s1748);
        svex2_43.v1 = svsub_f64_x(pg1, t1837, s1749);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_43);
        svex2_44.v0 = svadd_f64_x(pg1, t1878, s1768);
        svex2_44.v1 = svsub_f64_x(pg1, t1879, s1769);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_44);
        svex2_45.v0 = svadd_f64_x(pg1, t1920, s1788);
        svex2_45.v1 = svsub_f64_x(pg1, t1921, s1789);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_45);
        svex2_46.v0 = svsub_f64_x(pg1, t1828, s1744);
        svex2_46.v1 = svadd_f64_x(pg1, t1829, s1745);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_46);
        svex2_47.v0 = svsub_f64_x(pg1, t1870, s1764);
        svex2_47.v1 = svadd_f64_x(pg1, t1871, s1765);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_47);
        svex2_48.v0 = svsub_f64_x(pg1, t1912, s1784);
        svex2_48.v1 = svadd_f64_x(pg1, t1913, s1785);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((20)*(m1)))))), svex2_48);
        svex2_49.v0 = svsub_f64_x(pg1, t1832, s1746);
        svex2_49.v1 = svadd_f64_x(pg1, t1833, s1747);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((21)*(m1)))))), svex2_49);
        svex2_50.v0 = svsub_f64_x(pg1, t1874, s1766);
        svex2_50.v1 = svadd_f64_x(pg1, t1875, s1767);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((22)*(m1)))))), svex2_50);
        svex2_51.v0 = svsub_f64_x(pg1, t1916, s1786);
        svex2_51.v1 = svadd_f64_x(pg1, t1917, s1787);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((23)*(m1)))))), svex2_51);
        svex2_52.v0 = svsub_f64_x(pg1, t1836, s1748);
        svex2_52.v1 = svadd_f64_x(pg1, t1837, s1749);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((24)*(m1)))))), svex2_52);
        svex2_53.v0 = svsub_f64_x(pg1, t1878, s1768);
        svex2_53.v1 = svadd_f64_x(pg1, t1879, s1769);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((25)*(m1)))))), svex2_53);
        svex2_54.v0 = svsub_f64_x(pg1, t1920, s1788);
        svex2_54.v1 = svadd_f64_x(pg1, t1921, s1789);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((26)*(m1)))))), svex2_54);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
