/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft27a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D23[18];
    static float64_t D24[36];
    int l1;
    float64_t  *a3434;
    svfloat64x2_t s1787, s1790, s1793, s1796, s1799, s1802, s1805, s1808, 
            s1811, s1814, s1817, s1820, s1823, s1826, s1829, s1832, 
            s1835, s1838, s1841, s1844, s1847, s1850, s1853, s1856, 
            s1859, s1862, s1865;
    svfloat64_t a3435, a3436, a3437, a3438, a3439, a3440, a3441, a3442, 
            a3443, a3444, a3445, a3446, a3447, a3448, a3449, a3450, 
            a3451, a3452, a3453, a3454, a3455, a3456, a3457, a3458, 
            a3459, a3460, a3461, a3462, a3463, a3464, a3465, a3466, 
            a3467, a3468, a3469, a3470, a3471, a3472, a3473, a3474, 
            a3475, a3476, a3477, a3478, a3479, a3480, a3481, a3482, 
            a3483, a3484, a3485, a3486, s1788, s1789, s1791, s1792, 
            s1794, s1795, s1797, s1798, s1800, s1801, s1803, s1804, 
            s1806, s1807, s1809, s1810, s1812, s1813, s1815, s1816, 
            s1818, s1819, s1821, s1822, s1824, s1825, s1827, s1828, 
            s1830, s1831, s1833, s1834, s1836, s1837, s1839, s1840, 
            s1842, s1843, s1845, s1846, s1848, s1849, s1851, s1852, 
            s1854, s1855, s1857, s1858, s1860, s1861, s1863, s1864, 
            s1866, s1867, s1868, s1869, s1870, s1871, s1872, s1873, 
            s1874, s1875, s1876, s1877, s1878, s1879, s1880, s1881, 
            s1882, s1883, s1884, s1885, s1886, s1887, s1888, s1889, 
            s1890, s1891, s1892, s1893, s1894, s1895, s1896, s1897, 
            s1898, s1899, s1900, s1901, s1902, s1903, s1904, s1905, 
            s1906, s1907, s1908, s1909, s1910, s1911, s1912, s1913, 
            s1914, s1915, s1916, s1917, s1918, s1919, s1920, s1921, 
            s1922, s1923, s1924, s1925, s1926, s1927, s1928, s1929, 
            s1930, s1931, s1932, s1933, s1934, s1935, s1936, s1937, 
            s1938, s1939, s1940, s1941, s1942, s1943, s1944, s1945, 
            s1946, s1947, s1948, s1949, s1950, s1951, s1952, s1953, 
            s1954, s1955, s1956, s1957, s1958, s1959, s1960, s1961, 
            s1962, s1963, s1964, s1965, s1966, s1967, s1968, s1969, 
            s1970, s1971, s1972, s1973, s1974, s1975, s1976, s1977, 
            s1978, s1979, s1980, s1981, s1982, s1983, s1984, s1985, 
            s1986, s1987, s1988, s1989, s1990, s1991, s1992, s1993, 
            s1994, s1995, s1996, s1997, s1998, s1999, s2000, s2001, 
            s2002, s2003, s2004, s2005, s2006, s2007, s2008, s2009, 
            s2010, s2011, s2012, s2013, s2014, s2015, s2016, s2017, 
            s2018, s2019, s2020, s2021, s2022, s2023, s2024, s2025, 
            s2026, s2027, s2028, s2029, s2030, s2031, s2032, s2033, 
            s2034, s2035, s2036, s2037, s2038, s2039, s2040, s2041, 
            s2042, s2043, s2044, s2045, s2046, s2047, s2048, s2049, 
            s2050, s2051, s2052, s2053, s2054, s2055, s2056, s2057, 
            s2058, s2059, s2060, s2061, s2062, s2063, s2064, s2065, 
            s2066, s2067, s2068, s2069, s2070, s2071, s2072, s2073, 
            s2074, s2075, s2076, s2077, s2078, s2079, s2080, s2081, 
            s2082, s2083, s2084, s2085, s2086, s2087, s2088, s2089, 
            s2090, s2091, s2092, s2093, s2094, s2095, s2096, s2097, 
            s2098, s2099, s2100, s2101, s2102, s2103, s2104, s2105, 
            s2106, s2107, s2108, s2109, s2110, s2111, s2112, s2113, 
            s2114, s2115, s2116, s2117, s2118, s2119, s2120, s2121, 
            s2122, s2123, s2124, s2125, s2126, s2127, s2128, s2129, 
            t1707, t1708, t1709, t1710, t1711, t1712, t1713, t1714, 
            t1715, t1716, t1717, t1718, t1719, t1720, t1721, t1722, 
            t1723, t1724, t1725, t1726, t1727, t1728, t1729, t1730, 
            t1731, t1732, t1733, t1734, t1735, t1736, t1737, t1738, 
            t1739, t1740, t1741, t1742, t1743, t1744, t1745, t1746, 
            t1747, t1748, t1749, t1750, t1751, t1752, t1753, t1754, 
            t1755, t1756, t1757, t1758, t1759, t1760, t1761, t1762, 
            t1763, t1764, t1765, t1766, t1767, t1768, t1769, t1770, 
            t1771, t1772, t1773, t1774, t1775, t1776, t1777, t1778, 
            t1779, t1780, t1781, t1782, t1783, t1784, t1785, t1786, 
            t1787, t1788, t1789, t1790, t1791, t1792, t1793, t1794, 
            t1795, t1796, t1797, t1798, t1799, t1800, t1801, t1802, 
            t1803, t1804, t1805, t1806, t1807, t1808, t1809, t1810, 
            t1811, t1812, t1813, t1814, t1815, t1816, t1817, t1818, 
            t1819, t1820, t1821, t1822, t1823, t1824, t1825, t1826, 
            t1827, t1828, t1829, t1830, t1831, t1832, t1833, t1834, 
            t1835, t1836, t1837, t1838, t1839, t1840, t1841, t1842, 
            t1843, t1844, t1845, t1846, t1847, t1848, t1849, t1850, 
            t1851, t1852, t1853, t1854, t1855, t1856, t1857, t1858, 
            t1859, t1860, t1861, t1862, t1863, t1864, t1865, t1866, 
            t1867, t1868, t1869, t1870, t1871, t1872, t1873, t1874, 
            t1875, t1876, t1877, t1878, t1879, t1880, t1881, t1882, 
            t1883, t1884, t1885, t1886, t1887, t1888, t1889, t1890, 
            t1891, t1892, t1893, t1894, t1895, t1896, t1897, t1898, 
            t1899, t1900, t1901, t1902, t1903, t1904, t1905, t1906, 
            t1907, t1908, t1909, t1910, t1911, t1912, t1913, t1914, 
            t1915, t1916, t1917, t1918, t1919, t1920, t1921, t1922;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s1787 = svld2_f64(pg1, (X + ((2)*(j1))));
        s1788 = s1787.v0;
        s1789 = s1787.v1;
        s1790 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s1791 = s1790.v0;
        s1792 = s1790.v1;
        s1793 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s1794 = s1793.v0;
        s1795 = s1793.v1;
        s1796 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s1797 = s1796.v0;
        s1798 = s1796.v1;
        s1799 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s1800 = s1799.v0;
        s1801 = s1799.v1;
        s1802 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s1803 = s1802.v0;
        s1804 = s1802.v1;
        s1805 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s1806 = s1805.v0;
        s1807 = s1805.v1;
        s1808 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s1809 = s1808.v0;
        s1810 = s1808.v1;
        s1811 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s1812 = s1811.v0;
        s1813 = s1811.v1;
        s1814 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s1815 = s1814.v0;
        s1816 = s1814.v1;
        s1817 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s1818 = s1817.v0;
        s1819 = s1817.v1;
        s1820 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s1821 = s1820.v0;
        s1822 = s1820.v1;
        s1823 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s1824 = s1823.v0;
        s1825 = s1823.v1;
        s1826 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s1827 = s1826.v0;
        s1828 = s1826.v1;
        s1829 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s1830 = s1829.v0;
        s1831 = s1829.v1;
        s1832 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s1833 = s1832.v0;
        s1834 = s1832.v1;
        s1835 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s1836 = s1835.v0;
        s1837 = s1835.v1;
        s1838 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s1839 = s1838.v0;
        s1840 = s1838.v1;
        s1841 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s1842 = s1841.v0;
        s1843 = s1841.v1;
        s1844 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s1845 = s1844.v0;
        s1846 = s1844.v1;
        s1847 = svld2_f64(pg1, (X + ((2)*((j1 + ((20)*(l1)))))));
        s1848 = s1847.v0;
        s1849 = s1847.v1;
        s1850 = svld2_f64(pg1, (X + ((2)*((j1 + ((21)*(l1)))))));
        s1851 = s1850.v0;
        s1852 = s1850.v1;
        s1853 = svld2_f64(pg1, (X + ((2)*((j1 + ((22)*(l1)))))));
        s1854 = s1853.v0;
        s1855 = s1853.v1;
        s1856 = svld2_f64(pg1, (X + ((2)*((j1 + ((23)*(l1)))))));
        s1857 = s1856.v0;
        s1858 = s1856.v1;
        s1859 = svld2_f64(pg1, (X + ((2)*((j1 + ((24)*(l1)))))));
        s1860 = s1859.v0;
        s1861 = s1859.v1;
        s1862 = svld2_f64(pg1, (X + ((2)*((j1 + ((25)*(l1)))))));
        s1863 = s1862.v0;
        s1864 = s1862.v1;
        s1865 = svld2_f64(pg1, (X + ((2)*((j1 + ((26)*(l1)))))));
        s1866 = s1865.v0;
        s1867 = s1865.v1;
        t1707 = svadd_f64_x(pg1, s1815, s1842);
        t1708 = svadd_f64_x(pg1, s1816, s1843);
        t1709 = svadd_f64_x(pg1, s1788, t1707);
        t1710 = svadd_f64_x(pg1, s1789, t1708);
        t1711 = svmls_n_f64_x(pg1, s1788, t1707, 0.5);
        t1712 = svmls_n_f64_x(pg1, s1789, t1708, 0.5);
        s1868 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1816, s1843), 0.8660254037844386);
        s1869 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1815, s1842), 0.8660254037844386);
        s1870 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1710, D23[1]), t1709, D23[0]);
        s1871 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1710, D23[0]), t1709, D23[1]);
        t1713 = svadd_f64_x(pg1, t1711, s1868);
        t1714 = svsub_f64_x(pg1, t1712, s1869);
        t1715 = svsub_f64_x(pg1, t1711, s1868);
        t1716 = svadd_f64_x(pg1, t1712, s1869);
        s1872 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1714, D24[1]), t1713, D24[0]);
        s1873 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1714, D24[0]), t1713, D24[1]);
        s1874 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1716, D24[3]), t1715, D24[2]);
        s1875 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1716, D24[2]), t1715, D24[3]);
        t1717 = svadd_f64_x(pg1, s1818, s1845);
        t1718 = svadd_f64_x(pg1, s1819, s1846);
        t1719 = svadd_f64_x(pg1, s1791, t1717);
        t1720 = svadd_f64_x(pg1, s1792, t1718);
        t1721 = svmls_n_f64_x(pg1, s1791, t1717, 0.5);
        t1722 = svmls_n_f64_x(pg1, s1792, t1718, 0.5);
        s1876 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1819, s1846), 0.8660254037844386);
        s1877 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1818, s1845), 0.8660254037844386);
        s1878 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1720, D23[3]), t1719, D23[2]);
        s1879 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1720, D23[2]), t1719, D23[3]);
        t1723 = svadd_f64_x(pg1, t1721, s1876);
        t1724 = svsub_f64_x(pg1, t1722, s1877);
        t1725 = svsub_f64_x(pg1, t1721, s1876);
        t1726 = svadd_f64_x(pg1, t1722, s1877);
        s1880 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1724, D24[5]), t1723, D24[4]);
        s1881 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1724, D24[4]), t1723, D24[5]);
        s1882 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1726, D24[7]), t1725, D24[6]);
        s1883 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1726, D24[6]), t1725, D24[7]);
        t1727 = svadd_f64_x(pg1, s1821, s1848);
        t1728 = svadd_f64_x(pg1, s1822, s1849);
        t1729 = svadd_f64_x(pg1, s1794, t1727);
        t1730 = svadd_f64_x(pg1, s1795, t1728);
        t1731 = svmls_n_f64_x(pg1, s1794, t1727, 0.5);
        t1732 = svmls_n_f64_x(pg1, s1795, t1728, 0.5);
        s1884 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1822, s1849), 0.8660254037844386);
        s1885 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1821, s1848), 0.8660254037844386);
        s1886 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1730, D23[5]), t1729, D23[4]);
        s1887 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1730, D23[4]), t1729, D23[5]);
        t1733 = svadd_f64_x(pg1, t1731, s1884);
        t1734 = svsub_f64_x(pg1, t1732, s1885);
        t1735 = svsub_f64_x(pg1, t1731, s1884);
        t1736 = svadd_f64_x(pg1, t1732, s1885);
        s1888 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1734, D24[9]), t1733, D24[8]);
        s1889 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1734, D24[8]), t1733, D24[9]);
        s1890 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1736, D24[11]), t1735, D24[10]);
        s1891 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1736, D24[10]), t1735, D24[11]);
        t1737 = svadd_f64_x(pg1, s1824, s1851);
        t1738 = svadd_f64_x(pg1, s1825, s1852);
        t1739 = svadd_f64_x(pg1, s1797, t1737);
        t1740 = svadd_f64_x(pg1, s1798, t1738);
        t1741 = svmls_n_f64_x(pg1, s1797, t1737, 0.5);
        t1742 = svmls_n_f64_x(pg1, s1798, t1738, 0.5);
        s1892 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1825, s1852), 0.8660254037844386);
        s1893 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1824, s1851), 0.8660254037844386);
        s1894 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1740, D23[7]), t1739, D23[6]);
        s1895 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1740, D23[6]), t1739, D23[7]);
        t1743 = svadd_f64_x(pg1, t1741, s1892);
        t1744 = svsub_f64_x(pg1, t1742, s1893);
        t1745 = svsub_f64_x(pg1, t1741, s1892);
        t1746 = svadd_f64_x(pg1, t1742, s1893);
        s1896 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1744, D24[13]), t1743, D24[12]);
        s1897 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1744, D24[12]), t1743, D24[13]);
        s1898 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1746, D24[15]), t1745, D24[14]);
        s1899 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1746, D24[14]), t1745, D24[15]);
        t1747 = svadd_f64_x(pg1, s1827, s1854);
        t1748 = svadd_f64_x(pg1, s1828, s1855);
        t1749 = svadd_f64_x(pg1, s1800, t1747);
        t1750 = svadd_f64_x(pg1, s1801, t1748);
        t1751 = svmls_n_f64_x(pg1, s1800, t1747, 0.5);
        t1752 = svmls_n_f64_x(pg1, s1801, t1748, 0.5);
        s1900 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1828, s1855), 0.8660254037844386);
        s1901 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1827, s1854), 0.8660254037844386);
        s1902 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1750, D23[9]), t1749, D23[8]);
        s1903 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1750, D23[8]), t1749, D23[9]);
        t1753 = svadd_f64_x(pg1, t1751, s1900);
        t1754 = svsub_f64_x(pg1, t1752, s1901);
        t1755 = svsub_f64_x(pg1, t1751, s1900);
        t1756 = svadd_f64_x(pg1, t1752, s1901);
        s1904 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1754, D24[17]), t1753, D24[16]);
        s1905 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1754, D24[16]), t1753, D24[17]);
        s1906 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1756, D24[19]), t1755, D24[18]);
        s1907 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1756, D24[18]), t1755, D24[19]);
        t1757 = svadd_f64_x(pg1, s1830, s1857);
        t1758 = svadd_f64_x(pg1, s1831, s1858);
        t1759 = svadd_f64_x(pg1, s1803, t1757);
        t1760 = svadd_f64_x(pg1, s1804, t1758);
        t1761 = svmls_n_f64_x(pg1, s1803, t1757, 0.5);
        t1762 = svmls_n_f64_x(pg1, s1804, t1758, 0.5);
        s1908 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1831, s1858), 0.8660254037844386);
        s1909 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1830, s1857), 0.8660254037844386);
        s1910 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1760, D23[11]), t1759, D23[10]);
        s1911 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1760, D23[10]), t1759, D23[11]);
        t1763 = svadd_f64_x(pg1, t1761, s1908);
        t1764 = svsub_f64_x(pg1, t1762, s1909);
        t1765 = svsub_f64_x(pg1, t1761, s1908);
        t1766 = svadd_f64_x(pg1, t1762, s1909);
        s1912 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1764, D24[21]), t1763, D24[20]);
        s1913 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1764, D24[20]), t1763, D24[21]);
        s1914 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1766, D24[23]), t1765, D24[22]);
        s1915 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1766, D24[22]), t1765, D24[23]);
        t1767 = svadd_f64_x(pg1, s1833, s1860);
        t1768 = svadd_f64_x(pg1, s1834, s1861);
        t1769 = svadd_f64_x(pg1, s1806, t1767);
        t1770 = svadd_f64_x(pg1, s1807, t1768);
        t1771 = svmls_n_f64_x(pg1, s1806, t1767, 0.5);
        t1772 = svmls_n_f64_x(pg1, s1807, t1768, 0.5);
        s1916 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1834, s1861), 0.8660254037844386);
        s1917 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1833, s1860), 0.8660254037844386);
        s1918 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1770, D23[13]), t1769, D23[12]);
        s1919 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1770, D23[12]), t1769, D23[13]);
        t1773 = svadd_f64_x(pg1, t1771, s1916);
        t1774 = svsub_f64_x(pg1, t1772, s1917);
        t1775 = svsub_f64_x(pg1, t1771, s1916);
        t1776 = svadd_f64_x(pg1, t1772, s1917);
        s1920 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1774, D24[25]), t1773, D24[24]);
        s1921 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1774, D24[24]), t1773, D24[25]);
        s1922 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1776, D24[27]), t1775, D24[26]);
        s1923 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1776, D24[26]), t1775, D24[27]);
        t1777 = svadd_f64_x(pg1, s1836, s1863);
        t1778 = svadd_f64_x(pg1, s1837, s1864);
        t1779 = svadd_f64_x(pg1, s1809, t1777);
        t1780 = svadd_f64_x(pg1, s1810, t1778);
        t1781 = svmls_n_f64_x(pg1, s1809, t1777, 0.5);
        t1782 = svmls_n_f64_x(pg1, s1810, t1778, 0.5);
        s1924 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1837, s1864), 0.8660254037844386);
        s1925 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1836, s1863), 0.8660254037844386);
        s1926 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1780, D23[15]), t1779, D23[14]);
        s1927 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1780, D23[14]), t1779, D23[15]);
        t1783 = svadd_f64_x(pg1, t1781, s1924);
        t1784 = svsub_f64_x(pg1, t1782, s1925);
        t1785 = svsub_f64_x(pg1, t1781, s1924);
        t1786 = svadd_f64_x(pg1, t1782, s1925);
        s1928 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1784, D24[29]), t1783, D24[28]);
        s1929 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1784, D24[28]), t1783, D24[29]);
        s1930 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1786, D24[31]), t1785, D24[30]);
        s1931 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1786, D24[30]), t1785, D24[31]);
        t1787 = svadd_f64_x(pg1, s1839, s1866);
        t1788 = svadd_f64_x(pg1, s1840, s1867);
        t1789 = svadd_f64_x(pg1, s1812, t1787);
        t1790 = svadd_f64_x(pg1, s1813, t1788);
        t1791 = svmls_n_f64_x(pg1, s1812, t1787, 0.5);
        t1792 = svmls_n_f64_x(pg1, s1813, t1788, 0.5);
        s1932 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1840, s1867), 0.8660254037844386);
        s1933 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1839, s1866), 0.8660254037844386);
        s1934 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1790, D23[17]), t1789, D23[16]);
        s1935 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1790, D23[16]), t1789, D23[17]);
        t1793 = svadd_f64_x(pg1, t1791, s1932);
        t1794 = svsub_f64_x(pg1, t1792, s1933);
        t1795 = svsub_f64_x(pg1, t1791, s1932);
        t1796 = svadd_f64_x(pg1, t1792, s1933);
        s1936 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1794, D24[33]), t1793, D24[32]);
        s1937 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1794, D24[32]), t1793, D24[33]);
        s1938 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t1796, D24[35]), t1795, D24[34]);
        s1939 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t1796, D24[34]), t1795, D24[35]);
        t1797 = svadd_f64_x(pg1, s1894, s1918);
        t1798 = svadd_f64_x(pg1, s1895, s1919);
        t1799 = svadd_f64_x(pg1, s1870, t1797);
        t1800 = svadd_f64_x(pg1, s1871, t1798);
        t1801 = svmls_n_f64_x(pg1, s1870, t1797, 0.5);
        t1802 = svmls_n_f64_x(pg1, s1871, t1798, 0.5);
        s1940 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1895, s1919), 0.8660254037844386);
        s1941 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1894, s1918), 0.8660254037844386);
        t1803 = svadd_f64_x(pg1, t1801, s1940);
        t1804 = svsub_f64_x(pg1, t1802, s1941);
        t1805 = svsub_f64_x(pg1, t1801, s1940);
        t1806 = svadd_f64_x(pg1, t1802, s1941);
        t1807 = svadd_f64_x(pg1, s1902, s1926);
        t1808 = svadd_f64_x(pg1, s1903, s1927);
        t1809 = svadd_f64_x(pg1, s1878, t1807);
        t1810 = svadd_f64_x(pg1, s1879, t1808);
        t1811 = svmls_n_f64_x(pg1, s1878, t1807, 0.5);
        t1812 = svmls_n_f64_x(pg1, s1879, t1808, 0.5);
        s1942 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1903, s1927), 0.8660254037844386);
        s1943 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1902, s1926), 0.8660254037844386);
        t1813 = svadd_f64_x(pg1, t1811, s1942);
        t1814 = svsub_f64_x(pg1, t1812, s1943);
        t1815 = svsub_f64_x(pg1, t1811, s1942);
        t1816 = svadd_f64_x(pg1, t1812, s1943);
        s2106 = svmla_n_f64_x(pg1, t1813, t1814, 0.83909963117727981);
        s1944 = svmul_n_f64_x(pg1, s2106, 0.76604444311897812);
        s2107 = svmls_n_f64_x(pg1, t1814, t1813, 0.83909963117727981);
        s1945 = svmul_n_f64_x(pg1, s2107, 0.76604444311897812);
        s2108 = svmla_n_f64_x(pg1, t1815, t1816, 5.6712818196177102);
        s1946 = svmul_n_f64_x(pg1, s2108, 0.17364817766693033);
        s2109 = svmls_n_f64_x(pg1, t1816, t1815, 5.6712818196177102);
        s1947 = svmul_n_f64_x(pg1, s2109, 0.17364817766693033);
        t1817 = svadd_f64_x(pg1, s1910, s1934);
        t1818 = svadd_f64_x(pg1, s1911, s1935);
        t1819 = svadd_f64_x(pg1, s1886, t1817);
        t1820 = svadd_f64_x(pg1, s1887, t1818);
        t1821 = svmls_n_f64_x(pg1, s1886, t1817, 0.5);
        t1822 = svmls_n_f64_x(pg1, s1887, t1818, 0.5);
        s1948 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1911, s1935), 0.8660254037844386);
        s1949 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1910, s1934), 0.8660254037844386);
        t1823 = svadd_f64_x(pg1, t1821, s1948);
        t1824 = svsub_f64_x(pg1, t1822, s1949);
        t1825 = svsub_f64_x(pg1, t1821, s1948);
        t1826 = svadd_f64_x(pg1, t1822, s1949);
        s2110 = svmla_n_f64_x(pg1, t1823, t1824, 5.6712818196177102);
        s1950 = svmul_n_f64_x(pg1, s2110, 0.17364817766693033);
        s2111 = svmls_n_f64_x(pg1, t1824, t1823, 5.6712818196177102);
        s1951 = svmul_n_f64_x(pg1, s2111, 0.17364817766693033);
        s2112 = svmls_n_f64_x(pg1, t1826, t1825, 2.7474774194546225);
        s1952 = svmul_n_f64_x(pg1, s2112, 0.34202014332566871);
        s2113 = svmla_n_f64_x(pg1, t1825, t1826, 2.7474774194546225);
        s1953 = svmul_n_f64_x(pg1, s2113, 0.34202014332566871);
        t1827 = svadd_f64_x(pg1, t1809, t1819);
        t1828 = svadd_f64_x(pg1, t1810, t1820);
        t1829 = svmls_n_f64_x(pg1, t1799, t1827, 0.5);
        t1830 = svmls_n_f64_x(pg1, t1800, t1828, 0.5);
        s1954 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1810, t1820), 0.8660254037844386);
        s1955 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1809, t1819), 0.8660254037844386);
        s1956 = svadd_f64_x(pg1, t1799, t1827);
        s1957 = svadd_f64_x(pg1, t1800, t1828);
        s1958 = svadd_f64_x(pg1, t1829, s1954);
        s1959 = svsub_f64_x(pg1, t1830, s1955);
        s1960 = svsub_f64_x(pg1, t1829, s1954);
        s1961 = svadd_f64_x(pg1, t1830, s1955);
        t1831 = svadd_f64_x(pg1, s1944, s1950);
        t1832 = svadd_f64_x(pg1, s1945, s1951);
        t1833 = svmls_n_f64_x(pg1, t1803, t1831, 0.5);
        t1834 = svmls_n_f64_x(pg1, t1804, t1832, 0.5);
        s1962 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1945, s1951), 0.8660254037844386);
        s1963 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1944, s1950), 0.8660254037844386);
        s1964 = svadd_f64_x(pg1, t1803, t1831);
        s1965 = svadd_f64_x(pg1, t1804, t1832);
        s1966 = svadd_f64_x(pg1, t1833, s1962);
        s1967 = svsub_f64_x(pg1, t1834, s1963);
        s1968 = svsub_f64_x(pg1, t1833, s1962);
        s1969 = svadd_f64_x(pg1, t1834, s1963);
        t1835 = svadd_f64_x(pg1, s1946, s1952);
        t1836 = svsub_f64_x(pg1, s1947, s1953);
        t1837 = svmls_n_f64_x(pg1, t1805, t1835, 0.5);
        t1838 = svmls_n_f64_x(pg1, t1806, t1836, 0.5);
        s1970 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1947, s1953), 0.8660254037844386);
        s1971 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1946, s1952), 0.8660254037844386);
        s1972 = svadd_f64_x(pg1, t1805, t1835);
        s1973 = svadd_f64_x(pg1, t1806, t1836);
        s1974 = svadd_f64_x(pg1, t1837, s1970);
        s1975 = svsub_f64_x(pg1, t1838, s1971);
        s1976 = svsub_f64_x(pg1, t1837, s1970);
        s1977 = svadd_f64_x(pg1, t1838, s1971);
        t1839 = svadd_f64_x(pg1, s1896, s1920);
        t1840 = svadd_f64_x(pg1, s1897, s1921);
        t1841 = svadd_f64_x(pg1, s1872, t1839);
        t1842 = svadd_f64_x(pg1, s1873, t1840);
        t1843 = svmls_n_f64_x(pg1, s1872, t1839, 0.5);
        t1844 = svmls_n_f64_x(pg1, s1873, t1840, 0.5);
        s1978 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1897, s1921), 0.8660254037844386);
        s1979 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1896, s1920), 0.8660254037844386);
        t1845 = svadd_f64_x(pg1, t1843, s1978);
        t1846 = svsub_f64_x(pg1, t1844, s1979);
        t1847 = svsub_f64_x(pg1, t1843, s1978);
        t1848 = svadd_f64_x(pg1, t1844, s1979);
        t1849 = svadd_f64_x(pg1, s1904, s1928);
        t1850 = svadd_f64_x(pg1, s1905, s1929);
        t1851 = svadd_f64_x(pg1, s1880, t1849);
        t1852 = svadd_f64_x(pg1, s1881, t1850);
        t1853 = svmls_n_f64_x(pg1, s1880, t1849, 0.5);
        t1854 = svmls_n_f64_x(pg1, s1881, t1850, 0.5);
        s1980 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1905, s1929), 0.8660254037844386);
        s1981 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1904, s1928), 0.8660254037844386);
        t1855 = svadd_f64_x(pg1, t1853, s1980);
        t1856 = svsub_f64_x(pg1, t1854, s1981);
        t1857 = svsub_f64_x(pg1, t1853, s1980);
        t1858 = svadd_f64_x(pg1, t1854, s1981);
        s2114 = svmla_n_f64_x(pg1, t1855, t1856, 0.83909963117727981);
        s1982 = svmul_n_f64_x(pg1, s2114, 0.76604444311897812);
        s2115 = svmls_n_f64_x(pg1, t1856, t1855, 0.83909963117727981);
        s1983 = svmul_n_f64_x(pg1, s2115, 0.76604444311897812);
        s2116 = svmla_n_f64_x(pg1, t1857, t1858, 5.6712818196177102);
        s1984 = svmul_n_f64_x(pg1, s2116, 0.17364817766693033);
        s2117 = svmls_n_f64_x(pg1, t1858, t1857, 5.6712818196177102);
        s1985 = svmul_n_f64_x(pg1, s2117, 0.17364817766693033);
        t1859 = svadd_f64_x(pg1, s1912, s1936);
        t1860 = svadd_f64_x(pg1, s1913, s1937);
        t1861 = svadd_f64_x(pg1, s1888, t1859);
        t1862 = svadd_f64_x(pg1, s1889, t1860);
        t1863 = svmls_n_f64_x(pg1, s1888, t1859, 0.5);
        t1864 = svmls_n_f64_x(pg1, s1889, t1860, 0.5);
        s1986 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1913, s1937), 0.8660254037844386);
        s1987 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1912, s1936), 0.8660254037844386);
        t1865 = svadd_f64_x(pg1, t1863, s1986);
        t1866 = svsub_f64_x(pg1, t1864, s1987);
        t1867 = svsub_f64_x(pg1, t1863, s1986);
        t1868 = svadd_f64_x(pg1, t1864, s1987);
        s2118 = svmla_n_f64_x(pg1, t1865, t1866, 5.6712818196177102);
        s1988 = svmul_n_f64_x(pg1, s2118, 0.17364817766693033);
        s2119 = svmls_n_f64_x(pg1, t1866, t1865, 5.6712818196177102);
        s1989 = svmul_n_f64_x(pg1, s2119, 0.17364817766693033);
        s2120 = svmls_n_f64_x(pg1, t1868, t1867, 2.7474774194546225);
        s1990 = svmul_n_f64_x(pg1, s2120, 0.34202014332566871);
        s2121 = svmla_n_f64_x(pg1, t1867, t1868, 2.7474774194546225);
        s1991 = svmul_n_f64_x(pg1, s2121, 0.34202014332566871);
        t1869 = svadd_f64_x(pg1, t1851, t1861);
        t1870 = svadd_f64_x(pg1, t1852, t1862);
        t1871 = svmls_n_f64_x(pg1, t1841, t1869, 0.5);
        t1872 = svmls_n_f64_x(pg1, t1842, t1870, 0.5);
        s1992 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1852, t1862), 0.8660254037844386);
        s1993 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1851, t1861), 0.8660254037844386);
        s1994 = svadd_f64_x(pg1, t1841, t1869);
        s1995 = svadd_f64_x(pg1, t1842, t1870);
        s1996 = svadd_f64_x(pg1, t1871, s1992);
        s1997 = svsub_f64_x(pg1, t1872, s1993);
        s1998 = svsub_f64_x(pg1, t1871, s1992);
        s1999 = svadd_f64_x(pg1, t1872, s1993);
        t1873 = svadd_f64_x(pg1, s1982, s1988);
        t1874 = svadd_f64_x(pg1, s1983, s1989);
        t1875 = svmls_n_f64_x(pg1, t1845, t1873, 0.5);
        t1876 = svmls_n_f64_x(pg1, t1846, t1874, 0.5);
        s2000 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1983, s1989), 0.8660254037844386);
        s2001 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1982, s1988), 0.8660254037844386);
        s2002 = svadd_f64_x(pg1, t1845, t1873);
        s2003 = svadd_f64_x(pg1, t1846, t1874);
        s2004 = svadd_f64_x(pg1, t1875, s2000);
        s2005 = svsub_f64_x(pg1, t1876, s2001);
        s2006 = svsub_f64_x(pg1, t1875, s2000);
        s2007 = svadd_f64_x(pg1, t1876, s2001);
        t1877 = svadd_f64_x(pg1, s1984, s1990);
        t1878 = svsub_f64_x(pg1, s1985, s1991);
        t1879 = svmls_n_f64_x(pg1, t1847, t1877, 0.5);
        t1880 = svmls_n_f64_x(pg1, t1848, t1878, 0.5);
        s2008 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s1985, s1991), 0.8660254037844386);
        s2009 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1984, s1990), 0.8660254037844386);
        s2010 = svadd_f64_x(pg1, t1847, t1877);
        s2011 = svadd_f64_x(pg1, t1848, t1878);
        s2012 = svadd_f64_x(pg1, t1879, s2008);
        s2013 = svsub_f64_x(pg1, t1880, s2009);
        s2014 = svsub_f64_x(pg1, t1879, s2008);
        s2015 = svadd_f64_x(pg1, t1880, s2009);
        t1881 = svadd_f64_x(pg1, s1898, s1922);
        t1882 = svadd_f64_x(pg1, s1899, s1923);
        t1883 = svadd_f64_x(pg1, s1874, t1881);
        t1884 = svadd_f64_x(pg1, s1875, t1882);
        t1885 = svmls_n_f64_x(pg1, s1874, t1881, 0.5);
        t1886 = svmls_n_f64_x(pg1, s1875, t1882, 0.5);
        s2016 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1899, s1923), 0.8660254037844386);
        s2017 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1898, s1922), 0.8660254037844386);
        t1887 = svadd_f64_x(pg1, t1885, s2016);
        t1888 = svsub_f64_x(pg1, t1886, s2017);
        t1889 = svsub_f64_x(pg1, t1885, s2016);
        t1890 = svadd_f64_x(pg1, t1886, s2017);
        t1891 = svadd_f64_x(pg1, s1906, s1930);
        t1892 = svadd_f64_x(pg1, s1907, s1931);
        t1893 = svadd_f64_x(pg1, s1882, t1891);
        t1894 = svadd_f64_x(pg1, s1883, t1892);
        t1895 = svmls_n_f64_x(pg1, s1882, t1891, 0.5);
        t1896 = svmls_n_f64_x(pg1, s1883, t1892, 0.5);
        s2018 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1907, s1931), 0.8660254037844386);
        s2019 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1906, s1930), 0.8660254037844386);
        t1897 = svadd_f64_x(pg1, t1895, s2018);
        t1898 = svsub_f64_x(pg1, t1896, s2019);
        t1899 = svsub_f64_x(pg1, t1895, s2018);
        t1900 = svadd_f64_x(pg1, t1896, s2019);
        s2122 = svmla_n_f64_x(pg1, t1897, t1898, 0.83909963117727981);
        s2020 = svmul_n_f64_x(pg1, s2122, 0.76604444311897812);
        s2123 = svmls_n_f64_x(pg1, t1898, t1897, 0.83909963117727981);
        s2021 = svmul_n_f64_x(pg1, s2123, 0.76604444311897812);
        s2124 = svmla_n_f64_x(pg1, t1899, t1900, 5.6712818196177102);
        s2022 = svmul_n_f64_x(pg1, s2124, 0.17364817766693033);
        s2125 = svmls_n_f64_x(pg1, t1900, t1899, 5.6712818196177102);
        s2023 = svmul_n_f64_x(pg1, s2125, 0.17364817766693033);
        t1901 = svadd_f64_x(pg1, s1914, s1938);
        t1902 = svadd_f64_x(pg1, s1915, s1939);
        t1903 = svadd_f64_x(pg1, s1890, t1901);
        t1904 = svadd_f64_x(pg1, s1891, t1902);
        t1905 = svmls_n_f64_x(pg1, s1890, t1901, 0.5);
        t1906 = svmls_n_f64_x(pg1, s1891, t1902, 0.5);
        s2024 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1915, s1939), 0.8660254037844386);
        s2025 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s1914, s1938), 0.8660254037844386);
        t1907 = svadd_f64_x(pg1, t1905, s2024);
        t1908 = svsub_f64_x(pg1, t1906, s2025);
        t1909 = svsub_f64_x(pg1, t1905, s2024);
        t1910 = svadd_f64_x(pg1, t1906, s2025);
        s2126 = svmla_n_f64_x(pg1, t1907, t1908, 5.6712818196177102);
        s2026 = svmul_n_f64_x(pg1, s2126, 0.17364817766693033);
        s2127 = svmls_n_f64_x(pg1, t1908, t1907, 5.6712818196177102);
        s2027 = svmul_n_f64_x(pg1, s2127, 0.17364817766693033);
        s2128 = svmls_n_f64_x(pg1, t1910, t1909, 2.7474774194546225);
        s2028 = svmul_n_f64_x(pg1, s2128, 0.34202014332566871);
        s2129 = svmla_n_f64_x(pg1, t1909, t1910, 2.7474774194546225);
        s2029 = svmul_n_f64_x(pg1, s2129, 0.34202014332566871);
        t1911 = svadd_f64_x(pg1, t1893, t1903);
        t1912 = svadd_f64_x(pg1, t1894, t1904);
        t1913 = svmls_n_f64_x(pg1, t1883, t1911, 0.5);
        t1914 = svmls_n_f64_x(pg1, t1884, t1912, 0.5);
        s2030 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1894, t1904), 0.8660254037844386);
        s2031 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1893, t1903), 0.8660254037844386);
        s2032 = svadd_f64_x(pg1, t1883, t1911);
        s2033 = svadd_f64_x(pg1, t1884, t1912);
        s2034 = svadd_f64_x(pg1, t1913, s2030);
        s2035 = svsub_f64_x(pg1, t1914, s2031);
        s2036 = svsub_f64_x(pg1, t1913, s2030);
        s2037 = svadd_f64_x(pg1, t1914, s2031);
        t1915 = svadd_f64_x(pg1, s2020, s2026);
        t1916 = svadd_f64_x(pg1, s2021, s2027);
        t1917 = svmls_n_f64_x(pg1, t1887, t1915, 0.5);
        t1918 = svmls_n_f64_x(pg1, t1888, t1916, 0.5);
        s2038 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2021, s2027), 0.8660254037844386);
        s2039 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2020, s2026), 0.8660254037844386);
        s2040 = svadd_f64_x(pg1, t1887, t1915);
        s2041 = svadd_f64_x(pg1, t1888, t1916);
        s2042 = svadd_f64_x(pg1, t1917, s2038);
        s2043 = svsub_f64_x(pg1, t1918, s2039);
        s2044 = svsub_f64_x(pg1, t1917, s2038);
        s2045 = svadd_f64_x(pg1, t1918, s2039);
        t1919 = svadd_f64_x(pg1, s2022, s2028);
        t1920 = svsub_f64_x(pg1, s2023, s2029);
        t1921 = svmls_n_f64_x(pg1, t1889, t1919, 0.5);
        t1922 = svmls_n_f64_x(pg1, t1890, t1920, 0.5);
        s2046 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s2023, s2029), 0.8660254037844386);
        s2047 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s2022, s2028), 0.8660254037844386);
        s2048 = svadd_f64_x(pg1, t1889, t1919);
        s2049 = svadd_f64_x(pg1, t1890, t1920);
        s2050 = svadd_f64_x(pg1, t1921, s2046);
        s2051 = svsub_f64_x(pg1, t1922, s2047);
        s2052 = svsub_f64_x(pg1, t1921, s2046);
        s2053 = svadd_f64_x(pg1, t1922, s2047);
        a3434 = (TW1 + ((52)*(j1)));
        a3435 = svld1_gather_u64offset_f64(pg1, a3434, svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3436 = svld1_gather_u64offset_f64(pg1, (a3434 + 1), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2054 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3436, s1995), a3435, s1994);
        s2055 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3435, s1995), a3436, s1994);
        a3437 = svld1_gather_u64offset_f64(pg1, (a3434 + 2), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3438 = svld1_gather_u64offset_f64(pg1, (a3434 + 3), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2056 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3438, s2033), a3437, s2032);
        s2057 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3437, s2033), a3438, s2032);
        a3439 = svld1_gather_u64offset_f64(pg1, (a3434 + 4), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3440 = svld1_gather_u64offset_f64(pg1, (a3434 + 5), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2058 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3440, s1965), a3439, s1964);
        s2059 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3439, s1965), a3440, s1964);
        a3441 = svld1_gather_u64offset_f64(pg1, (a3434 + 6), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3442 = svld1_gather_u64offset_f64(pg1, (a3434 + 7), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2060 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3442, s2003), a3441, s2002);
        s2061 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3441, s2003), a3442, s2002);
        a3443 = svld1_gather_u64offset_f64(pg1, (a3434 + 8), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3444 = svld1_gather_u64offset_f64(pg1, (a3434 + 9), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2062 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3444, s2041), a3443, s2040);
        s2063 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3443, s2041), a3444, s2040);
        a3445 = svld1_gather_u64offset_f64(pg1, (a3434 + 10), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3446 = svld1_gather_u64offset_f64(pg1, (a3434 + 11), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2064 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3446, s1973), a3445, s1972);
        s2065 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3445, s1973), a3446, s1972);
        a3447 = svld1_gather_u64offset_f64(pg1, (a3434 + 12), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3448 = svld1_gather_u64offset_f64(pg1, (a3434 + 13), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2066 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3448, s2011), a3447, s2010);
        s2067 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3447, s2011), a3448, s2010);
        a3449 = svld1_gather_u64offset_f64(pg1, (a3434 + 14), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3450 = svld1_gather_u64offset_f64(pg1, (a3434 + 15), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2068 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3450, s2049), a3449, s2048);
        s2069 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3449, s2049), a3450, s2048);
        a3451 = svld1_gather_u64offset_f64(pg1, (a3434 + 16), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3452 = svld1_gather_u64offset_f64(pg1, (a3434 + 17), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2070 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3452, s1959), a3451, s1958);
        s2071 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3451, s1959), a3452, s1958);
        a3453 = svld1_gather_u64offset_f64(pg1, (a3434 + 18), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3454 = svld1_gather_u64offset_f64(pg1, (a3434 + 19), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2072 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3454, s1997), a3453, s1996);
        s2073 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3453, s1997), a3454, s1996);
        a3455 = svld1_gather_u64offset_f64(pg1, (a3434 + 20), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3456 = svld1_gather_u64offset_f64(pg1, (a3434 + 21), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2074 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3456, s2035), a3455, s2034);
        s2075 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3455, s2035), a3456, s2034);
        a3457 = svld1_gather_u64offset_f64(pg1, (a3434 + 22), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3458 = svld1_gather_u64offset_f64(pg1, (a3434 + 23), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2076 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3458, s1967), a3457, s1966);
        s2077 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3457, s1967), a3458, s1966);
        a3459 = svld1_gather_u64offset_f64(pg1, (a3434 + 24), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3460 = svld1_gather_u64offset_f64(pg1, (a3434 + 25), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2078 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3460, s2005), a3459, s2004);
        s2079 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3459, s2005), a3460, s2004);
        a3461 = svld1_gather_u64offset_f64(pg1, (a3434 + 26), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3462 = svld1_gather_u64offset_f64(pg1, (a3434 + 27), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2080 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3462, s2043), a3461, s2042);
        s2081 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3461, s2043), a3462, s2042);
        a3463 = svld1_gather_u64offset_f64(pg1, (a3434 + 28), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3464 = svld1_gather_u64offset_f64(pg1, (a3434 + 29), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2082 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3464, s1975), a3463, s1974);
        s2083 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3463, s1975), a3464, s1974);
        a3465 = svld1_gather_u64offset_f64(pg1, (a3434 + 30), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3466 = svld1_gather_u64offset_f64(pg1, (a3434 + 31), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2084 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3466, s2013), a3465, s2012);
        s2085 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3465, s2013), a3466, s2012);
        a3467 = svld1_gather_u64offset_f64(pg1, (a3434 + 32), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3468 = svld1_gather_u64offset_f64(pg1, (a3434 + 33), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2086 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3468, s2051), a3467, s2050);
        s2087 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3467, s2051), a3468, s2050);
        a3469 = svld1_gather_u64offset_f64(pg1, (a3434 + 34), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3470 = svld1_gather_u64offset_f64(pg1, (a3434 + 35), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2088 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3470, s1961), a3469, s1960);
        s2089 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3469, s1961), a3470, s1960);
        a3471 = svld1_gather_u64offset_f64(pg1, (a3434 + 36), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3472 = svld1_gather_u64offset_f64(pg1, (a3434 + 37), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2090 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3472, s1999), a3471, s1998);
        s2091 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3471, s1999), a3472, s1998);
        a3473 = svld1_gather_u64offset_f64(pg1, (a3434 + 38), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3474 = svld1_gather_u64offset_f64(pg1, (a3434 + 39), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2092 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3474, s2037), a3473, s2036);
        s2093 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3473, s2037), a3474, s2036);
        a3475 = svld1_gather_u64offset_f64(pg1, (a3434 + 40), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3476 = svld1_gather_u64offset_f64(pg1, (a3434 + 41), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2094 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3476, s1969), a3475, s1968);
        s2095 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3475, s1969), a3476, s1968);
        a3477 = svld1_gather_u64offset_f64(pg1, (a3434 + 42), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3478 = svld1_gather_u64offset_f64(pg1, (a3434 + 43), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2096 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3478, s2007), a3477, s2006);
        s2097 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3477, s2007), a3478, s2006);
        a3479 = svld1_gather_u64offset_f64(pg1, (a3434 + 44), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3480 = svld1_gather_u64offset_f64(pg1, (a3434 + 45), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2098 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3480, s2045), a3479, s2044);
        s2099 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3479, s2045), a3480, s2044);
        a3481 = svld1_gather_u64offset_f64(pg1, (a3434 + 46), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3482 = svld1_gather_u64offset_f64(pg1, (a3434 + 47), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2100 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3482, s1977), a3481, s1976);
        s2101 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3481, s1977), a3482, s1976);
        a3483 = svld1_gather_u64offset_f64(pg1, (a3434 + 48), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3484 = svld1_gather_u64offset_f64(pg1, (a3434 + 49), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2102 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3484, s2015), a3483, s2014);
        s2103 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3483, s2015), a3484, s2014);
        a3485 = svld1_gather_u64offset_f64(pg1, (a3434 + 50), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        a3486 = svld1_gather_u64offset_f64(pg1, (a3434 + 51), svindex_u64(0, (int64_t)(52 * sizeof(float64_t))));
        s2104 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3486, s2053), a3485, s2052);
        s2105 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3485, s2053), a3486, s2052);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s1956);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s1957);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2054);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2055);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2056);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2057);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2058);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2059);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2060);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2061);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2062);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2063);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2064);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2065);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2066);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2067);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2068);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2069);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2070);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2071);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2072);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2073);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2074);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2075);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2076);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2077);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2078);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2079);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2080);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2081);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2082);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2083);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2084);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2085);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2086);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2087);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2088);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2089);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2090);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2091);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(40 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2092);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(41 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2093);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(42 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2094);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(43 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2095);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(44 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2096);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(45 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2097);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(46 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2098);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(47 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2099);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(48 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2100);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(49 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2101);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(50 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2102);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(51 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2103);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(52 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2104);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(53 + Y + ((54)*(j1)))), svindex_u64(0, (int64_t)(54 * sizeof(float64_t))), s2105);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
