/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft20a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D23[40];
    int l1;
    float64_t  *a3984;
    svfloat64x2_t s1908, s1911, s1914, s1917, s1920, s1923, s1926, s1929, 
            s1932, s1935, s1938, s1941, s1944, s1947, s1950, s1953, 
            s1956, s1959, s1962, s1965;
    svfloat64_t a3985, a3986, a3987, a3988, a3989, a3990, a3991, a3992, 
            a3993, a3994, a3995, a3996, a3997, a3998, a3999, a4000, 
            a4001, a4002, a4003, a4004, a4005, a4006, a4007, a4008, 
            a4009, a4010, a4011, a4012, a4013, a4014, a4015, a4016, 
            a4017, a4018, a4019, a4020, a4021, a4022, s1909, s1910, 
            s1912, s1913, s1915, s1916, s1918, s1919, s1921, s1922, 
            s1924, s1925, s1927, s1928, s1930, s1931, s1933, s1934, 
            s1936, s1937, s1939, s1940, s1942, s1943, s1945, s1946, 
            s1948, s1949, s1951, s1952, s1954, s1955, s1957, s1958, 
            s1960, s1961, s1963, s1964, s1966, s1967, s1968, s1969, 
            s1970, s1971, s1972, s1973, s1974, s1975, s1976, s1977, 
            s1978, s1979, s1980, s1981, s1982, s1983, s1984, s1985, 
            s1986, s1987, s1988, s1989, s1990, s1991, s1992, s1993, 
            s1994, s1995, s1996, s1997, s1998, s1999, s2000, s2001, 
            s2002, s2003, s2004, s2005, s2006, s2007, s2008, s2009, 
            s2010, s2011, s2012, s2013, s2014, s2015, s2016, s2017, 
            s2018, s2019, s2020, s2021, s2022, s2023, s2024, s2025, 
            s2026, s2027, s2028, s2029, s2030, s2031, s2032, s2033, 
            s2034, s2035, s2036, s2037, s2038, s2039, s2040, s2041, 
            s2042, s2043, s2044, s2045, s2046, s2047, s2048, s2049, 
            s2050, s2051, s2052, s2053, s2054, s2055, s2056, s2057, 
            s2058, s2059, s2060, s2061, s2062, s2063, s2064, s2065, 
            s2066, s2067, s2068, s2069, s2070, s2071, s2072, s2073, 
            s2074, s2075, s2076, s2077, s2078, s2079, s2080, s2081, 
            s2082, s2083, s2084, s2085, s2086, s2087, s2088, s2089, 
            s2090, s2091, s2092, s2093, s2094, s2095, s2096, s2097, 
            s2098, s2099, s2100, s2101, s2102, s2103, s2104, s2105, 
            s2106, s2107, s2108, s2109, s2110, s2111, s2112, s2113, 
            s2114, s2115, s2116, s2117, s2118, s2119, s2120, s2121, 
            s2122, s2123, s2124, s2125, t2887, t2888, t2889, t2890, 
            t2891, t2892, t2893, t2894, t2895, t2896, t2897, t2898, 
            t2899, t2900, t2901, t2902, t2903, t2904, t2905, t2906, 
            t2907, t2908, t2909, t2910, t2911, t2912, t2913, t2914, 
            t2915, t2916, t2917, t2918, t2919, t2920, t2921, t2922, 
            t2923, t2924, t2925, t2926, t2927, t2928, t2929, t2930, 
            t2931, t2932, t2933, t2934, t2935, t2936, t2937, t2938, 
            t2939, t2940, t2941, t2942, t2943, t2944, t2945, t2946, 
            t2947, t2948, t2949, t2950, t2951, t2952, t2953, t2954, 
            t2955, t2956, t2957, t2958, t2959, t2960, t2961, t2962, 
            t2963, t2964, t2965, t2966, t2967, t2968, t2969, t2970, 
            t2971, t2972, t2973, t2974, t2975, t2976, t2977, t2978, 
            t2979, t2980, t2981, t2982, t2983, t2984, t2985, t2986, 
            t2987, t2988, t2989, t2990, t2991, t2992, t2993, t2994, 
            t2995, t2996, t2997, t2998, t2999, t3000, t3001, t3002, 
            t3003, t3004, t3005, t3006, t3007, t3008, t3009, t3010, 
            t3011, t3012, t3013, t3014, t3015, t3016, t3017, t3018, 
            t3019, t3020, t3021, t3022, t3023, t3024, t3025, t3026, 
            t3027, t3028, t3029, t3030, t3031, t3032, t3033, t3034, 
            t3035, t3036, t3037, t3038, t3039, t3040, t3041, t3042, 
            t3043, t3044, t3045, t3046, t3047, t3048, t3049, t3050, 
            t3051, t3052, t3053, t3054, t3055, t3056, t3057, t3058, 
            t3059, t3060, t3061, t3062;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s1908 = svld2_f64(pg1, (X + ((2)*(j1))));
        s1909 = s1908.v0;
        s1910 = s1908.v1;
        s1911 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s1912 = s1911.v0;
        s1913 = s1911.v1;
        s1914 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s1915 = s1914.v0;
        s1916 = s1914.v1;
        s1917 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s1918 = s1917.v0;
        s1919 = s1917.v1;
        s1920 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s1921 = s1920.v0;
        s1922 = s1920.v1;
        s1923 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s1924 = s1923.v0;
        s1925 = s1923.v1;
        s1926 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s1927 = s1926.v0;
        s1928 = s1926.v1;
        s1929 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s1930 = s1929.v0;
        s1931 = s1929.v1;
        s1932 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s1933 = s1932.v0;
        s1934 = s1932.v1;
        s1935 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s1936 = s1935.v0;
        s1937 = s1935.v1;
        s1938 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s1939 = s1938.v0;
        s1940 = s1938.v1;
        s1941 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s1942 = s1941.v0;
        s1943 = s1941.v1;
        s1944 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s1945 = s1944.v0;
        s1946 = s1944.v1;
        s1947 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s1948 = s1947.v0;
        s1949 = s1947.v1;
        s1950 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s1951 = s1950.v0;
        s1952 = s1950.v1;
        s1953 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s1954 = s1953.v0;
        s1955 = s1953.v1;
        s1956 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s1957 = s1956.v0;
        s1958 = s1956.v1;
        s1959 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s1960 = s1959.v0;
        s1961 = s1959.v1;
        s1962 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s1963 = s1962.v0;
        s1964 = s1962.v1;
        s1965 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s1966 = s1965.v0;
        s1967 = s1965.v1;
        t2887 = svadd_f64_x(pg1, s1909, s1939);
        t2888 = svadd_f64_x(pg1, s1910, s1940);
        t2889 = svsub_f64_x(pg1, s1909, s1939);
        t2890 = svsub_f64_x(pg1, s1910, s1940);
        t2891 = svadd_f64_x(pg1, s1924, s1954);
        t2892 = svadd_f64_x(pg1, s1925, s1955);
        t2893 = svsub_f64_x(pg1, s1924, s1954);
        t2894 = svsub_f64_x(pg1, s1925, s1955);
        t2895 = svadd_f64_x(pg1, t2887, t2891);
        t2896 = svadd_f64_x(pg1, t2888, t2892);
        t2897 = svsub_f64_x(pg1, t2887, t2891);
        t2898 = svsub_f64_x(pg1, t2888, t2892);
        s1968 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2896, D23[1]), t2895, D23[0]);
        s1969 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2896, D23[0]), t2895, D23[1]);
        s1970 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2898, D23[3]), t2897, D23[2]);
        s1971 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2898, D23[2]), t2897, D23[3]);
        t2899 = svadd_f64_x(pg1, t2889, t2894);
        t2900 = svsub_f64_x(pg1, t2890, t2893);
        t2901 = svsub_f64_x(pg1, t2889, t2894);
        t2902 = svadd_f64_x(pg1, t2890, t2893);
        s1972 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2900, D23[5]), t2899, D23[4]);
        s1973 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2900, D23[4]), t2899, D23[5]);
        s1974 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2902, D23[7]), t2901, D23[6]);
        s1975 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2902, D23[6]), t2901, D23[7]);
        t2903 = svadd_f64_x(pg1, s1912, s1942);
        t2904 = svadd_f64_x(pg1, s1913, s1943);
        t2905 = svsub_f64_x(pg1, s1912, s1942);
        t2906 = svsub_f64_x(pg1, s1913, s1943);
        t2907 = svadd_f64_x(pg1, s1927, s1957);
        t2908 = svadd_f64_x(pg1, s1928, s1958);
        t2909 = svsub_f64_x(pg1, s1927, s1957);
        t2910 = svsub_f64_x(pg1, s1928, s1958);
        t2911 = svadd_f64_x(pg1, t2903, t2907);
        t2912 = svadd_f64_x(pg1, t2904, t2908);
        t2913 = svsub_f64_x(pg1, t2903, t2907);
        t2914 = svsub_f64_x(pg1, t2904, t2908);
        s1976 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2912, D23[9]), t2911, D23[8]);
        s1977 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2912, D23[8]), t2911, D23[9]);
        s1978 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2914, D23[11]), t2913, D23[10]);
        s1979 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2914, D23[10]), t2913, D23[11]);
        t2915 = svadd_f64_x(pg1, t2905, t2910);
        t2916 = svsub_f64_x(pg1, t2906, t2909);
        t2917 = svsub_f64_x(pg1, t2905, t2910);
        t2918 = svadd_f64_x(pg1, t2906, t2909);
        s1980 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2916, D23[13]), t2915, D23[12]);
        s1981 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2916, D23[12]), t2915, D23[13]);
        s1982 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2918, D23[15]), t2917, D23[14]);
        s1983 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2918, D23[14]), t2917, D23[15]);
        t2919 = svadd_f64_x(pg1, s1915, s1945);
        t2920 = svadd_f64_x(pg1, s1916, s1946);
        t2921 = svsub_f64_x(pg1, s1915, s1945);
        t2922 = svsub_f64_x(pg1, s1916, s1946);
        t2923 = svadd_f64_x(pg1, s1930, s1960);
        t2924 = svadd_f64_x(pg1, s1931, s1961);
        t2925 = svsub_f64_x(pg1, s1930, s1960);
        t2926 = svsub_f64_x(pg1, s1931, s1961);
        t2927 = svadd_f64_x(pg1, t2919, t2923);
        t2928 = svadd_f64_x(pg1, t2920, t2924);
        t2929 = svsub_f64_x(pg1, t2919, t2923);
        t2930 = svsub_f64_x(pg1, t2920, t2924);
        s1984 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2928, D23[17]), t2927, D23[16]);
        s1985 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2928, D23[16]), t2927, D23[17]);
        s1986 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2930, D23[19]), t2929, D23[18]);
        s1987 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2930, D23[18]), t2929, D23[19]);
        t2931 = svadd_f64_x(pg1, t2921, t2926);
        t2932 = svsub_f64_x(pg1, t2922, t2925);
        t2933 = svsub_f64_x(pg1, t2921, t2926);
        t2934 = svadd_f64_x(pg1, t2922, t2925);
        s1988 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2932, D23[21]), t2931, D23[20]);
        s1989 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2932, D23[20]), t2931, D23[21]);
        s1990 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2934, D23[23]), t2933, D23[22]);
        s1991 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2934, D23[22]), t2933, D23[23]);
        t2935 = svadd_f64_x(pg1, s1918, s1948);
        t2936 = svadd_f64_x(pg1, s1919, s1949);
        t2937 = svsub_f64_x(pg1, s1918, s1948);
        t2938 = svsub_f64_x(pg1, s1919, s1949);
        t2939 = svadd_f64_x(pg1, s1933, s1963);
        t2940 = svadd_f64_x(pg1, s1934, s1964);
        t2941 = svsub_f64_x(pg1, s1933, s1963);
        t2942 = svsub_f64_x(pg1, s1934, s1964);
        t2943 = svadd_f64_x(pg1, t2935, t2939);
        t2944 = svadd_f64_x(pg1, t2936, t2940);
        t2945 = svsub_f64_x(pg1, t2935, t2939);
        t2946 = svsub_f64_x(pg1, t2936, t2940);
        s1992 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2944, D23[25]), t2943, D23[24]);
        s1993 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2944, D23[24]), t2943, D23[25]);
        s1994 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2946, D23[27]), t2945, D23[26]);
        s1995 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2946, D23[26]), t2945, D23[27]);
        t2947 = svadd_f64_x(pg1, t2937, t2942);
        t2948 = svsub_f64_x(pg1, t2938, t2941);
        t2949 = svsub_f64_x(pg1, t2937, t2942);
        t2950 = svadd_f64_x(pg1, t2938, t2941);
        s1996 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2948, D23[29]), t2947, D23[28]);
        s1997 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2948, D23[28]), t2947, D23[29]);
        s1998 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2950, D23[31]), t2949, D23[30]);
        s1999 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2950, D23[30]), t2949, D23[31]);
        t2951 = svadd_f64_x(pg1, s1921, s1951);
        t2952 = svadd_f64_x(pg1, s1922, s1952);
        t2953 = svsub_f64_x(pg1, s1921, s1951);
        t2954 = svsub_f64_x(pg1, s1922, s1952);
        t2955 = svadd_f64_x(pg1, s1936, s1966);
        t2956 = svadd_f64_x(pg1, s1937, s1967);
        t2957 = svsub_f64_x(pg1, s1936, s1966);
        t2958 = svsub_f64_x(pg1, s1937, s1967);
        t2959 = svadd_f64_x(pg1, t2951, t2955);
        t2960 = svadd_f64_x(pg1, t2952, t2956);
        t2961 = svsub_f64_x(pg1, t2951, t2955);
        t2962 = svsub_f64_x(pg1, t2952, t2956);
        s2000 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2960, D23[33]), t2959, D23[32]);
        s2001 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2960, D23[32]), t2959, D23[33]);
        s2002 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2962, D23[35]), t2961, D23[34]);
        s2003 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2962, D23[34]), t2961, D23[35]);
        t2963 = svadd_f64_x(pg1, t2953, t2958);
        t2964 = svsub_f64_x(pg1, t2954, t2957);
        t2965 = svsub_f64_x(pg1, t2953, t2958);
        t2966 = svadd_f64_x(pg1, t2954, t2957);
        s2004 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2964, D23[37]), t2963, D23[36]);
        s2005 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2964, D23[36]), t2963, D23[37]);
        s2006 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t2966, D23[39]), t2965, D23[38]);
        s2007 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t2966, D23[38]), t2965, D23[39]);
        t2967 = svadd_f64_x(pg1, s1976, s2000);
        t2968 = svadd_f64_x(pg1, s1977, s2001);
        t2969 = svsub_f64_x(pg1, s1976, s2000);
        t2970 = svsub_f64_x(pg1, s1977, s2001);
        t2971 = svadd_f64_x(pg1, s1984, s1992);
        t2972 = svadd_f64_x(pg1, s1985, s1993);
        t2973 = svsub_f64_x(pg1, s1984, s1992);
        t2974 = svsub_f64_x(pg1, s1985, s1993);
        t2975 = svadd_f64_x(pg1, t2967, t2971);
        t2976 = svadd_f64_x(pg1, t2968, t2972);
        t2977 = svadd_f64_x(pg1, t2969, t2974);
        t2978 = svsub_f64_x(pg1, t2970, t2973);
        t2979 = svsub_f64_x(pg1, t2969, t2974);
        t2980 = svadd_f64_x(pg1, t2970, t2973);
        t2981 = svmls_n_f64_x(pg1, s1968, t2975, 0.25);
        t2982 = svmls_n_f64_x(pg1, s1969, t2976, 0.25);
        s2110 = svmla_n_f64_x(pg1, t2977, t2978, 1.6180339887498947);
        s2008 = svmul_n_f64_x(pg1, s2110, 0.29389262614623657);
        s2111 = svmls_n_f64_x(pg1, t2978, t2977, 1.6180339887498947);
        s2009 = svmul_n_f64_x(pg1, s2111, 0.29389262614623657);
        s2010 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2967, t2971), 0.55901699437494745);
        s2011 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2968, t2972), 0.55901699437494745);
        s2112 = svmls_n_f64_x(pg1, t2980, t2979, 0.61803398874989479);
        s2012 = svmul_n_f64_x(pg1, s2112, 0.47552825814757682);
        s2113 = svmla_n_f64_x(pg1, t2979, t2980, 0.61803398874989479);
        s2013 = svmul_n_f64_x(pg1, s2113, 0.47552825814757682);
        s2014 = svadd_f64_x(pg1, s1968, t2975);
        s2015 = svadd_f64_x(pg1, s1969, t2976);
        t2983 = svadd_f64_x(pg1, t2981, s2010);
        t2984 = svadd_f64_x(pg1, t2982, s2011);
        t2985 = svsub_f64_x(pg1, t2981, s2010);
        t2986 = svsub_f64_x(pg1, t2982, s2011);
        t2987 = svadd_f64_x(pg1, s2008, s2012);
        t2988 = svsub_f64_x(pg1, s2009, s2013);
        t2989 = svsub_f64_x(pg1, s2008, s2012);
        t2990 = svadd_f64_x(pg1, s2009, s2013);
        s2016 = svadd_f64_x(pg1, t2983, t2987);
        s2017 = svadd_f64_x(pg1, t2984, t2988);
        s2018 = svsub_f64_x(pg1, t2983, t2987);
        s2019 = svsub_f64_x(pg1, t2984, t2988);
        s2020 = svadd_f64_x(pg1, t2985, t2990);
        s2021 = svsub_f64_x(pg1, t2986, t2989);
        s2022 = svsub_f64_x(pg1, t2985, t2990);
        s2023 = svadd_f64_x(pg1, t2986, t2989);
        t2991 = svadd_f64_x(pg1, s1980, s2004);
        t2992 = svadd_f64_x(pg1, s1981, s2005);
        t2993 = svsub_f64_x(pg1, s1980, s2004);
        t2994 = svsub_f64_x(pg1, s1981, s2005);
        t2995 = svadd_f64_x(pg1, s1988, s1996);
        t2996 = svadd_f64_x(pg1, s1989, s1997);
        t2997 = svsub_f64_x(pg1, s1988, s1996);
        t2998 = svsub_f64_x(pg1, s1989, s1997);
        t2999 = svadd_f64_x(pg1, t2991, t2995);
        t3000 = svadd_f64_x(pg1, t2992, t2996);
        t3001 = svadd_f64_x(pg1, t2993, t2998);
        t3002 = svsub_f64_x(pg1, t2994, t2997);
        t3003 = svsub_f64_x(pg1, t2993, t2998);
        t3004 = svadd_f64_x(pg1, t2994, t2997);
        t3005 = svmls_n_f64_x(pg1, s1972, t2999, 0.25);
        t3006 = svmls_n_f64_x(pg1, s1973, t3000, 0.25);
        s2114 = svmla_n_f64_x(pg1, t3001, t3002, 1.6180339887498947);
        s2024 = svmul_n_f64_x(pg1, s2114, 0.29389262614623657);
        s2115 = svmls_n_f64_x(pg1, t3002, t3001, 1.6180339887498947);
        s2025 = svmul_n_f64_x(pg1, s2115, 0.29389262614623657);
        s2026 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2991, t2995), 0.55901699437494745);
        s2027 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t2992, t2996), 0.55901699437494745);
        s2116 = svmls_n_f64_x(pg1, t3004, t3003, 0.61803398874989479);
        s2028 = svmul_n_f64_x(pg1, s2116, 0.47552825814757682);
        s2117 = svmla_n_f64_x(pg1, t3003, t3004, 0.61803398874989479);
        s2029 = svmul_n_f64_x(pg1, s2117, 0.47552825814757682);
        s2030 = svadd_f64_x(pg1, s1972, t2999);
        s2031 = svadd_f64_x(pg1, s1973, t3000);
        t3007 = svadd_f64_x(pg1, t3005, s2026);
        t3008 = svadd_f64_x(pg1, t3006, s2027);
        t3009 = svsub_f64_x(pg1, t3005, s2026);
        t3010 = svsub_f64_x(pg1, t3006, s2027);
        t3011 = svadd_f64_x(pg1, s2024, s2028);
        t3012 = svsub_f64_x(pg1, s2025, s2029);
        t3013 = svsub_f64_x(pg1, s2024, s2028);
        t3014 = svadd_f64_x(pg1, s2025, s2029);
        s2032 = svadd_f64_x(pg1, t3007, t3011);
        s2033 = svadd_f64_x(pg1, t3008, t3012);
        s2034 = svsub_f64_x(pg1, t3007, t3011);
        s2035 = svsub_f64_x(pg1, t3008, t3012);
        s2036 = svadd_f64_x(pg1, t3009, t3014);
        s2037 = svsub_f64_x(pg1, t3010, t3013);
        s2038 = svsub_f64_x(pg1, t3009, t3014);
        s2039 = svadd_f64_x(pg1, t3010, t3013);
        t3015 = svadd_f64_x(pg1, s1978, s2002);
        t3016 = svadd_f64_x(pg1, s1979, s2003);
        t3017 = svsub_f64_x(pg1, s1978, s2002);
        t3018 = svsub_f64_x(pg1, s1979, s2003);
        t3019 = svadd_f64_x(pg1, s1986, s1994);
        t3020 = svadd_f64_x(pg1, s1987, s1995);
        t3021 = svsub_f64_x(pg1, s1986, s1994);
        t3022 = svsub_f64_x(pg1, s1987, s1995);
        t3023 = svadd_f64_x(pg1, t3015, t3019);
        t3024 = svadd_f64_x(pg1, t3016, t3020);
        t3025 = svadd_f64_x(pg1, t3017, t3022);
        t3026 = svsub_f64_x(pg1, t3018, t3021);
        t3027 = svsub_f64_x(pg1, t3017, t3022);
        t3028 = svadd_f64_x(pg1, t3018, t3021);
        t3029 = svmls_n_f64_x(pg1, s1970, t3023, 0.25);
        t3030 = svmls_n_f64_x(pg1, s1971, t3024, 0.25);
        s2118 = svmla_n_f64_x(pg1, t3025, t3026, 1.6180339887498947);
        s2040 = svmul_n_f64_x(pg1, s2118, 0.29389262614623657);
        s2119 = svmls_n_f64_x(pg1, t3026, t3025, 1.6180339887498947);
        s2041 = svmul_n_f64_x(pg1, s2119, 0.29389262614623657);
        s2042 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3015, t3019), 0.55901699437494745);
        s2043 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3016, t3020), 0.55901699437494745);
        s2120 = svmls_n_f64_x(pg1, t3028, t3027, 0.61803398874989479);
        s2044 = svmul_n_f64_x(pg1, s2120, 0.47552825814757682);
        s2121 = svmla_n_f64_x(pg1, t3027, t3028, 0.61803398874989479);
        s2045 = svmul_n_f64_x(pg1, s2121, 0.47552825814757682);
        s2046 = svadd_f64_x(pg1, s1970, t3023);
        s2047 = svadd_f64_x(pg1, s1971, t3024);
        t3031 = svadd_f64_x(pg1, t3029, s2042);
        t3032 = svadd_f64_x(pg1, t3030, s2043);
        t3033 = svsub_f64_x(pg1, t3029, s2042);
        t3034 = svsub_f64_x(pg1, t3030, s2043);
        t3035 = svadd_f64_x(pg1, s2040, s2044);
        t3036 = svsub_f64_x(pg1, s2041, s2045);
        t3037 = svsub_f64_x(pg1, s2040, s2044);
        t3038 = svadd_f64_x(pg1, s2041, s2045);
        s2048 = svadd_f64_x(pg1, t3031, t3035);
        s2049 = svadd_f64_x(pg1, t3032, t3036);
        s2050 = svsub_f64_x(pg1, t3031, t3035);
        s2051 = svsub_f64_x(pg1, t3032, t3036);
        s2052 = svadd_f64_x(pg1, t3033, t3038);
        s2053 = svsub_f64_x(pg1, t3034, t3037);
        s2054 = svsub_f64_x(pg1, t3033, t3038);
        s2055 = svadd_f64_x(pg1, t3034, t3037);
        t3039 = svadd_f64_x(pg1, s1982, s2006);
        t3040 = svadd_f64_x(pg1, s1983, s2007);
        t3041 = svsub_f64_x(pg1, s1982, s2006);
        t3042 = svsub_f64_x(pg1, s1983, s2007);
        t3043 = svadd_f64_x(pg1, s1990, s1998);
        t3044 = svadd_f64_x(pg1, s1991, s1999);
        t3045 = svsub_f64_x(pg1, s1990, s1998);
        t3046 = svsub_f64_x(pg1, s1991, s1999);
        t3047 = svadd_f64_x(pg1, t3039, t3043);
        t3048 = svadd_f64_x(pg1, t3040, t3044);
        t3049 = svadd_f64_x(pg1, t3041, t3046);
        t3050 = svsub_f64_x(pg1, t3042, t3045);
        t3051 = svsub_f64_x(pg1, t3041, t3046);
        t3052 = svadd_f64_x(pg1, t3042, t3045);
        t3053 = svmls_n_f64_x(pg1, s1974, t3047, 0.25);
        t3054 = svmls_n_f64_x(pg1, s1975, t3048, 0.25);
        s2122 = svmla_n_f64_x(pg1, t3049, t3050, 1.6180339887498947);
        s2056 = svmul_n_f64_x(pg1, s2122, 0.29389262614623657);
        s2123 = svmls_n_f64_x(pg1, t3050, t3049, 1.6180339887498947);
        s2057 = svmul_n_f64_x(pg1, s2123, 0.29389262614623657);
        s2058 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3039, t3043), 0.55901699437494745);
        s2059 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t3040, t3044), 0.55901699437494745);
        s2124 = svmls_n_f64_x(pg1, t3052, t3051, 0.61803398874989479);
        s2060 = svmul_n_f64_x(pg1, s2124, 0.47552825814757682);
        s2125 = svmla_n_f64_x(pg1, t3051, t3052, 0.61803398874989479);
        s2061 = svmul_n_f64_x(pg1, s2125, 0.47552825814757682);
        s2062 = svadd_f64_x(pg1, s1974, t3047);
        s2063 = svadd_f64_x(pg1, s1975, t3048);
        t3055 = svadd_f64_x(pg1, t3053, s2058);
        t3056 = svadd_f64_x(pg1, t3054, s2059);
        t3057 = svsub_f64_x(pg1, t3053, s2058);
        t3058 = svsub_f64_x(pg1, t3054, s2059);
        t3059 = svadd_f64_x(pg1, s2056, s2060);
        t3060 = svsub_f64_x(pg1, s2057, s2061);
        t3061 = svsub_f64_x(pg1, s2056, s2060);
        t3062 = svadd_f64_x(pg1, s2057, s2061);
        s2064 = svadd_f64_x(pg1, t3055, t3059);
        s2065 = svadd_f64_x(pg1, t3056, t3060);
        s2066 = svsub_f64_x(pg1, t3055, t3059);
        s2067 = svsub_f64_x(pg1, t3056, t3060);
        s2068 = svadd_f64_x(pg1, t3057, t3062);
        s2069 = svsub_f64_x(pg1, t3058, t3061);
        s2070 = svsub_f64_x(pg1, t3057, t3062);
        s2071 = svadd_f64_x(pg1, t3058, t3061);
        a3984 = (TW1 + ((38)*(j1)));
        a3985 = svld1_gather_u64offset_f64(pg1, a3984, svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3986 = svld1_gather_u64offset_f64(pg1, (a3984 + 1), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2072 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3986, s2031), a3985, s2030);
        s2073 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3985, s2031), a3986, s2030);
        a3987 = svld1_gather_u64offset_f64(pg1, (a3984 + 2), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3988 = svld1_gather_u64offset_f64(pg1, (a3984 + 3), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2074 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3988, s2047), a3987, s2046);
        s2075 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3987, s2047), a3988, s2046);
        a3989 = svld1_gather_u64offset_f64(pg1, (a3984 + 4), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3990 = svld1_gather_u64offset_f64(pg1, (a3984 + 5), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2076 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3990, s2063), a3989, s2062);
        s2077 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3989, s2063), a3990, s2062);
        a3991 = svld1_gather_u64offset_f64(pg1, (a3984 + 6), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3992 = svld1_gather_u64offset_f64(pg1, (a3984 + 7), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2078 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3992, s2017), a3991, s2016);
        s2079 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3991, s2017), a3992, s2016);
        a3993 = svld1_gather_u64offset_f64(pg1, (a3984 + 8), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3994 = svld1_gather_u64offset_f64(pg1, (a3984 + 9), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2080 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3994, s2033), a3993, s2032);
        s2081 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3993, s2033), a3994, s2032);
        a3995 = svld1_gather_u64offset_f64(pg1, (a3984 + 10), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3996 = svld1_gather_u64offset_f64(pg1, (a3984 + 11), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2082 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3996, s2049), a3995, s2048);
        s2083 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3995, s2049), a3996, s2048);
        a3997 = svld1_gather_u64offset_f64(pg1, (a3984 + 12), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a3998 = svld1_gather_u64offset_f64(pg1, (a3984 + 13), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2084 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a3998, s2065), a3997, s2064);
        s2085 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3997, s2065), a3998, s2064);
        a3999 = svld1_gather_u64offset_f64(pg1, (a3984 + 14), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4000 = svld1_gather_u64offset_f64(pg1, (a3984 + 15), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2086 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4000, s2021), a3999, s2020);
        s2087 = svmla_f64_x(pg1, svmul_f64_x(pg1, a3999, s2021), a4000, s2020);
        a4001 = svld1_gather_u64offset_f64(pg1, (a3984 + 16), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4002 = svld1_gather_u64offset_f64(pg1, (a3984 + 17), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2088 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4002, s2037), a4001, s2036);
        s2089 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4001, s2037), a4002, s2036);
        a4003 = svld1_gather_u64offset_f64(pg1, (a3984 + 18), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4004 = svld1_gather_u64offset_f64(pg1, (a3984 + 19), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2090 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4004, s2053), a4003, s2052);
        s2091 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4003, s2053), a4004, s2052);
        a4005 = svld1_gather_u64offset_f64(pg1, (a3984 + 20), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4006 = svld1_gather_u64offset_f64(pg1, (a3984 + 21), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2092 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4006, s2069), a4005, s2068);
        s2093 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4005, s2069), a4006, s2068);
        a4007 = svld1_gather_u64offset_f64(pg1, (a3984 + 22), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4008 = svld1_gather_u64offset_f64(pg1, (a3984 + 23), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2094 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4008, s2023), a4007, s2022);
        s2095 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4007, s2023), a4008, s2022);
        a4009 = svld1_gather_u64offset_f64(pg1, (a3984 + 24), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4010 = svld1_gather_u64offset_f64(pg1, (a3984 + 25), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2096 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4010, s2039), a4009, s2038);
        s2097 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4009, s2039), a4010, s2038);
        a4011 = svld1_gather_u64offset_f64(pg1, (a3984 + 26), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4012 = svld1_gather_u64offset_f64(pg1, (a3984 + 27), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2098 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4012, s2055), a4011, s2054);
        s2099 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4011, s2055), a4012, s2054);
        a4013 = svld1_gather_u64offset_f64(pg1, (a3984 + 28), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4014 = svld1_gather_u64offset_f64(pg1, (a3984 + 29), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2100 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4014, s2071), a4013, s2070);
        s2101 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4013, s2071), a4014, s2070);
        a4015 = svld1_gather_u64offset_f64(pg1, (a3984 + 30), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4016 = svld1_gather_u64offset_f64(pg1, (a3984 + 31), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2102 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4016, s2019), a4015, s2018);
        s2103 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4015, s2019), a4016, s2018);
        a4017 = svld1_gather_u64offset_f64(pg1, (a3984 + 32), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4018 = svld1_gather_u64offset_f64(pg1, (a3984 + 33), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2104 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4018, s2035), a4017, s2034);
        s2105 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4017, s2035), a4018, s2034);
        a4019 = svld1_gather_u64offset_f64(pg1, (a3984 + 34), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4020 = svld1_gather_u64offset_f64(pg1, (a3984 + 35), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2106 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4020, s2051), a4019, s2050);
        s2107 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4019, s2051), a4020, s2050);
        a4021 = svld1_gather_u64offset_f64(pg1, (a3984 + 36), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        a4022 = svld1_gather_u64offset_f64(pg1, (a3984 + 37), svindex_u64(0, (int64_t)(38 * sizeof(float64_t))));
        s2108 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a4022, s2067), a4021, s2066);
        s2109 = svmla_f64_x(pg1, svmul_f64_x(pg1, a4021, s2067), a4022, s2066);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2014);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2015);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2072);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2073);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2074);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2075);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2076);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2077);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2078);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2079);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2080);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2081);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2082);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2083);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2084);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2085);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2086);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2087);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2088);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2089);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2090);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2091);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2092);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2093);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2094);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2095);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2096);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2097);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2098);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2099);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2100);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2101);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2102);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2103);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2104);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2105);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2106);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2107);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2108);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((40)*(j1)))), svindex_u64(0, (int64_t)(40 * sizeof(float64_t))), s2109);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
