/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft3a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a183;
    svfloat64x2_t s104, s107, s110;
    svfloat64_t a184, a185, a186, a187, s105, s106, s108, s109, 
            s111, s112, s113, s114, s115, s116, s117, s118, 
            s119, s120, s121, s122, s123, s124, t126, t127, 
            t128, t129;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s104 = svld2_f64(pg1, (X + ((2)*(j1))));
        s105 = s104.v0;
        s106 = s104.v1;
        s107 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s108 = s107.v0;
        s109 = s107.v1;
        s110 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s111 = s110.v0;
        s112 = s110.v1;
        t126 = svadd_f64_x(pg1, s108, s111);
        t127 = svadd_f64_x(pg1, s109, s112);
        t128 = svmls_n_f64_x(pg1, s105, t126, 0.5);
        t129 = svmls_n_f64_x(pg1, s106, t127, 0.5);
        s113 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s109, s112), 0.8660254037844386);
        s114 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s108, s111), 0.8660254037844386);
        s115 = svadd_f64_x(pg1, s105, t126);
        s116 = svadd_f64_x(pg1, s106, t127);
        s117 = svadd_f64_x(pg1, t128, s113);
        s118 = svsub_f64_x(pg1, t129, s114);
        s119 = svsub_f64_x(pg1, t128, s113);
        s120 = svadd_f64_x(pg1, t129, s114);
        a183 = (TW1 + ((4)*(j1)));
        a184 = svld1_gather_u64offset_f64(pg1, a183, svindex_u64(0, (int64_t)(4 * sizeof(float64_t))));
        a185 = svld1_gather_u64offset_f64(pg1, (a183 + 1), svindex_u64(0, (int64_t)(4 * sizeof(float64_t))));
        s121 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a185, s118), a184, s117);
        s122 = svmla_f64_x(pg1, svmul_f64_x(pg1, a184, s118), a185, s117);
        a186 = svld1_gather_u64offset_f64(pg1, (a183 + 2), svindex_u64(0, (int64_t)(4 * sizeof(float64_t))));
        a187 = svld1_gather_u64offset_f64(pg1, (a183 + 3), svindex_u64(0, (int64_t)(4 * sizeof(float64_t))));
        s123 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a187, s120), a186, s119);
        s124 = svmla_f64_x(pg1, svmul_f64_x(pg1, a186, s120), a187, s119);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s115);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s116);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s121);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s122);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s123);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((6)*(j1)))), svindex_u64(0, (int64_t)(6 * sizeof(float64_t))), s124);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
