/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft32b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    static float64_t D15[64];
    float64_t a10285, a10286, a10287, a10288, a10289, a10290, a10291, a10292, 
            a10293, a10294, a10295, a10296, a10297, a10298, a10299, a10300, 
            a10301, a10302, a10303, a10304, a10305, a10306, a10307, a10308, 
            a10309, a10310, a10311, a10312, a10313, a10314, a10315, a10316, 
            a10317, a10318, a10319, a10320, a10321, a10322, a10323, a10324, 
            a10325, a10326, a10327, a10328, a10329, a10330, a10331, a10332, 
            a10333, a10334, a10335, a10336, a10337, a10338, a10339, a10340, 
            a10341, a10342, a10343, a10344, a10345, a10346;
    int a10267, a10284, j1, l1, m1;
    svfloat64x2_t s4340, s4343, s4346, s4349, s4352, s4355, s4358, s4361, 
            s4364, s4367, s4370, s4373, s4376, s4379, s4382, s4385, 
            s4388, s4391, s4394, s4397, s4400, s4403, s4406, s4409, 
            s4412, s4415, s4418, s4421, s4424, s4427, s4430, s4433, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48, 
            svex2_49, svex2_50, svex2_51, svex2_52, svex2_53, svex2_54, svex2_55, svex2_56, 
            svex2_57, svex2_58, svex2_59, svex2_60, svex2_61, svex2_62, svex2_63, svex2_64;
    svfloat64_t a10268, a10269, a10270, a10271, a10272, a10273, a10274, a10275, 
            a10276, a10277, a10278, a10279, a10280, a10281, a10282, a10283, 
            s4341, s4342, s4344, s4345, s4347, s4348, s4350, s4351, 
            s4353, s4354, s4356, s4357, s4359, s4360, s4362, s4363, 
            s4365, s4366, s4368, s4369, s4371, s4372, s4374, s4375, 
            s4377, s4378, s4380, s4381, s4383, s4384, s4386, s4387, 
            s4389, s4390, s4392, s4393, s4395, s4396, s4398, s4399, 
            s4401, s4402, s4404, s4405, s4407, s4408, s4410, s4411, 
            s4413, s4414, s4416, s4417, s4419, s4420, s4422, s4423, 
            s4425, s4426, s4428, s4429, s4431, s4432, s4434, s4435, 
            s4436, s4437, s4438, s4439, s4440, s4441, s4442, s4443, 
            s4444, s4445, s4446, s4447, s4448, s4449, s4450, s4451, 
            s4452, s4453, s4454, s4455, s4456, s4457, s4458, s4459, 
            s4460, s4461, s4462, s4463, s4464, s4465, s4466, s4467, 
            s4468, s4469, s4470, s4471, s4472, s4473, s4474, s4475, 
            s4476, s4477, s4478, s4479, s4480, s4481, s4482, s4483, 
            s4484, s4485, s4486, s4487, s4488, s4489, s4490, s4491, 
            s4492, s4493, s4494, s4495, s4496, s4497, s4498, s4499, 
            s4500, s4501, s4502, s4503, s4504, s4505, s4506, s4507, 
            s4508, s4509, s4510, s4511, s4512, s4513, s4514, s4515, 
            s4516, s4517, s4518, s4519, s4520, s4521, s4522, s4523, 
            s4524, s4525, s4526, s4527, s4528, s4529, s4530, s4531, 
            s4532, s4533, s4534, s4535, s4536, s4537, s4538, s4539, 
            s4540, s4541, s4542, s4543, s4544, s4545, s4546, s4547, 
            s4548, s4549, s4550, s4551, s4552, s4553, s4554, s4555, 
            s4556, s4557, s4558, s4559, s4560, s4561, s4562, s4563, 
            s4564, s4565, s4566, s4567, s4568, s4569, s4570, s4571, 
            s4572, s4573, s4574, s4575, s4576, s4577, t7131, t7132, 
            t7133, t7134, t7135, t7136, t7137, t7138, t7139, t7140, 
            t7141, t7142, t7143, t7144, t7145, t7146, t7147, t7148, 
            t7149, t7150, t7151, t7152, t7153, t7154, t7155, t7156, 
            t7157, t7158, t7159, t7160, t7161, t7162, t7163, t7164, 
            t7165, t7166, t7167, t7168, t7169, t7170, t7171, t7172, 
            t7173, t7174, t7175, t7176, t7177, t7178, t7179, t7180, 
            t7181, t7182, t7183, t7184, t7185, t7186, t7187, t7188, 
            t7189, t7190, t7191, t7192, t7193, t7194, t7195, t7196, 
            t7197, t7198, t7199, t7200, t7201, t7202, t7203, t7204, 
            t7205, t7206, t7207, t7208, t7209, t7210, t7211, t7212, 
            t7213, t7214, t7215, t7216, t7217, t7218, t7219, t7220, 
            t7221, t7222, t7223, t7224, t7225, t7226, t7227, t7228, 
            t7229, t7230, t7231, t7232, t7233, t7234, t7235, t7236, 
            t7237, t7238, t7239, t7240, t7241, t7242, t7243, t7244, 
            t7245, t7246, t7247, t7248, t7249, t7250, t7251, t7252, 
            t7253, t7254, t7255, t7256, t7257, t7258, t7259, t7260, 
            t7261, t7262, t7263, t7264, t7265, t7266, t7267, t7268, 
            t7269, t7270, t7271, t7272, t7273, t7274, t7275, t7276, 
            t7277, t7278, t7279, t7280, t7281, t7282, t7283, t7284, 
            t7285, t7286, t7287, t7288, t7289, t7290, t7291, t7292, 
            t7293, t7294, t7295, t7296, t7297, t7298, t7299, t7300, 
            t7301, t7302, t7303, t7304, t7305, t7306, t7307, t7308, 
            t7309, t7310, t7311, t7312, t7313, t7314, t7315, t7316, 
            t7317, t7318, t7319, t7320, t7321, t7322, t7323, t7324, 
            t7325, t7326, t7327, t7328, t7329, t7330, t7331, t7332, 
            t7333, t7334, t7335, t7336, t7337, t7338, t7339, t7340, 
            t7341, t7342, t7343, t7344, t7345, t7346, t7347, t7348, 
            t7349, t7350, t7351, t7352, t7353, t7354, t7355, t7356, 
            t7357, t7358, t7359, t7360, t7361, t7362, t7363, t7364, 
            t7365, t7366, t7367, t7368, t7369, t7370;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a10267 = (k1 + ((j1)*(m1)));
            s4340 = svld2_f64(pg1, (X + ((2)*(a10267))));
            s4341 = s4340.v0;
            s4342 = s4340.v1;
            s4343 = svld2_f64(pg1, (X + ((2)*((a10267 + ((l1)*(m1)))))));
            s4344 = s4343.v0;
            s4345 = s4343.v1;
            s4346 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((2)*(l1)))*(m1)))))));
            s4347 = s4346.v0;
            s4348 = s4346.v1;
            s4349 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((3)*(l1)))*(m1)))))));
            s4350 = s4349.v0;
            s4351 = s4349.v1;
            s4352 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((4)*(l1)))*(m1)))))));
            s4353 = s4352.v0;
            s4354 = s4352.v1;
            s4355 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((5)*(l1)))*(m1)))))));
            s4356 = s4355.v0;
            s4357 = s4355.v1;
            s4358 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((6)*(l1)))*(m1)))))));
            s4359 = s4358.v0;
            s4360 = s4358.v1;
            s4361 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((7)*(l1)))*(m1)))))));
            s4362 = s4361.v0;
            s4363 = s4361.v1;
            s4364 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((8)*(l1)))*(m1)))))));
            s4365 = s4364.v0;
            s4366 = s4364.v1;
            s4367 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((9)*(l1)))*(m1)))))));
            s4368 = s4367.v0;
            s4369 = s4367.v1;
            s4370 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((10)*(l1)))*(m1)))))));
            s4371 = s4370.v0;
            s4372 = s4370.v1;
            s4373 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((11)*(l1)))*(m1)))))));
            s4374 = s4373.v0;
            s4375 = s4373.v1;
            s4376 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((12)*(l1)))*(m1)))))));
            s4377 = s4376.v0;
            s4378 = s4376.v1;
            s4379 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((13)*(l1)))*(m1)))))));
            s4380 = s4379.v0;
            s4381 = s4379.v1;
            s4382 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((14)*(l1)))*(m1)))))));
            s4383 = s4382.v0;
            s4384 = s4382.v1;
            s4385 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((15)*(l1)))*(m1)))))));
            s4386 = s4385.v0;
            s4387 = s4385.v1;
            s4388 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((16)*(l1)))*(m1)))))));
            s4389 = s4388.v0;
            s4390 = s4388.v1;
            s4391 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((17)*(l1)))*(m1)))))));
            s4392 = s4391.v0;
            s4393 = s4391.v1;
            s4394 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((18)*(l1)))*(m1)))))));
            s4395 = s4394.v0;
            s4396 = s4394.v1;
            s4397 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((19)*(l1)))*(m1)))))));
            s4398 = s4397.v0;
            s4399 = s4397.v1;
            s4400 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((20)*(l1)))*(m1)))))));
            s4401 = s4400.v0;
            s4402 = s4400.v1;
            s4403 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((21)*(l1)))*(m1)))))));
            s4404 = s4403.v0;
            s4405 = s4403.v1;
            s4406 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((22)*(l1)))*(m1)))))));
            s4407 = s4406.v0;
            s4408 = s4406.v1;
            s4409 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((23)*(l1)))*(m1)))))));
            s4410 = s4409.v0;
            s4411 = s4409.v1;
            s4412 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((24)*(l1)))*(m1)))))));
            s4413 = s4412.v0;
            s4414 = s4412.v1;
            s4415 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((25)*(l1)))*(m1)))))));
            s4416 = s4415.v0;
            s4417 = s4415.v1;
            s4418 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((26)*(l1)))*(m1)))))));
            s4419 = s4418.v0;
            s4420 = s4418.v1;
            s4421 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((27)*(l1)))*(m1)))))));
            s4422 = s4421.v0;
            s4423 = s4421.v1;
            s4424 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((28)*(l1)))*(m1)))))));
            s4425 = s4424.v0;
            s4426 = s4424.v1;
            s4427 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((29)*(l1)))*(m1)))))));
            s4428 = s4427.v0;
            s4429 = s4427.v1;
            s4430 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((30)*(l1)))*(m1)))))));
            s4431 = s4430.v0;
            s4432 = s4430.v1;
            s4433 = svld2_f64(pg1, (X + ((2)*((a10267 + ((((31)*(l1)))*(m1)))))));
            s4434 = s4433.v0;
            s4435 = s4433.v1;
            t7131 = svadd_f64_x(pg1, s4341, s4389);
            t7132 = svadd_f64_x(pg1, s4342, s4390);
            t7133 = svsub_f64_x(pg1, s4341, s4389);
            t7134 = svsub_f64_x(pg1, s4342, s4390);
            t7135 = svadd_f64_x(pg1, s4365, s4413);
            t7136 = svadd_f64_x(pg1, s4366, s4414);
            t7137 = svsub_f64_x(pg1, s4365, s4413);
            t7138 = svsub_f64_x(pg1, s4366, s4414);
            t7139 = svadd_f64_x(pg1, t7131, t7135);
            t7140 = svadd_f64_x(pg1, t7132, t7136);
            t7141 = svsub_f64_x(pg1, t7131, t7135);
            t7142 = svsub_f64_x(pg1, t7132, t7136);
            s4436 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7140, D15[1]), t7139, D15[0]);
            s4437 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7140, D15[0]), t7139, D15[1]);
            s4438 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7142, D15[3]), t7141, D15[2]);
            s4439 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7142, D15[2]), t7141, D15[3]);
            t7143 = svadd_f64_x(pg1, t7133, t7138);
            t7144 = svsub_f64_x(pg1, t7134, t7137);
            t7145 = svsub_f64_x(pg1, t7133, t7138);
            t7146 = svadd_f64_x(pg1, t7134, t7137);
            s4440 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7144, D15[5]), t7143, D15[4]);
            s4441 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7144, D15[4]), t7143, D15[5]);
            s4442 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7146, D15[7]), t7145, D15[6]);
            s4443 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7146, D15[6]), t7145, D15[7]);
            t7147 = svadd_f64_x(pg1, s4344, s4392);
            t7148 = svadd_f64_x(pg1, s4345, s4393);
            t7149 = svsub_f64_x(pg1, s4344, s4392);
            t7150 = svsub_f64_x(pg1, s4345, s4393);
            t7151 = svadd_f64_x(pg1, s4368, s4416);
            t7152 = svadd_f64_x(pg1, s4369, s4417);
            t7153 = svsub_f64_x(pg1, s4368, s4416);
            t7154 = svsub_f64_x(pg1, s4369, s4417);
            t7155 = svadd_f64_x(pg1, t7147, t7151);
            t7156 = svadd_f64_x(pg1, t7148, t7152);
            t7157 = svsub_f64_x(pg1, t7147, t7151);
            t7158 = svsub_f64_x(pg1, t7148, t7152);
            s4444 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7156, D15[9]), t7155, D15[8]);
            s4445 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7156, D15[8]), t7155, D15[9]);
            s4446 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7158, D15[11]), t7157, D15[10]);
            s4447 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7158, D15[10]), t7157, D15[11]);
            t7159 = svadd_f64_x(pg1, t7149, t7154);
            t7160 = svsub_f64_x(pg1, t7150, t7153);
            t7161 = svsub_f64_x(pg1, t7149, t7154);
            t7162 = svadd_f64_x(pg1, t7150, t7153);
            s4448 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7160, D15[13]), t7159, D15[12]);
            s4449 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7160, D15[12]), t7159, D15[13]);
            s4450 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7162, D15[15]), t7161, D15[14]);
            s4451 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7162, D15[14]), t7161, D15[15]);
            t7163 = svadd_f64_x(pg1, s4347, s4395);
            t7164 = svadd_f64_x(pg1, s4348, s4396);
            t7165 = svsub_f64_x(pg1, s4347, s4395);
            t7166 = svsub_f64_x(pg1, s4348, s4396);
            t7167 = svadd_f64_x(pg1, s4371, s4419);
            t7168 = svadd_f64_x(pg1, s4372, s4420);
            t7169 = svsub_f64_x(pg1, s4371, s4419);
            t7170 = svsub_f64_x(pg1, s4372, s4420);
            t7171 = svadd_f64_x(pg1, t7163, t7167);
            t7172 = svadd_f64_x(pg1, t7164, t7168);
            t7173 = svsub_f64_x(pg1, t7163, t7167);
            t7174 = svsub_f64_x(pg1, t7164, t7168);
            s4452 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7172, D15[17]), t7171, D15[16]);
            s4453 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7172, D15[16]), t7171, D15[17]);
            s4454 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7174, D15[19]), t7173, D15[18]);
            s4455 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7174, D15[18]), t7173, D15[19]);
            t7175 = svadd_f64_x(pg1, t7165, t7170);
            t7176 = svsub_f64_x(pg1, t7166, t7169);
            t7177 = svsub_f64_x(pg1, t7165, t7170);
            t7178 = svadd_f64_x(pg1, t7166, t7169);
            s4456 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7176, D15[21]), t7175, D15[20]);
            s4457 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7176, D15[20]), t7175, D15[21]);
            s4458 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7178, D15[23]), t7177, D15[22]);
            s4459 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7178, D15[22]), t7177, D15[23]);
            t7179 = svadd_f64_x(pg1, s4350, s4398);
            t7180 = svadd_f64_x(pg1, s4351, s4399);
            t7181 = svsub_f64_x(pg1, s4350, s4398);
            t7182 = svsub_f64_x(pg1, s4351, s4399);
            t7183 = svadd_f64_x(pg1, s4374, s4422);
            t7184 = svadd_f64_x(pg1, s4375, s4423);
            t7185 = svsub_f64_x(pg1, s4374, s4422);
            t7186 = svsub_f64_x(pg1, s4375, s4423);
            t7187 = svadd_f64_x(pg1, t7179, t7183);
            t7188 = svadd_f64_x(pg1, t7180, t7184);
            t7189 = svsub_f64_x(pg1, t7179, t7183);
            t7190 = svsub_f64_x(pg1, t7180, t7184);
            s4460 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7188, D15[25]), t7187, D15[24]);
            s4461 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7188, D15[24]), t7187, D15[25]);
            s4462 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7190, D15[27]), t7189, D15[26]);
            s4463 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7190, D15[26]), t7189, D15[27]);
            t7191 = svadd_f64_x(pg1, t7181, t7186);
            t7192 = svsub_f64_x(pg1, t7182, t7185);
            t7193 = svsub_f64_x(pg1, t7181, t7186);
            t7194 = svadd_f64_x(pg1, t7182, t7185);
            s4464 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7192, D15[29]), t7191, D15[28]);
            s4465 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7192, D15[28]), t7191, D15[29]);
            s4466 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7194, D15[31]), t7193, D15[30]);
            s4467 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7194, D15[30]), t7193, D15[31]);
            t7195 = svadd_f64_x(pg1, s4353, s4401);
            t7196 = svadd_f64_x(pg1, s4354, s4402);
            t7197 = svsub_f64_x(pg1, s4353, s4401);
            t7198 = svsub_f64_x(pg1, s4354, s4402);
            t7199 = svadd_f64_x(pg1, s4377, s4425);
            t7200 = svadd_f64_x(pg1, s4378, s4426);
            t7201 = svsub_f64_x(pg1, s4377, s4425);
            t7202 = svsub_f64_x(pg1, s4378, s4426);
            t7203 = svadd_f64_x(pg1, t7195, t7199);
            t7204 = svadd_f64_x(pg1, t7196, t7200);
            t7205 = svsub_f64_x(pg1, t7195, t7199);
            t7206 = svsub_f64_x(pg1, t7196, t7200);
            s4468 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7204, D15[33]), t7203, D15[32]);
            s4469 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7204, D15[32]), t7203, D15[33]);
            s4470 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7206, D15[35]), t7205, D15[34]);
            s4471 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7206, D15[34]), t7205, D15[35]);
            t7207 = svadd_f64_x(pg1, t7197, t7202);
            t7208 = svsub_f64_x(pg1, t7198, t7201);
            t7209 = svsub_f64_x(pg1, t7197, t7202);
            t7210 = svadd_f64_x(pg1, t7198, t7201);
            s4472 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7208, D15[37]), t7207, D15[36]);
            s4473 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7208, D15[36]), t7207, D15[37]);
            s4474 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7210, D15[39]), t7209, D15[38]);
            s4475 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7210, D15[38]), t7209, D15[39]);
            t7211 = svadd_f64_x(pg1, s4356, s4404);
            t7212 = svadd_f64_x(pg1, s4357, s4405);
            t7213 = svsub_f64_x(pg1, s4356, s4404);
            t7214 = svsub_f64_x(pg1, s4357, s4405);
            t7215 = svadd_f64_x(pg1, s4380, s4428);
            t7216 = svadd_f64_x(pg1, s4381, s4429);
            t7217 = svsub_f64_x(pg1, s4380, s4428);
            t7218 = svsub_f64_x(pg1, s4381, s4429);
            t7219 = svadd_f64_x(pg1, t7211, t7215);
            t7220 = svadd_f64_x(pg1, t7212, t7216);
            t7221 = svsub_f64_x(pg1, t7211, t7215);
            t7222 = svsub_f64_x(pg1, t7212, t7216);
            s4476 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7220, D15[41]), t7219, D15[40]);
            s4477 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7220, D15[40]), t7219, D15[41]);
            s4478 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7222, D15[43]), t7221, D15[42]);
            s4479 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7222, D15[42]), t7221, D15[43]);
            t7223 = svadd_f64_x(pg1, t7213, t7218);
            t7224 = svsub_f64_x(pg1, t7214, t7217);
            t7225 = svsub_f64_x(pg1, t7213, t7218);
            t7226 = svadd_f64_x(pg1, t7214, t7217);
            s4480 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7224, D15[45]), t7223, D15[44]);
            s4481 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7224, D15[44]), t7223, D15[45]);
            s4482 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7226, D15[47]), t7225, D15[46]);
            s4483 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7226, D15[46]), t7225, D15[47]);
            t7227 = svadd_f64_x(pg1, s4359, s4407);
            t7228 = svadd_f64_x(pg1, s4360, s4408);
            t7229 = svsub_f64_x(pg1, s4359, s4407);
            t7230 = svsub_f64_x(pg1, s4360, s4408);
            t7231 = svadd_f64_x(pg1, s4383, s4431);
            t7232 = svadd_f64_x(pg1, s4384, s4432);
            t7233 = svsub_f64_x(pg1, s4383, s4431);
            t7234 = svsub_f64_x(pg1, s4384, s4432);
            t7235 = svadd_f64_x(pg1, t7227, t7231);
            t7236 = svadd_f64_x(pg1, t7228, t7232);
            t7237 = svsub_f64_x(pg1, t7227, t7231);
            t7238 = svsub_f64_x(pg1, t7228, t7232);
            s4484 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7236, D15[49]), t7235, D15[48]);
            s4485 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7236, D15[48]), t7235, D15[49]);
            s4486 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7238, D15[51]), t7237, D15[50]);
            s4487 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7238, D15[50]), t7237, D15[51]);
            t7239 = svadd_f64_x(pg1, t7229, t7234);
            t7240 = svsub_f64_x(pg1, t7230, t7233);
            t7241 = svsub_f64_x(pg1, t7229, t7234);
            t7242 = svadd_f64_x(pg1, t7230, t7233);
            s4488 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7240, D15[53]), t7239, D15[52]);
            s4489 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7240, D15[52]), t7239, D15[53]);
            s4490 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7242, D15[55]), t7241, D15[54]);
            s4491 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7242, D15[54]), t7241, D15[55]);
            t7243 = svadd_f64_x(pg1, s4362, s4410);
            t7244 = svadd_f64_x(pg1, s4363, s4411);
            t7245 = svsub_f64_x(pg1, s4362, s4410);
            t7246 = svsub_f64_x(pg1, s4363, s4411);
            t7247 = svadd_f64_x(pg1, s4386, s4434);
            t7248 = svadd_f64_x(pg1, s4387, s4435);
            t7249 = svsub_f64_x(pg1, s4386, s4434);
            t7250 = svsub_f64_x(pg1, s4387, s4435);
            t7251 = svadd_f64_x(pg1, t7243, t7247);
            t7252 = svadd_f64_x(pg1, t7244, t7248);
            t7253 = svsub_f64_x(pg1, t7243, t7247);
            t7254 = svsub_f64_x(pg1, t7244, t7248);
            s4492 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7252, D15[57]), t7251, D15[56]);
            s4493 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7252, D15[56]), t7251, D15[57]);
            s4494 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7254, D15[59]), t7253, D15[58]);
            s4495 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7254, D15[58]), t7253, D15[59]);
            t7255 = svadd_f64_x(pg1, t7245, t7250);
            t7256 = svsub_f64_x(pg1, t7246, t7249);
            t7257 = svsub_f64_x(pg1, t7245, t7250);
            t7258 = svadd_f64_x(pg1, t7246, t7249);
            s4496 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7256, D15[61]), t7255, D15[60]);
            s4497 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7256, D15[60]), t7255, D15[61]);
            s4498 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7258, D15[63]), t7257, D15[62]);
            s4499 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7258, D15[62]), t7257, D15[63]);
            t7259 = svadd_f64_x(pg1, s4436, s4468);
            t7260 = svadd_f64_x(pg1, s4437, s4469);
            t7261 = svsub_f64_x(pg1, s4436, s4468);
            t7262 = svsub_f64_x(pg1, s4437, s4469);
            t7263 = svadd_f64_x(pg1, s4452, s4484);
            t7264 = svadd_f64_x(pg1, s4453, s4485);
            t7265 = svsub_f64_x(pg1, s4452, s4484);
            t7266 = svsub_f64_x(pg1, s4453, s4485);
            t7267 = svadd_f64_x(pg1, t7259, t7263);
            t7268 = svadd_f64_x(pg1, t7260, t7264);
            t7269 = svsub_f64_x(pg1, t7259, t7263);
            t7270 = svsub_f64_x(pg1, t7260, t7264);
            t7271 = svadd_f64_x(pg1, t7261, t7266);
            t7272 = svsub_f64_x(pg1, t7262, t7265);
            t7273 = svsub_f64_x(pg1, t7261, t7266);
            t7274 = svadd_f64_x(pg1, t7262, t7265);
            t7275 = svadd_f64_x(pg1, s4444, s4476);
            t7276 = svadd_f64_x(pg1, s4445, s4477);
            t7277 = svsub_f64_x(pg1, s4444, s4476);
            t7278 = svsub_f64_x(pg1, s4445, s4477);
            t7279 = svadd_f64_x(pg1, s4460, s4492);
            t7280 = svadd_f64_x(pg1, s4461, s4493);
            t7281 = svsub_f64_x(pg1, s4460, s4492);
            t7282 = svsub_f64_x(pg1, s4461, s4493);
            t7283 = svadd_f64_x(pg1, t7275, t7279);
            t7284 = svadd_f64_x(pg1, t7276, t7280);
            t7285 = svsub_f64_x(pg1, t7275, t7279);
            t7286 = svsub_f64_x(pg1, t7276, t7280);
            a10268 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7277, t7282), 0.70710678118654757);
            a10269 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7278, t7281), 0.70710678118654757);
            s4500 = svadd_f64_x(pg1, a10268, a10269);
            s4501 = svsub_f64_x(pg1, a10269, a10268);
            a10270 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7278, t7281), 0.70710678118654757);
            a10271 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7277, t7282), 0.70710678118654757);
            s4502 = svsub_f64_x(pg1, a10270, a10271);
            s4503 = svadd_f64_x(pg1, a10271, a10270);
            s4504 = svsub_f64_x(pg1, t7267, t7283);
            s4505 = svsub_f64_x(pg1, t7268, t7284);
            s4506 = svadd_f64_x(pg1, t7271, s4500);
            s4507 = svadd_f64_x(pg1, t7272, s4501);
            s4508 = svsub_f64_x(pg1, t7271, s4500);
            s4509 = svsub_f64_x(pg1, t7272, s4501);
            s4510 = svadd_f64_x(pg1, t7269, t7286);
            s4511 = svsub_f64_x(pg1, t7270, t7285);
            s4512 = svsub_f64_x(pg1, t7269, t7286);
            s4513 = svadd_f64_x(pg1, t7270, t7285);
            s4514 = svadd_f64_x(pg1, t7273, s4502);
            s4515 = svsub_f64_x(pg1, t7274, s4503);
            s4516 = svsub_f64_x(pg1, t7273, s4502);
            s4517 = svadd_f64_x(pg1, t7274, s4503);
            t7287 = svadd_f64_x(pg1, s4440, s4472);
            t7288 = svadd_f64_x(pg1, s4441, s4473);
            t7289 = svsub_f64_x(pg1, s4440, s4472);
            t7290 = svsub_f64_x(pg1, s4441, s4473);
            t7291 = svadd_f64_x(pg1, s4456, s4488);
            t7292 = svadd_f64_x(pg1, s4457, s4489);
            t7293 = svsub_f64_x(pg1, s4456, s4488);
            t7294 = svsub_f64_x(pg1, s4457, s4489);
            t7295 = svadd_f64_x(pg1, t7287, t7291);
            t7296 = svadd_f64_x(pg1, t7288, t7292);
            t7297 = svsub_f64_x(pg1, t7287, t7291);
            t7298 = svsub_f64_x(pg1, t7288, t7292);
            t7299 = svadd_f64_x(pg1, t7289, t7294);
            t7300 = svsub_f64_x(pg1, t7290, t7293);
            t7301 = svsub_f64_x(pg1, t7289, t7294);
            t7302 = svadd_f64_x(pg1, t7290, t7293);
            t7303 = svadd_f64_x(pg1, s4448, s4480);
            t7304 = svadd_f64_x(pg1, s4449, s4481);
            t7305 = svsub_f64_x(pg1, s4448, s4480);
            t7306 = svsub_f64_x(pg1, s4449, s4481);
            t7307 = svadd_f64_x(pg1, s4464, s4496);
            t7308 = svadd_f64_x(pg1, s4465, s4497);
            t7309 = svsub_f64_x(pg1, s4464, s4496);
            t7310 = svsub_f64_x(pg1, s4465, s4497);
            t7311 = svadd_f64_x(pg1, t7303, t7307);
            t7312 = svadd_f64_x(pg1, t7304, t7308);
            t7313 = svsub_f64_x(pg1, t7303, t7307);
            t7314 = svsub_f64_x(pg1, t7304, t7308);
            a10272 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7305, t7310), 0.70710678118654757);
            a10273 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7306, t7309), 0.70710678118654757);
            s4518 = svadd_f64_x(pg1, a10272, a10273);
            s4519 = svsub_f64_x(pg1, a10273, a10272);
            a10274 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7306, t7309), 0.70710678118654757);
            a10275 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7305, t7310), 0.70710678118654757);
            s4520 = svsub_f64_x(pg1, a10274, a10275);
            s4521 = svadd_f64_x(pg1, a10275, a10274);
            s4522 = svadd_f64_x(pg1, t7295, t7311);
            s4523 = svadd_f64_x(pg1, t7296, t7312);
            s4524 = svsub_f64_x(pg1, t7295, t7311);
            s4525 = svsub_f64_x(pg1, t7296, t7312);
            s4526 = svadd_f64_x(pg1, t7299, s4518);
            s4527 = svadd_f64_x(pg1, t7300, s4519);
            s4528 = svsub_f64_x(pg1, t7299, s4518);
            s4529 = svsub_f64_x(pg1, t7300, s4519);
            s4530 = svadd_f64_x(pg1, t7297, t7314);
            s4531 = svsub_f64_x(pg1, t7298, t7313);
            s4532 = svsub_f64_x(pg1, t7297, t7314);
            s4533 = svadd_f64_x(pg1, t7298, t7313);
            s4534 = svadd_f64_x(pg1, t7301, s4520);
            s4535 = svsub_f64_x(pg1, t7302, s4521);
            s4536 = svsub_f64_x(pg1, t7301, s4520);
            s4537 = svadd_f64_x(pg1, t7302, s4521);
            t7315 = svadd_f64_x(pg1, s4438, s4470);
            t7316 = svadd_f64_x(pg1, s4439, s4471);
            t7317 = svsub_f64_x(pg1, s4438, s4470);
            t7318 = svsub_f64_x(pg1, s4439, s4471);
            t7319 = svadd_f64_x(pg1, s4454, s4486);
            t7320 = svadd_f64_x(pg1, s4455, s4487);
            t7321 = svsub_f64_x(pg1, s4454, s4486);
            t7322 = svsub_f64_x(pg1, s4455, s4487);
            t7323 = svadd_f64_x(pg1, t7315, t7319);
            t7324 = svadd_f64_x(pg1, t7316, t7320);
            t7325 = svsub_f64_x(pg1, t7315, t7319);
            t7326 = svsub_f64_x(pg1, t7316, t7320);
            t7327 = svadd_f64_x(pg1, t7317, t7322);
            t7328 = svsub_f64_x(pg1, t7318, t7321);
            t7329 = svsub_f64_x(pg1, t7317, t7322);
            t7330 = svadd_f64_x(pg1, t7318, t7321);
            t7331 = svadd_f64_x(pg1, s4446, s4478);
            t7332 = svadd_f64_x(pg1, s4447, s4479);
            t7333 = svsub_f64_x(pg1, s4446, s4478);
            t7334 = svsub_f64_x(pg1, s4447, s4479);
            t7335 = svadd_f64_x(pg1, s4462, s4494);
            t7336 = svadd_f64_x(pg1, s4463, s4495);
            t7337 = svsub_f64_x(pg1, s4462, s4494);
            t7338 = svsub_f64_x(pg1, s4463, s4495);
            t7339 = svadd_f64_x(pg1, t7331, t7335);
            t7340 = svadd_f64_x(pg1, t7332, t7336);
            t7341 = svsub_f64_x(pg1, t7331, t7335);
            t7342 = svsub_f64_x(pg1, t7332, t7336);
            a10276 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7333, t7338), 0.70710678118654757);
            a10277 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7334, t7337), 0.70710678118654757);
            s4538 = svadd_f64_x(pg1, a10276, a10277);
            s4539 = svsub_f64_x(pg1, a10277, a10276);
            a10278 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7334, t7337), 0.70710678118654757);
            a10279 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7333, t7338), 0.70710678118654757);
            s4540 = svsub_f64_x(pg1, a10278, a10279);
            s4541 = svadd_f64_x(pg1, a10279, a10278);
            s4542 = svadd_f64_x(pg1, t7323, t7339);
            s4543 = svadd_f64_x(pg1, t7324, t7340);
            s4544 = svsub_f64_x(pg1, t7323, t7339);
            s4545 = svsub_f64_x(pg1, t7324, t7340);
            s4546 = svadd_f64_x(pg1, t7327, s4538);
            s4547 = svadd_f64_x(pg1, t7328, s4539);
            s4548 = svsub_f64_x(pg1, t7327, s4538);
            s4549 = svsub_f64_x(pg1, t7328, s4539);
            s4550 = svadd_f64_x(pg1, t7325, t7342);
            s4551 = svsub_f64_x(pg1, t7326, t7341);
            s4552 = svsub_f64_x(pg1, t7325, t7342);
            s4553 = svadd_f64_x(pg1, t7326, t7341);
            s4554 = svadd_f64_x(pg1, t7329, s4540);
            s4555 = svsub_f64_x(pg1, t7330, s4541);
            s4556 = svsub_f64_x(pg1, t7329, s4540);
            s4557 = svadd_f64_x(pg1, t7330, s4541);
            t7343 = svadd_f64_x(pg1, s4442, s4474);
            t7344 = svadd_f64_x(pg1, s4443, s4475);
            t7345 = svsub_f64_x(pg1, s4442, s4474);
            t7346 = svsub_f64_x(pg1, s4443, s4475);
            t7347 = svadd_f64_x(pg1, s4458, s4490);
            t7348 = svadd_f64_x(pg1, s4459, s4491);
            t7349 = svsub_f64_x(pg1, s4458, s4490);
            t7350 = svsub_f64_x(pg1, s4459, s4491);
            t7351 = svadd_f64_x(pg1, t7343, t7347);
            t7352 = svadd_f64_x(pg1, t7344, t7348);
            t7353 = svsub_f64_x(pg1, t7343, t7347);
            t7354 = svsub_f64_x(pg1, t7344, t7348);
            t7355 = svadd_f64_x(pg1, t7345, t7350);
            t7356 = svsub_f64_x(pg1, t7346, t7349);
            t7357 = svsub_f64_x(pg1, t7345, t7350);
            t7358 = svadd_f64_x(pg1, t7346, t7349);
            t7359 = svadd_f64_x(pg1, s4450, s4482);
            t7360 = svadd_f64_x(pg1, s4451, s4483);
            t7361 = svsub_f64_x(pg1, s4450, s4482);
            t7362 = svsub_f64_x(pg1, s4451, s4483);
            t7363 = svadd_f64_x(pg1, s4466, s4498);
            t7364 = svadd_f64_x(pg1, s4467, s4499);
            t7365 = svsub_f64_x(pg1, s4466, s4498);
            t7366 = svsub_f64_x(pg1, s4467, s4499);
            t7367 = svadd_f64_x(pg1, t7359, t7363);
            t7368 = svadd_f64_x(pg1, t7360, t7364);
            t7369 = svsub_f64_x(pg1, t7359, t7363);
            t7370 = svsub_f64_x(pg1, t7360, t7364);
            a10280 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7361, t7366), 0.70710678118654757);
            a10281 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7362, t7365), 0.70710678118654757);
            s4558 = svadd_f64_x(pg1, a10280, a10281);
            s4559 = svsub_f64_x(pg1, a10281, a10280);
            a10282 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7362, t7365), 0.70710678118654757);
            a10283 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7361, t7366), 0.70710678118654757);
            s4560 = svsub_f64_x(pg1, a10282, a10283);
            s4561 = svadd_f64_x(pg1, a10283, a10282);
            s4562 = svadd_f64_x(pg1, t7351, t7367);
            s4563 = svadd_f64_x(pg1, t7352, t7368);
            s4564 = svsub_f64_x(pg1, t7351, t7367);
            s4565 = svsub_f64_x(pg1, t7352, t7368);
            s4566 = svadd_f64_x(pg1, t7355, s4558);
            s4567 = svadd_f64_x(pg1, t7356, s4559);
            s4568 = svsub_f64_x(pg1, t7355, s4558);
            s4569 = svsub_f64_x(pg1, t7356, s4559);
            s4570 = svadd_f64_x(pg1, t7353, t7370);
            s4571 = svsub_f64_x(pg1, t7354, t7369);
            s4572 = svsub_f64_x(pg1, t7353, t7370);
            s4573 = svadd_f64_x(pg1, t7354, t7369);
            s4574 = svadd_f64_x(pg1, t7357, s4560);
            s4575 = svsub_f64_x(pg1, t7358, s4561);
            s4576 = svsub_f64_x(pg1, t7357, s4560);
            s4577 = svadd_f64_x(pg1, t7358, s4561);
            a10284 = ((62)*(j1));
            a10285 = TW1[a10284];
            a10286 = TW1[(a10284 + 1)];
            a10287 = TW1[(a10284 + 2)];
            a10288 = TW1[(a10284 + 3)];
            a10289 = TW1[(a10284 + 4)];
            a10290 = TW1[(a10284 + 5)];
            a10291 = TW1[(a10284 + 6)];
            a10292 = TW1[(a10284 + 7)];
            a10293 = TW1[(a10284 + 8)];
            a10294 = TW1[(a10284 + 9)];
            a10295 = TW1[(a10284 + 10)];
            a10296 = TW1[(a10284 + 11)];
            a10297 = TW1[(a10284 + 12)];
            a10298 = TW1[(a10284 + 13)];
            a10299 = TW1[(a10284 + 14)];
            a10300 = TW1[(a10284 + 15)];
            a10301 = TW1[(a10284 + 16)];
            a10302 = TW1[(a10284 + 17)];
            a10303 = TW1[(a10284 + 18)];
            a10304 = TW1[(a10284 + 19)];
            a10305 = TW1[(a10284 + 20)];
            a10306 = TW1[(a10284 + 21)];
            a10307 = TW1[(a10284 + 22)];
            a10308 = TW1[(a10284 + 23)];
            a10309 = TW1[(a10284 + 24)];
            a10310 = TW1[(a10284 + 25)];
            a10311 = TW1[(a10284 + 26)];
            a10312 = TW1[(a10284 + 27)];
            a10313 = TW1[(a10284 + 28)];
            a10314 = TW1[(a10284 + 29)];
            a10315 = TW1[(a10284 + 30)];
            a10316 = TW1[(a10284 + 31)];
            a10317 = TW1[(a10284 + 32)];
            a10318 = TW1[(a10284 + 33)];
            a10319 = TW1[(a10284 + 34)];
            a10320 = TW1[(a10284 + 35)];
            a10321 = TW1[(a10284 + 36)];
            a10322 = TW1[(a10284 + 37)];
            a10323 = TW1[(a10284 + 38)];
            a10324 = TW1[(a10284 + 39)];
            a10325 = TW1[(a10284 + 40)];
            a10326 = TW1[(a10284 + 41)];
            a10327 = TW1[(a10284 + 42)];
            a10328 = TW1[(a10284 + 43)];
            a10329 = TW1[(a10284 + 44)];
            a10330 = TW1[(a10284 + 45)];
            a10331 = TW1[(a10284 + 46)];
            a10332 = TW1[(a10284 + 47)];
            a10333 = TW1[(a10284 + 48)];
            a10334 = TW1[(a10284 + 49)];
            a10335 = TW1[(a10284 + 50)];
            a10336 = TW1[(a10284 + 51)];
            a10337 = TW1[(a10284 + 52)];
            a10338 = TW1[(a10284 + 53)];
            a10339 = TW1[(a10284 + 54)];
            a10340 = TW1[(a10284 + 55)];
            a10341 = TW1[(a10284 + 56)];
            a10342 = TW1[(a10284 + 57)];
            a10343 = TW1[(a10284 + 58)];
            a10344 = TW1[(a10284 + 59)];
            a10345 = TW1[(a10284 + 60)];
            a10346 = TW1[(a10284 + 61)];
            svex2_33.v0 = svadd_f64_x(pg1, t7267, t7283);
            svex2_33.v1 = svadd_f64_x(pg1, t7268, t7284);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)))))), svex2_33);
            svex2_34.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4523, a10286), s4522, a10285);
            svex2_34.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4523, a10285), s4522, a10286);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + m1)))), svex2_34);
            svex2_35.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4543, a10288), s4542, a10287);
            svex2_35.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4543, a10287), s4542, a10288);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_35);
            svex2_36.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4563, a10290), s4562, a10289);
            svex2_36.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4563, a10289), s4562, a10290);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_36);
            svex2_37.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4507, a10292), s4506, a10291);
            svex2_37.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4507, a10291), s4506, a10292);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_37);
            svex2_38.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4527, a10294), s4526, a10293);
            svex2_38.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4527, a10293), s4526, a10294);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_38);
            svex2_39.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4547, a10296), s4546, a10295);
            svex2_39.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4547, a10295), s4546, a10296);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_39);
            svex2_40.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4567, a10298), s4566, a10297);
            svex2_40.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4567, a10297), s4566, a10298);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_40);
            svex2_41.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4511, a10300), s4510, a10299);
            svex2_41.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4511, a10299), s4510, a10300);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_41);
            svex2_42.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4531, a10302), s4530, a10301);
            svex2_42.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4531, a10301), s4530, a10302);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((9)*(m1)))))), svex2_42);
            svex2_43.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4551, a10304), s4550, a10303);
            svex2_43.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4551, a10303), s4550, a10304);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((10)*(m1)))))), svex2_43);
            svex2_44.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4571, a10306), s4570, a10305);
            svex2_44.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4571, a10305), s4570, a10306);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((11)*(m1)))))), svex2_44);
            svex2_45.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4515, a10308), s4514, a10307);
            svex2_45.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4515, a10307), s4514, a10308);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((12)*(m1)))))), svex2_45);
            svex2_46.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4535, a10310), s4534, a10309);
            svex2_46.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4535, a10309), s4534, a10310);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((13)*(m1)))))), svex2_46);
            svex2_47.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4555, a10312), s4554, a10311);
            svex2_47.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4555, a10311), s4554, a10312);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((14)*(m1)))))), svex2_47);
            svex2_48.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4575, a10314), s4574, a10313);
            svex2_48.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4575, a10313), s4574, a10314);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((15)*(m1)))))), svex2_48);
            svex2_49.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4505, a10316), s4504, a10315);
            svex2_49.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4505, a10315), s4504, a10316);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((16)*(m1)))))), svex2_49);
            svex2_50.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4525, a10318), s4524, a10317);
            svex2_50.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4525, a10317), s4524, a10318);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((17)*(m1)))))), svex2_50);
            svex2_51.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4545, a10320), s4544, a10319);
            svex2_51.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4545, a10319), s4544, a10320);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((18)*(m1)))))), svex2_51);
            svex2_52.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4565, a10322), s4564, a10321);
            svex2_52.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4565, a10321), s4564, a10322);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((19)*(m1)))))), svex2_52);
            svex2_53.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4509, a10324), s4508, a10323);
            svex2_53.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4509, a10323), s4508, a10324);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((20)*(m1)))))), svex2_53);
            svex2_54.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4529, a10326), s4528, a10325);
            svex2_54.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4529, a10325), s4528, a10326);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((21)*(m1)))))), svex2_54);
            svex2_55.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4549, a10328), s4548, a10327);
            svex2_55.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4549, a10327), s4548, a10328);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((22)*(m1)))))), svex2_55);
            svex2_56.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4569, a10330), s4568, a10329);
            svex2_56.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4569, a10329), s4568, a10330);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((23)*(m1)))))), svex2_56);
            svex2_57.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4513, a10332), s4512, a10331);
            svex2_57.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4513, a10331), s4512, a10332);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((24)*(m1)))))), svex2_57);
            svex2_58.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4533, a10334), s4532, a10333);
            svex2_58.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4533, a10333), s4532, a10334);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((25)*(m1)))))), svex2_58);
            svex2_59.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4553, a10336), s4552, a10335);
            svex2_59.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4553, a10335), s4552, a10336);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((26)*(m1)))))), svex2_59);
            svex2_60.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4573, a10338), s4572, a10337);
            svex2_60.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4573, a10337), s4572, a10338);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((27)*(m1)))))), svex2_60);
            svex2_61.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4517, a10340), s4516, a10339);
            svex2_61.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4517, a10339), s4516, a10340);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((28)*(m1)))))), svex2_61);
            svex2_62.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4537, a10342), s4536, a10341);
            svex2_62.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4537, a10341), s4536, a10342);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((29)*(m1)))))), svex2_62);
            svex2_63.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4557, a10344), s4556, a10343);
            svex2_63.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4557, a10343), s4556, a10344);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((30)*(m1)))))), svex2_63);
            svex2_64.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s4577, a10346), s4576, a10345);
            svex2_64.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s4577, a10345), s4576, a10346);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((32)*(j1)))*(m1)) + ((31)*(m1)))))), svex2_64);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
