/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft30c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D73[12];
    static float64_t D74[48];
    int l1, m1;
    svfloat64x2_t s4124, s4127, s4130, s4133, s4136, s4139, s4142, s4145, 
            s4148, s4151, s4154, s4157, s4160, s4163, s4166, s4169, 
            s4172, s4175, s4178, s4181, s4184, s4187, s4190, s4193, 
            s4196, s4199, s4202, s4205, s4208, s4211, svex2_31, svex2_32, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48, 
            svex2_49, svex2_50, svex2_51, svex2_52, svex2_53, svex2_54, svex2_55, svex2_56, 
            svex2_57, svex2_58, svex2_59, svex2_60;
    svfloat64_t s4125, s4126, s4128, s4129, s4131, s4132, s4134, s4135, 
            s4137, s4138, s4140, s4141, s4143, s4144, s4146, s4147, 
            s4149, s4150, s4152, s4153, s4155, s4156, s4158, s4159, 
            s4161, s4162, s4164, s4165, s4167, s4168, s4170, s4171, 
            s4173, s4174, s4176, s4177, s4179, s4180, s4182, s4183, 
            s4185, s4186, s4188, s4189, s4191, s4192, s4194, s4195, 
            s4197, s4198, s4200, s4201, s4203, s4204, s4206, s4207, 
            s4209, s4210, s4212, s4213, s4214, s4215, s4216, s4217, 
            s4218, s4219, s4220, s4221, s4222, s4223, s4224, s4225, 
            s4226, s4227, s4228, s4229, s4230, s4231, s4232, s4233, 
            s4234, s4235, s4236, s4237, s4238, s4239, s4240, s4241, 
            s4242, s4243, s4244, s4245, s4246, s4247, s4248, s4249, 
            s4250, s4251, s4252, s4253, s4254, s4255, s4256, s4257, 
            s4258, s4259, s4260, s4261, s4262, s4263, s4264, s4265, 
            s4266, s4267, s4268, s4269, s4270, s4271, s4272, s4273, 
            s4274, s4275, s4276, s4277, s4278, s4279, s4280, s4281, 
            s4282, s4283, s4284, s4285, s4286, s4287, s4288, s4289, 
            s4290, s4291, s4292, s4293, s4294, s4295, s4296, s4297, 
            s4298, s4299, s4300, s4301, s4302, s4303, s4304, s4305, 
            s4306, s4307, s4308, s4309, s4310, s4311, s4312, s4313, 
            s4314, s4315, s4316, s4317, s4318, s4319, s4320, s4321, 
            s4322, s4323, s4324, s4325, s4326, s4327, s4328, s4329, 
            s4330, s4331, s4332, s4333, s4334, s4335, s4336, s4337, 
            s4338, s4339, s4340, s4341, s4342, s4343, s4344, s4345, 
            s4346, s4347, s4348, s4349, s4350, s4351, s4352, s4353, 
            s4354, s4355, s4356, s4357, s4358, s4359, s4360, s4361, 
            s4362, s4363, s4364, s4365, s4366, s4367, s4368, s4369, 
            s4370, s4371, s4372, s4373, s4374, s4375, s4376, s4377, 
            s4378, s4379, s4380, s4381, s4382, s4383, s4384, s4385, 
            s4386, s4387, s4388, s4389, s4390, s4391, s4392, s4393, 
            t7118, t7119, t7120, t7121, t7122, t7123, t7124, t7125, 
            t7126, t7127, t7128, t7129, t7130, t7131, t7132, t7133, 
            t7134, t7135, t7136, t7137, t7138, t7139, t7140, t7141, 
            t7142, t7143, t7144, t7145, t7146, t7147, t7148, t7149, 
            t7150, t7151, t7152, t7153, t7154, t7155, t7156, t7157, 
            t7158, t7159, t7160, t7161, t7162, t7163, t7164, t7165, 
            t7166, t7167, t7168, t7169, t7170, t7171, t7172, t7173, 
            t7174, t7175, t7176, t7177, t7178, t7179, t7180, t7181, 
            t7182, t7183, t7184, t7185, t7186, t7187, t7188, t7189, 
            t7190, t7191, t7192, t7193, t7194, t7195, t7196, t7197, 
            t7198, t7199, t7200, t7201, t7202, t7203, t7204, t7205, 
            t7206, t7207, t7208, t7209, t7210, t7211, t7212, t7213, 
            t7214, t7215, t7216, t7217, t7218, t7219, t7220, t7221, 
            t7222, t7223, t7224, t7225, t7226, t7227, t7228, t7229, 
            t7230, t7231, t7232, t7233, t7234, t7235, t7236, t7237, 
            t7238, t7239, t7240, t7241, t7242, t7243, t7244, t7245, 
            t7246, t7247, t7248, t7249, t7250, t7251, t7252, t7253, 
            t7254, t7255, t7256, t7257, t7258, t7259, t7260, t7261, 
            t7262, t7263, t7264, t7265, t7266, t7267, t7268, t7269, 
            t7270, t7271, t7272, t7273, t7274, t7275, t7276, t7277, 
            t7278, t7279, t7280, t7281, t7282, t7283, t7284, t7285, 
            t7286, t7287, t7288, t7289, t7290, t7291, t7292, t7293, 
            t7294, t7295, t7296, t7297, t7298, t7299, t7300, t7301, 
            t7302, t7303, t7304, t7305, t7306, t7307, t7308, t7309, 
            t7310, t7311, t7312, t7313, t7314, t7315, t7316, t7317, 
            t7318, t7319, t7320, t7321, t7322, t7323, t7324, t7325, 
            t7326, t7327, t7328, t7329, t7330, t7331, t7332, t7333, 
            t7334, t7335, t7336, t7337, t7338, t7339, t7340, t7341, 
            t7342, t7343, t7344, t7345, t7346, t7347, t7348, t7349, 
            t7350, t7351, t7352, t7353, t7354, t7355, t7356, t7357, 
            t7358, t7359, t7360, t7361, t7362, t7363, t7364, t7365, 
            t7366, t7367, t7368, t7369, t7370, t7371, t7372, t7373, 
            t7374, t7375, t7376, t7377, t7378, t7379, t7380, t7381, 
            t7382, t7383, t7384, t7385, t7386, t7387, t7388, t7389, 
            t7390, t7391, t7392, t7393, t7394, t7395, t7396, t7397, 
            t7398, t7399, t7400, t7401, t7402, t7403, t7404, t7405, 
            t7406, t7407, t7408, t7409, t7410, t7411, t7412, t7413, 
            t7414, t7415, t7416, t7417, t7418, t7419, t7420, t7421;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s4124 = svld2_f64(pg1, (X + ((2)*(k1))));
        s4125 = s4124.v0;
        s4126 = s4124.v1;
        s4127 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s4128 = s4127.v0;
        s4129 = s4127.v1;
        s4130 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s4131 = s4130.v0;
        s4132 = s4130.v1;
        s4133 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s4134 = s4133.v0;
        s4135 = s4133.v1;
        s4136 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s4137 = s4136.v0;
        s4138 = s4136.v1;
        s4139 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s4140 = s4139.v0;
        s4141 = s4139.v1;
        s4142 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s4143 = s4142.v0;
        s4144 = s4142.v1;
        s4145 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s4146 = s4145.v0;
        s4147 = s4145.v1;
        s4148 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s4149 = s4148.v0;
        s4150 = s4148.v1;
        s4151 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s4152 = s4151.v0;
        s4153 = s4151.v1;
        s4154 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s4155 = s4154.v0;
        s4156 = s4154.v1;
        s4157 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s4158 = s4157.v0;
        s4159 = s4157.v1;
        s4160 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s4161 = s4160.v0;
        s4162 = s4160.v1;
        s4163 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s4164 = s4163.v0;
        s4165 = s4163.v1;
        s4166 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s4167 = s4166.v0;
        s4168 = s4166.v1;
        s4169 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s4170 = s4169.v0;
        s4171 = s4169.v1;
        s4172 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s4173 = s4172.v0;
        s4174 = s4172.v1;
        s4175 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s4176 = s4175.v0;
        s4177 = s4175.v1;
        s4178 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s4179 = s4178.v0;
        s4180 = s4178.v1;
        s4181 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s4182 = s4181.v0;
        s4183 = s4181.v1;
        s4184 = svld2_f64(pg1, (X + ((2)*((k1 + ((((20)*(l1)))*(m1)))))));
        s4185 = s4184.v0;
        s4186 = s4184.v1;
        s4187 = svld2_f64(pg1, (X + ((2)*((k1 + ((((21)*(l1)))*(m1)))))));
        s4188 = s4187.v0;
        s4189 = s4187.v1;
        s4190 = svld2_f64(pg1, (X + ((2)*((k1 + ((((22)*(l1)))*(m1)))))));
        s4191 = s4190.v0;
        s4192 = s4190.v1;
        s4193 = svld2_f64(pg1, (X + ((2)*((k1 + ((((23)*(l1)))*(m1)))))));
        s4194 = s4193.v0;
        s4195 = s4193.v1;
        s4196 = svld2_f64(pg1, (X + ((2)*((k1 + ((((24)*(l1)))*(m1)))))));
        s4197 = s4196.v0;
        s4198 = s4196.v1;
        s4199 = svld2_f64(pg1, (X + ((2)*((k1 + ((((25)*(l1)))*(m1)))))));
        s4200 = s4199.v0;
        s4201 = s4199.v1;
        s4202 = svld2_f64(pg1, (X + ((2)*((k1 + ((((26)*(l1)))*(m1)))))));
        s4203 = s4202.v0;
        s4204 = s4202.v1;
        s4205 = svld2_f64(pg1, (X + ((2)*((k1 + ((((27)*(l1)))*(m1)))))));
        s4206 = s4205.v0;
        s4207 = s4205.v1;
        s4208 = svld2_f64(pg1, (X + ((2)*((k1 + ((((28)*(l1)))*(m1)))))));
        s4209 = s4208.v0;
        s4210 = s4208.v1;
        s4211 = svld2_f64(pg1, (X + ((2)*((k1 + ((((29)*(l1)))*(m1)))))));
        s4212 = s4211.v0;
        s4213 = s4211.v1;
        t7118 = svadd_f64_x(pg1, s4143, s4197);
        t7119 = svadd_f64_x(pg1, s4144, s4198);
        t7120 = svsub_f64_x(pg1, s4143, s4197);
        t7121 = svsub_f64_x(pg1, s4144, s4198);
        t7122 = svadd_f64_x(pg1, s4161, s4179);
        t7123 = svadd_f64_x(pg1, s4162, s4180);
        t7124 = svsub_f64_x(pg1, s4161, s4179);
        t7125 = svsub_f64_x(pg1, s4162, s4180);
        t7126 = svadd_f64_x(pg1, t7118, t7122);
        t7127 = svadd_f64_x(pg1, t7119, t7123);
        t7128 = svadd_f64_x(pg1, t7120, t7125);
        t7129 = svsub_f64_x(pg1, t7121, t7124);
        t7130 = svsub_f64_x(pg1, t7120, t7125);
        t7131 = svadd_f64_x(pg1, t7121, t7124);
        t7132 = svadd_f64_x(pg1, s4125, t7126);
        t7133 = svadd_f64_x(pg1, s4126, t7127);
        t7134 = svmls_n_f64_x(pg1, s4125, t7126, 0.25);
        t7135 = svmls_n_f64_x(pg1, s4126, t7127, 0.25);
        s4350 = svmla_n_f64_x(pg1, t7128, t7129, 1.6180339887498947);
        s4214 = svmul_n_f64_x(pg1, s4350, 0.29389262614623657);
        s4351 = svmls_n_f64_x(pg1, t7129, t7128, 1.6180339887498947);
        s4215 = svmul_n_f64_x(pg1, s4351, 0.29389262614623657);
        s4216 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7118, t7122), 0.55901699437494745);
        s4217 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7119, t7123), 0.55901699437494745);
        s4352 = svmls_n_f64_x(pg1, t7131, t7130, 0.61803398874989479);
        s4218 = svmul_n_f64_x(pg1, s4352, 0.47552825814757682);
        s4353 = svmla_n_f64_x(pg1, t7130, t7131, 0.61803398874989479);
        s4219 = svmul_n_f64_x(pg1, s4353, 0.47552825814757682);
        s4220 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7133, D73[1]), t7132, D73[0]);
        s4221 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7133, D73[0]), t7132, D73[1]);
        t7136 = svadd_f64_x(pg1, t7134, s4216);
        t7137 = svadd_f64_x(pg1, t7135, s4217);
        t7138 = svsub_f64_x(pg1, t7134, s4216);
        t7139 = svsub_f64_x(pg1, t7135, s4217);
        t7140 = svadd_f64_x(pg1, s4214, s4218);
        t7141 = svsub_f64_x(pg1, s4215, s4219);
        t7142 = svsub_f64_x(pg1, s4214, s4218);
        t7143 = svadd_f64_x(pg1, s4215, s4219);
        t7144 = svadd_f64_x(pg1, t7136, t7140);
        t7145 = svadd_f64_x(pg1, t7137, t7141);
        t7146 = svsub_f64_x(pg1, t7136, t7140);
        t7147 = svsub_f64_x(pg1, t7137, t7141);
        s4222 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7145, D74[1]), t7144, D74[0]);
        s4223 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7145, D74[0]), t7144, D74[1]);
        s4224 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7147, D74[3]), t7146, D74[2]);
        s4225 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7147, D74[2]), t7146, D74[3]);
        t7148 = svadd_f64_x(pg1, t7138, t7143);
        t7149 = svsub_f64_x(pg1, t7139, t7142);
        t7150 = svsub_f64_x(pg1, t7138, t7143);
        t7151 = svadd_f64_x(pg1, t7139, t7142);
        s4226 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7149, D74[5]), t7148, D74[4]);
        s4227 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7149, D74[4]), t7148, D74[5]);
        s4228 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7151, D74[7]), t7150, D74[6]);
        s4229 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7151, D74[6]), t7150, D74[7]);
        t7152 = svadd_f64_x(pg1, s4146, s4200);
        t7153 = svadd_f64_x(pg1, s4147, s4201);
        t7154 = svsub_f64_x(pg1, s4146, s4200);
        t7155 = svsub_f64_x(pg1, s4147, s4201);
        t7156 = svadd_f64_x(pg1, s4164, s4182);
        t7157 = svadd_f64_x(pg1, s4165, s4183);
        t7158 = svsub_f64_x(pg1, s4164, s4182);
        t7159 = svsub_f64_x(pg1, s4165, s4183);
        t7160 = svadd_f64_x(pg1, t7152, t7156);
        t7161 = svadd_f64_x(pg1, t7153, t7157);
        t7162 = svadd_f64_x(pg1, t7154, t7159);
        t7163 = svsub_f64_x(pg1, t7155, t7158);
        t7164 = svsub_f64_x(pg1, t7154, t7159);
        t7165 = svadd_f64_x(pg1, t7155, t7158);
        t7166 = svadd_f64_x(pg1, s4128, t7160);
        t7167 = svadd_f64_x(pg1, s4129, t7161);
        t7168 = svmls_n_f64_x(pg1, s4128, t7160, 0.25);
        t7169 = svmls_n_f64_x(pg1, s4129, t7161, 0.25);
        s4354 = svmla_n_f64_x(pg1, t7162, t7163, 1.6180339887498947);
        s4230 = svmul_n_f64_x(pg1, s4354, 0.29389262614623657);
        s4355 = svmls_n_f64_x(pg1, t7163, t7162, 1.6180339887498947);
        s4231 = svmul_n_f64_x(pg1, s4355, 0.29389262614623657);
        s4232 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7152, t7156), 0.55901699437494745);
        s4233 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7153, t7157), 0.55901699437494745);
        s4356 = svmls_n_f64_x(pg1, t7165, t7164, 0.61803398874989479);
        s4234 = svmul_n_f64_x(pg1, s4356, 0.47552825814757682);
        s4357 = svmla_n_f64_x(pg1, t7164, t7165, 0.61803398874989479);
        s4235 = svmul_n_f64_x(pg1, s4357, 0.47552825814757682);
        s4236 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7167, D73[3]), t7166, D73[2]);
        s4237 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7167, D73[2]), t7166, D73[3]);
        t7170 = svadd_f64_x(pg1, t7168, s4232);
        t7171 = svadd_f64_x(pg1, t7169, s4233);
        t7172 = svsub_f64_x(pg1, t7168, s4232);
        t7173 = svsub_f64_x(pg1, t7169, s4233);
        t7174 = svadd_f64_x(pg1, s4230, s4234);
        t7175 = svsub_f64_x(pg1, s4231, s4235);
        t7176 = svsub_f64_x(pg1, s4230, s4234);
        t7177 = svadd_f64_x(pg1, s4231, s4235);
        t7178 = svadd_f64_x(pg1, t7170, t7174);
        t7179 = svadd_f64_x(pg1, t7171, t7175);
        t7180 = svsub_f64_x(pg1, t7170, t7174);
        t7181 = svsub_f64_x(pg1, t7171, t7175);
        s4238 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7179, D74[9]), t7178, D74[8]);
        s4239 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7179, D74[8]), t7178, D74[9]);
        s4240 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7181, D74[11]), t7180, D74[10]);
        s4241 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7181, D74[10]), t7180, D74[11]);
        t7182 = svadd_f64_x(pg1, t7172, t7177);
        t7183 = svsub_f64_x(pg1, t7173, t7176);
        t7184 = svsub_f64_x(pg1, t7172, t7177);
        t7185 = svadd_f64_x(pg1, t7173, t7176);
        s4242 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7183, D74[13]), t7182, D74[12]);
        s4243 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7183, D74[12]), t7182, D74[13]);
        s4244 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7185, D74[15]), t7184, D74[14]);
        s4245 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7185, D74[14]), t7184, D74[15]);
        t7186 = svadd_f64_x(pg1, s4149, s4203);
        t7187 = svadd_f64_x(pg1, s4150, s4204);
        t7188 = svsub_f64_x(pg1, s4149, s4203);
        t7189 = svsub_f64_x(pg1, s4150, s4204);
        t7190 = svadd_f64_x(pg1, s4167, s4185);
        t7191 = svadd_f64_x(pg1, s4168, s4186);
        t7192 = svsub_f64_x(pg1, s4167, s4185);
        t7193 = svsub_f64_x(pg1, s4168, s4186);
        t7194 = svadd_f64_x(pg1, t7186, t7190);
        t7195 = svadd_f64_x(pg1, t7187, t7191);
        t7196 = svadd_f64_x(pg1, t7188, t7193);
        t7197 = svsub_f64_x(pg1, t7189, t7192);
        t7198 = svsub_f64_x(pg1, t7188, t7193);
        t7199 = svadd_f64_x(pg1, t7189, t7192);
        t7200 = svadd_f64_x(pg1, s4131, t7194);
        t7201 = svadd_f64_x(pg1, s4132, t7195);
        t7202 = svmls_n_f64_x(pg1, s4131, t7194, 0.25);
        t7203 = svmls_n_f64_x(pg1, s4132, t7195, 0.25);
        s4358 = svmla_n_f64_x(pg1, t7196, t7197, 1.6180339887498947);
        s4246 = svmul_n_f64_x(pg1, s4358, 0.29389262614623657);
        s4359 = svmls_n_f64_x(pg1, t7197, t7196, 1.6180339887498947);
        s4247 = svmul_n_f64_x(pg1, s4359, 0.29389262614623657);
        s4248 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7186, t7190), 0.55901699437494745);
        s4249 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7187, t7191), 0.55901699437494745);
        s4360 = svmls_n_f64_x(pg1, t7199, t7198, 0.61803398874989479);
        s4250 = svmul_n_f64_x(pg1, s4360, 0.47552825814757682);
        s4361 = svmla_n_f64_x(pg1, t7198, t7199, 0.61803398874989479);
        s4251 = svmul_n_f64_x(pg1, s4361, 0.47552825814757682);
        s4252 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7201, D73[5]), t7200, D73[4]);
        s4253 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7201, D73[4]), t7200, D73[5]);
        t7204 = svadd_f64_x(pg1, t7202, s4248);
        t7205 = svadd_f64_x(pg1, t7203, s4249);
        t7206 = svsub_f64_x(pg1, t7202, s4248);
        t7207 = svsub_f64_x(pg1, t7203, s4249);
        t7208 = svadd_f64_x(pg1, s4246, s4250);
        t7209 = svsub_f64_x(pg1, s4247, s4251);
        t7210 = svsub_f64_x(pg1, s4246, s4250);
        t7211 = svadd_f64_x(pg1, s4247, s4251);
        t7212 = svadd_f64_x(pg1, t7204, t7208);
        t7213 = svadd_f64_x(pg1, t7205, t7209);
        t7214 = svsub_f64_x(pg1, t7204, t7208);
        t7215 = svsub_f64_x(pg1, t7205, t7209);
        s4254 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7213, D74[17]), t7212, D74[16]);
        s4255 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7213, D74[16]), t7212, D74[17]);
        s4256 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7215, D74[19]), t7214, D74[18]);
        s4257 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7215, D74[18]), t7214, D74[19]);
        t7216 = svadd_f64_x(pg1, t7206, t7211);
        t7217 = svsub_f64_x(pg1, t7207, t7210);
        t7218 = svsub_f64_x(pg1, t7206, t7211);
        t7219 = svadd_f64_x(pg1, t7207, t7210);
        s4258 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7217, D74[21]), t7216, D74[20]);
        s4259 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7217, D74[20]), t7216, D74[21]);
        s4260 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7219, D74[23]), t7218, D74[22]);
        s4261 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7219, D74[22]), t7218, D74[23]);
        t7220 = svadd_f64_x(pg1, s4152, s4206);
        t7221 = svadd_f64_x(pg1, s4153, s4207);
        t7222 = svsub_f64_x(pg1, s4152, s4206);
        t7223 = svsub_f64_x(pg1, s4153, s4207);
        t7224 = svadd_f64_x(pg1, s4170, s4188);
        t7225 = svadd_f64_x(pg1, s4171, s4189);
        t7226 = svsub_f64_x(pg1, s4170, s4188);
        t7227 = svsub_f64_x(pg1, s4171, s4189);
        t7228 = svadd_f64_x(pg1, t7220, t7224);
        t7229 = svadd_f64_x(pg1, t7221, t7225);
        t7230 = svadd_f64_x(pg1, t7222, t7227);
        t7231 = svsub_f64_x(pg1, t7223, t7226);
        t7232 = svsub_f64_x(pg1, t7222, t7227);
        t7233 = svadd_f64_x(pg1, t7223, t7226);
        t7234 = svadd_f64_x(pg1, s4134, t7228);
        t7235 = svadd_f64_x(pg1, s4135, t7229);
        t7236 = svmls_n_f64_x(pg1, s4134, t7228, 0.25);
        t7237 = svmls_n_f64_x(pg1, s4135, t7229, 0.25);
        s4362 = svmla_n_f64_x(pg1, t7230, t7231, 1.6180339887498947);
        s4262 = svmul_n_f64_x(pg1, s4362, 0.29389262614623657);
        s4363 = svmls_n_f64_x(pg1, t7231, t7230, 1.6180339887498947);
        s4263 = svmul_n_f64_x(pg1, s4363, 0.29389262614623657);
        s4264 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7220, t7224), 0.55901699437494745);
        s4265 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7221, t7225), 0.55901699437494745);
        s4364 = svmls_n_f64_x(pg1, t7233, t7232, 0.61803398874989479);
        s4266 = svmul_n_f64_x(pg1, s4364, 0.47552825814757682);
        s4365 = svmla_n_f64_x(pg1, t7232, t7233, 0.61803398874989479);
        s4267 = svmul_n_f64_x(pg1, s4365, 0.47552825814757682);
        s4268 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7235, D73[7]), t7234, D73[6]);
        s4269 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7235, D73[6]), t7234, D73[7]);
        t7238 = svadd_f64_x(pg1, t7236, s4264);
        t7239 = svadd_f64_x(pg1, t7237, s4265);
        t7240 = svsub_f64_x(pg1, t7236, s4264);
        t7241 = svsub_f64_x(pg1, t7237, s4265);
        t7242 = svadd_f64_x(pg1, s4262, s4266);
        t7243 = svsub_f64_x(pg1, s4263, s4267);
        t7244 = svsub_f64_x(pg1, s4262, s4266);
        t7245 = svadd_f64_x(pg1, s4263, s4267);
        t7246 = svadd_f64_x(pg1, t7238, t7242);
        t7247 = svadd_f64_x(pg1, t7239, t7243);
        t7248 = svsub_f64_x(pg1, t7238, t7242);
        t7249 = svsub_f64_x(pg1, t7239, t7243);
        s4270 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7247, D74[25]), t7246, D74[24]);
        s4271 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7247, D74[24]), t7246, D74[25]);
        s4272 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7249, D74[27]), t7248, D74[26]);
        s4273 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7249, D74[26]), t7248, D74[27]);
        t7250 = svadd_f64_x(pg1, t7240, t7245);
        t7251 = svsub_f64_x(pg1, t7241, t7244);
        t7252 = svsub_f64_x(pg1, t7240, t7245);
        t7253 = svadd_f64_x(pg1, t7241, t7244);
        s4274 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7251, D74[29]), t7250, D74[28]);
        s4275 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7251, D74[28]), t7250, D74[29]);
        s4276 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7253, D74[31]), t7252, D74[30]);
        s4277 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7253, D74[30]), t7252, D74[31]);
        t7254 = svadd_f64_x(pg1, s4155, s4209);
        t7255 = svadd_f64_x(pg1, s4156, s4210);
        t7256 = svsub_f64_x(pg1, s4155, s4209);
        t7257 = svsub_f64_x(pg1, s4156, s4210);
        t7258 = svadd_f64_x(pg1, s4173, s4191);
        t7259 = svadd_f64_x(pg1, s4174, s4192);
        t7260 = svsub_f64_x(pg1, s4173, s4191);
        t7261 = svsub_f64_x(pg1, s4174, s4192);
        t7262 = svadd_f64_x(pg1, t7254, t7258);
        t7263 = svadd_f64_x(pg1, t7255, t7259);
        t7264 = svadd_f64_x(pg1, t7256, t7261);
        t7265 = svsub_f64_x(pg1, t7257, t7260);
        t7266 = svsub_f64_x(pg1, t7256, t7261);
        t7267 = svadd_f64_x(pg1, t7257, t7260);
        t7268 = svadd_f64_x(pg1, s4137, t7262);
        t7269 = svadd_f64_x(pg1, s4138, t7263);
        t7270 = svmls_n_f64_x(pg1, s4137, t7262, 0.25);
        t7271 = svmls_n_f64_x(pg1, s4138, t7263, 0.25);
        s4366 = svmla_n_f64_x(pg1, t7264, t7265, 1.6180339887498947);
        s4278 = svmul_n_f64_x(pg1, s4366, 0.29389262614623657);
        s4367 = svmls_n_f64_x(pg1, t7265, t7264, 1.6180339887498947);
        s4279 = svmul_n_f64_x(pg1, s4367, 0.29389262614623657);
        s4280 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7254, t7258), 0.55901699437494745);
        s4281 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7255, t7259), 0.55901699437494745);
        s4368 = svmls_n_f64_x(pg1, t7267, t7266, 0.61803398874989479);
        s4282 = svmul_n_f64_x(pg1, s4368, 0.47552825814757682);
        s4369 = svmla_n_f64_x(pg1, t7266, t7267, 0.61803398874989479);
        s4283 = svmul_n_f64_x(pg1, s4369, 0.47552825814757682);
        s4284 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7269, D73[9]), t7268, D73[8]);
        s4285 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7269, D73[8]), t7268, D73[9]);
        t7272 = svadd_f64_x(pg1, t7270, s4280);
        t7273 = svadd_f64_x(pg1, t7271, s4281);
        t7274 = svsub_f64_x(pg1, t7270, s4280);
        t7275 = svsub_f64_x(pg1, t7271, s4281);
        t7276 = svadd_f64_x(pg1, s4278, s4282);
        t7277 = svsub_f64_x(pg1, s4279, s4283);
        t7278 = svsub_f64_x(pg1, s4278, s4282);
        t7279 = svadd_f64_x(pg1, s4279, s4283);
        t7280 = svadd_f64_x(pg1, t7272, t7276);
        t7281 = svadd_f64_x(pg1, t7273, t7277);
        t7282 = svsub_f64_x(pg1, t7272, t7276);
        t7283 = svsub_f64_x(pg1, t7273, t7277);
        s4286 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7281, D74[33]), t7280, D74[32]);
        s4287 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7281, D74[32]), t7280, D74[33]);
        s4288 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7283, D74[35]), t7282, D74[34]);
        s4289 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7283, D74[34]), t7282, D74[35]);
        t7284 = svadd_f64_x(pg1, t7274, t7279);
        t7285 = svsub_f64_x(pg1, t7275, t7278);
        t7286 = svsub_f64_x(pg1, t7274, t7279);
        t7287 = svadd_f64_x(pg1, t7275, t7278);
        s4290 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7285, D74[37]), t7284, D74[36]);
        s4291 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7285, D74[36]), t7284, D74[37]);
        s4292 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7287, D74[39]), t7286, D74[38]);
        s4293 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7287, D74[38]), t7286, D74[39]);
        t7288 = svadd_f64_x(pg1, s4158, s4212);
        t7289 = svadd_f64_x(pg1, s4159, s4213);
        t7290 = svsub_f64_x(pg1, s4158, s4212);
        t7291 = svsub_f64_x(pg1, s4159, s4213);
        t7292 = svadd_f64_x(pg1, s4176, s4194);
        t7293 = svadd_f64_x(pg1, s4177, s4195);
        t7294 = svsub_f64_x(pg1, s4176, s4194);
        t7295 = svsub_f64_x(pg1, s4177, s4195);
        t7296 = svadd_f64_x(pg1, t7288, t7292);
        t7297 = svadd_f64_x(pg1, t7289, t7293);
        t7298 = svadd_f64_x(pg1, t7290, t7295);
        t7299 = svsub_f64_x(pg1, t7291, t7294);
        t7300 = svsub_f64_x(pg1, t7290, t7295);
        t7301 = svadd_f64_x(pg1, t7291, t7294);
        t7302 = svadd_f64_x(pg1, s4140, t7296);
        t7303 = svadd_f64_x(pg1, s4141, t7297);
        t7304 = svmls_n_f64_x(pg1, s4140, t7296, 0.25);
        t7305 = svmls_n_f64_x(pg1, s4141, t7297, 0.25);
        s4370 = svmla_n_f64_x(pg1, t7298, t7299, 1.6180339887498947);
        s4294 = svmul_n_f64_x(pg1, s4370, 0.29389262614623657);
        s4371 = svmls_n_f64_x(pg1, t7299, t7298, 1.6180339887498947);
        s4295 = svmul_n_f64_x(pg1, s4371, 0.29389262614623657);
        s4296 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7288, t7292), 0.55901699437494745);
        s4297 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7289, t7293), 0.55901699437494745);
        s4372 = svmls_n_f64_x(pg1, t7301, t7300, 0.61803398874989479);
        s4298 = svmul_n_f64_x(pg1, s4372, 0.47552825814757682);
        s4373 = svmla_n_f64_x(pg1, t7300, t7301, 0.61803398874989479);
        s4299 = svmul_n_f64_x(pg1, s4373, 0.47552825814757682);
        s4300 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7303, D73[11]), t7302, D73[10]);
        s4301 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7303, D73[10]), t7302, D73[11]);
        t7306 = svadd_f64_x(pg1, t7304, s4296);
        t7307 = svadd_f64_x(pg1, t7305, s4297);
        t7308 = svsub_f64_x(pg1, t7304, s4296);
        t7309 = svsub_f64_x(pg1, t7305, s4297);
        t7310 = svadd_f64_x(pg1, s4294, s4298);
        t7311 = svsub_f64_x(pg1, s4295, s4299);
        t7312 = svsub_f64_x(pg1, s4294, s4298);
        t7313 = svadd_f64_x(pg1, s4295, s4299);
        t7314 = svadd_f64_x(pg1, t7306, t7310);
        t7315 = svadd_f64_x(pg1, t7307, t7311);
        t7316 = svsub_f64_x(pg1, t7306, t7310);
        t7317 = svsub_f64_x(pg1, t7307, t7311);
        s4302 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7315, D74[41]), t7314, D74[40]);
        s4303 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7315, D74[40]), t7314, D74[41]);
        s4304 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7317, D74[43]), t7316, D74[42]);
        s4305 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7317, D74[42]), t7316, D74[43]);
        t7318 = svadd_f64_x(pg1, t7308, t7313);
        t7319 = svsub_f64_x(pg1, t7309, t7312);
        t7320 = svsub_f64_x(pg1, t7308, t7313);
        t7321 = svadd_f64_x(pg1, t7309, t7312);
        s4306 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7319, D74[45]), t7318, D74[44]);
        s4307 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7319, D74[44]), t7318, D74[45]);
        s4308 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7321, D74[47]), t7320, D74[46]);
        s4309 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7321, D74[46]), t7320, D74[47]);
        t7322 = svadd_f64_x(pg1, s4252, s4284);
        t7323 = svadd_f64_x(pg1, s4253, s4285);
        t7324 = svadd_f64_x(pg1, s4220, t7322);
        t7325 = svadd_f64_x(pg1, s4221, t7323);
        t7326 = svmls_n_f64_x(pg1, s4220, t7322, 0.5);
        t7327 = svmls_n_f64_x(pg1, s4221, t7323, 0.5);
        s4310 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4253, s4285), 0.8660254037844386);
        s4311 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4252, s4284), 0.8660254037844386);
        t7328 = svadd_f64_x(pg1, t7326, s4310);
        t7329 = svsub_f64_x(pg1, t7327, s4311);
        t7330 = svsub_f64_x(pg1, t7326, s4310);
        t7331 = svadd_f64_x(pg1, t7327, s4311);
        t7332 = svadd_f64_x(pg1, s4268, s4300);
        t7333 = svadd_f64_x(pg1, s4269, s4301);
        t7334 = svadd_f64_x(pg1, s4236, t7332);
        t7335 = svadd_f64_x(pg1, s4237, t7333);
        t7336 = svmls_n_f64_x(pg1, s4236, t7332, 0.5);
        t7337 = svmls_n_f64_x(pg1, s4237, t7333, 0.5);
        s4312 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4269, s4301), 0.8660254037844386);
        s4313 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4268, s4300), 0.8660254037844386);
        t7338 = svadd_f64_x(pg1, t7336, s4312);
        t7339 = svsub_f64_x(pg1, t7337, s4313);
        t7340 = svsub_f64_x(pg1, t7336, s4312);
        t7341 = svadd_f64_x(pg1, t7337, s4313);
        s4374 = svmla_n_f64_x(pg1, t7338, t7339, 1.7320508075688772);
        s4314 = svmul_n_f64_x(pg1, s4374, 0.5);
        s4375 = svmls_n_f64_x(pg1, t7339, t7338, 1.7320508075688772);
        s4315 = svmul_n_f64_x(pg1, s4375, 0.5);
        s4376 = svmls_n_f64_x(pg1, t7341, t7340, 0.57735026918962584);
        s4316 = svmul_n_f64_x(pg1, s4376, 0.8660254037844386);
        s4377 = svmla_n_f64_x(pg1, t7340, t7341, 0.57735026918962584);
        s4317 = svmul_n_f64_x(pg1, s4377, 0.8660254037844386);
        t7342 = svadd_f64_x(pg1, s4254, s4286);
        t7343 = svadd_f64_x(pg1, s4255, s4287);
        t7344 = svadd_f64_x(pg1, s4222, t7342);
        t7345 = svadd_f64_x(pg1, s4223, t7343);
        t7346 = svmls_n_f64_x(pg1, s4222, t7342, 0.5);
        t7347 = svmls_n_f64_x(pg1, s4223, t7343, 0.5);
        s4318 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4255, s4287), 0.8660254037844386);
        s4319 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4254, s4286), 0.8660254037844386);
        t7348 = svadd_f64_x(pg1, t7346, s4318);
        t7349 = svsub_f64_x(pg1, t7347, s4319);
        t7350 = svsub_f64_x(pg1, t7346, s4318);
        t7351 = svadd_f64_x(pg1, t7347, s4319);
        t7352 = svadd_f64_x(pg1, s4270, s4302);
        t7353 = svadd_f64_x(pg1, s4271, s4303);
        t7354 = svadd_f64_x(pg1, s4238, t7352);
        t7355 = svadd_f64_x(pg1, s4239, t7353);
        t7356 = svmls_n_f64_x(pg1, s4238, t7352, 0.5);
        t7357 = svmls_n_f64_x(pg1, s4239, t7353, 0.5);
        s4320 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4271, s4303), 0.8660254037844386);
        s4321 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4270, s4302), 0.8660254037844386);
        t7358 = svadd_f64_x(pg1, t7356, s4320);
        t7359 = svsub_f64_x(pg1, t7357, s4321);
        t7360 = svsub_f64_x(pg1, t7356, s4320);
        t7361 = svadd_f64_x(pg1, t7357, s4321);
        s4378 = svmla_n_f64_x(pg1, t7358, t7359, 1.7320508075688772);
        s4322 = svmul_n_f64_x(pg1, s4378, 0.5);
        s4379 = svmls_n_f64_x(pg1, t7359, t7358, 1.7320508075688772);
        s4323 = svmul_n_f64_x(pg1, s4379, 0.5);
        s4380 = svmls_n_f64_x(pg1, t7361, t7360, 0.57735026918962584);
        s4324 = svmul_n_f64_x(pg1, s4380, 0.8660254037844386);
        s4381 = svmla_n_f64_x(pg1, t7360, t7361, 0.57735026918962584);
        s4325 = svmul_n_f64_x(pg1, s4381, 0.8660254037844386);
        t7362 = svadd_f64_x(pg1, s4258, s4290);
        t7363 = svadd_f64_x(pg1, s4259, s4291);
        t7364 = svadd_f64_x(pg1, s4226, t7362);
        t7365 = svadd_f64_x(pg1, s4227, t7363);
        t7366 = svmls_n_f64_x(pg1, s4226, t7362, 0.5);
        t7367 = svmls_n_f64_x(pg1, s4227, t7363, 0.5);
        s4326 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4259, s4291), 0.8660254037844386);
        s4327 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4258, s4290), 0.8660254037844386);
        t7368 = svadd_f64_x(pg1, t7366, s4326);
        t7369 = svsub_f64_x(pg1, t7367, s4327);
        t7370 = svsub_f64_x(pg1, t7366, s4326);
        t7371 = svadd_f64_x(pg1, t7367, s4327);
        t7372 = svadd_f64_x(pg1, s4274, s4306);
        t7373 = svadd_f64_x(pg1, s4275, s4307);
        t7374 = svadd_f64_x(pg1, s4242, t7372);
        t7375 = svadd_f64_x(pg1, s4243, t7373);
        t7376 = svmls_n_f64_x(pg1, s4242, t7372, 0.5);
        t7377 = svmls_n_f64_x(pg1, s4243, t7373, 0.5);
        s4328 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4275, s4307), 0.8660254037844386);
        s4329 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4274, s4306), 0.8660254037844386);
        t7378 = svadd_f64_x(pg1, t7376, s4328);
        t7379 = svsub_f64_x(pg1, t7377, s4329);
        t7380 = svsub_f64_x(pg1, t7376, s4328);
        t7381 = svadd_f64_x(pg1, t7377, s4329);
        s4382 = svmla_n_f64_x(pg1, t7378, t7379, 1.7320508075688772);
        s4330 = svmul_n_f64_x(pg1, s4382, 0.5);
        s4383 = svmls_n_f64_x(pg1, t7379, t7378, 1.7320508075688772);
        s4331 = svmul_n_f64_x(pg1, s4383, 0.5);
        s4384 = svmls_n_f64_x(pg1, t7381, t7380, 0.57735026918962584);
        s4332 = svmul_n_f64_x(pg1, s4384, 0.8660254037844386);
        s4385 = svmla_n_f64_x(pg1, t7380, t7381, 0.57735026918962584);
        s4333 = svmul_n_f64_x(pg1, s4385, 0.8660254037844386);
        t7382 = svadd_f64_x(pg1, s4260, s4292);
        t7383 = svadd_f64_x(pg1, s4261, s4293);
        t7384 = svadd_f64_x(pg1, s4228, t7382);
        t7385 = svadd_f64_x(pg1, s4229, t7383);
        t7386 = svmls_n_f64_x(pg1, s4228, t7382, 0.5);
        t7387 = svmls_n_f64_x(pg1, s4229, t7383, 0.5);
        s4334 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4261, s4293), 0.8660254037844386);
        s4335 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4260, s4292), 0.8660254037844386);
        t7388 = svadd_f64_x(pg1, t7386, s4334);
        t7389 = svsub_f64_x(pg1, t7387, s4335);
        t7390 = svsub_f64_x(pg1, t7386, s4334);
        t7391 = svadd_f64_x(pg1, t7387, s4335);
        t7392 = svadd_f64_x(pg1, s4276, s4308);
        t7393 = svadd_f64_x(pg1, s4277, s4309);
        t7394 = svadd_f64_x(pg1, s4244, t7392);
        t7395 = svadd_f64_x(pg1, s4245, t7393);
        t7396 = svmls_n_f64_x(pg1, s4244, t7392, 0.5);
        t7397 = svmls_n_f64_x(pg1, s4245, t7393, 0.5);
        s4336 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4277, s4309), 0.8660254037844386);
        s4337 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4276, s4308), 0.8660254037844386);
        t7398 = svadd_f64_x(pg1, t7396, s4336);
        t7399 = svsub_f64_x(pg1, t7397, s4337);
        t7400 = svsub_f64_x(pg1, t7396, s4336);
        t7401 = svadd_f64_x(pg1, t7397, s4337);
        s4386 = svmla_n_f64_x(pg1, t7398, t7399, 1.7320508075688772);
        s4338 = svmul_n_f64_x(pg1, s4386, 0.5);
        s4387 = svmls_n_f64_x(pg1, t7399, t7398, 1.7320508075688772);
        s4339 = svmul_n_f64_x(pg1, s4387, 0.5);
        s4388 = svmls_n_f64_x(pg1, t7401, t7400, 0.57735026918962584);
        s4340 = svmul_n_f64_x(pg1, s4388, 0.8660254037844386);
        s4389 = svmla_n_f64_x(pg1, t7400, t7401, 0.57735026918962584);
        s4341 = svmul_n_f64_x(pg1, s4389, 0.8660254037844386);
        t7402 = svadd_f64_x(pg1, s4256, s4288);
        t7403 = svadd_f64_x(pg1, s4257, s4289);
        t7404 = svadd_f64_x(pg1, s4224, t7402);
        t7405 = svadd_f64_x(pg1, s4225, t7403);
        t7406 = svmls_n_f64_x(pg1, s4224, t7402, 0.5);
        t7407 = svmls_n_f64_x(pg1, s4225, t7403, 0.5);
        s4342 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4257, s4289), 0.8660254037844386);
        s4343 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4256, s4288), 0.8660254037844386);
        t7408 = svadd_f64_x(pg1, t7406, s4342);
        t7409 = svsub_f64_x(pg1, t7407, s4343);
        t7410 = svsub_f64_x(pg1, t7406, s4342);
        t7411 = svadd_f64_x(pg1, t7407, s4343);
        t7412 = svadd_f64_x(pg1, s4272, s4304);
        t7413 = svadd_f64_x(pg1, s4273, s4305);
        t7414 = svadd_f64_x(pg1, s4240, t7412);
        t7415 = svadd_f64_x(pg1, s4241, t7413);
        t7416 = svmls_n_f64_x(pg1, s4240, t7412, 0.5);
        t7417 = svmls_n_f64_x(pg1, s4241, t7413, 0.5);
        s4344 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4273, s4305), 0.8660254037844386);
        s4345 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s4272, s4304), 0.8660254037844386);
        t7418 = svadd_f64_x(pg1, t7416, s4344);
        t7419 = svsub_f64_x(pg1, t7417, s4345);
        t7420 = svsub_f64_x(pg1, t7416, s4344);
        t7421 = svadd_f64_x(pg1, t7417, s4345);
        s4390 = svmla_n_f64_x(pg1, t7418, t7419, 1.7320508075688772);
        s4346 = svmul_n_f64_x(pg1, s4390, 0.5);
        s4391 = svmls_n_f64_x(pg1, t7419, t7418, 1.7320508075688772);
        s4347 = svmul_n_f64_x(pg1, s4391, 0.5);
        s4392 = svmls_n_f64_x(pg1, t7421, t7420, 0.57735026918962584);
        s4348 = svmul_n_f64_x(pg1, s4392, 0.8660254037844386);
        s4393 = svmla_n_f64_x(pg1, t7420, t7421, 0.57735026918962584);
        s4349 = svmul_n_f64_x(pg1, s4393, 0.8660254037844386);
        svex2_31.v0 = svadd_f64_x(pg1, t7324, t7334);
        svex2_31.v1 = svadd_f64_x(pg1, t7325, t7335);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_31);
        svex2_32.v0 = svadd_f64_x(pg1, t7344, t7354);
        svex2_32.v1 = svadd_f64_x(pg1, t7345, t7355);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_32);
        svex2_33.v0 = svadd_f64_x(pg1, t7364, t7374);
        svex2_33.v1 = svadd_f64_x(pg1, t7365, t7375);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_33);
        svex2_34.v0 = svadd_f64_x(pg1, t7384, t7394);
        svex2_34.v1 = svadd_f64_x(pg1, t7385, t7395);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_34);
        svex2_35.v0 = svadd_f64_x(pg1, t7404, t7414);
        svex2_35.v1 = svadd_f64_x(pg1, t7405, t7415);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_35);
        svex2_36.v0 = svadd_f64_x(pg1, t7328, s4314);
        svex2_36.v1 = svadd_f64_x(pg1, t7329, s4315);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_36);
        svex2_37.v0 = svadd_f64_x(pg1, t7348, s4322);
        svex2_37.v1 = svadd_f64_x(pg1, t7349, s4323);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_37);
        svex2_38.v0 = svadd_f64_x(pg1, t7368, s4330);
        svex2_38.v1 = svadd_f64_x(pg1, t7369, s4331);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_38);
        svex2_39.v0 = svadd_f64_x(pg1, t7388, s4338);
        svex2_39.v1 = svadd_f64_x(pg1, t7389, s4339);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_39);
        svex2_40.v0 = svadd_f64_x(pg1, t7408, s4346);
        svex2_40.v1 = svadd_f64_x(pg1, t7409, s4347);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_40);
        svex2_41.v0 = svadd_f64_x(pg1, t7330, s4316);
        svex2_41.v1 = svsub_f64_x(pg1, t7331, s4317);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_41);
        svex2_42.v0 = svadd_f64_x(pg1, t7350, s4324);
        svex2_42.v1 = svsub_f64_x(pg1, t7351, s4325);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_42);
        svex2_43.v0 = svadd_f64_x(pg1, t7370, s4332);
        svex2_43.v1 = svsub_f64_x(pg1, t7371, s4333);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_43);
        svex2_44.v0 = svadd_f64_x(pg1, t7390, s4340);
        svex2_44.v1 = svsub_f64_x(pg1, t7391, s4341);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_44);
        svex2_45.v0 = svadd_f64_x(pg1, t7410, s4348);
        svex2_45.v1 = svsub_f64_x(pg1, t7411, s4349);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_45);
        svex2_46.v0 = svsub_f64_x(pg1, t7324, t7334);
        svex2_46.v1 = svsub_f64_x(pg1, t7325, t7335);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_46);
        svex2_47.v0 = svsub_f64_x(pg1, t7344, t7354);
        svex2_47.v1 = svsub_f64_x(pg1, t7345, t7355);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_47);
        svex2_48.v0 = svsub_f64_x(pg1, t7364, t7374);
        svex2_48.v1 = svsub_f64_x(pg1, t7365, t7375);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_48);
        svex2_49.v0 = svsub_f64_x(pg1, t7384, t7394);
        svex2_49.v1 = svsub_f64_x(pg1, t7385, t7395);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_49);
        svex2_50.v0 = svsub_f64_x(pg1, t7404, t7414);
        svex2_50.v1 = svsub_f64_x(pg1, t7405, t7415);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_50);
        svex2_51.v0 = svsub_f64_x(pg1, t7328, s4314);
        svex2_51.v1 = svsub_f64_x(pg1, t7329, s4315);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((20)*(m1)))))), svex2_51);
        svex2_52.v0 = svsub_f64_x(pg1, t7348, s4322);
        svex2_52.v1 = svsub_f64_x(pg1, t7349, s4323);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((21)*(m1)))))), svex2_52);
        svex2_53.v0 = svsub_f64_x(pg1, t7368, s4330);
        svex2_53.v1 = svsub_f64_x(pg1, t7369, s4331);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((22)*(m1)))))), svex2_53);
        svex2_54.v0 = svsub_f64_x(pg1, t7388, s4338);
        svex2_54.v1 = svsub_f64_x(pg1, t7389, s4339);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((23)*(m1)))))), svex2_54);
        svex2_55.v0 = svsub_f64_x(pg1, t7408, s4346);
        svex2_55.v1 = svsub_f64_x(pg1, t7409, s4347);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((24)*(m1)))))), svex2_55);
        svex2_56.v0 = svsub_f64_x(pg1, t7330, s4316);
        svex2_56.v1 = svadd_f64_x(pg1, t7331, s4317);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((25)*(m1)))))), svex2_56);
        svex2_57.v0 = svsub_f64_x(pg1, t7350, s4324);
        svex2_57.v1 = svadd_f64_x(pg1, t7351, s4325);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((26)*(m1)))))), svex2_57);
        svex2_58.v0 = svsub_f64_x(pg1, t7370, s4332);
        svex2_58.v1 = svadd_f64_x(pg1, t7371, s4333);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((27)*(m1)))))), svex2_58);
        svex2_59.v0 = svsub_f64_x(pg1, t7390, s4340);
        svex2_59.v1 = svadd_f64_x(pg1, t7391, s4341);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((28)*(m1)))))), svex2_59);
        svex2_60.v0 = svsub_f64_x(pg1, t7410, s4348);
        svex2_60.v1 = svadd_f64_x(pg1, t7411, s4349);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((29)*(m1)))))), svex2_60);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
