/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft32a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    static float64_t D15[64];
    int l1;
    float64_t  *a10122;
    svfloat64x2_t s4404, s4407, s4410, s4413, s4416, s4419, s4422, s4425, 
            s4428, s4431, s4434, s4437, s4440, s4443, s4446, s4449, 
            s4452, s4455, s4458, s4461, s4464, s4467, s4470, s4473, 
            s4476, s4479, s4482, s4485, s4488, s4491, s4494, s4497;
    svfloat64_t a10106, a10107, a10108, a10109, a10110, a10111, a10112, a10113, 
            a10114, a10115, a10116, a10117, a10118, a10119, a10120, a10121, 
            a10123, a10124, a10125, a10126, a10127, a10128, a10129, a10130, 
            a10131, a10132, a10133, a10134, a10135, a10136, a10137, a10138, 
            a10139, a10140, a10141, a10142, a10143, a10144, a10145, a10146, 
            a10147, a10148, a10149, a10150, a10151, a10152, a10153, a10154, 
            a10155, a10156, a10157, a10158, a10159, a10160, a10161, a10162, 
            a10163, a10164, a10165, a10166, a10167, a10168, a10169, a10170, 
            a10171, a10172, a10173, a10174, a10175, a10176, a10177, a10178, 
            a10179, a10180, a10181, a10182, a10183, a10184, s4405, s4406, 
            s4408, s4409, s4411, s4412, s4414, s4415, s4417, s4418, 
            s4420, s4421, s4423, s4424, s4426, s4427, s4429, s4430, 
            s4432, s4433, s4435, s4436, s4438, s4439, s4441, s4442, 
            s4444, s4445, s4447, s4448, s4450, s4451, s4453, s4454, 
            s4456, s4457, s4459, s4460, s4462, s4463, s4465, s4466, 
            s4468, s4469, s4471, s4472, s4474, s4475, s4477, s4478, 
            s4480, s4481, s4483, s4484, s4486, s4487, s4489, s4490, 
            s4492, s4493, s4495, s4496, s4498, s4499, s4500, s4501, 
            s4502, s4503, s4504, s4505, s4506, s4507, s4508, s4509, 
            s4510, s4511, s4512, s4513, s4514, s4515, s4516, s4517, 
            s4518, s4519, s4520, s4521, s4522, s4523, s4524, s4525, 
            s4526, s4527, s4528, s4529, s4530, s4531, s4532, s4533, 
            s4534, s4535, s4536, s4537, s4538, s4539, s4540, s4541, 
            s4542, s4543, s4544, s4545, s4546, s4547, s4548, s4549, 
            s4550, s4551, s4552, s4553, s4554, s4555, s4556, s4557, 
            s4558, s4559, s4560, s4561, s4562, s4563, s4564, s4565, 
            s4566, s4567, s4568, s4569, s4570, s4571, s4572, s4573, 
            s4574, s4575, s4576, s4577, s4578, s4579, s4580, s4581, 
            s4582, s4583, s4584, s4585, s4586, s4587, s4588, s4589, 
            s4590, s4591, s4592, s4593, s4594, s4595, s4596, s4597, 
            s4598, s4599, s4600, s4601, s4602, s4603, s4604, s4605, 
            s4606, s4607, s4608, s4609, s4610, s4611, s4612, s4613, 
            s4614, s4615, s4616, s4617, s4618, s4619, s4620, s4621, 
            s4622, s4623, s4624, s4625, s4626, s4627, s4628, s4629, 
            s4630, s4631, s4632, s4633, s4634, s4635, s4636, s4637, 
            s4638, s4639, s4640, s4641, s4642, s4643, s4644, s4645, 
            s4646, s4647, s4648, s4649, s4650, s4651, s4652, s4653, 
            s4654, s4655, s4656, s4657, s4658, s4659, s4660, s4661, 
            s4662, s4663, s4664, s4665, s4666, s4667, s4668, s4669, 
            s4670, s4671, s4672, s4673, s4674, s4675, s4676, s4677, 
            s4678, s4679, s4680, s4681, s4682, s4683, s4684, s4685, 
            s4686, s4687, s4688, s4689, s4690, s4691, s4692, s4693, 
            s4694, s4695, s4696, s4697, s4698, s4699, s4700, s4701, 
            s4702, s4703, s4704, s4705, t7131, t7132, t7133, t7134, 
            t7135, t7136, t7137, t7138, t7139, t7140, t7141, t7142, 
            t7143, t7144, t7145, t7146, t7147, t7148, t7149, t7150, 
            t7151, t7152, t7153, t7154, t7155, t7156, t7157, t7158, 
            t7159, t7160, t7161, t7162, t7163, t7164, t7165, t7166, 
            t7167, t7168, t7169, t7170, t7171, t7172, t7173, t7174, 
            t7175, t7176, t7177, t7178, t7179, t7180, t7181, t7182, 
            t7183, t7184, t7185, t7186, t7187, t7188, t7189, t7190, 
            t7191, t7192, t7193, t7194, t7195, t7196, t7197, t7198, 
            t7199, t7200, t7201, t7202, t7203, t7204, t7205, t7206, 
            t7207, t7208, t7209, t7210, t7211, t7212, t7213, t7214, 
            t7215, t7216, t7217, t7218, t7219, t7220, t7221, t7222, 
            t7223, t7224, t7225, t7226, t7227, t7228, t7229, t7230, 
            t7231, t7232, t7233, t7234, t7235, t7236, t7237, t7238, 
            t7239, t7240, t7241, t7242, t7243, t7244, t7245, t7246, 
            t7247, t7248, t7249, t7250, t7251, t7252, t7253, t7254, 
            t7255, t7256, t7257, t7258, t7259, t7260, t7261, t7262, 
            t7263, t7264, t7265, t7266, t7267, t7268, t7269, t7270, 
            t7271, t7272, t7273, t7274, t7275, t7276, t7277, t7278, 
            t7279, t7280, t7281, t7282, t7283, t7284, t7285, t7286, 
            t7287, t7288, t7289, t7290, t7291, t7292, t7293, t7294, 
            t7295, t7296, t7297, t7298, t7299, t7300, t7301, t7302, 
            t7303, t7304, t7305, t7306, t7307, t7308, t7309, t7310, 
            t7311, t7312, t7313, t7314, t7315, t7316, t7317, t7318, 
            t7319, t7320, t7321, t7322, t7323, t7324, t7325, t7326, 
            t7327, t7328, t7329, t7330, t7331, t7332, t7333, t7334, 
            t7335, t7336, t7337, t7338, t7339, t7340, t7341, t7342, 
            t7343, t7344, t7345, t7346, t7347, t7348, t7349, t7350, 
            t7351, t7352, t7353, t7354, t7355, t7356, t7357, t7358, 
            t7359, t7360, t7361, t7362, t7363, t7364, t7365, t7366, 
            t7367, t7368, t7369, t7370;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s4404 = svld2_f64(pg1, (X + ((2)*(j1))));
        s4405 = s4404.v0;
        s4406 = s4404.v1;
        s4407 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s4408 = s4407.v0;
        s4409 = s4407.v1;
        s4410 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s4411 = s4410.v0;
        s4412 = s4410.v1;
        s4413 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s4414 = s4413.v0;
        s4415 = s4413.v1;
        s4416 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s4417 = s4416.v0;
        s4418 = s4416.v1;
        s4419 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s4420 = s4419.v0;
        s4421 = s4419.v1;
        s4422 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s4423 = s4422.v0;
        s4424 = s4422.v1;
        s4425 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s4426 = s4425.v0;
        s4427 = s4425.v1;
        s4428 = svld2_f64(pg1, (X + ((2)*((j1 + ((8)*(l1)))))));
        s4429 = s4428.v0;
        s4430 = s4428.v1;
        s4431 = svld2_f64(pg1, (X + ((2)*((j1 + ((9)*(l1)))))));
        s4432 = s4431.v0;
        s4433 = s4431.v1;
        s4434 = svld2_f64(pg1, (X + ((2)*((j1 + ((10)*(l1)))))));
        s4435 = s4434.v0;
        s4436 = s4434.v1;
        s4437 = svld2_f64(pg1, (X + ((2)*((j1 + ((11)*(l1)))))));
        s4438 = s4437.v0;
        s4439 = s4437.v1;
        s4440 = svld2_f64(pg1, (X + ((2)*((j1 + ((12)*(l1)))))));
        s4441 = s4440.v0;
        s4442 = s4440.v1;
        s4443 = svld2_f64(pg1, (X + ((2)*((j1 + ((13)*(l1)))))));
        s4444 = s4443.v0;
        s4445 = s4443.v1;
        s4446 = svld2_f64(pg1, (X + ((2)*((j1 + ((14)*(l1)))))));
        s4447 = s4446.v0;
        s4448 = s4446.v1;
        s4449 = svld2_f64(pg1, (X + ((2)*((j1 + ((15)*(l1)))))));
        s4450 = s4449.v0;
        s4451 = s4449.v1;
        s4452 = svld2_f64(pg1, (X + ((2)*((j1 + ((16)*(l1)))))));
        s4453 = s4452.v0;
        s4454 = s4452.v1;
        s4455 = svld2_f64(pg1, (X + ((2)*((j1 + ((17)*(l1)))))));
        s4456 = s4455.v0;
        s4457 = s4455.v1;
        s4458 = svld2_f64(pg1, (X + ((2)*((j1 + ((18)*(l1)))))));
        s4459 = s4458.v0;
        s4460 = s4458.v1;
        s4461 = svld2_f64(pg1, (X + ((2)*((j1 + ((19)*(l1)))))));
        s4462 = s4461.v0;
        s4463 = s4461.v1;
        s4464 = svld2_f64(pg1, (X + ((2)*((j1 + ((20)*(l1)))))));
        s4465 = s4464.v0;
        s4466 = s4464.v1;
        s4467 = svld2_f64(pg1, (X + ((2)*((j1 + ((21)*(l1)))))));
        s4468 = s4467.v0;
        s4469 = s4467.v1;
        s4470 = svld2_f64(pg1, (X + ((2)*((j1 + ((22)*(l1)))))));
        s4471 = s4470.v0;
        s4472 = s4470.v1;
        s4473 = svld2_f64(pg1, (X + ((2)*((j1 + ((23)*(l1)))))));
        s4474 = s4473.v0;
        s4475 = s4473.v1;
        s4476 = svld2_f64(pg1, (X + ((2)*((j1 + ((24)*(l1)))))));
        s4477 = s4476.v0;
        s4478 = s4476.v1;
        s4479 = svld2_f64(pg1, (X + ((2)*((j1 + ((25)*(l1)))))));
        s4480 = s4479.v0;
        s4481 = s4479.v1;
        s4482 = svld2_f64(pg1, (X + ((2)*((j1 + ((26)*(l1)))))));
        s4483 = s4482.v0;
        s4484 = s4482.v1;
        s4485 = svld2_f64(pg1, (X + ((2)*((j1 + ((27)*(l1)))))));
        s4486 = s4485.v0;
        s4487 = s4485.v1;
        s4488 = svld2_f64(pg1, (X + ((2)*((j1 + ((28)*(l1)))))));
        s4489 = s4488.v0;
        s4490 = s4488.v1;
        s4491 = svld2_f64(pg1, (X + ((2)*((j1 + ((29)*(l1)))))));
        s4492 = s4491.v0;
        s4493 = s4491.v1;
        s4494 = svld2_f64(pg1, (X + ((2)*((j1 + ((30)*(l1)))))));
        s4495 = s4494.v0;
        s4496 = s4494.v1;
        s4497 = svld2_f64(pg1, (X + ((2)*((j1 + ((31)*(l1)))))));
        s4498 = s4497.v0;
        s4499 = s4497.v1;
        t7131 = svadd_f64_x(pg1, s4405, s4453);
        t7132 = svadd_f64_x(pg1, s4406, s4454);
        t7133 = svsub_f64_x(pg1, s4405, s4453);
        t7134 = svsub_f64_x(pg1, s4406, s4454);
        t7135 = svadd_f64_x(pg1, s4429, s4477);
        t7136 = svadd_f64_x(pg1, s4430, s4478);
        t7137 = svsub_f64_x(pg1, s4429, s4477);
        t7138 = svsub_f64_x(pg1, s4430, s4478);
        t7139 = svadd_f64_x(pg1, t7131, t7135);
        t7140 = svadd_f64_x(pg1, t7132, t7136);
        t7141 = svsub_f64_x(pg1, t7131, t7135);
        t7142 = svsub_f64_x(pg1, t7132, t7136);
        s4500 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7140, D15[1]), t7139, D15[0]);
        s4501 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7140, D15[0]), t7139, D15[1]);
        s4502 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7142, D15[3]), t7141, D15[2]);
        s4503 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7142, D15[2]), t7141, D15[3]);
        t7143 = svadd_f64_x(pg1, t7133, t7138);
        t7144 = svsub_f64_x(pg1, t7134, t7137);
        t7145 = svsub_f64_x(pg1, t7133, t7138);
        t7146 = svadd_f64_x(pg1, t7134, t7137);
        s4504 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7144, D15[5]), t7143, D15[4]);
        s4505 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7144, D15[4]), t7143, D15[5]);
        s4506 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7146, D15[7]), t7145, D15[6]);
        s4507 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7146, D15[6]), t7145, D15[7]);
        t7147 = svadd_f64_x(pg1, s4408, s4456);
        t7148 = svadd_f64_x(pg1, s4409, s4457);
        t7149 = svsub_f64_x(pg1, s4408, s4456);
        t7150 = svsub_f64_x(pg1, s4409, s4457);
        t7151 = svadd_f64_x(pg1, s4432, s4480);
        t7152 = svadd_f64_x(pg1, s4433, s4481);
        t7153 = svsub_f64_x(pg1, s4432, s4480);
        t7154 = svsub_f64_x(pg1, s4433, s4481);
        t7155 = svadd_f64_x(pg1, t7147, t7151);
        t7156 = svadd_f64_x(pg1, t7148, t7152);
        t7157 = svsub_f64_x(pg1, t7147, t7151);
        t7158 = svsub_f64_x(pg1, t7148, t7152);
        s4508 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7156, D15[9]), t7155, D15[8]);
        s4509 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7156, D15[8]), t7155, D15[9]);
        s4510 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7158, D15[11]), t7157, D15[10]);
        s4511 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7158, D15[10]), t7157, D15[11]);
        t7159 = svadd_f64_x(pg1, t7149, t7154);
        t7160 = svsub_f64_x(pg1, t7150, t7153);
        t7161 = svsub_f64_x(pg1, t7149, t7154);
        t7162 = svadd_f64_x(pg1, t7150, t7153);
        s4512 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7160, D15[13]), t7159, D15[12]);
        s4513 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7160, D15[12]), t7159, D15[13]);
        s4514 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7162, D15[15]), t7161, D15[14]);
        s4515 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7162, D15[14]), t7161, D15[15]);
        t7163 = svadd_f64_x(pg1, s4411, s4459);
        t7164 = svadd_f64_x(pg1, s4412, s4460);
        t7165 = svsub_f64_x(pg1, s4411, s4459);
        t7166 = svsub_f64_x(pg1, s4412, s4460);
        t7167 = svadd_f64_x(pg1, s4435, s4483);
        t7168 = svadd_f64_x(pg1, s4436, s4484);
        t7169 = svsub_f64_x(pg1, s4435, s4483);
        t7170 = svsub_f64_x(pg1, s4436, s4484);
        t7171 = svadd_f64_x(pg1, t7163, t7167);
        t7172 = svadd_f64_x(pg1, t7164, t7168);
        t7173 = svsub_f64_x(pg1, t7163, t7167);
        t7174 = svsub_f64_x(pg1, t7164, t7168);
        s4516 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7172, D15[17]), t7171, D15[16]);
        s4517 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7172, D15[16]), t7171, D15[17]);
        s4518 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7174, D15[19]), t7173, D15[18]);
        s4519 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7174, D15[18]), t7173, D15[19]);
        t7175 = svadd_f64_x(pg1, t7165, t7170);
        t7176 = svsub_f64_x(pg1, t7166, t7169);
        t7177 = svsub_f64_x(pg1, t7165, t7170);
        t7178 = svadd_f64_x(pg1, t7166, t7169);
        s4520 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7176, D15[21]), t7175, D15[20]);
        s4521 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7176, D15[20]), t7175, D15[21]);
        s4522 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7178, D15[23]), t7177, D15[22]);
        s4523 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7178, D15[22]), t7177, D15[23]);
        t7179 = svadd_f64_x(pg1, s4414, s4462);
        t7180 = svadd_f64_x(pg1, s4415, s4463);
        t7181 = svsub_f64_x(pg1, s4414, s4462);
        t7182 = svsub_f64_x(pg1, s4415, s4463);
        t7183 = svadd_f64_x(pg1, s4438, s4486);
        t7184 = svadd_f64_x(pg1, s4439, s4487);
        t7185 = svsub_f64_x(pg1, s4438, s4486);
        t7186 = svsub_f64_x(pg1, s4439, s4487);
        t7187 = svadd_f64_x(pg1, t7179, t7183);
        t7188 = svadd_f64_x(pg1, t7180, t7184);
        t7189 = svsub_f64_x(pg1, t7179, t7183);
        t7190 = svsub_f64_x(pg1, t7180, t7184);
        s4524 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7188, D15[25]), t7187, D15[24]);
        s4525 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7188, D15[24]), t7187, D15[25]);
        s4526 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7190, D15[27]), t7189, D15[26]);
        s4527 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7190, D15[26]), t7189, D15[27]);
        t7191 = svadd_f64_x(pg1, t7181, t7186);
        t7192 = svsub_f64_x(pg1, t7182, t7185);
        t7193 = svsub_f64_x(pg1, t7181, t7186);
        t7194 = svadd_f64_x(pg1, t7182, t7185);
        s4528 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7192, D15[29]), t7191, D15[28]);
        s4529 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7192, D15[28]), t7191, D15[29]);
        s4530 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7194, D15[31]), t7193, D15[30]);
        s4531 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7194, D15[30]), t7193, D15[31]);
        t7195 = svadd_f64_x(pg1, s4417, s4465);
        t7196 = svadd_f64_x(pg1, s4418, s4466);
        t7197 = svsub_f64_x(pg1, s4417, s4465);
        t7198 = svsub_f64_x(pg1, s4418, s4466);
        t7199 = svadd_f64_x(pg1, s4441, s4489);
        t7200 = svadd_f64_x(pg1, s4442, s4490);
        t7201 = svsub_f64_x(pg1, s4441, s4489);
        t7202 = svsub_f64_x(pg1, s4442, s4490);
        t7203 = svadd_f64_x(pg1, t7195, t7199);
        t7204 = svadd_f64_x(pg1, t7196, t7200);
        t7205 = svsub_f64_x(pg1, t7195, t7199);
        t7206 = svsub_f64_x(pg1, t7196, t7200);
        s4532 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7204, D15[33]), t7203, D15[32]);
        s4533 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7204, D15[32]), t7203, D15[33]);
        s4534 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7206, D15[35]), t7205, D15[34]);
        s4535 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7206, D15[34]), t7205, D15[35]);
        t7207 = svadd_f64_x(pg1, t7197, t7202);
        t7208 = svsub_f64_x(pg1, t7198, t7201);
        t7209 = svsub_f64_x(pg1, t7197, t7202);
        t7210 = svadd_f64_x(pg1, t7198, t7201);
        s4536 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7208, D15[37]), t7207, D15[36]);
        s4537 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7208, D15[36]), t7207, D15[37]);
        s4538 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7210, D15[39]), t7209, D15[38]);
        s4539 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7210, D15[38]), t7209, D15[39]);
        t7211 = svadd_f64_x(pg1, s4420, s4468);
        t7212 = svadd_f64_x(pg1, s4421, s4469);
        t7213 = svsub_f64_x(pg1, s4420, s4468);
        t7214 = svsub_f64_x(pg1, s4421, s4469);
        t7215 = svadd_f64_x(pg1, s4444, s4492);
        t7216 = svadd_f64_x(pg1, s4445, s4493);
        t7217 = svsub_f64_x(pg1, s4444, s4492);
        t7218 = svsub_f64_x(pg1, s4445, s4493);
        t7219 = svadd_f64_x(pg1, t7211, t7215);
        t7220 = svadd_f64_x(pg1, t7212, t7216);
        t7221 = svsub_f64_x(pg1, t7211, t7215);
        t7222 = svsub_f64_x(pg1, t7212, t7216);
        s4540 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7220, D15[41]), t7219, D15[40]);
        s4541 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7220, D15[40]), t7219, D15[41]);
        s4542 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7222, D15[43]), t7221, D15[42]);
        s4543 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7222, D15[42]), t7221, D15[43]);
        t7223 = svadd_f64_x(pg1, t7213, t7218);
        t7224 = svsub_f64_x(pg1, t7214, t7217);
        t7225 = svsub_f64_x(pg1, t7213, t7218);
        t7226 = svadd_f64_x(pg1, t7214, t7217);
        s4544 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7224, D15[45]), t7223, D15[44]);
        s4545 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7224, D15[44]), t7223, D15[45]);
        s4546 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7226, D15[47]), t7225, D15[46]);
        s4547 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7226, D15[46]), t7225, D15[47]);
        t7227 = svadd_f64_x(pg1, s4423, s4471);
        t7228 = svadd_f64_x(pg1, s4424, s4472);
        t7229 = svsub_f64_x(pg1, s4423, s4471);
        t7230 = svsub_f64_x(pg1, s4424, s4472);
        t7231 = svadd_f64_x(pg1, s4447, s4495);
        t7232 = svadd_f64_x(pg1, s4448, s4496);
        t7233 = svsub_f64_x(pg1, s4447, s4495);
        t7234 = svsub_f64_x(pg1, s4448, s4496);
        t7235 = svadd_f64_x(pg1, t7227, t7231);
        t7236 = svadd_f64_x(pg1, t7228, t7232);
        t7237 = svsub_f64_x(pg1, t7227, t7231);
        t7238 = svsub_f64_x(pg1, t7228, t7232);
        s4548 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7236, D15[49]), t7235, D15[48]);
        s4549 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7236, D15[48]), t7235, D15[49]);
        s4550 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7238, D15[51]), t7237, D15[50]);
        s4551 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7238, D15[50]), t7237, D15[51]);
        t7239 = svadd_f64_x(pg1, t7229, t7234);
        t7240 = svsub_f64_x(pg1, t7230, t7233);
        t7241 = svsub_f64_x(pg1, t7229, t7234);
        t7242 = svadd_f64_x(pg1, t7230, t7233);
        s4552 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7240, D15[53]), t7239, D15[52]);
        s4553 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7240, D15[52]), t7239, D15[53]);
        s4554 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7242, D15[55]), t7241, D15[54]);
        s4555 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7242, D15[54]), t7241, D15[55]);
        t7243 = svadd_f64_x(pg1, s4426, s4474);
        t7244 = svadd_f64_x(pg1, s4427, s4475);
        t7245 = svsub_f64_x(pg1, s4426, s4474);
        t7246 = svsub_f64_x(pg1, s4427, s4475);
        t7247 = svadd_f64_x(pg1, s4450, s4498);
        t7248 = svadd_f64_x(pg1, s4451, s4499);
        t7249 = svsub_f64_x(pg1, s4450, s4498);
        t7250 = svsub_f64_x(pg1, s4451, s4499);
        t7251 = svadd_f64_x(pg1, t7243, t7247);
        t7252 = svadd_f64_x(pg1, t7244, t7248);
        t7253 = svsub_f64_x(pg1, t7243, t7247);
        t7254 = svsub_f64_x(pg1, t7244, t7248);
        s4556 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7252, D15[57]), t7251, D15[56]);
        s4557 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7252, D15[56]), t7251, D15[57]);
        s4558 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7254, D15[59]), t7253, D15[58]);
        s4559 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7254, D15[58]), t7253, D15[59]);
        t7255 = svadd_f64_x(pg1, t7245, t7250);
        t7256 = svsub_f64_x(pg1, t7246, t7249);
        t7257 = svsub_f64_x(pg1, t7245, t7250);
        t7258 = svadd_f64_x(pg1, t7246, t7249);
        s4560 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7256, D15[61]), t7255, D15[60]);
        s4561 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7256, D15[60]), t7255, D15[61]);
        s4562 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7258, D15[63]), t7257, D15[62]);
        s4563 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7258, D15[62]), t7257, D15[63]);
        t7259 = svadd_f64_x(pg1, s4500, s4532);
        t7260 = svadd_f64_x(pg1, s4501, s4533);
        t7261 = svsub_f64_x(pg1, s4500, s4532);
        t7262 = svsub_f64_x(pg1, s4501, s4533);
        t7263 = svadd_f64_x(pg1, s4516, s4548);
        t7264 = svadd_f64_x(pg1, s4517, s4549);
        t7265 = svsub_f64_x(pg1, s4516, s4548);
        t7266 = svsub_f64_x(pg1, s4517, s4549);
        t7267 = svadd_f64_x(pg1, t7259, t7263);
        t7268 = svadd_f64_x(pg1, t7260, t7264);
        t7269 = svsub_f64_x(pg1, t7259, t7263);
        t7270 = svsub_f64_x(pg1, t7260, t7264);
        t7271 = svadd_f64_x(pg1, t7261, t7266);
        t7272 = svsub_f64_x(pg1, t7262, t7265);
        t7273 = svsub_f64_x(pg1, t7261, t7266);
        t7274 = svadd_f64_x(pg1, t7262, t7265);
        t7275 = svadd_f64_x(pg1, s4508, s4540);
        t7276 = svadd_f64_x(pg1, s4509, s4541);
        t7277 = svsub_f64_x(pg1, s4508, s4540);
        t7278 = svsub_f64_x(pg1, s4509, s4541);
        t7279 = svadd_f64_x(pg1, s4524, s4556);
        t7280 = svadd_f64_x(pg1, s4525, s4557);
        t7281 = svsub_f64_x(pg1, s4524, s4556);
        t7282 = svsub_f64_x(pg1, s4525, s4557);
        t7283 = svadd_f64_x(pg1, t7275, t7279);
        t7284 = svadd_f64_x(pg1, t7276, t7280);
        t7285 = svsub_f64_x(pg1, t7275, t7279);
        t7286 = svsub_f64_x(pg1, t7276, t7280);
        a10106 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7277, t7282), 0.70710678118654757);
        a10107 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7278, t7281), 0.70710678118654757);
        s4564 = svadd_f64_x(pg1, a10106, a10107);
        s4565 = svsub_f64_x(pg1, a10107, a10106);
        a10108 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7278, t7281), 0.70710678118654757);
        a10109 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7277, t7282), 0.70710678118654757);
        s4566 = svsub_f64_x(pg1, a10108, a10109);
        s4567 = svadd_f64_x(pg1, a10109, a10108);
        s4568 = svadd_f64_x(pg1, t7267, t7283);
        s4569 = svadd_f64_x(pg1, t7268, t7284);
        s4570 = svsub_f64_x(pg1, t7267, t7283);
        s4571 = svsub_f64_x(pg1, t7268, t7284);
        s4572 = svadd_f64_x(pg1, t7271, s4564);
        s4573 = svadd_f64_x(pg1, t7272, s4565);
        s4574 = svsub_f64_x(pg1, t7271, s4564);
        s4575 = svsub_f64_x(pg1, t7272, s4565);
        s4576 = svadd_f64_x(pg1, t7269, t7286);
        s4577 = svsub_f64_x(pg1, t7270, t7285);
        s4578 = svsub_f64_x(pg1, t7269, t7286);
        s4579 = svadd_f64_x(pg1, t7270, t7285);
        s4580 = svadd_f64_x(pg1, t7273, s4566);
        s4581 = svsub_f64_x(pg1, t7274, s4567);
        s4582 = svsub_f64_x(pg1, t7273, s4566);
        s4583 = svadd_f64_x(pg1, t7274, s4567);
        t7287 = svadd_f64_x(pg1, s4504, s4536);
        t7288 = svadd_f64_x(pg1, s4505, s4537);
        t7289 = svsub_f64_x(pg1, s4504, s4536);
        t7290 = svsub_f64_x(pg1, s4505, s4537);
        t7291 = svadd_f64_x(pg1, s4520, s4552);
        t7292 = svadd_f64_x(pg1, s4521, s4553);
        t7293 = svsub_f64_x(pg1, s4520, s4552);
        t7294 = svsub_f64_x(pg1, s4521, s4553);
        t7295 = svadd_f64_x(pg1, t7287, t7291);
        t7296 = svadd_f64_x(pg1, t7288, t7292);
        t7297 = svsub_f64_x(pg1, t7287, t7291);
        t7298 = svsub_f64_x(pg1, t7288, t7292);
        t7299 = svadd_f64_x(pg1, t7289, t7294);
        t7300 = svsub_f64_x(pg1, t7290, t7293);
        t7301 = svsub_f64_x(pg1, t7289, t7294);
        t7302 = svadd_f64_x(pg1, t7290, t7293);
        t7303 = svadd_f64_x(pg1, s4512, s4544);
        t7304 = svadd_f64_x(pg1, s4513, s4545);
        t7305 = svsub_f64_x(pg1, s4512, s4544);
        t7306 = svsub_f64_x(pg1, s4513, s4545);
        t7307 = svadd_f64_x(pg1, s4528, s4560);
        t7308 = svadd_f64_x(pg1, s4529, s4561);
        t7309 = svsub_f64_x(pg1, s4528, s4560);
        t7310 = svsub_f64_x(pg1, s4529, s4561);
        t7311 = svadd_f64_x(pg1, t7303, t7307);
        t7312 = svadd_f64_x(pg1, t7304, t7308);
        t7313 = svsub_f64_x(pg1, t7303, t7307);
        t7314 = svsub_f64_x(pg1, t7304, t7308);
        a10110 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7305, t7310), 0.70710678118654757);
        a10111 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7306, t7309), 0.70710678118654757);
        s4584 = svadd_f64_x(pg1, a10110, a10111);
        s4585 = svsub_f64_x(pg1, a10111, a10110);
        a10112 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7306, t7309), 0.70710678118654757);
        a10113 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7305, t7310), 0.70710678118654757);
        s4586 = svsub_f64_x(pg1, a10112, a10113);
        s4587 = svadd_f64_x(pg1, a10113, a10112);
        s4588 = svadd_f64_x(pg1, t7295, t7311);
        s4589 = svadd_f64_x(pg1, t7296, t7312);
        s4590 = svsub_f64_x(pg1, t7295, t7311);
        s4591 = svsub_f64_x(pg1, t7296, t7312);
        s4592 = svadd_f64_x(pg1, t7299, s4584);
        s4593 = svadd_f64_x(pg1, t7300, s4585);
        s4594 = svsub_f64_x(pg1, t7299, s4584);
        s4595 = svsub_f64_x(pg1, t7300, s4585);
        s4596 = svadd_f64_x(pg1, t7297, t7314);
        s4597 = svsub_f64_x(pg1, t7298, t7313);
        s4598 = svsub_f64_x(pg1, t7297, t7314);
        s4599 = svadd_f64_x(pg1, t7298, t7313);
        s4600 = svadd_f64_x(pg1, t7301, s4586);
        s4601 = svsub_f64_x(pg1, t7302, s4587);
        s4602 = svsub_f64_x(pg1, t7301, s4586);
        s4603 = svadd_f64_x(pg1, t7302, s4587);
        t7315 = svadd_f64_x(pg1, s4502, s4534);
        t7316 = svadd_f64_x(pg1, s4503, s4535);
        t7317 = svsub_f64_x(pg1, s4502, s4534);
        t7318 = svsub_f64_x(pg1, s4503, s4535);
        t7319 = svadd_f64_x(pg1, s4518, s4550);
        t7320 = svadd_f64_x(pg1, s4519, s4551);
        t7321 = svsub_f64_x(pg1, s4518, s4550);
        t7322 = svsub_f64_x(pg1, s4519, s4551);
        t7323 = svadd_f64_x(pg1, t7315, t7319);
        t7324 = svadd_f64_x(pg1, t7316, t7320);
        t7325 = svsub_f64_x(pg1, t7315, t7319);
        t7326 = svsub_f64_x(pg1, t7316, t7320);
        t7327 = svadd_f64_x(pg1, t7317, t7322);
        t7328 = svsub_f64_x(pg1, t7318, t7321);
        t7329 = svsub_f64_x(pg1, t7317, t7322);
        t7330 = svadd_f64_x(pg1, t7318, t7321);
        t7331 = svadd_f64_x(pg1, s4510, s4542);
        t7332 = svadd_f64_x(pg1, s4511, s4543);
        t7333 = svsub_f64_x(pg1, s4510, s4542);
        t7334 = svsub_f64_x(pg1, s4511, s4543);
        t7335 = svadd_f64_x(pg1, s4526, s4558);
        t7336 = svadd_f64_x(pg1, s4527, s4559);
        t7337 = svsub_f64_x(pg1, s4526, s4558);
        t7338 = svsub_f64_x(pg1, s4527, s4559);
        t7339 = svadd_f64_x(pg1, t7331, t7335);
        t7340 = svadd_f64_x(pg1, t7332, t7336);
        t7341 = svsub_f64_x(pg1, t7331, t7335);
        t7342 = svsub_f64_x(pg1, t7332, t7336);
        a10114 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7333, t7338), 0.70710678118654757);
        a10115 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7334, t7337), 0.70710678118654757);
        s4604 = svadd_f64_x(pg1, a10114, a10115);
        s4605 = svsub_f64_x(pg1, a10115, a10114);
        a10116 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7334, t7337), 0.70710678118654757);
        a10117 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7333, t7338), 0.70710678118654757);
        s4606 = svsub_f64_x(pg1, a10116, a10117);
        s4607 = svadd_f64_x(pg1, a10117, a10116);
        s4608 = svadd_f64_x(pg1, t7323, t7339);
        s4609 = svadd_f64_x(pg1, t7324, t7340);
        s4610 = svsub_f64_x(pg1, t7323, t7339);
        s4611 = svsub_f64_x(pg1, t7324, t7340);
        s4612 = svadd_f64_x(pg1, t7327, s4604);
        s4613 = svadd_f64_x(pg1, t7328, s4605);
        s4614 = svsub_f64_x(pg1, t7327, s4604);
        s4615 = svsub_f64_x(pg1, t7328, s4605);
        s4616 = svadd_f64_x(pg1, t7325, t7342);
        s4617 = svsub_f64_x(pg1, t7326, t7341);
        s4618 = svsub_f64_x(pg1, t7325, t7342);
        s4619 = svadd_f64_x(pg1, t7326, t7341);
        s4620 = svadd_f64_x(pg1, t7329, s4606);
        s4621 = svsub_f64_x(pg1, t7330, s4607);
        s4622 = svsub_f64_x(pg1, t7329, s4606);
        s4623 = svadd_f64_x(pg1, t7330, s4607);
        t7343 = svadd_f64_x(pg1, s4506, s4538);
        t7344 = svadd_f64_x(pg1, s4507, s4539);
        t7345 = svsub_f64_x(pg1, s4506, s4538);
        t7346 = svsub_f64_x(pg1, s4507, s4539);
        t7347 = svadd_f64_x(pg1, s4522, s4554);
        t7348 = svadd_f64_x(pg1, s4523, s4555);
        t7349 = svsub_f64_x(pg1, s4522, s4554);
        t7350 = svsub_f64_x(pg1, s4523, s4555);
        t7351 = svadd_f64_x(pg1, t7343, t7347);
        t7352 = svadd_f64_x(pg1, t7344, t7348);
        t7353 = svsub_f64_x(pg1, t7343, t7347);
        t7354 = svsub_f64_x(pg1, t7344, t7348);
        t7355 = svadd_f64_x(pg1, t7345, t7350);
        t7356 = svsub_f64_x(pg1, t7346, t7349);
        t7357 = svsub_f64_x(pg1, t7345, t7350);
        t7358 = svadd_f64_x(pg1, t7346, t7349);
        t7359 = svadd_f64_x(pg1, s4514, s4546);
        t7360 = svadd_f64_x(pg1, s4515, s4547);
        t7361 = svsub_f64_x(pg1, s4514, s4546);
        t7362 = svsub_f64_x(pg1, s4515, s4547);
        t7363 = svadd_f64_x(pg1, s4530, s4562);
        t7364 = svadd_f64_x(pg1, s4531, s4563);
        t7365 = svsub_f64_x(pg1, s4530, s4562);
        t7366 = svsub_f64_x(pg1, s4531, s4563);
        t7367 = svadd_f64_x(pg1, t7359, t7363);
        t7368 = svadd_f64_x(pg1, t7360, t7364);
        t7369 = svsub_f64_x(pg1, t7359, t7363);
        t7370 = svsub_f64_x(pg1, t7360, t7364);
        a10118 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7361, t7366), 0.70710678118654757);
        a10119 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7362, t7365), 0.70710678118654757);
        s4624 = svadd_f64_x(pg1, a10118, a10119);
        s4625 = svsub_f64_x(pg1, a10119, a10118);
        a10120 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7362, t7365), 0.70710678118654757);
        a10121 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7361, t7366), 0.70710678118654757);
        s4626 = svsub_f64_x(pg1, a10120, a10121);
        s4627 = svadd_f64_x(pg1, a10121, a10120);
        s4628 = svadd_f64_x(pg1, t7351, t7367);
        s4629 = svadd_f64_x(pg1, t7352, t7368);
        s4630 = svsub_f64_x(pg1, t7351, t7367);
        s4631 = svsub_f64_x(pg1, t7352, t7368);
        s4632 = svadd_f64_x(pg1, t7355, s4624);
        s4633 = svadd_f64_x(pg1, t7356, s4625);
        s4634 = svsub_f64_x(pg1, t7355, s4624);
        s4635 = svsub_f64_x(pg1, t7356, s4625);
        s4636 = svadd_f64_x(pg1, t7353, t7370);
        s4637 = svsub_f64_x(pg1, t7354, t7369);
        s4638 = svsub_f64_x(pg1, t7353, t7370);
        s4639 = svadd_f64_x(pg1, t7354, t7369);
        s4640 = svadd_f64_x(pg1, t7357, s4626);
        s4641 = svsub_f64_x(pg1, t7358, s4627);
        s4642 = svsub_f64_x(pg1, t7357, s4626);
        s4643 = svadd_f64_x(pg1, t7358, s4627);
        a10122 = (TW1 + ((62)*(j1)));
        a10123 = svld1_gather_u64offset_f64(pg1, a10122, svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10124 = svld1_gather_u64offset_f64(pg1, (a10122 + 1), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4644 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10124, s4589), a10123, s4588);
        s4645 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10123, s4589), a10124, s4588);
        a10125 = svld1_gather_u64offset_f64(pg1, (a10122 + 2), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10126 = svld1_gather_u64offset_f64(pg1, (a10122 + 3), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4646 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10126, s4609), a10125, s4608);
        s4647 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10125, s4609), a10126, s4608);
        a10127 = svld1_gather_u64offset_f64(pg1, (a10122 + 4), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10128 = svld1_gather_u64offset_f64(pg1, (a10122 + 5), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4648 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10128, s4629), a10127, s4628);
        s4649 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10127, s4629), a10128, s4628);
        a10129 = svld1_gather_u64offset_f64(pg1, (a10122 + 6), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10130 = svld1_gather_u64offset_f64(pg1, (a10122 + 7), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4650 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10130, s4573), a10129, s4572);
        s4651 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10129, s4573), a10130, s4572);
        a10131 = svld1_gather_u64offset_f64(pg1, (a10122 + 8), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10132 = svld1_gather_u64offset_f64(pg1, (a10122 + 9), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4652 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10132, s4593), a10131, s4592);
        s4653 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10131, s4593), a10132, s4592);
        a10133 = svld1_gather_u64offset_f64(pg1, (a10122 + 10), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10134 = svld1_gather_u64offset_f64(pg1, (a10122 + 11), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4654 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10134, s4613), a10133, s4612);
        s4655 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10133, s4613), a10134, s4612);
        a10135 = svld1_gather_u64offset_f64(pg1, (a10122 + 12), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10136 = svld1_gather_u64offset_f64(pg1, (a10122 + 13), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4656 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10136, s4633), a10135, s4632);
        s4657 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10135, s4633), a10136, s4632);
        a10137 = svld1_gather_u64offset_f64(pg1, (a10122 + 14), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10138 = svld1_gather_u64offset_f64(pg1, (a10122 + 15), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4658 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10138, s4577), a10137, s4576);
        s4659 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10137, s4577), a10138, s4576);
        a10139 = svld1_gather_u64offset_f64(pg1, (a10122 + 16), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10140 = svld1_gather_u64offset_f64(pg1, (a10122 + 17), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4660 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10140, s4597), a10139, s4596);
        s4661 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10139, s4597), a10140, s4596);
        a10141 = svld1_gather_u64offset_f64(pg1, (a10122 + 18), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10142 = svld1_gather_u64offset_f64(pg1, (a10122 + 19), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4662 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10142, s4617), a10141, s4616);
        s4663 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10141, s4617), a10142, s4616);
        a10143 = svld1_gather_u64offset_f64(pg1, (a10122 + 20), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10144 = svld1_gather_u64offset_f64(pg1, (a10122 + 21), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4664 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10144, s4637), a10143, s4636);
        s4665 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10143, s4637), a10144, s4636);
        a10145 = svld1_gather_u64offset_f64(pg1, (a10122 + 22), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10146 = svld1_gather_u64offset_f64(pg1, (a10122 + 23), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4666 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10146, s4581), a10145, s4580);
        s4667 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10145, s4581), a10146, s4580);
        a10147 = svld1_gather_u64offset_f64(pg1, (a10122 + 24), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10148 = svld1_gather_u64offset_f64(pg1, (a10122 + 25), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4668 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10148, s4601), a10147, s4600);
        s4669 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10147, s4601), a10148, s4600);
        a10149 = svld1_gather_u64offset_f64(pg1, (a10122 + 26), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10150 = svld1_gather_u64offset_f64(pg1, (a10122 + 27), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4670 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10150, s4621), a10149, s4620);
        s4671 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10149, s4621), a10150, s4620);
        a10151 = svld1_gather_u64offset_f64(pg1, (a10122 + 28), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10152 = svld1_gather_u64offset_f64(pg1, (a10122 + 29), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4672 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10152, s4641), a10151, s4640);
        s4673 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10151, s4641), a10152, s4640);
        a10153 = svld1_gather_u64offset_f64(pg1, (a10122 + 30), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10154 = svld1_gather_u64offset_f64(pg1, (a10122 + 31), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4674 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10154, s4571), a10153, s4570);
        s4675 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10153, s4571), a10154, s4570);
        a10155 = svld1_gather_u64offset_f64(pg1, (a10122 + 32), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10156 = svld1_gather_u64offset_f64(pg1, (a10122 + 33), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4676 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10156, s4591), a10155, s4590);
        s4677 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10155, s4591), a10156, s4590);
        a10157 = svld1_gather_u64offset_f64(pg1, (a10122 + 34), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10158 = svld1_gather_u64offset_f64(pg1, (a10122 + 35), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4678 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10158, s4611), a10157, s4610);
        s4679 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10157, s4611), a10158, s4610);
        a10159 = svld1_gather_u64offset_f64(pg1, (a10122 + 36), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10160 = svld1_gather_u64offset_f64(pg1, (a10122 + 37), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4680 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10160, s4631), a10159, s4630);
        s4681 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10159, s4631), a10160, s4630);
        a10161 = svld1_gather_u64offset_f64(pg1, (a10122 + 38), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10162 = svld1_gather_u64offset_f64(pg1, (a10122 + 39), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4682 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10162, s4575), a10161, s4574);
        s4683 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10161, s4575), a10162, s4574);
        a10163 = svld1_gather_u64offset_f64(pg1, (a10122 + 40), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10164 = svld1_gather_u64offset_f64(pg1, (a10122 + 41), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4684 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10164, s4595), a10163, s4594);
        s4685 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10163, s4595), a10164, s4594);
        a10165 = svld1_gather_u64offset_f64(pg1, (a10122 + 42), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10166 = svld1_gather_u64offset_f64(pg1, (a10122 + 43), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4686 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10166, s4615), a10165, s4614);
        s4687 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10165, s4615), a10166, s4614);
        a10167 = svld1_gather_u64offset_f64(pg1, (a10122 + 44), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10168 = svld1_gather_u64offset_f64(pg1, (a10122 + 45), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4688 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10168, s4635), a10167, s4634);
        s4689 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10167, s4635), a10168, s4634);
        a10169 = svld1_gather_u64offset_f64(pg1, (a10122 + 46), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10170 = svld1_gather_u64offset_f64(pg1, (a10122 + 47), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4690 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10170, s4579), a10169, s4578);
        s4691 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10169, s4579), a10170, s4578);
        a10171 = svld1_gather_u64offset_f64(pg1, (a10122 + 48), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10172 = svld1_gather_u64offset_f64(pg1, (a10122 + 49), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4692 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10172, s4599), a10171, s4598);
        s4693 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10171, s4599), a10172, s4598);
        a10173 = svld1_gather_u64offset_f64(pg1, (a10122 + 50), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10174 = svld1_gather_u64offset_f64(pg1, (a10122 + 51), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4694 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10174, s4619), a10173, s4618);
        s4695 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10173, s4619), a10174, s4618);
        a10175 = svld1_gather_u64offset_f64(pg1, (a10122 + 52), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10176 = svld1_gather_u64offset_f64(pg1, (a10122 + 53), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4696 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10176, s4639), a10175, s4638);
        s4697 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10175, s4639), a10176, s4638);
        a10177 = svld1_gather_u64offset_f64(pg1, (a10122 + 54), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10178 = svld1_gather_u64offset_f64(pg1, (a10122 + 55), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4698 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10178, s4583), a10177, s4582);
        s4699 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10177, s4583), a10178, s4582);
        a10179 = svld1_gather_u64offset_f64(pg1, (a10122 + 56), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10180 = svld1_gather_u64offset_f64(pg1, (a10122 + 57), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4700 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10180, s4603), a10179, s4602);
        s4701 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10179, s4603), a10180, s4602);
        a10181 = svld1_gather_u64offset_f64(pg1, (a10122 + 58), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10182 = svld1_gather_u64offset_f64(pg1, (a10122 + 59), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4702 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10182, s4623), a10181, s4622);
        s4703 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10181, s4623), a10182, s4622);
        a10183 = svld1_gather_u64offset_f64(pg1, (a10122 + 60), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        a10184 = svld1_gather_u64offset_f64(pg1, (a10122 + 61), svindex_u64(0, (int64_t)(62 * sizeof(float64_t))));
        s4704 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a10184, s4643), a10183, s4642);
        s4705 = svmla_f64_x(pg1, svmul_f64_x(pg1, a10183, s4643), a10184, s4642);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4568);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4569);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4644);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4645);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4646);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4647);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4648);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4649);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4650);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4651);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4652);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4653);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4654);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4655);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4656);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4657);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(16 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4658);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(17 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4659);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(18 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4660);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(19 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4661);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(20 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4662);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(21 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4663);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(22 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4664);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(23 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4665);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(24 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4666);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(25 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4667);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(26 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4668);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(27 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4669);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(28 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4670);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(29 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4671);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(30 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4672);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(31 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4673);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(32 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4674);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(33 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4675);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(34 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4676);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(35 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4677);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(36 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4678);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(37 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4679);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(38 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4680);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(39 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4681);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(40 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4682);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(41 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4683);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(42 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4684);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(43 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4685);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(44 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4686);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(45 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4687);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(46 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4688);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(47 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4689);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(48 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4690);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(49 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4691);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(50 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4692);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(51 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4693);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(52 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4694);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(53 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4695);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(54 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4696);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(55 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4697);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(56 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4698);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(57 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4699);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(58 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4700);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(59 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4701);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(60 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4702);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(61 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4703);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(62 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4704);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(63 + Y + ((64)*(j1)))), svindex_u64(0, (int64_t)(64 * sizeof(float64_t))), s4705);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
