/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft32c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    static float64_t D15[64];
    int l1, m1;
    svfloat64x2_t s4154, s4157, s4160, s4163, s4166, s4169, s4172, s4175, 
            s4178, s4181, s4184, s4187, s4190, s4193, s4196, s4199, 
            s4202, s4205, s4208, s4211, s4214, s4217, s4220, s4223, 
            s4226, s4229, s4232, s4235, s4238, s4241, s4244, s4247, 
            svex2_33, svex2_34, svex2_35, svex2_36, svex2_37, svex2_38, svex2_39, svex2_40, 
            svex2_41, svex2_42, svex2_43, svex2_44, svex2_45, svex2_46, svex2_47, svex2_48, 
            svex2_49, svex2_50, svex2_51, svex2_52, svex2_53, svex2_54, svex2_55, svex2_56, 
            svex2_57, svex2_58, svex2_59, svex2_60, svex2_61, svex2_62, svex2_63, svex2_64;
    svfloat64_t a8674, a8675, a8676, a8677, a8678, a8679, a8680, a8681, 
            a8682, a8683, a8684, a8685, a8686, a8687, a8688, a8689, 
            s4155, s4156, s4158, s4159, s4161, s4162, s4164, s4165, 
            s4167, s4168, s4170, s4171, s4173, s4174, s4176, s4177, 
            s4179, s4180, s4182, s4183, s4185, s4186, s4188, s4189, 
            s4191, s4192, s4194, s4195, s4197, s4198, s4200, s4201, 
            s4203, s4204, s4206, s4207, s4209, s4210, s4212, s4213, 
            s4215, s4216, s4218, s4219, s4221, s4222, s4224, s4225, 
            s4227, s4228, s4230, s4231, s4233, s4234, s4236, s4237, 
            s4239, s4240, s4242, s4243, s4245, s4246, s4248, s4249, 
            s4250, s4251, s4252, s4253, s4254, s4255, s4256, s4257, 
            s4258, s4259, s4260, s4261, s4262, s4263, s4264, s4265, 
            s4266, s4267, s4268, s4269, s4270, s4271, s4272, s4273, 
            s4274, s4275, s4276, s4277, s4278, s4279, s4280, s4281, 
            s4282, s4283, s4284, s4285, s4286, s4287, s4288, s4289, 
            s4290, s4291, s4292, s4293, s4294, s4295, s4296, s4297, 
            s4298, s4299, s4300, s4301, s4302, s4303, s4304, s4305, 
            s4306, s4307, s4308, s4309, s4310, s4311, s4312, s4313, 
            s4314, s4315, s4316, s4317, s4318, s4319, s4320, s4321, 
            s4322, s4323, s4324, s4325, s4326, s4327, s4328, s4329, 
            t7130, t7131, t7132, t7133, t7134, t7135, t7136, t7137, 
            t7138, t7139, t7140, t7141, t7142, t7143, t7144, t7145, 
            t7146, t7147, t7148, t7149, t7150, t7151, t7152, t7153, 
            t7154, t7155, t7156, t7157, t7158, t7159, t7160, t7161, 
            t7162, t7163, t7164, t7165, t7166, t7167, t7168, t7169, 
            t7170, t7171, t7172, t7173, t7174, t7175, t7176, t7177, 
            t7178, t7179, t7180, t7181, t7182, t7183, t7184, t7185, 
            t7186, t7187, t7188, t7189, t7190, t7191, t7192, t7193, 
            t7194, t7195, t7196, t7197, t7198, t7199, t7200, t7201, 
            t7202, t7203, t7204, t7205, t7206, t7207, t7208, t7209, 
            t7210, t7211, t7212, t7213, t7214, t7215, t7216, t7217, 
            t7218, t7219, t7220, t7221, t7222, t7223, t7224, t7225, 
            t7226, t7227, t7228, t7229, t7230, t7231, t7232, t7233, 
            t7234, t7235, t7236, t7237, t7238, t7239, t7240, t7241, 
            t7242, t7243, t7244, t7245, t7246, t7247, t7248, t7249, 
            t7250, t7251, t7252, t7253, t7254, t7255, t7256, t7257, 
            t7258, t7259, t7260, t7261, t7262, t7263, t7264, t7265, 
            t7266, t7267, t7268, t7269, t7270, t7271, t7272, t7273, 
            t7274, t7275, t7276, t7277, t7278, t7279, t7280, t7281, 
            t7282, t7283, t7284, t7285, t7286, t7287, t7288, t7289, 
            t7290, t7291, t7292, t7293, t7294, t7295, t7296, t7297, 
            t7298, t7299, t7300, t7301, t7302, t7303, t7304, t7305, 
            t7306, t7307, t7308, t7309, t7310, t7311, t7312, t7313, 
            t7314, t7315, t7316, t7317, t7318, t7319, t7320, t7321, 
            t7322, t7323, t7324, t7325, t7326, t7327, t7328, t7329, 
            t7330, t7331, t7332, t7333, t7334, t7335, t7336, t7337, 
            t7338, t7339, t7340, t7341, t7342, t7343, t7344, t7345, 
            t7346, t7347, t7348, t7349, t7350, t7351, t7352, t7353, 
            t7354, t7355, t7356, t7357, t7358, t7359, t7360, t7361, 
            t7362, t7363, t7364, t7365, t7366, t7367, t7368, t7369;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s4154 = svld2_f64(pg1, (X + ((2)*(k1))));
        s4155 = s4154.v0;
        s4156 = s4154.v1;
        s4157 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s4158 = s4157.v0;
        s4159 = s4157.v1;
        s4160 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s4161 = s4160.v0;
        s4162 = s4160.v1;
        s4163 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s4164 = s4163.v0;
        s4165 = s4163.v1;
        s4166 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s4167 = s4166.v0;
        s4168 = s4166.v1;
        s4169 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s4170 = s4169.v0;
        s4171 = s4169.v1;
        s4172 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s4173 = s4172.v0;
        s4174 = s4172.v1;
        s4175 = svld2_f64(pg1, (X + ((2)*((k1 + ((((7)*(l1)))*(m1)))))));
        s4176 = s4175.v0;
        s4177 = s4175.v1;
        s4178 = svld2_f64(pg1, (X + ((2)*((k1 + ((((8)*(l1)))*(m1)))))));
        s4179 = s4178.v0;
        s4180 = s4178.v1;
        s4181 = svld2_f64(pg1, (X + ((2)*((k1 + ((((9)*(l1)))*(m1)))))));
        s4182 = s4181.v0;
        s4183 = s4181.v1;
        s4184 = svld2_f64(pg1, (X + ((2)*((k1 + ((((10)*(l1)))*(m1)))))));
        s4185 = s4184.v0;
        s4186 = s4184.v1;
        s4187 = svld2_f64(pg1, (X + ((2)*((k1 + ((((11)*(l1)))*(m1)))))));
        s4188 = s4187.v0;
        s4189 = s4187.v1;
        s4190 = svld2_f64(pg1, (X + ((2)*((k1 + ((((12)*(l1)))*(m1)))))));
        s4191 = s4190.v0;
        s4192 = s4190.v1;
        s4193 = svld2_f64(pg1, (X + ((2)*((k1 + ((((13)*(l1)))*(m1)))))));
        s4194 = s4193.v0;
        s4195 = s4193.v1;
        s4196 = svld2_f64(pg1, (X + ((2)*((k1 + ((((14)*(l1)))*(m1)))))));
        s4197 = s4196.v0;
        s4198 = s4196.v1;
        s4199 = svld2_f64(pg1, (X + ((2)*((k1 + ((((15)*(l1)))*(m1)))))));
        s4200 = s4199.v0;
        s4201 = s4199.v1;
        s4202 = svld2_f64(pg1, (X + ((2)*((k1 + ((((16)*(l1)))*(m1)))))));
        s4203 = s4202.v0;
        s4204 = s4202.v1;
        s4205 = svld2_f64(pg1, (X + ((2)*((k1 + ((((17)*(l1)))*(m1)))))));
        s4206 = s4205.v0;
        s4207 = s4205.v1;
        s4208 = svld2_f64(pg1, (X + ((2)*((k1 + ((((18)*(l1)))*(m1)))))));
        s4209 = s4208.v0;
        s4210 = s4208.v1;
        s4211 = svld2_f64(pg1, (X + ((2)*((k1 + ((((19)*(l1)))*(m1)))))));
        s4212 = s4211.v0;
        s4213 = s4211.v1;
        s4214 = svld2_f64(pg1, (X + ((2)*((k1 + ((((20)*(l1)))*(m1)))))));
        s4215 = s4214.v0;
        s4216 = s4214.v1;
        s4217 = svld2_f64(pg1, (X + ((2)*((k1 + ((((21)*(l1)))*(m1)))))));
        s4218 = s4217.v0;
        s4219 = s4217.v1;
        s4220 = svld2_f64(pg1, (X + ((2)*((k1 + ((((22)*(l1)))*(m1)))))));
        s4221 = s4220.v0;
        s4222 = s4220.v1;
        s4223 = svld2_f64(pg1, (X + ((2)*((k1 + ((((23)*(l1)))*(m1)))))));
        s4224 = s4223.v0;
        s4225 = s4223.v1;
        s4226 = svld2_f64(pg1, (X + ((2)*((k1 + ((((24)*(l1)))*(m1)))))));
        s4227 = s4226.v0;
        s4228 = s4226.v1;
        s4229 = svld2_f64(pg1, (X + ((2)*((k1 + ((((25)*(l1)))*(m1)))))));
        s4230 = s4229.v0;
        s4231 = s4229.v1;
        s4232 = svld2_f64(pg1, (X + ((2)*((k1 + ((((26)*(l1)))*(m1)))))));
        s4233 = s4232.v0;
        s4234 = s4232.v1;
        s4235 = svld2_f64(pg1, (X + ((2)*((k1 + ((((27)*(l1)))*(m1)))))));
        s4236 = s4235.v0;
        s4237 = s4235.v1;
        s4238 = svld2_f64(pg1, (X + ((2)*((k1 + ((((28)*(l1)))*(m1)))))));
        s4239 = s4238.v0;
        s4240 = s4238.v1;
        s4241 = svld2_f64(pg1, (X + ((2)*((k1 + ((((29)*(l1)))*(m1)))))));
        s4242 = s4241.v0;
        s4243 = s4241.v1;
        s4244 = svld2_f64(pg1, (X + ((2)*((k1 + ((((30)*(l1)))*(m1)))))));
        s4245 = s4244.v0;
        s4246 = s4244.v1;
        s4247 = svld2_f64(pg1, (X + ((2)*((k1 + ((((31)*(l1)))*(m1)))))));
        s4248 = s4247.v0;
        s4249 = s4247.v1;
        t7130 = svadd_f64_x(pg1, s4155, s4203);
        t7131 = svadd_f64_x(pg1, s4156, s4204);
        t7132 = svsub_f64_x(pg1, s4155, s4203);
        t7133 = svsub_f64_x(pg1, s4156, s4204);
        t7134 = svadd_f64_x(pg1, s4179, s4227);
        t7135 = svadd_f64_x(pg1, s4180, s4228);
        t7136 = svsub_f64_x(pg1, s4179, s4227);
        t7137 = svsub_f64_x(pg1, s4180, s4228);
        t7138 = svadd_f64_x(pg1, t7130, t7134);
        t7139 = svadd_f64_x(pg1, t7131, t7135);
        t7140 = svsub_f64_x(pg1, t7130, t7134);
        t7141 = svsub_f64_x(pg1, t7131, t7135);
        s4250 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7139, D15[1]), t7138, D15[0]);
        s4251 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7139, D15[0]), t7138, D15[1]);
        s4252 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7141, D15[3]), t7140, D15[2]);
        s4253 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7141, D15[2]), t7140, D15[3]);
        t7142 = svadd_f64_x(pg1, t7132, t7137);
        t7143 = svsub_f64_x(pg1, t7133, t7136);
        t7144 = svsub_f64_x(pg1, t7132, t7137);
        t7145 = svadd_f64_x(pg1, t7133, t7136);
        s4254 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7143, D15[5]), t7142, D15[4]);
        s4255 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7143, D15[4]), t7142, D15[5]);
        s4256 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7145, D15[7]), t7144, D15[6]);
        s4257 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7145, D15[6]), t7144, D15[7]);
        t7146 = svadd_f64_x(pg1, s4158, s4206);
        t7147 = svadd_f64_x(pg1, s4159, s4207);
        t7148 = svsub_f64_x(pg1, s4158, s4206);
        t7149 = svsub_f64_x(pg1, s4159, s4207);
        t7150 = svadd_f64_x(pg1, s4182, s4230);
        t7151 = svadd_f64_x(pg1, s4183, s4231);
        t7152 = svsub_f64_x(pg1, s4182, s4230);
        t7153 = svsub_f64_x(pg1, s4183, s4231);
        t7154 = svadd_f64_x(pg1, t7146, t7150);
        t7155 = svadd_f64_x(pg1, t7147, t7151);
        t7156 = svsub_f64_x(pg1, t7146, t7150);
        t7157 = svsub_f64_x(pg1, t7147, t7151);
        s4258 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7155, D15[9]), t7154, D15[8]);
        s4259 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7155, D15[8]), t7154, D15[9]);
        s4260 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7157, D15[11]), t7156, D15[10]);
        s4261 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7157, D15[10]), t7156, D15[11]);
        t7158 = svadd_f64_x(pg1, t7148, t7153);
        t7159 = svsub_f64_x(pg1, t7149, t7152);
        t7160 = svsub_f64_x(pg1, t7148, t7153);
        t7161 = svadd_f64_x(pg1, t7149, t7152);
        s4262 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7159, D15[13]), t7158, D15[12]);
        s4263 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7159, D15[12]), t7158, D15[13]);
        s4264 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7161, D15[15]), t7160, D15[14]);
        s4265 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7161, D15[14]), t7160, D15[15]);
        t7162 = svadd_f64_x(pg1, s4161, s4209);
        t7163 = svadd_f64_x(pg1, s4162, s4210);
        t7164 = svsub_f64_x(pg1, s4161, s4209);
        t7165 = svsub_f64_x(pg1, s4162, s4210);
        t7166 = svadd_f64_x(pg1, s4185, s4233);
        t7167 = svadd_f64_x(pg1, s4186, s4234);
        t7168 = svsub_f64_x(pg1, s4185, s4233);
        t7169 = svsub_f64_x(pg1, s4186, s4234);
        t7170 = svadd_f64_x(pg1, t7162, t7166);
        t7171 = svadd_f64_x(pg1, t7163, t7167);
        t7172 = svsub_f64_x(pg1, t7162, t7166);
        t7173 = svsub_f64_x(pg1, t7163, t7167);
        s4266 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7171, D15[17]), t7170, D15[16]);
        s4267 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7171, D15[16]), t7170, D15[17]);
        s4268 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7173, D15[19]), t7172, D15[18]);
        s4269 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7173, D15[18]), t7172, D15[19]);
        t7174 = svadd_f64_x(pg1, t7164, t7169);
        t7175 = svsub_f64_x(pg1, t7165, t7168);
        t7176 = svsub_f64_x(pg1, t7164, t7169);
        t7177 = svadd_f64_x(pg1, t7165, t7168);
        s4270 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7175, D15[21]), t7174, D15[20]);
        s4271 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7175, D15[20]), t7174, D15[21]);
        s4272 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7177, D15[23]), t7176, D15[22]);
        s4273 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7177, D15[22]), t7176, D15[23]);
        t7178 = svadd_f64_x(pg1, s4164, s4212);
        t7179 = svadd_f64_x(pg1, s4165, s4213);
        t7180 = svsub_f64_x(pg1, s4164, s4212);
        t7181 = svsub_f64_x(pg1, s4165, s4213);
        t7182 = svadd_f64_x(pg1, s4188, s4236);
        t7183 = svadd_f64_x(pg1, s4189, s4237);
        t7184 = svsub_f64_x(pg1, s4188, s4236);
        t7185 = svsub_f64_x(pg1, s4189, s4237);
        t7186 = svadd_f64_x(pg1, t7178, t7182);
        t7187 = svadd_f64_x(pg1, t7179, t7183);
        t7188 = svsub_f64_x(pg1, t7178, t7182);
        t7189 = svsub_f64_x(pg1, t7179, t7183);
        s4274 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7187, D15[25]), t7186, D15[24]);
        s4275 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7187, D15[24]), t7186, D15[25]);
        s4276 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7189, D15[27]), t7188, D15[26]);
        s4277 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7189, D15[26]), t7188, D15[27]);
        t7190 = svadd_f64_x(pg1, t7180, t7185);
        t7191 = svsub_f64_x(pg1, t7181, t7184);
        t7192 = svsub_f64_x(pg1, t7180, t7185);
        t7193 = svadd_f64_x(pg1, t7181, t7184);
        s4278 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7191, D15[29]), t7190, D15[28]);
        s4279 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7191, D15[28]), t7190, D15[29]);
        s4280 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7193, D15[31]), t7192, D15[30]);
        s4281 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7193, D15[30]), t7192, D15[31]);
        t7194 = svadd_f64_x(pg1, s4167, s4215);
        t7195 = svadd_f64_x(pg1, s4168, s4216);
        t7196 = svsub_f64_x(pg1, s4167, s4215);
        t7197 = svsub_f64_x(pg1, s4168, s4216);
        t7198 = svadd_f64_x(pg1, s4191, s4239);
        t7199 = svadd_f64_x(pg1, s4192, s4240);
        t7200 = svsub_f64_x(pg1, s4191, s4239);
        t7201 = svsub_f64_x(pg1, s4192, s4240);
        t7202 = svadd_f64_x(pg1, t7194, t7198);
        t7203 = svadd_f64_x(pg1, t7195, t7199);
        t7204 = svsub_f64_x(pg1, t7194, t7198);
        t7205 = svsub_f64_x(pg1, t7195, t7199);
        s4282 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7203, D15[33]), t7202, D15[32]);
        s4283 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7203, D15[32]), t7202, D15[33]);
        s4284 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7205, D15[35]), t7204, D15[34]);
        s4285 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7205, D15[34]), t7204, D15[35]);
        t7206 = svadd_f64_x(pg1, t7196, t7201);
        t7207 = svsub_f64_x(pg1, t7197, t7200);
        t7208 = svsub_f64_x(pg1, t7196, t7201);
        t7209 = svadd_f64_x(pg1, t7197, t7200);
        s4286 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7207, D15[37]), t7206, D15[36]);
        s4287 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7207, D15[36]), t7206, D15[37]);
        s4288 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7209, D15[39]), t7208, D15[38]);
        s4289 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7209, D15[38]), t7208, D15[39]);
        t7210 = svadd_f64_x(pg1, s4170, s4218);
        t7211 = svadd_f64_x(pg1, s4171, s4219);
        t7212 = svsub_f64_x(pg1, s4170, s4218);
        t7213 = svsub_f64_x(pg1, s4171, s4219);
        t7214 = svadd_f64_x(pg1, s4194, s4242);
        t7215 = svadd_f64_x(pg1, s4195, s4243);
        t7216 = svsub_f64_x(pg1, s4194, s4242);
        t7217 = svsub_f64_x(pg1, s4195, s4243);
        t7218 = svadd_f64_x(pg1, t7210, t7214);
        t7219 = svadd_f64_x(pg1, t7211, t7215);
        t7220 = svsub_f64_x(pg1, t7210, t7214);
        t7221 = svsub_f64_x(pg1, t7211, t7215);
        s4290 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7219, D15[41]), t7218, D15[40]);
        s4291 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7219, D15[40]), t7218, D15[41]);
        s4292 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7221, D15[43]), t7220, D15[42]);
        s4293 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7221, D15[42]), t7220, D15[43]);
        t7222 = svadd_f64_x(pg1, t7212, t7217);
        t7223 = svsub_f64_x(pg1, t7213, t7216);
        t7224 = svsub_f64_x(pg1, t7212, t7217);
        t7225 = svadd_f64_x(pg1, t7213, t7216);
        s4294 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7223, D15[45]), t7222, D15[44]);
        s4295 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7223, D15[44]), t7222, D15[45]);
        s4296 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7225, D15[47]), t7224, D15[46]);
        s4297 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7225, D15[46]), t7224, D15[47]);
        t7226 = svadd_f64_x(pg1, s4173, s4221);
        t7227 = svadd_f64_x(pg1, s4174, s4222);
        t7228 = svsub_f64_x(pg1, s4173, s4221);
        t7229 = svsub_f64_x(pg1, s4174, s4222);
        t7230 = svadd_f64_x(pg1, s4197, s4245);
        t7231 = svadd_f64_x(pg1, s4198, s4246);
        t7232 = svsub_f64_x(pg1, s4197, s4245);
        t7233 = svsub_f64_x(pg1, s4198, s4246);
        t7234 = svadd_f64_x(pg1, t7226, t7230);
        t7235 = svadd_f64_x(pg1, t7227, t7231);
        t7236 = svsub_f64_x(pg1, t7226, t7230);
        t7237 = svsub_f64_x(pg1, t7227, t7231);
        s4298 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7235, D15[49]), t7234, D15[48]);
        s4299 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7235, D15[48]), t7234, D15[49]);
        s4300 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7237, D15[51]), t7236, D15[50]);
        s4301 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7237, D15[50]), t7236, D15[51]);
        t7238 = svadd_f64_x(pg1, t7228, t7233);
        t7239 = svsub_f64_x(pg1, t7229, t7232);
        t7240 = svsub_f64_x(pg1, t7228, t7233);
        t7241 = svadd_f64_x(pg1, t7229, t7232);
        s4302 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7239, D15[53]), t7238, D15[52]);
        s4303 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7239, D15[52]), t7238, D15[53]);
        s4304 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7241, D15[55]), t7240, D15[54]);
        s4305 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7241, D15[54]), t7240, D15[55]);
        t7242 = svadd_f64_x(pg1, s4176, s4224);
        t7243 = svadd_f64_x(pg1, s4177, s4225);
        t7244 = svsub_f64_x(pg1, s4176, s4224);
        t7245 = svsub_f64_x(pg1, s4177, s4225);
        t7246 = svadd_f64_x(pg1, s4200, s4248);
        t7247 = svadd_f64_x(pg1, s4201, s4249);
        t7248 = svsub_f64_x(pg1, s4200, s4248);
        t7249 = svsub_f64_x(pg1, s4201, s4249);
        t7250 = svadd_f64_x(pg1, t7242, t7246);
        t7251 = svadd_f64_x(pg1, t7243, t7247);
        t7252 = svsub_f64_x(pg1, t7242, t7246);
        t7253 = svsub_f64_x(pg1, t7243, t7247);
        s4306 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7251, D15[57]), t7250, D15[56]);
        s4307 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7251, D15[56]), t7250, D15[57]);
        s4308 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7253, D15[59]), t7252, D15[58]);
        s4309 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7253, D15[58]), t7252, D15[59]);
        t7254 = svadd_f64_x(pg1, t7244, t7249);
        t7255 = svsub_f64_x(pg1, t7245, t7248);
        t7256 = svsub_f64_x(pg1, t7244, t7249);
        t7257 = svadd_f64_x(pg1, t7245, t7248);
        s4310 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7255, D15[61]), t7254, D15[60]);
        s4311 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7255, D15[60]), t7254, D15[61]);
        s4312 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, t7257, D15[63]), t7256, D15[62]);
        s4313 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, t7257, D15[62]), t7256, D15[63]);
        t7258 = svadd_f64_x(pg1, s4250, s4282);
        t7259 = svadd_f64_x(pg1, s4251, s4283);
        t7260 = svsub_f64_x(pg1, s4250, s4282);
        t7261 = svsub_f64_x(pg1, s4251, s4283);
        t7262 = svadd_f64_x(pg1, s4266, s4298);
        t7263 = svadd_f64_x(pg1, s4267, s4299);
        t7264 = svsub_f64_x(pg1, s4266, s4298);
        t7265 = svsub_f64_x(pg1, s4267, s4299);
        t7266 = svadd_f64_x(pg1, t7258, t7262);
        t7267 = svadd_f64_x(pg1, t7259, t7263);
        t7268 = svsub_f64_x(pg1, t7258, t7262);
        t7269 = svsub_f64_x(pg1, t7259, t7263);
        t7270 = svadd_f64_x(pg1, t7260, t7265);
        t7271 = svsub_f64_x(pg1, t7261, t7264);
        t7272 = svsub_f64_x(pg1, t7260, t7265);
        t7273 = svadd_f64_x(pg1, t7261, t7264);
        t7274 = svadd_f64_x(pg1, s4258, s4290);
        t7275 = svadd_f64_x(pg1, s4259, s4291);
        t7276 = svsub_f64_x(pg1, s4258, s4290);
        t7277 = svsub_f64_x(pg1, s4259, s4291);
        t7278 = svadd_f64_x(pg1, s4274, s4306);
        t7279 = svadd_f64_x(pg1, s4275, s4307);
        t7280 = svsub_f64_x(pg1, s4274, s4306);
        t7281 = svsub_f64_x(pg1, s4275, s4307);
        t7282 = svadd_f64_x(pg1, t7274, t7278);
        t7283 = svadd_f64_x(pg1, t7275, t7279);
        t7284 = svsub_f64_x(pg1, t7274, t7278);
        t7285 = svsub_f64_x(pg1, t7275, t7279);
        a8674 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7276, t7281), 0.70710678118654757);
        a8675 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7277, t7280), 0.70710678118654757);
        s4314 = svadd_f64_x(pg1, a8674, a8675);
        s4315 = svsub_f64_x(pg1, a8675, a8674);
        a8676 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7277, t7280), 0.70710678118654757);
        a8677 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7276, t7281), 0.70710678118654757);
        s4316 = svsub_f64_x(pg1, a8676, a8677);
        s4317 = svadd_f64_x(pg1, a8677, a8676);
        t7286 = svadd_f64_x(pg1, s4254, s4286);
        t7287 = svadd_f64_x(pg1, s4255, s4287);
        t7288 = svsub_f64_x(pg1, s4254, s4286);
        t7289 = svsub_f64_x(pg1, s4255, s4287);
        t7290 = svadd_f64_x(pg1, s4270, s4302);
        t7291 = svadd_f64_x(pg1, s4271, s4303);
        t7292 = svsub_f64_x(pg1, s4270, s4302);
        t7293 = svsub_f64_x(pg1, s4271, s4303);
        t7294 = svadd_f64_x(pg1, t7286, t7290);
        t7295 = svadd_f64_x(pg1, t7287, t7291);
        t7296 = svsub_f64_x(pg1, t7286, t7290);
        t7297 = svsub_f64_x(pg1, t7287, t7291);
        t7298 = svadd_f64_x(pg1, t7288, t7293);
        t7299 = svsub_f64_x(pg1, t7289, t7292);
        t7300 = svsub_f64_x(pg1, t7288, t7293);
        t7301 = svadd_f64_x(pg1, t7289, t7292);
        t7302 = svadd_f64_x(pg1, s4262, s4294);
        t7303 = svadd_f64_x(pg1, s4263, s4295);
        t7304 = svsub_f64_x(pg1, s4262, s4294);
        t7305 = svsub_f64_x(pg1, s4263, s4295);
        t7306 = svadd_f64_x(pg1, s4278, s4310);
        t7307 = svadd_f64_x(pg1, s4279, s4311);
        t7308 = svsub_f64_x(pg1, s4278, s4310);
        t7309 = svsub_f64_x(pg1, s4279, s4311);
        t7310 = svadd_f64_x(pg1, t7302, t7306);
        t7311 = svadd_f64_x(pg1, t7303, t7307);
        t7312 = svsub_f64_x(pg1, t7302, t7306);
        t7313 = svsub_f64_x(pg1, t7303, t7307);
        a8678 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7304, t7309), 0.70710678118654757);
        a8679 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7305, t7308), 0.70710678118654757);
        s4318 = svadd_f64_x(pg1, a8678, a8679);
        s4319 = svsub_f64_x(pg1, a8679, a8678);
        a8680 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7305, t7308), 0.70710678118654757);
        a8681 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7304, t7309), 0.70710678118654757);
        s4320 = svsub_f64_x(pg1, a8680, a8681);
        s4321 = svadd_f64_x(pg1, a8681, a8680);
        t7314 = svadd_f64_x(pg1, s4252, s4284);
        t7315 = svadd_f64_x(pg1, s4253, s4285);
        t7316 = svsub_f64_x(pg1, s4252, s4284);
        t7317 = svsub_f64_x(pg1, s4253, s4285);
        t7318 = svadd_f64_x(pg1, s4268, s4300);
        t7319 = svadd_f64_x(pg1, s4269, s4301);
        t7320 = svsub_f64_x(pg1, s4268, s4300);
        t7321 = svsub_f64_x(pg1, s4269, s4301);
        t7322 = svadd_f64_x(pg1, t7314, t7318);
        t7323 = svadd_f64_x(pg1, t7315, t7319);
        t7324 = svsub_f64_x(pg1, t7314, t7318);
        t7325 = svsub_f64_x(pg1, t7315, t7319);
        t7326 = svadd_f64_x(pg1, t7316, t7321);
        t7327 = svsub_f64_x(pg1, t7317, t7320);
        t7328 = svsub_f64_x(pg1, t7316, t7321);
        t7329 = svadd_f64_x(pg1, t7317, t7320);
        t7330 = svadd_f64_x(pg1, s4260, s4292);
        t7331 = svadd_f64_x(pg1, s4261, s4293);
        t7332 = svsub_f64_x(pg1, s4260, s4292);
        t7333 = svsub_f64_x(pg1, s4261, s4293);
        t7334 = svadd_f64_x(pg1, s4276, s4308);
        t7335 = svadd_f64_x(pg1, s4277, s4309);
        t7336 = svsub_f64_x(pg1, s4276, s4308);
        t7337 = svsub_f64_x(pg1, s4277, s4309);
        t7338 = svadd_f64_x(pg1, t7330, t7334);
        t7339 = svadd_f64_x(pg1, t7331, t7335);
        t7340 = svsub_f64_x(pg1, t7330, t7334);
        t7341 = svsub_f64_x(pg1, t7331, t7335);
        a8682 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7332, t7337), 0.70710678118654757);
        a8683 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7333, t7336), 0.70710678118654757);
        s4322 = svadd_f64_x(pg1, a8682, a8683);
        s4323 = svsub_f64_x(pg1, a8683, a8682);
        a8684 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7333, t7336), 0.70710678118654757);
        a8685 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7332, t7337), 0.70710678118654757);
        s4324 = svsub_f64_x(pg1, a8684, a8685);
        s4325 = svadd_f64_x(pg1, a8685, a8684);
        t7342 = svadd_f64_x(pg1, s4256, s4288);
        t7343 = svadd_f64_x(pg1, s4257, s4289);
        t7344 = svsub_f64_x(pg1, s4256, s4288);
        t7345 = svsub_f64_x(pg1, s4257, s4289);
        t7346 = svadd_f64_x(pg1, s4272, s4304);
        t7347 = svadd_f64_x(pg1, s4273, s4305);
        t7348 = svsub_f64_x(pg1, s4272, s4304);
        t7349 = svsub_f64_x(pg1, s4273, s4305);
        t7350 = svadd_f64_x(pg1, t7342, t7346);
        t7351 = svadd_f64_x(pg1, t7343, t7347);
        t7352 = svsub_f64_x(pg1, t7342, t7346);
        t7353 = svsub_f64_x(pg1, t7343, t7347);
        t7354 = svadd_f64_x(pg1, t7344, t7349);
        t7355 = svsub_f64_x(pg1, t7345, t7348);
        t7356 = svsub_f64_x(pg1, t7344, t7349);
        t7357 = svadd_f64_x(pg1, t7345, t7348);
        t7358 = svadd_f64_x(pg1, s4264, s4296);
        t7359 = svadd_f64_x(pg1, s4265, s4297);
        t7360 = svsub_f64_x(pg1, s4264, s4296);
        t7361 = svsub_f64_x(pg1, s4265, s4297);
        t7362 = svadd_f64_x(pg1, s4280, s4312);
        t7363 = svadd_f64_x(pg1, s4281, s4313);
        t7364 = svsub_f64_x(pg1, s4280, s4312);
        t7365 = svsub_f64_x(pg1, s4281, s4313);
        t7366 = svadd_f64_x(pg1, t7358, t7362);
        t7367 = svadd_f64_x(pg1, t7359, t7363);
        t7368 = svsub_f64_x(pg1, t7358, t7362);
        t7369 = svsub_f64_x(pg1, t7359, t7363);
        a8686 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7360, t7365), 0.70710678118654757);
        a8687 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7361, t7364), 0.70710678118654757);
        s4326 = svadd_f64_x(pg1, a8686, a8687);
        s4327 = svsub_f64_x(pg1, a8687, a8686);
        a8688 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t7361, t7364), 0.70710678118654757);
        a8689 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t7360, t7365), 0.70710678118654757);
        s4328 = svsub_f64_x(pg1, a8688, a8689);
        s4329 = svadd_f64_x(pg1, a8689, a8688);
        svex2_33.v0 = svadd_f64_x(pg1, t7266, t7282);
        svex2_33.v1 = svadd_f64_x(pg1, t7267, t7283);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_33);
        svex2_34.v0 = svadd_f64_x(pg1, t7294, t7310);
        svex2_34.v1 = svadd_f64_x(pg1, t7295, t7311);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_34);
        svex2_35.v0 = svadd_f64_x(pg1, t7322, t7338);
        svex2_35.v1 = svadd_f64_x(pg1, t7323, t7339);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_35);
        svex2_36.v0 = svadd_f64_x(pg1, t7350, t7366);
        svex2_36.v1 = svadd_f64_x(pg1, t7351, t7367);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_36);
        svex2_37.v0 = svadd_f64_x(pg1, t7270, s4314);
        svex2_37.v1 = svadd_f64_x(pg1, t7271, s4315);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_37);
        svex2_38.v0 = svadd_f64_x(pg1, t7298, s4318);
        svex2_38.v1 = svadd_f64_x(pg1, t7299, s4319);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_38);
        svex2_39.v0 = svadd_f64_x(pg1, t7326, s4322);
        svex2_39.v1 = svadd_f64_x(pg1, t7327, s4323);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_39);
        svex2_40.v0 = svadd_f64_x(pg1, t7354, s4326);
        svex2_40.v1 = svadd_f64_x(pg1, t7355, s4327);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((7)*(m1)))))), svex2_40);
        svex2_41.v0 = svadd_f64_x(pg1, t7268, t7285);
        svex2_41.v1 = svsub_f64_x(pg1, t7269, t7284);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((8)*(m1)))))), svex2_41);
        svex2_42.v0 = svadd_f64_x(pg1, t7296, t7313);
        svex2_42.v1 = svsub_f64_x(pg1, t7297, t7312);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((9)*(m1)))))), svex2_42);
        svex2_43.v0 = svadd_f64_x(pg1, t7324, t7341);
        svex2_43.v1 = svsub_f64_x(pg1, t7325, t7340);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((10)*(m1)))))), svex2_43);
        svex2_44.v0 = svadd_f64_x(pg1, t7352, t7369);
        svex2_44.v1 = svsub_f64_x(pg1, t7353, t7368);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((11)*(m1)))))), svex2_44);
        svex2_45.v0 = svadd_f64_x(pg1, t7272, s4316);
        svex2_45.v1 = svsub_f64_x(pg1, t7273, s4317);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((12)*(m1)))))), svex2_45);
        svex2_46.v0 = svadd_f64_x(pg1, t7300, s4320);
        svex2_46.v1 = svsub_f64_x(pg1, t7301, s4321);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((13)*(m1)))))), svex2_46);
        svex2_47.v0 = svadd_f64_x(pg1, t7328, s4324);
        svex2_47.v1 = svsub_f64_x(pg1, t7329, s4325);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((14)*(m1)))))), svex2_47);
        svex2_48.v0 = svadd_f64_x(pg1, t7356, s4328);
        svex2_48.v1 = svsub_f64_x(pg1, t7357, s4329);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((15)*(m1)))))), svex2_48);
        svex2_49.v0 = svsub_f64_x(pg1, t7266, t7282);
        svex2_49.v1 = svsub_f64_x(pg1, t7267, t7283);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((16)*(m1)))))), svex2_49);
        svex2_50.v0 = svsub_f64_x(pg1, t7294, t7310);
        svex2_50.v1 = svsub_f64_x(pg1, t7295, t7311);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((17)*(m1)))))), svex2_50);
        svex2_51.v0 = svsub_f64_x(pg1, t7322, t7338);
        svex2_51.v1 = svsub_f64_x(pg1, t7323, t7339);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((18)*(m1)))))), svex2_51);
        svex2_52.v0 = svsub_f64_x(pg1, t7350, t7366);
        svex2_52.v1 = svsub_f64_x(pg1, t7351, t7367);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((19)*(m1)))))), svex2_52);
        svex2_53.v0 = svsub_f64_x(pg1, t7270, s4314);
        svex2_53.v1 = svsub_f64_x(pg1, t7271, s4315);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((20)*(m1)))))), svex2_53);
        svex2_54.v0 = svsub_f64_x(pg1, t7298, s4318);
        svex2_54.v1 = svsub_f64_x(pg1, t7299, s4319);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((21)*(m1)))))), svex2_54);
        svex2_55.v0 = svsub_f64_x(pg1, t7326, s4322);
        svex2_55.v1 = svsub_f64_x(pg1, t7327, s4323);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((22)*(m1)))))), svex2_55);
        svex2_56.v0 = svsub_f64_x(pg1, t7354, s4326);
        svex2_56.v1 = svsub_f64_x(pg1, t7355, s4327);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((23)*(m1)))))), svex2_56);
        svex2_57.v0 = svsub_f64_x(pg1, t7268, t7285);
        svex2_57.v1 = svadd_f64_x(pg1, t7269, t7284);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((24)*(m1)))))), svex2_57);
        svex2_58.v0 = svsub_f64_x(pg1, t7296, t7313);
        svex2_58.v1 = svadd_f64_x(pg1, t7297, t7312);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((25)*(m1)))))), svex2_58);
        svex2_59.v0 = svsub_f64_x(pg1, t7324, t7341);
        svex2_59.v1 = svadd_f64_x(pg1, t7325, t7340);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((26)*(m1)))))), svex2_59);
        svex2_60.v0 = svsub_f64_x(pg1, t7352, t7369);
        svex2_60.v1 = svadd_f64_x(pg1, t7353, t7368);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((27)*(m1)))))), svex2_60);
        svex2_61.v0 = svsub_f64_x(pg1, t7272, s4316);
        svex2_61.v1 = svadd_f64_x(pg1, t7273, s4317);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((28)*(m1)))))), svex2_61);
        svex2_62.v0 = svsub_f64_x(pg1, t7300, s4320);
        svex2_62.v1 = svadd_f64_x(pg1, t7301, s4321);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((29)*(m1)))))), svex2_62);
        svex2_63.v0 = svsub_f64_x(pg1, t7328, s4324);
        svex2_63.v1 = svadd_f64_x(pg1, t7329, s4325);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((30)*(m1)))))), svex2_63);
        svex2_64.v0 = svsub_f64_x(pg1, t7356, s4328);
        svex2_64.v1 = svadd_f64_x(pg1, t7357, s4329);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((31)*(m1)))))), svex2_64);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
