/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft3c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    int l1, m1;
    svfloat64x2_t s86, s89, s92, svex2_4, svex2_5, svex2_6;
    svfloat64_t s87, s88, s90, s91, s93, s94, s95, s96, 
            t125, t126, t127, t128;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s86 = svld2_f64(pg1, (X + ((2)*(k1))));
        s87 = s86.v0;
        s88 = s86.v1;
        s89 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s90 = s89.v0;
        s91 = s89.v1;
        s92 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s93 = s92.v0;
        s94 = s92.v1;
        t125 = svadd_f64_x(pg1, s90, s93);
        t126 = svadd_f64_x(pg1, s91, s94);
        t127 = svmls_n_f64_x(pg1, s87, t125, 0.5);
        t128 = svmls_n_f64_x(pg1, s88, t126, 0.5);
        s95 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s91, s94), 0.8660254037844386);
        s96 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s90, s93), 0.8660254037844386);
        svex2_4.v0 = svadd_f64_x(pg1, s87, t125);
        svex2_4.v1 = svadd_f64_x(pg1, s88, t126);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_4);
        svex2_5.v0 = svadd_f64_x(pg1, t127, s95);
        svex2_5.v1 = svsub_f64_x(pg1, t128, s96);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_5);
        svex2_6.v0 = svsub_f64_x(pg1, t127, s95);
        svex2_6.v1 = svadd_f64_x(pg1, t128, s96);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_6);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
