/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft4c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    int l1, m1;
    svfloat64x2_t s85, s88, s91, s94, svex2_5, svex2_6, svex2_7, svex2_8;
    svfloat64_t s86, s87, s89, s90, s92, s93, s95, s96, 
            t153, t154, t155, t156, t157, t158, t159, t160;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s85 = svld2_f64(pg1, (X + ((2)*(k1))));
        s86 = s85.v0;
        s87 = s85.v1;
        s88 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s89 = s88.v0;
        s90 = s88.v1;
        s91 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s92 = s91.v0;
        s93 = s91.v1;
        s94 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s95 = s94.v0;
        s96 = s94.v1;
        t153 = svadd_f64_x(pg1, s86, s92);
        t154 = svadd_f64_x(pg1, s87, s93);
        t155 = svsub_f64_x(pg1, s86, s92);
        t156 = svsub_f64_x(pg1, s87, s93);
        t157 = svadd_f64_x(pg1, s89, s95);
        t158 = svadd_f64_x(pg1, s90, s96);
        t159 = svsub_f64_x(pg1, s89, s95);
        t160 = svsub_f64_x(pg1, s90, s96);
        svex2_5.v0 = svadd_f64_x(pg1, t153, t157);
        svex2_5.v1 = svadd_f64_x(pg1, t154, t158);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_5);
        svex2_6.v0 = svadd_f64_x(pg1, t155, t160);
        svex2_6.v1 = svsub_f64_x(pg1, t156, t159);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_6);
        svex2_7.v0 = svsub_f64_x(pg1, t153, t157);
        svex2_7.v1 = svsub_f64_x(pg1, t154, t158);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_7);
        svex2_8.v0 = svsub_f64_x(pg1, t155, t160);
        svex2_8.v1 = svadd_f64_x(pg1, t156, t159);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_8);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
