/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft5a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a379;
    svfloat64x2_t s206, s209, s212, s215, s218;
    svfloat64_t a380, a381, a382, a383, a384, a385, a387, a388, 
            s207, s208, s210, s211, s213, s214, s216, s217, 
            s219, s220, s221, s222, s223, s224, s225, s226, 
            s227, s228, s229, s230, s231, s232, s233, s234, 
            s235, s236, s237, s238, s239, s240, s241, s242, 
            s243, s244, s245, s246, s247, s248, t395, t396, 
            t397, t398, t399, t400, t401, t402, t403, t404, 
            t405, t406, t407, t408, t409, t410, t411, t412, 
            t413, t414, t415, t416, t417, t418;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s206 = svld2_f64(pg1, (X + ((2)*(j1))));
        s207 = s206.v0;
        s208 = s206.v1;
        s209 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s210 = s209.v0;
        s211 = s209.v1;
        s212 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s213 = s212.v0;
        s214 = s212.v1;
        s215 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s216 = s215.v0;
        s217 = s215.v1;
        s218 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s219 = s218.v0;
        s220 = s218.v1;
        t395 = svadd_f64_x(pg1, s210, s219);
        t396 = svadd_f64_x(pg1, s211, s220);
        t397 = svsub_f64_x(pg1, s210, s219);
        t398 = svsub_f64_x(pg1, s211, s220);
        t399 = svadd_f64_x(pg1, s213, s216);
        t400 = svadd_f64_x(pg1, s214, s217);
        t401 = svsub_f64_x(pg1, s213, s216);
        t402 = svsub_f64_x(pg1, s214, s217);
        t403 = svadd_f64_x(pg1, t395, t399);
        t404 = svadd_f64_x(pg1, t396, t400);
        t405 = svadd_f64_x(pg1, t397, t402);
        t406 = svsub_f64_x(pg1, t398, t401);
        t407 = svsub_f64_x(pg1, t397, t402);
        t408 = svadd_f64_x(pg1, t398, t401);
        t409 = svmls_n_f64_x(pg1, s207, t403, 0.25);
        t410 = svmls_n_f64_x(pg1, s208, t404, 0.25);
        s245 = svmla_n_f64_x(pg1, t405, t406, 1.6180339887498947);
        s221 = svmul_n_f64_x(pg1, s245, 0.29389262614623657);
        s246 = svmls_n_f64_x(pg1, t406, t405, 1.6180339887498947);
        s222 = svmul_n_f64_x(pg1, s246, 0.29389262614623657);
        s223 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t395, t399), 0.55901699437494745);
        s224 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t396, t400), 0.55901699437494745);
        s247 = svmls_n_f64_x(pg1, t408, t407, 0.61803398874989479);
        s225 = svmul_n_f64_x(pg1, s247, 0.47552825814757682);
        s248 = svmla_n_f64_x(pg1, t407, t408, 0.61803398874989479);
        s226 = svmul_n_f64_x(pg1, s248, 0.47552825814757682);
        s227 = svadd_f64_x(pg1, s207, t403);
        s228 = svadd_f64_x(pg1, s208, t404);
        t411 = svadd_f64_x(pg1, t409, s223);
        t412 = svadd_f64_x(pg1, t410, s224);
        t413 = svsub_f64_x(pg1, t409, s223);
        t414 = svsub_f64_x(pg1, t410, s224);
        t415 = svadd_f64_x(pg1, s221, s225);
        t416 = svsub_f64_x(pg1, s222, s226);
        t417 = svsub_f64_x(pg1, s221, s225);
        t418 = svadd_f64_x(pg1, s222, s226);
        s229 = svadd_f64_x(pg1, t411, t415);
        s230 = svadd_f64_x(pg1, t412, t416);
        s231 = svsub_f64_x(pg1, t411, t415);
        s232 = svsub_f64_x(pg1, t412, t416);
        s233 = svadd_f64_x(pg1, t413, t418);
        s234 = svsub_f64_x(pg1, t414, t417);
        s235 = svsub_f64_x(pg1, t413, t418);
        s236 = svadd_f64_x(pg1, t414, t417);
        a379 = (TW1 + ((8)*(j1)));
        a380 = svld1_gather_u64offset_f64(pg1, a379, svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        a381 = svld1_gather_u64offset_f64(pg1, (a379 + 1), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        s237 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a381, s230), a380, s229);
        s238 = svmla_f64_x(pg1, svmul_f64_x(pg1, a380, s230), a381, s229);
        a382 = svld1_gather_u64offset_f64(pg1, (a379 + 2), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        a383 = svld1_gather_u64offset_f64(pg1, (a379 + 3), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        s239 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a383, s234), a382, s233);
        s240 = svmla_f64_x(pg1, svmul_f64_x(pg1, a382, s234), a383, s233);
        a384 = svld1_gather_u64offset_f64(pg1, (a379 + 4), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        a385 = svld1_gather_u64offset_f64(pg1, (a379 + 5), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        s241 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a385, s236), a384, s235);
        s242 = svmla_f64_x(pg1, svmul_f64_x(pg1, a384, s236), a385, s235);
        a387 = svld1_gather_u64offset_f64(pg1, (a379 + 6), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        a388 = svld1_gather_u64offset_f64(pg1, (a379 + 7), svindex_u64(0, (int64_t)(8 * sizeof(float64_t))));
        s243 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a388, s232), a387, s231);
        s244 = svmla_f64_x(pg1, svmul_f64_x(pg1, a387, s232), a388, s231);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s227);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s228);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s237);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s238);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s239);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s240);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s241);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s242);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s243);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((10)*(j1)))), svindex_u64(0, (int64_t)(10 * sizeof(float64_t))), s244);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
