/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft7a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a1072;
    svfloat64x2_t s797, s800, s803, s806, s809, s812, s815;
    svfloat64_t a1073, a1074, a1075, a1076, a1077, a1078, a1079, a1080, 
            a1081, a1082, a1083, a1084, s798, s799, s801, s802, 
            s804, s805, s807, s808, s810, s811, s813, s814, 
            s816, s817, s818, s819, s820, s821, s822, s823, 
            s824, s825, s826, s827, s828, s829, s830, s831, 
            s832, s833, s834, s835, s836, s837, s838, s839, 
            s840, s841, s842, s843, s844, s845, s846, s847, 
            s848, s849, s850, s851, s852, s853, s854, s855, 
            s856, s857, s858, s859, s860, s861, s862, s863, 
            s864, s865, s866, s867, s868, s869, s870, s871, 
            s872, s873, s874, s875, s876, s877, s878, s879, 
            s880, s881, s882, s883, s884, s885, t1799, t1800, 
            t1801, t1802, t1803, t1804, t1805, t1806, t1807, t1808, 
            t1809, t1810, t1811, t1812, t1813, t1814, t1815, t1816, 
            t1817, t1818, t1819, t1820, t1821, t1822, t1823, t1824, 
            t1825, t1826, t1827, t1828, t1829, t1830, t1831, t1832, 
            t1833, t1834, t1835, t1836, t1837, t1838, t1839, t1840, 
            t1841, t1842, t1843, t1844, t1845, t1846, t1847, t1848, 
            t1849, t1850;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s797 = svld2_f64(pg1, (X + ((2)*(j1))));
        s798 = s797.v0;
        s799 = s797.v1;
        s800 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s801 = s800.v0;
        s802 = s800.v1;
        s803 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s804 = s803.v0;
        s805 = s803.v1;
        s806 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s807 = s806.v0;
        s808 = s806.v1;
        s809 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s810 = s809.v0;
        s811 = s809.v1;
        s812 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s813 = s812.v0;
        s814 = s812.v1;
        s815 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s816 = s815.v0;
        s817 = s815.v1;
        t1799 = svadd_f64_x(pg1, s804, s810);
        t1800 = svadd_f64_x(pg1, s805, s811);
        t1801 = svadd_f64_x(pg1, s801, t1799);
        t1802 = svadd_f64_x(pg1, s802, t1800);
        t1803 = svmls_n_f64_x(pg1, s801, t1799, 0.5);
        t1804 = svmls_n_f64_x(pg1, s802, t1800, 0.5);
        s818 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s805, s811), 0.8660254037844386);
        s819 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s804, s810), 0.8660254037844386);
        t1805 = svadd_f64_x(pg1, t1803, s818);
        t1806 = svsub_f64_x(pg1, t1804, s819);
        t1807 = svsub_f64_x(pg1, t1803, s818);
        t1808 = svadd_f64_x(pg1, t1804, s819);
        t1809 = svadd_f64_x(pg1, s816, s813);
        t1810 = svadd_f64_x(pg1, s817, s814);
        t1811 = svadd_f64_x(pg1, s807, t1809);
        t1812 = svadd_f64_x(pg1, s808, t1810);
        t1813 = svmls_n_f64_x(pg1, s807, t1809, 0.5);
        t1814 = svmls_n_f64_x(pg1, s808, t1810, 0.5);
        s820 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s817, s814), 0.8660254037844386);
        s821 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s816, s813), 0.8660254037844386);
        t1815 = svadd_f64_x(pg1, t1813, s820);
        t1816 = svsub_f64_x(pg1, t1814, s821);
        t1817 = svsub_f64_x(pg1, t1813, s820);
        t1818 = svadd_f64_x(pg1, t1814, s821);
        s870 = svmla_n_f64_x(pg1, t1815, t1816, 1.7320508075688772);
        s822 = svmul_n_f64_x(pg1, s870, 0.5);
        s871 = svmls_n_f64_x(pg1, t1816, t1815, 1.7320508075688772);
        s823 = svmul_n_f64_x(pg1, s871, 0.5);
        s872 = svmls_n_f64_x(pg1, t1818, t1817, 0.57735026918962584);
        s824 = svmul_n_f64_x(pg1, s872, 0.8660254037844386);
        s873 = svmla_n_f64_x(pg1, t1817, t1818, 0.57735026918962584);
        s825 = svmul_n_f64_x(pg1, s873, 0.8660254037844386);
        t1819 = svadd_f64_x(pg1, t1801, t1811);
        t1820 = svadd_f64_x(pg1, t1802, t1812);
        t1821 = svadd_f64_x(pg1, t1805, s822);
        t1822 = svadd_f64_x(pg1, t1806, s823);
        t1823 = svsub_f64_x(pg1, t1805, s822);
        t1824 = svsub_f64_x(pg1, t1806, s823);
        t1825 = svadd_f64_x(pg1, t1807, s824);
        t1826 = svsub_f64_x(pg1, t1808, s825);
        t1827 = svsub_f64_x(pg1, t1807, s824);
        t1828 = svadd_f64_x(pg1, t1808, s825);
        t1829 = svmls_n_f64_x(pg1, s798, t1819, 0.16666666666666666);
        t1830 = svmls_n_f64_x(pg1, s799, t1820, 0.16666666666666666);
        s874 = svmla_n_f64_x(pg1, t1821, t1822, 0.41908315722758349);
        s826 = svmul_n_f64_x(pg1, s874, 0.4066888930575896);
        s875 = svmls_n_f64_x(pg1, t1822, t1821, 0.41908315722758349);
        s827 = svmul_n_f64_x(pg1, s875, 0.4066888930575896);
        s876 = svmla_n_f64_x(pg1, t1825, t1826, 0.49572725516748389);
        s828 = svmul_n_f64_x(pg1, s876, 0.39507823426270006);
        s877 = svmls_n_f64_x(pg1, t1826, t1825, 0.49572725516748389);
        s829 = svmul_n_f64_x(pg1, s877, 0.39507823426270006);
        s830 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1802, t1812), 0.44095855184409843);
        s831 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1801, t1811), 0.44095855184409843);
        s878 = svmls_n_f64_x(pg1, t1823, t1824, 0.49572725516748389);
        s832 = svmul_n_f64_x(pg1, s878, 0.39507823426270006);
        s879 = svmla_n_f64_x(pg1, t1823, t1824, 2.0172382889501304);
        s833 = svmul_n_f64_x(pg1, s879, 0.1958510486474645);
        s880 = svmls_n_f64_x(pg1, t1828, t1827, 2.386161273135941);
        s834 = svmul_n_f64_x(pg1, s880, 0.17043646531196566);
        s881 = svmla_n_f64_x(pg1, t1827, t1828, 2.386161273135941);
        s835 = svmul_n_f64_x(pg1, s881, 0.17043646531196566);
        s836 = svadd_f64_x(pg1, s798, t1819);
        s837 = svadd_f64_x(pg1, s799, t1820);
        t1831 = svadd_f64_x(pg1, s828, s832);
        t1832 = svadd_f64_x(pg1, s829, s833);
        t1833 = svadd_f64_x(pg1, t1829, t1831);
        t1834 = svadd_f64_x(pg1, t1830, t1832);
        t1835 = svmls_n_f64_x(pg1, t1829, t1831, 0.5);
        t1836 = svmls_n_f64_x(pg1, t1830, t1832, 0.5);
        s838 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s829, s833), 0.8660254037844386);
        s839 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s828, s832), 0.8660254037844386);
        t1837 = svadd_f64_x(pg1, t1835, s838);
        t1838 = svsub_f64_x(pg1, t1836, s839);
        t1839 = svsub_f64_x(pg1, t1835, s838);
        t1840 = svadd_f64_x(pg1, t1836, s839);
        t1841 = svadd_f64_x(pg1, s830, s834);
        t1842 = svadd_f64_x(pg1, s831, s835);
        t1843 = svadd_f64_x(pg1, s826, t1841);
        t1844 = svsub_f64_x(pg1, s827, t1842);
        t1845 = svmls_n_f64_x(pg1, s826, t1841, 0.5);
        t1846 = svmla_n_f64_x(pg1, s827, t1842, 0.5);
        s840 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s835, s831), 0.8660254037844386);
        s841 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s830, s834), 0.8660254037844386);
        t1847 = svadd_f64_x(pg1, t1845, s840);
        t1848 = svsub_f64_x(pg1, t1846, s841);
        t1849 = svsub_f64_x(pg1, t1845, s840);
        t1850 = svadd_f64_x(pg1, t1846, s841);
        s882 = svmla_n_f64_x(pg1, t1847, t1848, 1.7320508075688772);
        s842 = svmul_n_f64_x(pg1, s882, 0.5);
        s883 = svmls_n_f64_x(pg1, t1848, t1847, 1.7320508075688772);
        s843 = svmul_n_f64_x(pg1, s883, 0.5);
        s884 = svmls_n_f64_x(pg1, t1850, t1849, 0.57735026918962584);
        s844 = svmul_n_f64_x(pg1, s884, 0.8660254037844386);
        s885 = svmla_n_f64_x(pg1, t1849, t1850, 0.57735026918962584);
        s845 = svmul_n_f64_x(pg1, s885, 0.8660254037844386);
        s846 = svadd_f64_x(pg1, t1833, t1843);
        s847 = svadd_f64_x(pg1, t1834, t1844);
        s848 = svsub_f64_x(pg1, t1833, t1843);
        s849 = svsub_f64_x(pg1, t1834, t1844);
        s850 = svadd_f64_x(pg1, t1837, s842);
        s851 = svadd_f64_x(pg1, t1838, s843);
        s852 = svsub_f64_x(pg1, t1837, s842);
        s853 = svsub_f64_x(pg1, t1838, s843);
        s854 = svadd_f64_x(pg1, t1839, s844);
        s855 = svsub_f64_x(pg1, t1840, s845);
        s856 = svsub_f64_x(pg1, t1839, s844);
        s857 = svadd_f64_x(pg1, t1840, s845);
        a1072 = (TW1 + ((12)*(j1)));
        a1073 = svld1_gather_u64offset_f64(pg1, a1072, svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1074 = svld1_gather_u64offset_f64(pg1, (a1072 + 1), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s858 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1074, s847), a1073, s846);
        s859 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1073, s847), a1074, s846);
        a1075 = svld1_gather_u64offset_f64(pg1, (a1072 + 2), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1076 = svld1_gather_u64offset_f64(pg1, (a1072 + 3), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s860 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1076, s855), a1075, s854);
        s861 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1075, s855), a1076, s854);
        a1077 = svld1_gather_u64offset_f64(pg1, (a1072 + 4), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1078 = svld1_gather_u64offset_f64(pg1, (a1072 + 5), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s862 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1078, s851), a1077, s850);
        s863 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1077, s851), a1078, s850);
        a1079 = svld1_gather_u64offset_f64(pg1, (a1072 + 6), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1080 = svld1_gather_u64offset_f64(pg1, (a1072 + 7), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s864 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1080, s853), a1079, s852);
        s865 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1079, s853), a1080, s852);
        a1081 = svld1_gather_u64offset_f64(pg1, (a1072 + 8), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1082 = svld1_gather_u64offset_f64(pg1, (a1072 + 9), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s866 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1082, s857), a1081, s856);
        s867 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1081, s857), a1082, s856);
        a1083 = svld1_gather_u64offset_f64(pg1, (a1072 + 10), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        a1084 = svld1_gather_u64offset_f64(pg1, (a1072 + 11), svindex_u64(0, (int64_t)(12 * sizeof(float64_t))));
        s868 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a1084, s849), a1083, s848);
        s869 = svmla_f64_x(pg1, svmul_f64_x(pg1, a1083, s849), a1084, s848);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s836);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s837);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s858);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s859);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s860);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s861);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s862);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s863);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s864);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s865);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s866);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s867);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s868);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((14)*(j1)))), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))), s869);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
