/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft7c_(float64_t  *Y, float64_t  *X, int  *lp1, int  *mp1) {
    int l1, m1;
    svfloat64x2_t s747, s750, s753, s756, s759, s762, s765, svex2_10, 
            svex2_11, svex2_12, svex2_13, svex2_14, svex2_8, svex2_9;
    svfloat64_t s748, s749, s751, s752, s754, s755, s757, s758, 
            s760, s761, s763, s764, s766, s767, s768, s769, 
            s770, s771, s772, s773, s774, s775, s776, s777, 
            s778, s779, s780, s781, s782, s783, s784, s785, 
            s786, s787, s788, s789, s790, s791, s792, s793, 
            s794, s795, s796, s797, s798, s799, s800, s801, 
            s802, s803, s804, s805, s806, s807, s808, s809, 
            t1798, t1799, t1800, t1801, t1802, t1803, t1804, t1805, 
            t1806, t1807, t1808, t1809, t1810, t1811, t1812, t1813, 
            t1814, t1815, t1816, t1817, t1818, t1819, t1820, t1821, 
            t1822, t1823, t1824, t1825, t1826, t1827, t1828, t1829, 
            t1830, t1831, t1832, t1833, t1834, t1835, t1836, t1837, 
            t1838, t1839, t1840, t1841, t1842, t1843, t1844, t1845, 
            t1846, t1847, t1848, t1849;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    int k1 = 0;
    pg1 = svwhilelt_b64(k1, m1);
    do {
        s747 = svld2_f64(pg1, (X + ((2)*(k1))));
        s748 = s747.v0;
        s749 = s747.v1;
        s750 = svld2_f64(pg1, (X + ((2)*((k1 + ((l1)*(m1)))))));
        s751 = s750.v0;
        s752 = s750.v1;
        s753 = svld2_f64(pg1, (X + ((2)*((k1 + ((((2)*(l1)))*(m1)))))));
        s754 = s753.v0;
        s755 = s753.v1;
        s756 = svld2_f64(pg1, (X + ((2)*((k1 + ((((3)*(l1)))*(m1)))))));
        s757 = s756.v0;
        s758 = s756.v1;
        s759 = svld2_f64(pg1, (X + ((2)*((k1 + ((((4)*(l1)))*(m1)))))));
        s760 = s759.v0;
        s761 = s759.v1;
        s762 = svld2_f64(pg1, (X + ((2)*((k1 + ((((5)*(l1)))*(m1)))))));
        s763 = s762.v0;
        s764 = s762.v1;
        s765 = svld2_f64(pg1, (X + ((2)*((k1 + ((((6)*(l1)))*(m1)))))));
        s766 = s765.v0;
        s767 = s765.v1;
        t1798 = svadd_f64_x(pg1, s754, s760);
        t1799 = svadd_f64_x(pg1, s755, s761);
        t1800 = svadd_f64_x(pg1, s751, t1798);
        t1801 = svadd_f64_x(pg1, s752, t1799);
        t1802 = svmls_n_f64_x(pg1, s751, t1798, 0.5);
        t1803 = svmls_n_f64_x(pg1, s752, t1799, 0.5);
        s768 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s755, s761), 0.8660254037844386);
        s769 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s754, s760), 0.8660254037844386);
        t1804 = svadd_f64_x(pg1, t1802, s768);
        t1805 = svsub_f64_x(pg1, t1803, s769);
        t1806 = svsub_f64_x(pg1, t1802, s768);
        t1807 = svadd_f64_x(pg1, t1803, s769);
        t1808 = svadd_f64_x(pg1, s766, s763);
        t1809 = svadd_f64_x(pg1, s767, s764);
        t1810 = svadd_f64_x(pg1, s757, t1808);
        t1811 = svadd_f64_x(pg1, s758, t1809);
        t1812 = svmls_n_f64_x(pg1, s757, t1808, 0.5);
        t1813 = svmls_n_f64_x(pg1, s758, t1809, 0.5);
        s770 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s767, s764), 0.8660254037844386);
        s771 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s766, s763), 0.8660254037844386);
        t1814 = svadd_f64_x(pg1, t1812, s770);
        t1815 = svsub_f64_x(pg1, t1813, s771);
        t1816 = svsub_f64_x(pg1, t1812, s770);
        t1817 = svadd_f64_x(pg1, t1813, s771);
        s794 = svmla_n_f64_x(pg1, t1814, t1815, 1.7320508075688772);
        s772 = svmul_n_f64_x(pg1, s794, 0.5);
        s795 = svmls_n_f64_x(pg1, t1815, t1814, 1.7320508075688772);
        s773 = svmul_n_f64_x(pg1, s795, 0.5);
        s796 = svmls_n_f64_x(pg1, t1817, t1816, 0.57735026918962584);
        s774 = svmul_n_f64_x(pg1, s796, 0.8660254037844386);
        s797 = svmla_n_f64_x(pg1, t1816, t1817, 0.57735026918962584);
        s775 = svmul_n_f64_x(pg1, s797, 0.8660254037844386);
        t1818 = svadd_f64_x(pg1, t1800, t1810);
        t1819 = svadd_f64_x(pg1, t1801, t1811);
        t1820 = svadd_f64_x(pg1, t1804, s772);
        t1821 = svadd_f64_x(pg1, t1805, s773);
        t1822 = svsub_f64_x(pg1, t1804, s772);
        t1823 = svsub_f64_x(pg1, t1805, s773);
        t1824 = svadd_f64_x(pg1, t1806, s774);
        t1825 = svsub_f64_x(pg1, t1807, s775);
        t1826 = svsub_f64_x(pg1, t1806, s774);
        t1827 = svadd_f64_x(pg1, t1807, s775);
        t1828 = svmls_n_f64_x(pg1, s748, t1818, 0.16666666666666666);
        t1829 = svmls_n_f64_x(pg1, s749, t1819, 0.16666666666666666);
        s798 = svmla_n_f64_x(pg1, t1820, t1821, 0.41908315722758349);
        s776 = svmul_n_f64_x(pg1, s798, 0.4066888930575896);
        s799 = svmls_n_f64_x(pg1, t1821, t1820, 0.41908315722758349);
        s777 = svmul_n_f64_x(pg1, s799, 0.4066888930575896);
        s800 = svmla_n_f64_x(pg1, t1824, t1825, 0.49572725516748389);
        s778 = svmul_n_f64_x(pg1, s800, 0.39507823426270006);
        s801 = svmls_n_f64_x(pg1, t1825, t1824, 0.49572725516748389);
        s779 = svmul_n_f64_x(pg1, s801, 0.39507823426270006);
        s780 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1801, t1811), 0.44095855184409843);
        s781 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t1800, t1810), 0.44095855184409843);
        s802 = svmls_n_f64_x(pg1, t1822, t1823, 0.49572725516748389);
        s782 = svmul_n_f64_x(pg1, s802, 0.39507823426270006);
        s803 = svmla_n_f64_x(pg1, t1822, t1823, 2.0172382889501304);
        s783 = svmul_n_f64_x(pg1, s803, 0.1958510486474645);
        s804 = svmls_n_f64_x(pg1, t1827, t1826, 2.386161273135941);
        s784 = svmul_n_f64_x(pg1, s804, 0.17043646531196566);
        s805 = svmla_n_f64_x(pg1, t1826, t1827, 2.386161273135941);
        s785 = svmul_n_f64_x(pg1, s805, 0.17043646531196566);
        t1830 = svadd_f64_x(pg1, s778, s782);
        t1831 = svadd_f64_x(pg1, s779, s783);
        t1832 = svadd_f64_x(pg1, t1828, t1830);
        t1833 = svadd_f64_x(pg1, t1829, t1831);
        t1834 = svmls_n_f64_x(pg1, t1828, t1830, 0.5);
        t1835 = svmls_n_f64_x(pg1, t1829, t1831, 0.5);
        s786 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s779, s783), 0.8660254037844386);
        s787 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s778, s782), 0.8660254037844386);
        t1836 = svadd_f64_x(pg1, t1834, s786);
        t1837 = svsub_f64_x(pg1, t1835, s787);
        t1838 = svsub_f64_x(pg1, t1834, s786);
        t1839 = svadd_f64_x(pg1, t1835, s787);
        t1840 = svadd_f64_x(pg1, s780, s784);
        t1841 = svadd_f64_x(pg1, s781, s785);
        t1842 = svadd_f64_x(pg1, s776, t1840);
        t1843 = svsub_f64_x(pg1, s777, t1841);
        t1844 = svmls_n_f64_x(pg1, s776, t1840, 0.5);
        t1845 = svmla_n_f64_x(pg1, s777, t1841, 0.5);
        s788 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s785, s781), 0.8660254037844386);
        s789 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s780, s784), 0.8660254037844386);
        t1846 = svadd_f64_x(pg1, t1844, s788);
        t1847 = svsub_f64_x(pg1, t1845, s789);
        t1848 = svsub_f64_x(pg1, t1844, s788);
        t1849 = svadd_f64_x(pg1, t1845, s789);
        s806 = svmla_n_f64_x(pg1, t1846, t1847, 1.7320508075688772);
        s790 = svmul_n_f64_x(pg1, s806, 0.5);
        s807 = svmls_n_f64_x(pg1, t1847, t1846, 1.7320508075688772);
        s791 = svmul_n_f64_x(pg1, s807, 0.5);
        s808 = svmls_n_f64_x(pg1, t1849, t1848, 0.57735026918962584);
        s792 = svmul_n_f64_x(pg1, s808, 0.8660254037844386);
        s809 = svmla_n_f64_x(pg1, t1848, t1849, 0.57735026918962584);
        s793 = svmul_n_f64_x(pg1, s809, 0.8660254037844386);
        svex2_8.v0 = svadd_f64_x(pg1, s748, t1818);
        svex2_8.v1 = svadd_f64_x(pg1, s749, t1819);
        svst2_f64(pg1, (Y + ((2)*(k1))), svex2_8);
        svex2_9.v0 = svadd_f64_x(pg1, t1832, t1842);
        svex2_9.v1 = svadd_f64_x(pg1, t1833, t1843);
        svst2_f64(pg1, (Y + ((2)*((k1 + m1)))), svex2_9);
        svex2_10.v0 = svadd_f64_x(pg1, t1838, s792);
        svex2_10.v1 = svsub_f64_x(pg1, t1839, s793);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((2)*(m1)))))), svex2_10);
        svex2_11.v0 = svadd_f64_x(pg1, t1836, s790);
        svex2_11.v1 = svadd_f64_x(pg1, t1837, s791);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((3)*(m1)))))), svex2_11);
        svex2_12.v0 = svsub_f64_x(pg1, t1836, s790);
        svex2_12.v1 = svsub_f64_x(pg1, t1837, s791);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((4)*(m1)))))), svex2_12);
        svex2_13.v0 = svsub_f64_x(pg1, t1838, s792);
        svex2_13.v1 = svadd_f64_x(pg1, t1839, s793);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((5)*(m1)))))), svex2_13);
        svex2_14.v0 = svsub_f64_x(pg1, t1832, t1842);
        svex2_14.v1 = svsub_f64_x(pg1, t1833, t1843);
        svst2_f64(pg1, (Y + ((2)*((k1 + ((6)*(m1)))))), svex2_14);
        k1 += svcntd();
        pg1 = svwhilelt_b64(k1, m1);
    } while(svptest_any(svptrue_b64(), pg1));
}
