/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft8b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    float64_t a697, a698, a699, a700, a701, a702, a703, a704, 
            a705, a706, a707, a708, a709, a710;
    int a691, a696, j1, l1, m1;
    svfloat64x2_t s271, s274, s277, s280, s283, s286, s289, s292, 
            svex2_10, svex2_11, svex2_12, svex2_13, svex2_14, svex2_15, svex2_16, svex2_9;
    svfloat64_t a692, a693, a694, a695, s272, s273, s275, s276, 
            s278, s279, s281, s282, s284, s285, s287, s288, 
            s290, s291, s293, s294, s295, s296, s297, s298, 
            s299, s300, s301, s302, s303, s304, s305, s306, 
            s307, s308, s309, s310, s311, s312, t615, t616, 
            t617, t618, t619, t620, t621, t622, t623, t624, 
            t625, t626, t627, t628, t629, t630, t631, t632, 
            t633, t634, t635, t636, t637, t638, t639, t640, 
            t641, t642;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a691 = (k1 + ((j1)*(m1)));
            s271 = svld2_f64(pg1, (X + ((2)*(a691))));
            s272 = s271.v0;
            s273 = s271.v1;
            s274 = svld2_f64(pg1, (X + ((2)*((a691 + ((l1)*(m1)))))));
            s275 = s274.v0;
            s276 = s274.v1;
            s277 = svld2_f64(pg1, (X + ((2)*((a691 + ((((2)*(l1)))*(m1)))))));
            s278 = s277.v0;
            s279 = s277.v1;
            s280 = svld2_f64(pg1, (X + ((2)*((a691 + ((((3)*(l1)))*(m1)))))));
            s281 = s280.v0;
            s282 = s280.v1;
            s283 = svld2_f64(pg1, (X + ((2)*((a691 + ((((4)*(l1)))*(m1)))))));
            s284 = s283.v0;
            s285 = s283.v1;
            s286 = svld2_f64(pg1, (X + ((2)*((a691 + ((((5)*(l1)))*(m1)))))));
            s287 = s286.v0;
            s288 = s286.v1;
            s289 = svld2_f64(pg1, (X + ((2)*((a691 + ((((6)*(l1)))*(m1)))))));
            s290 = s289.v0;
            s291 = s289.v1;
            s292 = svld2_f64(pg1, (X + ((2)*((a691 + ((((7)*(l1)))*(m1)))))));
            s293 = s292.v0;
            s294 = s292.v1;
            t615 = svadd_f64_x(pg1, s272, s284);
            t616 = svadd_f64_x(pg1, s273, s285);
            t617 = svsub_f64_x(pg1, s272, s284);
            t618 = svsub_f64_x(pg1, s273, s285);
            t619 = svadd_f64_x(pg1, s278, s290);
            t620 = svadd_f64_x(pg1, s279, s291);
            t621 = svsub_f64_x(pg1, s278, s290);
            t622 = svsub_f64_x(pg1, s279, s291);
            t623 = svadd_f64_x(pg1, t615, t619);
            t624 = svadd_f64_x(pg1, t616, t620);
            t625 = svsub_f64_x(pg1, t615, t619);
            t626 = svsub_f64_x(pg1, t616, t620);
            t627 = svadd_f64_x(pg1, t617, t622);
            t628 = svsub_f64_x(pg1, t618, t621);
            t629 = svsub_f64_x(pg1, t617, t622);
            t630 = svadd_f64_x(pg1, t618, t621);
            t631 = svadd_f64_x(pg1, s275, s287);
            t632 = svadd_f64_x(pg1, s276, s288);
            t633 = svsub_f64_x(pg1, s275, s287);
            t634 = svsub_f64_x(pg1, s276, s288);
            t635 = svadd_f64_x(pg1, s281, s293);
            t636 = svadd_f64_x(pg1, s282, s294);
            t637 = svsub_f64_x(pg1, s281, s293);
            t638 = svsub_f64_x(pg1, s282, s294);
            t639 = svadd_f64_x(pg1, t631, t635);
            t640 = svadd_f64_x(pg1, t632, t636);
            t641 = svsub_f64_x(pg1, t631, t635);
            t642 = svsub_f64_x(pg1, t632, t636);
            a692 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t633, t638), 0.70710678118654757);
            a693 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t634, t637), 0.70710678118654757);
            s295 = svadd_f64_x(pg1, a692, a693);
            s296 = svsub_f64_x(pg1, a693, a692);
            a694 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t634, t637), 0.70710678118654757);
            a695 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t633, t638), 0.70710678118654757);
            s297 = svsub_f64_x(pg1, a694, a695);
            s298 = svadd_f64_x(pg1, a695, a694);
            s299 = svsub_f64_x(pg1, t623, t639);
            s300 = svsub_f64_x(pg1, t624, t640);
            s301 = svadd_f64_x(pg1, t627, s295);
            s302 = svadd_f64_x(pg1, t628, s296);
            s303 = svsub_f64_x(pg1, t627, s295);
            s304 = svsub_f64_x(pg1, t628, s296);
            s305 = svadd_f64_x(pg1, t625, t642);
            s306 = svsub_f64_x(pg1, t626, t641);
            s307 = svsub_f64_x(pg1, t625, t642);
            s308 = svadd_f64_x(pg1, t626, t641);
            s309 = svadd_f64_x(pg1, t629, s297);
            s310 = svsub_f64_x(pg1, t630, s298);
            s311 = svsub_f64_x(pg1, t629, s297);
            s312 = svadd_f64_x(pg1, t630, s298);
            a696 = ((14)*(j1));
            a697 = TW1[a696];
            a698 = TW1[(a696 + 1)];
            a699 = TW1[(a696 + 2)];
            a700 = TW1[(a696 + 3)];
            a701 = TW1[(a696 + 4)];
            a702 = TW1[(a696 + 5)];
            a703 = TW1[(a696 + 6)];
            a704 = TW1[(a696 + 7)];
            a705 = TW1[(a696 + 8)];
            a706 = TW1[(a696 + 9)];
            a707 = TW1[(a696 + 10)];
            a708 = TW1[(a696 + 11)];
            a709 = TW1[(a696 + 12)];
            a710 = TW1[(a696 + 13)];
            svex2_9.v0 = svadd_f64_x(pg1, t623, t639);
            svex2_9.v1 = svadd_f64_x(pg1, t624, t640);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)))))), svex2_9);
            svex2_10.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s302, a698), s301, a697);
            svex2_10.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s302, a697), s301, a698);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + m1)))), svex2_10);
            svex2_11.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s306, a700), s305, a699);
            svex2_11.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s306, a699), s305, a700);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_11);
            svex2_12.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s310, a702), s309, a701);
            svex2_12.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s310, a701), s309, a702);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_12);
            svex2_13.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s300, a704), s299, a703);
            svex2_13.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s300, a703), s299, a704);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_13);
            svex2_14.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s304, a706), s303, a705);
            svex2_14.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s304, a705), s303, a706);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_14);
            svex2_15.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s308, a708), s307, a707);
            svex2_15.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s308, a707), s307, a708);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_15);
            svex2_16.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s312, a710), s311, a709);
            svex2_16.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s312, a709), s311, a710);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((8)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_16);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
