/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft8a_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1) {
    int l1;
    float64_t  *a654;
    svfloat64x2_t s287, s290, s293, s296, s299, s302, s305, s308;
    svfloat64_t a650, a651, a652, a653, a655, a656, a657, a658, 
            a659, a660, a661, a662, a663, a664, a665, a666, 
            a667, a668, s288, s289, s291, s292, s294, s295, 
            s297, s298, s300, s301, s303, s304, s306, s307, 
            s309, s310, s311, s312, s313, s314, s315, s316, 
            s317, s318, s319, s320, s321, s322, s323, s324, 
            s325, s326, s327, s328, s329, s330, s331, s332, 
            s333, s334, s335, s336, s337, s338, s339, s340, 
            s341, s342, s343, s344, t615, t616, t617, t618, 
            t619, t620, t621, t622, t623, t624, t625, t626, 
            t627, t628, t629, t630, t631, t632, t633, t634, 
            t635, t636, t637, t638, t639, t640, t641, t642;
    svbool_t pg1;
    l1 = *(lp1);
    int j1 = 0;
    pg1 = svwhilelt_b64(j1, l1);
    do {
        s287 = svld2_f64(pg1, (X + ((2)*(j1))));
        s288 = s287.v0;
        s289 = s287.v1;
        s290 = svld2_f64(pg1, (X + ((2)*((j1 + l1)))));
        s291 = s290.v0;
        s292 = s290.v1;
        s293 = svld2_f64(pg1, (X + ((2)*((j1 + ((2)*(l1)))))));
        s294 = s293.v0;
        s295 = s293.v1;
        s296 = svld2_f64(pg1, (X + ((2)*((j1 + ((3)*(l1)))))));
        s297 = s296.v0;
        s298 = s296.v1;
        s299 = svld2_f64(pg1, (X + ((2)*((j1 + ((4)*(l1)))))));
        s300 = s299.v0;
        s301 = s299.v1;
        s302 = svld2_f64(pg1, (X + ((2)*((j1 + ((5)*(l1)))))));
        s303 = s302.v0;
        s304 = s302.v1;
        s305 = svld2_f64(pg1, (X + ((2)*((j1 + ((6)*(l1)))))));
        s306 = s305.v0;
        s307 = s305.v1;
        s308 = svld2_f64(pg1, (X + ((2)*((j1 + ((7)*(l1)))))));
        s309 = s308.v0;
        s310 = s308.v1;
        t615 = svadd_f64_x(pg1, s288, s300);
        t616 = svadd_f64_x(pg1, s289, s301);
        t617 = svsub_f64_x(pg1, s288, s300);
        t618 = svsub_f64_x(pg1, s289, s301);
        t619 = svadd_f64_x(pg1, s294, s306);
        t620 = svadd_f64_x(pg1, s295, s307);
        t621 = svsub_f64_x(pg1, s294, s306);
        t622 = svsub_f64_x(pg1, s295, s307);
        t623 = svadd_f64_x(pg1, t615, t619);
        t624 = svadd_f64_x(pg1, t616, t620);
        t625 = svsub_f64_x(pg1, t615, t619);
        t626 = svsub_f64_x(pg1, t616, t620);
        t627 = svadd_f64_x(pg1, t617, t622);
        t628 = svsub_f64_x(pg1, t618, t621);
        t629 = svsub_f64_x(pg1, t617, t622);
        t630 = svadd_f64_x(pg1, t618, t621);
        t631 = svadd_f64_x(pg1, s291, s303);
        t632 = svadd_f64_x(pg1, s292, s304);
        t633 = svsub_f64_x(pg1, s291, s303);
        t634 = svsub_f64_x(pg1, s292, s304);
        t635 = svadd_f64_x(pg1, s297, s309);
        t636 = svadd_f64_x(pg1, s298, s310);
        t637 = svsub_f64_x(pg1, s297, s309);
        t638 = svsub_f64_x(pg1, s298, s310);
        t639 = svadd_f64_x(pg1, t631, t635);
        t640 = svadd_f64_x(pg1, t632, t636);
        t641 = svsub_f64_x(pg1, t631, t635);
        t642 = svsub_f64_x(pg1, t632, t636);
        a650 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t633, t638), 0.70710678118654757);
        a651 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t634, t637), 0.70710678118654757);
        s311 = svadd_f64_x(pg1, a650, a651);
        s312 = svsub_f64_x(pg1, a651, a650);
        a652 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, t634, t637), 0.70710678118654757);
        a653 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t633, t638), 0.70710678118654757);
        s313 = svsub_f64_x(pg1, a652, a653);
        s314 = svadd_f64_x(pg1, a653, a652);
        s315 = svadd_f64_x(pg1, t623, t639);
        s316 = svadd_f64_x(pg1, t624, t640);
        s317 = svsub_f64_x(pg1, t623, t639);
        s318 = svsub_f64_x(pg1, t624, t640);
        s319 = svadd_f64_x(pg1, t627, s311);
        s320 = svadd_f64_x(pg1, t628, s312);
        s321 = svsub_f64_x(pg1, t627, s311);
        s322 = svsub_f64_x(pg1, t628, s312);
        s323 = svadd_f64_x(pg1, t625, t642);
        s324 = svsub_f64_x(pg1, t626, t641);
        s325 = svsub_f64_x(pg1, t625, t642);
        s326 = svadd_f64_x(pg1, t626, t641);
        s327 = svadd_f64_x(pg1, t629, s313);
        s328 = svsub_f64_x(pg1, t630, s314);
        s329 = svsub_f64_x(pg1, t629, s313);
        s330 = svadd_f64_x(pg1, t630, s314);
        a654 = (TW1 + ((14)*(j1)));
        a655 = svld1_gather_u64offset_f64(pg1, a654, svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a656 = svld1_gather_u64offset_f64(pg1, (a654 + 1), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s331 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a656, s320), a655, s319);
        s332 = svmla_f64_x(pg1, svmul_f64_x(pg1, a655, s320), a656, s319);
        a657 = svld1_gather_u64offset_f64(pg1, (a654 + 2), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a658 = svld1_gather_u64offset_f64(pg1, (a654 + 3), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s333 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a658, s324), a657, s323);
        s334 = svmla_f64_x(pg1, svmul_f64_x(pg1, a657, s324), a658, s323);
        a659 = svld1_gather_u64offset_f64(pg1, (a654 + 4), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a660 = svld1_gather_u64offset_f64(pg1, (a654 + 5), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s335 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a660, s328), a659, s327);
        s336 = svmla_f64_x(pg1, svmul_f64_x(pg1, a659, s328), a660, s327);
        a661 = svld1_gather_u64offset_f64(pg1, (a654 + 6), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a662 = svld1_gather_u64offset_f64(pg1, (a654 + 7), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s337 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a662, s318), a661, s317);
        s338 = svmla_f64_x(pg1, svmul_f64_x(pg1, a661, s318), a662, s317);
        a663 = svld1_gather_u64offset_f64(pg1, (a654 + 8), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a664 = svld1_gather_u64offset_f64(pg1, (a654 + 9), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s339 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a664, s322), a663, s321);
        s340 = svmla_f64_x(pg1, svmul_f64_x(pg1, a663, s322), a664, s321);
        a665 = svld1_gather_u64offset_f64(pg1, (a654 + 10), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a666 = svld1_gather_u64offset_f64(pg1, (a654 + 11), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s341 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a666, s326), a665, s325);
        s342 = svmla_f64_x(pg1, svmul_f64_x(pg1, a665, s326), a666, s325);
        a667 = svld1_gather_u64offset_f64(pg1, (a654 + 12), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        a668 = svld1_gather_u64offset_f64(pg1, (a654 + 13), svindex_u64(0, (int64_t)(14 * sizeof(float64_t))));
        s343 = svnmls_f64_x(pg1, svmul_f64_x(pg1, a668, s330), a667, s329);
        s344 = svmla_f64_x(pg1, svmul_f64_x(pg1, a667, s330), a668, s329);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s315);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(1 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s316);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(2 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s331);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(3 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s332);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(4 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s333);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(5 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s334);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(6 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s335);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(7 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s336);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(8 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s337);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(9 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s338);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(10 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s339);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(11 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s340);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(12 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s341);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(13 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s342);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(14 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s343);
        svst1_scatter_u64offset_f64(pg1, ((float64_t  *)(15 + Y + ((16)*(j1)))), svindex_u64(0, (int64_t)(16 * sizeof(float64_t))), s344);
        j1 += svcntd();
        pg1 = svwhilelt_b64(j1, l1);
    } while(svptest_any(svptrue_b64(), pg1));
}
