/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/

#include <arm_sve.h>

void dft9b_(float64_t  *Y, float64_t  *X, float64_t  *TW1, int  *lp1, int  *mp1) {
    float64_t a852, a853, a854, a855, a856, a857, a858, a859, 
            a860, a861, a862, a863, a864, a865, a866, a867;
    int a850, a851, j1, l1, m1;
    svfloat64x2_t s459, s462, s465, s468, s471, s474, s477, s480, 
            s483, svex2_10, svex2_11, svex2_12, svex2_13, svex2_14, svex2_15, svex2_16, 
            svex2_17, svex2_18;
    svfloat64_t s460, s461, s463, s464, s466, s467, s469, s470, 
            s472, s473, s475, s476, s478, s479, s481, s482, 
            s484, s485, s486, s487, s488, s489, s490, s491, 
            s492, s493, s494, s495, s496, s497, s498, s499, 
            s500, s501, s502, s503, s504, s505, s506, s507, 
            s508, s509, s510, s511, s512, s513, s514, s515, 
            s516, s517, s518, s519, s520, s521, s522, s523, 
            s524, s525, s526, s527, s528, s529, t681, t682, 
            t683, t684, t685, t686, t687, t688, t689, t690, 
            t691, t692, t693, t694, t695, t696, t697, t698, 
            t699, t700, t701, t702, t703, t704, t705, t706, 
            t707, t708, t709, t710, t711, t712, t713, t714, 
            t715, t716, t717, t718, t719, t720, t721, t722;
    svbool_t pg1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        int k1 = 0;
        pg1 = svwhilelt_b64(k1, m1);
        do {
            a850 = (k1 + ((j1)*(m1)));
            s459 = svld2_f64(pg1, (X + ((2)*(a850))));
            s460 = s459.v0;
            s461 = s459.v1;
            s462 = svld2_f64(pg1, (X + ((2)*((a850 + ((l1)*(m1)))))));
            s463 = s462.v0;
            s464 = s462.v1;
            s465 = svld2_f64(pg1, (X + ((2)*((a850 + ((((2)*(l1)))*(m1)))))));
            s466 = s465.v0;
            s467 = s465.v1;
            s468 = svld2_f64(pg1, (X + ((2)*((a850 + ((((3)*(l1)))*(m1)))))));
            s469 = s468.v0;
            s470 = s468.v1;
            s471 = svld2_f64(pg1, (X + ((2)*((a850 + ((((4)*(l1)))*(m1)))))));
            s472 = s471.v0;
            s473 = s471.v1;
            s474 = svld2_f64(pg1, (X + ((2)*((a850 + ((((5)*(l1)))*(m1)))))));
            s475 = s474.v0;
            s476 = s474.v1;
            s477 = svld2_f64(pg1, (X + ((2)*((a850 + ((((6)*(l1)))*(m1)))))));
            s478 = s477.v0;
            s479 = s477.v1;
            s480 = svld2_f64(pg1, (X + ((2)*((a850 + ((((7)*(l1)))*(m1)))))));
            s481 = s480.v0;
            s482 = s480.v1;
            s483 = svld2_f64(pg1, (X + ((2)*((a850 + ((((8)*(l1)))*(m1)))))));
            s484 = s483.v0;
            s485 = s483.v1;
            t681 = svadd_f64_x(pg1, s469, s478);
            t682 = svadd_f64_x(pg1, s470, s479);
            t683 = svadd_f64_x(pg1, s460, t681);
            t684 = svadd_f64_x(pg1, s461, t682);
            t685 = svmls_n_f64_x(pg1, s460, t681, 0.5);
            t686 = svmls_n_f64_x(pg1, s461, t682, 0.5);
            s486 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s470, s479), 0.8660254037844386);
            s487 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s469, s478), 0.8660254037844386);
            t687 = svadd_f64_x(pg1, t685, s486);
            t688 = svsub_f64_x(pg1, t686, s487);
            t689 = svsub_f64_x(pg1, t685, s486);
            t690 = svadd_f64_x(pg1, t686, s487);
            t691 = svadd_f64_x(pg1, s472, s481);
            t692 = svadd_f64_x(pg1, s473, s482);
            t693 = svadd_f64_x(pg1, s463, t691);
            t694 = svadd_f64_x(pg1, s464, t692);
            t695 = svmls_n_f64_x(pg1, s463, t691, 0.5);
            t696 = svmls_n_f64_x(pg1, s464, t692, 0.5);
            s488 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s473, s482), 0.8660254037844386);
            s489 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s472, s481), 0.8660254037844386);
            t697 = svadd_f64_x(pg1, t695, s488);
            t698 = svsub_f64_x(pg1, t696, s489);
            t699 = svsub_f64_x(pg1, t695, s488);
            t700 = svadd_f64_x(pg1, t696, s489);
            s522 = svmla_n_f64_x(pg1, t697, t698, 0.83909963117727981);
            s490 = svmul_n_f64_x(pg1, s522, 0.76604444311897812);
            s523 = svmls_n_f64_x(pg1, t698, t697, 0.83909963117727981);
            s491 = svmul_n_f64_x(pg1, s523, 0.76604444311897812);
            s524 = svmla_n_f64_x(pg1, t699, t700, 5.6712818196177102);
            s492 = svmul_n_f64_x(pg1, s524, 0.17364817766693033);
            s525 = svmls_n_f64_x(pg1, t700, t699, 5.6712818196177102);
            s493 = svmul_n_f64_x(pg1, s525, 0.17364817766693033);
            t701 = svadd_f64_x(pg1, s475, s484);
            t702 = svadd_f64_x(pg1, s476, s485);
            t703 = svadd_f64_x(pg1, s466, t701);
            t704 = svadd_f64_x(pg1, s467, t702);
            t705 = svmls_n_f64_x(pg1, s466, t701, 0.5);
            t706 = svmls_n_f64_x(pg1, s467, t702, 0.5);
            s494 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s476, s485), 0.8660254037844386);
            s495 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s475, s484), 0.8660254037844386);
            t707 = svadd_f64_x(pg1, t705, s494);
            t708 = svsub_f64_x(pg1, t706, s495);
            t709 = svsub_f64_x(pg1, t705, s494);
            t710 = svadd_f64_x(pg1, t706, s495);
            s526 = svmla_n_f64_x(pg1, t707, t708, 5.6712818196177102);
            s496 = svmul_n_f64_x(pg1, s526, 0.17364817766693033);
            s527 = svmls_n_f64_x(pg1, t708, t707, 5.6712818196177102);
            s497 = svmul_n_f64_x(pg1, s527, 0.17364817766693033);
            s528 = svmls_n_f64_x(pg1, t710, t709, 2.7474774194546225);
            s498 = svmul_n_f64_x(pg1, s528, 0.34202014332566871);
            s529 = svmla_n_f64_x(pg1, t709, t710, 2.7474774194546225);
            s499 = svmul_n_f64_x(pg1, s529, 0.34202014332566871);
            t711 = svadd_f64_x(pg1, t693, t703);
            t712 = svadd_f64_x(pg1, t694, t704);
            t713 = svmls_n_f64_x(pg1, t683, t711, 0.5);
            t714 = svmls_n_f64_x(pg1, t684, t712, 0.5);
            s500 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t694, t704), 0.8660254037844386);
            s501 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, t693, t703), 0.8660254037844386);
            s502 = svadd_f64_x(pg1, t713, s500);
            s503 = svsub_f64_x(pg1, t714, s501);
            s504 = svsub_f64_x(pg1, t713, s500);
            s505 = svadd_f64_x(pg1, t714, s501);
            t715 = svadd_f64_x(pg1, s490, s496);
            t716 = svadd_f64_x(pg1, s491, s497);
            t717 = svmls_n_f64_x(pg1, t687, t715, 0.5);
            t718 = svmls_n_f64_x(pg1, t688, t716, 0.5);
            s506 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s491, s497), 0.8660254037844386);
            s507 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s490, s496), 0.8660254037844386);
            s508 = svadd_f64_x(pg1, t687, t715);
            s509 = svadd_f64_x(pg1, t688, t716);
            s510 = svadd_f64_x(pg1, t717, s506);
            s511 = svsub_f64_x(pg1, t718, s507);
            s512 = svsub_f64_x(pg1, t717, s506);
            s513 = svadd_f64_x(pg1, t718, s507);
            t719 = svadd_f64_x(pg1, s492, s498);
            t720 = svsub_f64_x(pg1, s493, s499);
            t721 = svmls_n_f64_x(pg1, t689, t719, 0.5);
            t722 = svmls_n_f64_x(pg1, t690, t720, 0.5);
            s514 = svmul_n_f64_x(pg1, svadd_f64_x(pg1, s493, s499), 0.8660254037844386);
            s515 = svmul_n_f64_x(pg1, svsub_f64_x(pg1, s492, s498), 0.8660254037844386);
            s516 = svadd_f64_x(pg1, t689, t719);
            s517 = svadd_f64_x(pg1, t690, t720);
            s518 = svadd_f64_x(pg1, t721, s514);
            s519 = svsub_f64_x(pg1, t722, s515);
            s520 = svsub_f64_x(pg1, t721, s514);
            s521 = svadd_f64_x(pg1, t722, s515);
            a851 = ((16)*(j1));
            a852 = TW1[a851];
            a853 = TW1[(a851 + 1)];
            a854 = TW1[(a851 + 2)];
            a855 = TW1[(a851 + 3)];
            a856 = TW1[(a851 + 4)];
            a857 = TW1[(a851 + 5)];
            a858 = TW1[(a851 + 6)];
            a859 = TW1[(a851 + 7)];
            a860 = TW1[(a851 + 8)];
            a861 = TW1[(a851 + 9)];
            a862 = TW1[(a851 + 10)];
            a863 = TW1[(a851 + 11)];
            a864 = TW1[(a851 + 12)];
            a865 = TW1[(a851 + 13)];
            a866 = TW1[(a851 + 14)];
            a867 = TW1[(a851 + 15)];
            svex2_10.v0 = svadd_f64_x(pg1, t683, t711);
            svex2_10.v1 = svadd_f64_x(pg1, t684, t712);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)))))), svex2_10);
            svex2_11.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s509, a853), s508, a852);
            svex2_11.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s509, a852), s508, a853);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + m1)))), svex2_11);
            svex2_12.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s517, a855), s516, a854);
            svex2_12.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s517, a854), s516, a855);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((2)*(m1)))))), svex2_12);
            svex2_13.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s503, a857), s502, a856);
            svex2_13.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s503, a856), s502, a857);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((3)*(m1)))))), svex2_13);
            svex2_14.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s511, a859), s510, a858);
            svex2_14.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s511, a858), s510, a859);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((4)*(m1)))))), svex2_14);
            svex2_15.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s519, a861), s518, a860);
            svex2_15.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s519, a860), s518, a861);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((5)*(m1)))))), svex2_15);
            svex2_16.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s505, a863), s504, a862);
            svex2_16.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s505, a862), s504, a863);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((6)*(m1)))))), svex2_16);
            svex2_17.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s513, a865), s512, a864);
            svex2_17.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s513, a864), s512, a865);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((7)*(m1)))))), svex2_17);
            svex2_18.v0 = svnmls_n_f64_x(pg1, svmul_n_f64_x(pg1, s521, a867), s520, a866);
            svex2_18.v1 = svmla_n_f64_x(pg1, svmul_n_f64_x(pg1, s521, a866), s520, a867);
            svst2_f64(pg1, (Y + ((2)*((k1 + ((((9)*(j1)))*(m1)) + ((8)*(m1)))))), svex2_18);
            k1 += svcntd();
            pg1 = svwhilelt_b64(k1, m1);
        } while(svptest_any(svptrue_b64(), pg1));
    }
}
