/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft2c_(double  *Y, double  *X, int  *lp1, int  *mp1) {
    double s21, s22, s23, s24;
    int a76, a77, a78, a79, l1, m1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int k1 = 0; k1 < m1; k1++) {
        a76 = (2*k1);
        s21 = X[a76];
        a77 = (a76 + 1);
        s22 = X[a77];
        a78 = (a76 + (2*(l1*m1)));
        s23 = X[a78];
        s24 = X[(a78 + 1)];
        Y[a76] = (s21 + s23);
        Y[a77] = (s22 + s24);
        a79 = (a76 + (2*m1));
        Y[a79] = (s21 - s23);
        Y[(a79 + 1)] = (s22 - s24);
    }
}
