/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft2b_(double  *Y, double  *X, double  *TW1, int  *lp1, int  *mp1) {
    double a166, a167, s27, s28, s29, s30, s31, s32;
    int a161, a162, a163, a164, a165, a168, a169, a170, 
            j1, l1, m1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        for(int k1 = 0; k1 < m1; k1++) {
            a161 = (2*k1);
            a162 = (j1*m1);
            a163 = (a161 + (2*a162));
            s27 = X[a163];
            s28 = X[(a163 + 1)];
            a164 = (a163 + (2*(l1*m1)));
            s29 = X[a164];
            s30 = X[(a164 + 1)];
            s31 = (s27 - s29);
            s32 = (s28 - s30);
            a165 = (2*j1);
            a166 = TW1[a165];
            a167 = TW1[(a165 + 1)];
            a168 = (4*a162);
            a169 = (a161 + a168);
            Y[a169] = (s27 + s29);
            Y[(a169 + 1)] = (s28 + s30);
            a170 = (a161 + (2*m1) + a168);
            Y[a170] = ((a166*s31) - (a167*s32));
            Y[(a170 + 1)] = ((a167*s31) + (a166*s32));
        }
    }
}
