/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft2a_(double  *Y, double  *X, double  *TW1, int  *lp1) {
    double a120, a121, s27, s28, s29, s30, s31, s32;
    int a117, a118, a119, a122, l1;
    l1 = *(lp1);
    for(int j1 = 0; j1 < l1; j1++) {
        l1 = *(lp1);
        a117 = (2*j1);
        s27 = X[a117];
        a118 = (a117 + 1);
        s28 = X[a118];
        a119 = (a117 + (2*l1));
        s29 = X[a119];
        s30 = X[(a119 + 1)];
        s31 = (s27 - s29);
        s32 = (s28 - s30);
        a120 = TW1[a117];
        a121 = TW1[a118];
        a122 = (4*j1);
        Y[a122] = (s27 + s29);
        Y[(a122 + 1)] = (s28 + s30);
        Y[(a122 + 2)] = ((a120*s31) - (a121*s32));
        Y[(a122 + 3)] = ((a121*s31) + (a120*s32));
    }
}
