/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft3c_(double  *Y, double  *X, int  *lp1, int  *mp1) {
    double s53, s54, s55, s56, s57, s58, s59, s60, 
            t125, t126, t127, t128;
    int a134, a135, a136, a137, a138, a139, b15, l1, 
            m1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int k1 = 0; k1 < m1; k1++) {
        a134 = (2*k1);
        s53 = X[a134];
        a135 = (a134 + 1);
        s54 = X[a135];
        b15 = (l1*m1);
        a136 = (a134 + (2*b15));
        s55 = X[a136];
        s56 = X[(a136 + 1)];
        a137 = (a134 + (4*b15));
        s57 = X[a137];
        s58 = X[(a137 + 1)];
        t125 = (s55 + s57);
        t126 = (s56 + s58);
        t127 = (s53 - (0.5*t125));
        t128 = (s54 - (0.5*t126));
        s59 = (0.8660254037844386*(s56 - s58));
        s60 = (0.8660254037844386*(s55 - s57));
        Y[a134] = (s53 + t125);
        Y[a135] = (s54 + t126);
        a138 = (a134 + (2*m1));
        Y[a138] = (t127 + s59);
        Y[(a138 + 1)] = (t128 - s60);
        a139 = (a134 + (4*m1));
        Y[a139] = (t127 - s59);
        Y[(a139 + 1)] = (t128 + s60);
    }
}
