/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft3a_(double  *Y, double  *X, double  *TW1, int  *lp1) {
    double a226, a227, a228, a229, s65, s66, s67, s68, 
            s69, s70, s71, s72, s73, s74, s75, s76, 
            t125, t126, t127, t128;
    int a222, a223, a224, a225, a230, l1;
    l1 = *(lp1);
    for(int j1 = 0; j1 < l1; j1++) {
        l1 = *(lp1);
        a222 = (2*j1);
        s65 = X[a222];
        s66 = X[(a222 + 1)];
        a223 = (a222 + (2*l1));
        s67 = X[a223];
        s68 = X[(a223 + 1)];
        a224 = (a222 + (4*l1));
        s69 = X[a224];
        s70 = X[(a224 + 1)];
        t125 = (s67 + s69);
        t126 = (s68 + s70);
        t127 = (s65 - (0.5*t125));
        t128 = (s66 - (0.5*t126));
        s71 = (0.8660254037844386*(s68 - s70));
        s72 = (0.8660254037844386*(s67 - s69));
        s73 = (t127 + s71);
        s74 = (t128 - s72);
        s75 = (t127 - s71);
        s76 = (t128 + s72);
        a225 = (4*j1);
        a226 = TW1[a225];
        a227 = TW1[(a225 + 1)];
        a228 = TW1[(a225 + 2)];
        a229 = TW1[(a225 + 3)];
        a230 = (6*j1);
        Y[a230] = (s65 + t125);
        Y[(a230 + 1)] = (s66 + t126);
        Y[(a230 + 2)] = ((a226*s73) - (a227*s74));
        Y[(a230 + 3)] = ((a227*s73) + (a226*s74));
        Y[(a230 + 4)] = ((a228*s75) - (a229*s76));
        Y[(a230 + 5)] = ((a229*s75) + (a228*s76));
    }
}
