/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft4c_(double  *Y, double  *X, int  *lp1, int  *mp1) {
    double s41, s42, s43, s44, s45, s46, s47, s48, 
            t153, t154, t155, t156, t157, t158, t159, t160;
    int a162, a163, a164, a165, a166, a167, a168, a169, 
            b19, l1, m1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int k1 = 0; k1 < m1; k1++) {
        a162 = (2*k1);
        s41 = X[a162];
        a163 = (a162 + 1);
        s42 = X[a163];
        b19 = (l1*m1);
        a164 = (a162 + (2*b19));
        s43 = X[a164];
        s44 = X[(a164 + 1)];
        a165 = (a162 + (4*b19));
        s45 = X[a165];
        s46 = X[(a165 + 1)];
        a166 = (a162 + (6*b19));
        s47 = X[a166];
        s48 = X[(a166 + 1)];
        t153 = (s41 + s45);
        t154 = (s42 + s46);
        t155 = (s41 - s45);
        t156 = (s42 - s46);
        t157 = (s43 + s47);
        t158 = (s44 + s48);
        t159 = (s43 - s47);
        t160 = (s44 - s48);
        Y[a162] = (t153 + t157);
        Y[a163] = (t154 + t158);
        a167 = (a162 + (2*m1));
        Y[a167] = (t155 + t160);
        Y[(a167 + 1)] = (t156 - t159);
        a168 = (a162 + (4*m1));
        Y[a168] = (t153 - t157);
        Y[(a168 + 1)] = (t154 - t158);
        a169 = (a162 + (6*m1));
        Y[a169] = (t155 - t160);
        Y[(a169 + 1)] = (t156 + t159);
    }
}
