/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft4a_(double  *Y, double  *X, double  *TW1, int  *lp1) {
    double a297, a298, a299, a300, a301, a302, s59, s60, 
            s61, s62, s63, s64, s65, s66, s67, s68, 
            s69, s70, s71, s72, t153, t154, t155, t156, 
            t157, t158, t159, t160;
    int a292, a293, a294, a295, a296, a303, l1;
    l1 = *(lp1);
    for(int j1 = 0; j1 < l1; j1++) {
        l1 = *(lp1);
        a292 = (2*j1);
        s59 = X[a292];
        s60 = X[(a292 + 1)];
        a293 = (a292 + (2*l1));
        s61 = X[a293];
        s62 = X[(a293 + 1)];
        a294 = (a292 + (4*l1));
        s63 = X[a294];
        s64 = X[(a294 + 1)];
        a295 = (a292 + (6*l1));
        s65 = X[a295];
        s66 = X[(a295 + 1)];
        t153 = (s59 + s63);
        t154 = (s60 + s64);
        t155 = (s59 - s63);
        t156 = (s60 - s64);
        t157 = (s61 + s65);
        t158 = (s62 + s66);
        t159 = (s61 - s65);
        t160 = (s62 - s66);
        s67 = (t153 - t157);
        s68 = (t154 - t158);
        s69 = (t155 + t160);
        s70 = (t156 - t159);
        s71 = (t155 - t160);
        s72 = (t156 + t159);
        a296 = (6*j1);
        a297 = TW1[a296];
        a298 = TW1[(a296 + 1)];
        a299 = TW1[(a296 + 2)];
        a300 = TW1[(a296 + 3)];
        a301 = TW1[(a296 + 4)];
        a302 = TW1[(a296 + 5)];
        a303 = (8*j1);
        Y[a303] = (t153 + t157);
        Y[(a303 + 1)] = (t154 + t158);
        Y[(a303 + 2)] = ((a297*s69) - (a298*s70));
        Y[(a303 + 3)] = ((a298*s69) + (a297*s70));
        Y[(a303 + 4)] = ((a299*s67) - (a300*s68));
        Y[(a303 + 5)] = ((a300*s67) + (a299*s68));
        Y[(a303 + 6)] = ((a301*s71) - (a302*s72));
        Y[(a303 + 7)] = ((a302*s71) + (a301*s72));
    }
}
