/*

     FFTE: A FAST FOURIER TRANSFORM PACKAGE

     (C) COPYRIGHT SOFTWARE, 2000-2004, 2008-2014, ALL RIGHTS RESERVED
                BY
         DAISUKE TAKAHASHI
         FACULTY OF ENGINEERING, INFORMATION AND SYSTEMS
         UNIVERSITY OF TSUKUBA
         1-1-1 TENNODAI, TSUKUBA, IBARAKI 305-8573, JAPAN
         E-MAIL: daisuke@cs.tsukuba.ac.jp


     WRITTEN BY DAISUKE TAKAHASHI

     THIS KERNEL WAS GENERATED BY SPIRAL 8.2.0a03
*/


void dft4b_(double  *Y, double  *X, double  *TW1, int  *lp1, int  *mp1) {
    double a362, a363, a364, a365, a366, a367, s59, s60, 
            s61, s62, s63, s64, s65, s66, s67, s68, 
            s69, s70, s71, s72, t153, t154, t155, t156, 
            t157, t158, t159, t160;
    int a355, a356, a357, a358, a359, a360, a361, a368, 
            a369, a370, a371, a372, b60, j1, l1, m1;
    l1 = *(lp1);
    m1 = *(mp1);
    for(int j2 = 0; j2 < (l1 - 1); j2++) {
        j1 = (j2 + 1);
        for(int k1 = 0; k1 < m1; k1++) {
            a355 = (2*k1);
            a356 = (j1*m1);
            a357 = (a355 + (2*a356));
            s59 = X[a357];
            s60 = X[(a357 + 1)];
            b60 = (l1*m1);
            a358 = (a357 + (2*b60));
            s61 = X[a358];
            s62 = X[(a358 + 1)];
            a359 = (a357 + (4*b60));
            s63 = X[a359];
            s64 = X[(a359 + 1)];
            a360 = (a357 + (6*b60));
            s65 = X[a360];
            s66 = X[(a360 + 1)];
            t153 = (s59 + s63);
            t154 = (s60 + s64);
            t155 = (s59 - s63);
            t156 = (s60 - s64);
            t157 = (s61 + s65);
            t158 = (s62 + s66);
            t159 = (s61 - s65);
            t160 = (s62 - s66);
            s67 = (t153 - t157);
            s68 = (t154 - t158);
            s69 = (t155 + t160);
            s70 = (t156 - t159);
            s71 = (t155 - t160);
            s72 = (t156 + t159);
            a361 = (6*j1);
            a362 = TW1[a361];
            a363 = TW1[(a361 + 1)];
            a364 = TW1[(a361 + 2)];
            a365 = TW1[(a361 + 3)];
            a366 = TW1[(a361 + 4)];
            a367 = TW1[(a361 + 5)];
            a368 = (8*a356);
            a369 = (a355 + a368);
            Y[a369] = (t153 + t157);
            Y[(a369 + 1)] = (t154 + t158);
            a370 = (a355 + (2*m1) + a368);
            Y[a370] = ((a362*s69) - (a363*s70));
            Y[(a370 + 1)] = ((a363*s69) + (a362*s70));
            a371 = (a355 + (4*m1) + a368);
            Y[a371] = ((a364*s67) - (a365*s68));
            Y[(a371 + 1)] = ((a365*s67) + (a364*s68));
            a372 = (a355 + (6*m1) + a368);
            Y[a372] = ((a366*s71) - (a367*s72));
            Y[(a372 + 1)] = ((a367*s71) + (a366*s72));
        }
    }
}
